/**
 * MEB Maarif Modeli - 5, 6 ve 7. Sınıflar 36 Haftalık Müfredat ve Kazanım Takvimi
 * T.C. Millî Eğitim Bakanlığı & Türkiye Yüzyılı Maarif Modeli
 * 
 * 5, 6 ve 7. Sınıflar için 4 branşta (Türkçe, Matematik, Fen Bilimleri, Sosyal Bilgiler)
 * 36 haftalık ünite haritası, kazanım kodları ve pedagojik öğrenme alanlarını tanımlar.
 */

export const ACADEMIC_CALENDAR_GRADE_5 = {
  turkce: [
    { week: 1, topic: "Sözcükte Anlam (Gerçek ve Mecaz)", outcome: "T.5.1.1" },
    { week: 2, topic: "Terim Anlam ve Eş/Zıt Anlamlı Sözcükler", outcome: "T.5.1.2" },
    { week: 3, topic: "Deyimler ve Atasözleri", outcome: "T.5.1.3" },
    { week: 4, topic: "Cümlede Anlam (Öznel ve Nesnel Yargılar)", outcome: "T.5.1.4" },
    { week: 5, topic: "Neden-Sonuç ve Amaç-Sonuç Cümleleri", outcome: "T.5.1.5" },
    { week: 6, topic: "Koşul (Şart) ve Karşılaştırma Cümleleri", outcome: "T.5.1.6" },
    { week: 7, topic: "Paragrafta Konu ve Başlık", outcome: "T.5.3.1" },
    { week: 8, topic: "Paragrafta Ana Fikir ve Yardımcı Fikirler", outcome: "T.5.3.2" },
    { week: 9, topic: "Paragrafın Giriş, Gelişme ve Sonuç Bölümleri", outcome: "T.5.3.3" },
    { week: 10, topic: "Anlatım Biçimleri: Öyküleme ve Betimleme", outcome: "T.5.3.4" },
    { week: 11, topic: "Düşünceyi Geliştirme: Tanımlama ve Örnekleme", outcome: "T.5.3.5" },
    { week: 12, topic: "Metin Türleri: Hikâye (Öykü) ve Masal", outcome: "T.5.3.6" },
    { week: 13, topic: "Metin Türleri: Fabl ve Şiir", outcome: "T.5.3.7" },
    { week: 14, topic: "Söz Sanatları: Benzetme (Teşbih) ve Kişileştirme (Teşhis)", outcome: "T.5.3.8" },
    { week: 15, topic: "Görsel, Karikatür ve İnfografik Yorumlama", outcome: "T.5.3.9" },
    { week: 16, topic: "Tablo ve Grafik Okuma", outcome: "T.5.3.10" },
    { week: 17, topic: "Kökler ve Ekler (İsim ve Fiil Kökleri)", outcome: "T.5.4.1" },
    { week: 18, topic: "Yapım Ekleri ve Türemiş Sözcükler", outcome: "T.5.4.2" },
    { week: 19, topic: "Çekim Ekleri (Çoğul ve Hâl Ekleri)", outcome: "T.5.4.3" },
    { week: 20, topic: "İyilik ve İlgi Ekleri", outcome: "T.5.4.4" },
    { week: 21, topic: "Büyük Harflerin Kullanıldığı Yerler", outcome: "T.5.4.5" },
    { week: 22, topic: "Sayıların ve Tarihlerin Yazımı", outcome: "T.5.4.6" },
    { week: 23, topic: "'de/da' ve 'ki' Bağlaçlarının Yazımı", outcome: "T.5.4.7" },
    { week: 24, topic: "Soru Eki 'mi'nin Yazımı", outcome: "T.5.4.8" },
    { week: 25, topic: "Nokta, Virgül ve İki Nokta", outcome: "T.5.4.9" },
    { week: 26, topic: "Üç Nokta, Soru İşareti ve Ünlem İşareti", outcome: "T.5.4.10" },
    { week: 27, topic: "Kısa Çizgi, Tırnak ve Kesme İşareti", outcome: "T.5.4.11" },
    { week: 28, topic: "Akıcı Okuma ve Sesli Düşünme Becerileri", outcome: "T.5.2.1" },
    { week: 29, topic: "Örtülü Anlam ve Çıkarım Yapma", outcome: "T.5.3.11" },
    { week: 30, topic: "Metin İçi Mantık ve Olay Akışı", outcome: "T.5.3.12" },
    { week: 31, topic: "Eleştirel Okuma ve Metin Değerlendirme", outcome: "T.5.3.13" },
    { week: 32, topic: "Biyografi ve Mektup İncelemesi", outcome: "T.5.3.14" },
    { week: 33, topic: "Karma Dil ve Anlam Bilgisi Denemesi - I", outcome: "T.5.LGS.01" },
    { week: 34, topic: "Karma Dil ve Anlam Bilgisi Denemesi - II", outcome: "T.5.LGS.02" },
    { week: 35, topic: "5. Sınıf Yıl Sonu Bütüncül Sözel Prova - I", outcome: "T.5.LGS.03" },
    { week: 36, topic: "5. Sınıf Yıl Sonu Bütüncül Sözel Prova - II", outcome: "T.5.LGS.04" }
  ],
  matematik: [
    { week: 1, topic: "Milyonlu Doğal Sayıların Okunuşu ve Yazılışı", outcome: "M.5.1.1.1" },
    { week: 2, topic: "Basamak Değeri ve Bölük Kavramı", outcome: "M.5.1.1.2" },
    { week: 3, topic: "Doğal Sayılarla Toplama ve Çıkarma İşlemleri", outcome: "M.5.1.2.1" },
    { week: 4, topic: "Zihinden Toplama-Çıkarma ve Tahmin", outcome: "M.5.1.2.2" },
    { week: 5, topic: "Doğal Sayılarla Çarpma İşlemi ve Modelleme", outcome: "M.5.1.2.3" },
    { week: 6, topic: "Doğal Sayılarla Bölme İşlemi ve Kalan Yorumlama", outcome: "M.5.1.2.4" },
    { week: 7, topic: "Doğal Sayıların Karesi ve Küpü", outcome: "M.5.1.2.5" },
    { week: 8, topic: "Parantezli İşlemler ve İşlem Önceliği", outcome: "M.5.1.2.6" },
    { week: 9, topic: "Birim Kesirler ve Sayı Doğrusunda Gösterimi", outcome: "M.5.1.3.1" },
    { week: 10, topic: "Tam Sayılı ve Bileşik Kesir Dönüşümleri", outcome: "M.5.1.3.2" },
    { week: 11, topic: "Denk Kesirler ve Sadeleştirme/Genişletme", outcome: "M.5.1.3.3" },
    { week: 12, topic: "Kesirleri Sıralama ve Karşılaştırma", outcome: "M.5.1.3.4" },
    { week: 13, topic: "Bir Çokluğun İstenen Basit Kesir Kadarını Bulma", outcome: "M.5.1.3.5" },
    { week: 14, topic: "Kesirlerle Toplama ve Çıkarma İşlemleri", outcome: "M.5.1.4.1" },
    { week: 15, topic: "Ondalık Gösterim: Onda Birler, Yüzde Birler, Binde Birler", outcome: "M.5.1.5.1" },
    { week: 16, topic: "Ondalık Gösterimleri Sayı Doğrusunda Sıralama", outcome: "M.5.1.5.2" },
    { week: 17, topic: "Ondalık Gösterimlerle Toplama ve Çıkarma", outcome: "M.5.1.5.3" },
    { week: 18, topic: "Yüzde Kavramı (%) ve Kesir-Ondalık Dönüşümü", outcome: "M.5.1.6.1" },
    { week: 19, topic: "Bir Çokluğun Belirtilen Yüzdesini Hesaplama", outcome: "M.5.1.6.2" },
    { week: 20, topic: "Temel Geometrik Kavramlar: Nokta, Doğru, Işın, Doğru Parçası", outcome: "M.5.2.1.1" },
    { week: 21, topic: "İki Noktanın Birbirine Göre Konumu", outcome: "M.5.2.1.2" },
    { week: 22, topic: "Eşit Uzunluktaki Doğru Parçaları Çizme", outcome: "M.5.2.1.3" },
    { week: 23, topic: "Dar, Dik, Geniş ve Doğru Açılar", outcome: "M.5.2.1.4" },
    { week: 24, topic: "Üçgen Çeşitleri (Açılarına ve Kenarlarına Göre)", outcome: "M.5.2.2.1" },
    { week: 25, topic: "Dörtgenler: Kare, Dikdörtgen, Paralelkenar, Eşkenar Dörtgen, Yamuk", outcome: "M.5.2.2.2" },
    { week: 26, topic: "Üçgen ve Dörtgenlerde İç Açılar Toplamı", outcome: "M.5.2.2.3" },
    { week: 27, topic: "Uzunluk Ölçme Birimleri ve Dönüşümleri (m, cm, mm, km)", outcome: "M.5.2.3.1" },
    { week: 28, topic: "Çevre Uzunluğu Hesaplama Problemleri", outcome: "M.5.2.3.2" },
    { week: 29, topic: "Zaman Ölçme Birimleri ve Süre Problemleri", outcome: "M.5.2.4.1" },
    { week: 30, topic: "Dikdörtgenin Alanını Hesaplama ve Birim Kareler", outcome: "M.5.2.5.1" },
    { week: 31, topic: "Aynı Alana Sahip Farklı Dikdörtgenler Oluşturma", outcome: "M.5.2.5.2" },
    { week: 32, topic: "Dikdörtgenler Prizması, Kare Prizma ve Küp Açınımları", outcome: "M.5.2.6.1" },
    { week: 33, topic: "Dikdörtgenler Prizmasının Yüzey Alanı", outcome: "M.5.2.6.2" },
    { week: 34, topic: "Veri Toplama, Çetele ve Sıklık Tablosu", outcome: "M.5.3.1.1" },
    { week: 35, topic: "Sütun Grafiği Çizme ve Yorumlama", outcome: "M.5.3.1.2" },
    { week: 36, topic: "5. Sınıf Yıl Sonu Bütüncül Sayısal Prova", outcome: "M.5.LGS.01" }
  ],
  fen: [
    { week: 1, topic: "Güneş'in Yapısı ve Dönme Hareketi", outcome: "F.5.1.1.1" },
    { week: 2, topic: "Ay'ın Yapısı, Atmosferi ve Yüzey Şekilleri", outcome: "F.5.1.2.1" },
    { week: 3, topic: "Ay'ın Hareketleri ve Evreleri (Ana ve Ara Evreler)", outcome: "F.5.1.3.1" },
    { week: 4, topic: "Güneş, Dünya ve Ay'ın Birbirine Göre Hareketleri", outcome: "F.5.1.4.1" },
    { week: 5, topic: "Canlıların Sınıflandırılması: Mikroskobik Canlılar", outcome: "F.5.2.1.1" },
    { week: 6, topic: "Mantarlar Dünyası (Şapkalı, Küf, Maya, Parazit)", outcome: "F.5.2.1.2" },
    { week: 7, topic: "Bitkiler Dünyası (Çiçekli ve Çiçeksiz Bitkiler)", outcome: "F.5.2.1.3" },
    { week: 8, topic: "Hayvanlar Dünyası (Omurgalı ve Omurgasız Hayvanlar)", outcome: "F.5.2.1.4" },
    { week: 9, topic: "Kuvvetin Ölçülmesi ve Dinamometre", outcome: "F.5.3.1.1" },
    { week: 10, topic: "Sürtünme Kuvveti ve Harekete Etkisi (Katı Yüzeyler)", outcome: "F.5.3.2.1" },
    { week: 11, topic: "Hava ve Su Direnci (Sürtünmenin Teknolojideki Yeri)", outcome: "F.5.3.2.2" },
    { week: 12, topic: "Maddenin Hâl Değişimi: Erime ve Donma", outcome: "F.5.4.1.1" },
    { week: 13, topic: "Buharlaşma, Kaynama ve Yoğuşma", outcome: "F.5.4.1.2" },
    { week: 14, topic: "Süblimleşme ve Kırağılaşma", outcome: "F.5.4.1.3" },
    { week: 15, topic: "Maddenin Ayırt Edici Özellikleri: Erime ve Donma Noktası", outcome: "F.5.4.2.1" },
    { week: 16, topic: "Kaynama Noktası ve Saf Maddeler", outcome: "F.5.4.2.2" },
    { week: 17, topic: "Isı ve Sıcaklık Arasındaki Farklar", outcome: "F.5.4.3.1" },
    { week: 18, topic: "Isı Alışverişi ve Termal Denge", outcome: "F.5.4.3.2" },
    { week: 19, topic: "Genleşme ve Büzülme Olayları (Katı, Sıvı, Gaz)", outcome: "F.5.4.4.1" },
    { week: 20, topic: "Işığın Doğrusal Yayılması ve Işık Işını", outcome: "F.5.5.1.1" },
    { week: 21, topic: "Işığın Yansıması: Düzgün ve Dağınık Yansıma", outcome: "F.5.5.2.1" },
    { week: 22, topic: "Yansıma Kanunları (Gelen Işın, Normal, Yansıyan Işın)", outcome: "F.5.5.2.2" },
    { week: 23, topic: "Işığın Maddeyle Karşılaşması: Saydam, Yarı Saydam, Opak", outcome: "F.5.5.3.1" },
    { week: 24, topic: "Tam Gölge Oluşumu ve Gölge Boyunu Etkileyen Değişkenler", outcome: "F.5.5.4.1" },
    { week: 25, topic: "Biyoçeşitlilik ve Ülkemizin Biyolojik Zenginlikleri", outcome: "F.5.6.1.1" },
    { week: 26, topic: "Nesli Tükenen ve Tükenme Tehlikesinde Olan Canlılar", outcome: "F.5.6.1.2" },
    { week: 27, topic: "İnsan ve Çevre İlişkisi: Çevre Kirliliği Çeşitleri", outcome: "F.5.6.2.1" },
    { week: 28, topic: "Yıkıcı Doğa Olayları: Deprem, Sel, Heyelan, Fırtına, Volkan", outcome: "F.5.6.3.1" },
    { week: 29, topic: "Doğal Afetlerden Korunma Yolları ve Bilinçlenme", outcome: "F.5.6.3.2" },
    { week: 30, topic: "Basit Elektrik Devresi Elemanları ve Sembolleri", outcome: "F.5.7.1.1" },
    { week: 31, topic: "Devre Şeması Çizimi ve Kurulumu", outcome: "F.5.7.1.2" },
    { week: 32, topic: "Ampul Parlaklığını Etkileyen Değişkenler (Pil Sayısı)", outcome: "F.5.7.2.1" },
    { week: 33, topic: "Ampul Parlaklığını Etkileyen Değişkenler (Ampul Sayısı)", outcome: "F.5.7.2.2" },
    { week: 34, topic: "Bağımlı, Bağımsız ve Sabit Tutulan Değişken Deneyleri", outcome: "F.5.7.2.3" },
    { week: 35, topic: "5. Sınıf Fen Bilimleri Bütüncül Deneme - I", outcome: "F.5.LGS.01" },
    { week: 36, topic: "5. Sınıf Fen Bilimleri Bütüncül Deneme - II", outcome: "F.5.LGS.02" }
  ],
  sosyal: [
    { week: 1, topic: "Sosyal Bilgiler Dersi ve Bize Kazandırdıkları", outcome: "SB.5.1.1" },
    { week: 2, topic: "Yeni Bir Kulüpteyim: Hak ve Sorumluluklarım", outcome: "SB.5.1.2" },
    { week: 3, topic: "Çocuk Hakları ve Dünya Çocukları", outcome: "SB.5.1.3" },
    { week: 4, topic: "Tarihe Yolculuk: Anadolu ve Mezopotamya Uygarlıkları", outcome: "SB.5.2.1" },
    { week: 5, topic: "Güzel Ülkem: Doğal Varlıklar ve Tarihî Eserler", outcome: "SB.5.2.2" },
    { week: 6, topic: "Kültürel Zenginliğimiz: Bayramlarımız ve Geleneklerimiz", outcome: "SB.5.2.3" },
    { week: 7, topic: "Geçmişten Günümüze Kültürel Değişim", outcome: "SB.5.2.4" },
    { week: 8, topic: "Haritayı Tanıyorum: Yeryüzü Şekilleri ve Renkler", outcome: "SB.5.3.1" },
    { week: 9, topic: "İklim ve İnsan Faaliyetleri (Karadeniz, Akdeniz, Karasal)", outcome: "SB.5.3.2" },
    { week: 10, topic: "Nüfus ve Yerleşmeyi Etkileyen Doğal ve Beşerî Faktörler", outcome: "SB.5.3.3" },
    { week: 11, topic: "Afetler ve Çevre Sorunları", outcome: "SB.5.3.4" },
    { week: 12, topic: "Teknoloji ve Toplum: Doğru ve Güvenli İnternet Kullanımı", outcome: "SB.5.4.1" },
    { week: 13, topic: "Bilgi Kaynaklarını Değerlendirme ve Bilimsel Etik", outcome: "SB.5.4.2" },
    { week: 14, topic: "Buluşlar ve Bilim İnsanlarının Ortak Özellikleri", outcome: "SB.5.4.3" },
    { week: 15, topic: "Fikir Hakları, Telif ve Patent", outcome: "SB.5.4.4" },
    { week: 16, topic: "Çevremizdeki Ekonomik Faaliyetler (Tarım, Sanayi, Hizmet)", outcome: "SB.5.5.1" },
    { week: 17, topic: "Ekonomik Faaliyetlerin Mesleklere Etkisi", outcome: "SB.5.5.2" },
    { week: 18, topic: "Ekonomi ve Yaşam: Üretimden Tüketime Yolculuk", outcome: "SB.5.5.3" },
    { week: 19, topic: "Bilinçli Tüketici Hakları ve Bütçe Planlama", outcome: "SB.5.5.4" },
    { week: 20, topic: "Halka Hizmet Veren Kurumlar (Bakanlıklar, Belediyeler)", outcome: "SB.5.6.1" },
    { week: 21, topic: "Sivil Toplum Kuruluşları (STK) ve Dayanışma", outcome: "SB.5.6.2" },
    { week: 22, topic: "Yerel Yönetimler: Valilik, Kaymakamlık, Muhtarlık", outcome: "SB.5.6.3" },
    { week: 23, topic: "Egemenlik ve Bağımsızlık Sembollerimiz", outcome: "SB.5.6.4" },
    { week: 24, topic: "Yaşadığım Çevrenin Yönetimi", outcome: "SB.5.6.5" },
    { week: 25, topic: "Ülkeler Arası Ekonomik İlişkiler ve Ticaret", outcome: "SB.5.7.1" },
    { week: 26, topic: "Kültür Elçileri ve Uluslararası Ortak Miras", outcome: "SB.5.7.2" },
    { week: 27, topic: "Dünya Çocuk Oyunları ve Evrensel Değerler", outcome: "SB.5.7.3" },
    { week: 28, topic: "Turizm ve Kültürlerarası Etkileşim", outcome: "SB.5.7.4" },
    { week: 29, topic: "Doğal Çevreyi Koruma ve Sürdürülebilirlik Bilinci", outcome: "SB.5.3.5" },
    { week: 30, topic: "Girişimcilik ve Yeni İş Fikirleri", outcome: "SB.5.5.5" },
    { week: 31, topic: "Yardımlaşma ve Paylaşma Kültürü (Kızılay, Yeşilay)", outcome: "SB.5.6.6" },
    { week: 32, topic: "Cumhuriyetimizin Kuruluş Felsefesi ve Değerleri", outcome: "SB.5.6.7" },
    { week: 33, topic: "Karma Sosyal Bilgiler Kazanım Denemesi - I", outcome: "SB.5.LGS.01" },
    { week: 34, topic: "Karma Sosyal Bilgiler Kazanım Denemesi - II", outcome: "SB.5.LGS.02" },
    { week: 35, topic: "5. Sınıf Sosyal Bilgiler Yıl Sonu Denemesi - I", outcome: "SB.5.LGS.03" },
    { week: 36, topic: "5. Sınıf Sosyal Bilgiler Yıl Sonu Denemesi - II", outcome: "SB.5.LGS.04" }
  ]
};

export const ACADEMIC_CALENDAR_GRADE_6 = {
  turkce: [
    { week: 1, topic: "Sözcükte Anlam (Mecaz, Terim, Söz Öbekleri)", outcome: "T.6.1.1" },
    { week: 2, topic: "Sözcüğün Yapısı: Kökler (İsim ve Fiil Kökü)", outcome: "T.6.4.1" },
    { week: 3, topic: "Sözcüğün Yapısı: Yapım Ekleri ve Gövde", outcome: "T.6.4.2" },
    { week: 4, topic: "Sözcüğün Yapısı: Çekim Ekleri (İsim Çekim Ekleri)", outcome: "T.6.4.3" },
    { week: 5, topic: "Basit, Türemiş ve Birleşik Sözcükler", outcome: "T.6.4.4" },
    { week: 6, topic: "İsimler (Adlar): Varlıklara Verilişine Göre İsimler", outcome: "T.6.4.5" },
    { week: 7, topic: "İsim Tamlamaları (Belirtili, Belirtisiz, Zincirleme)", outcome: "T.6.4.6" },
    { week: 8, topic: "Sıfatlar (Ön Adlar): Niteleme ve Belirtme Sıfatları", outcome: "T.6.4.7" },
    { week: 9, topic: "Sıfat Tamlamaları ve Metindeki İşlevleri", outcome: "T.6.4.8" },
    { week: 10, topic: "Zamirler (Adıllar): Kişi, İşaret, Belgisiz, Soru Zamirleri", outcome: "T.6.4.9" },
    { week: 11, topic: "Edat, Bağlaç ve Ünlemler", outcome: "T.6.4.10" },
    { week: 12, topic: "Paragrafta Konu, Ana Fikir ve Başlık", outcome: "T.6.3.1" },
    { week: 13, topic: "Paragrafta Yardımcı Fikirler ve Değinilmemiştir Soruları", outcome: "T.6.3.2" },
    { week: 14, topic: "Paragrafın Yapısı: Akışı Bozan Cümle ve İkiye Bölme", outcome: "T.6.3.3" },
    { week: 15, topic: "Anlatım Biçimleri: Açıklama ve Tartışma", outcome: "T.6.3.4" },
    { week: 16, topic: "Düşünceyi Geliştirme: Benzetme ve Karşılaştırma", outcome: "T.6.3.5" },
    { week: 17, topic: "Metin Türleri: Tiyatro, Anı (Hatıra) ve Mektup", outcome: "T.6.3.6" },
    { week: 18, topic: "Metin Türleri: Gezi Yazısı ve Günlük", outcome: "T.6.3.7" },
    { week: 19, topic: "Söz Sanatları: Tezat (Karşıtlık) ve Konuşturma (İntak)", outcome: "T.6.3.8" },
    { week: 20, topic: "Cümlede Anlam İlişkileri (Neden, Amaç, Koşul)", outcome: "T.6.1.2" },
    { week: 21, topic: "Öznel ve Nesnel Anlatım, Doğrudan/Dolaylı Aktarım", outcome: "T.6.1.3" },
    { week: 22, topic: "Örtülü Anlam ve Cümle Vurgusu", outcome: "T.6.1.4" },
    { week: 23, topic: "Büyük Harfler ve Birleşik Kelimelerin Yazımı", outcome: "T.6.4.11" },
    { week: 24, topic: "'de', 'ki' ve 'mi' Ek/Bağlaçlarının Yazımı", outcome: "T.6.4.12" },
    { week: 25, topic: "Noktalama: Noktalı Virgül ve İki Nokta Ayrımı", outcome: "T.6.4.13" },
    { week: 26, topic: "Noktalama: Yay Ayraç, Köşeli Ayraç ve Kesme İşareti", outcome: "T.6.4.14" },
    { week: 27, topic: "Sözel Mantık: İki Değişkenli Tablo Okuma", outcome: "T.6.3.9" },
    { week: 28, topic: "Sözel Mantık: Sıralama ve Kısıt Çözümleme", outcome: "T.6.3.10" },
    { week: 29, topic: "Görsel, İnfografik ve Çizgi Grafik Yorumlama", outcome: "T.6.3.11" },
    { week: 30, topic: "Metin Karşılaştırma ve Bakış Açısı Analizi", outcome: "T.6.3.12" },
    { week: 31, topic: "Deyim ve Atasözü Eşleme Soruları", outcome: "T.6.1.5" },
    { week: 32, topic: "Eleştirel Okuma ve Metin Tahlili", outcome: "T.6.3.13" },
    { week: 33, topic: "6. Sınıf Türkçe Kazanım Denemesi - I", outcome: "T.6.LGS.01" },
    { week: 34, topic: "6. Sınıf Türkçe Kazanım Denemesi - II", outcome: "T.6.LGS.02" },
    { week: 35, topic: "6. Sınıf Yıl Sonu Bütüncül Sözel Prova - I", outcome: "T.6.LGS.03" },
    { week: 36, topic: "6. Sınıf Yıl Sonu Bütüncül Sözel Prova - II", outcome: "T.6.LGS.04" }
  ],
  matematik: [
    { week: 1, topic: "Doğal Sayılarla İşlemler ve İşlem Önceliği", outcome: "M.6.1.1.1" },
    { week: 2, topic: "Ortak Çarpan Parantezi ve Dağılma Özelliği", outcome: "M.6.1.1.2" },
    { week: 3, topic: "Doğal Sayı Problemleri (Dört İşlem)", outcome: "M.6.1.1.3" },
    { week: 4, topic: "Çarpanlar ve Katlar: Doğal Sayıların Çarpanları", outcome: "M.6.1.2.1" },
    { week: 5, topic: "2, 3, 4, 5, 6, 9 ve 10 ile Bölünebilme Kuralları", outcome: "M.6.1.2.2" },
    { week: 6, topic: "Asal Sayılar ve Asal Çarpanlara Ayırma", outcome: "M.6.1.2.3" },
    { week: 7, topic: "Ortak Bölenler ve Ortak Katlar (EBOB-EKOK Temeli)", outcome: "M.6.1.2.4" },
    { week: 8, topic: "Kümeler: Küme Gösterimi (Liste, Venn Şeması, Ortak Özellik)", outcome: "M.6.1.3.1" },
    { week: 9, topic: "Kümelerde Kesişim ve Birleşim İşlemleri", outcome: "M.6.1.3.2" },
    { week: 10, topic: "Tam Sayılar: Negatif ve Pozitif Sayılar", outcome: "M.6.1.4.1" },
    { week: 11, topic: "Tam Sayıları Sayı Doğrusunda Gösterme ve Sıralama", outcome: "M.6.1.4.2" },
    { week: 12, topic: "Mutlak Değer Kavramı ve Sayı Doğrusu Uzaklığı", outcome: "M.6.1.4.3" },
    { week: 13, topic: "Kesirlerle İşlemler: Kesirleri Karşılaştırma ve Sıralama", outcome: "M.6.1.5.1" },
    { week: 14, topic: "Kesirlerle Toplama ve Çıkarma İşlemleri", outcome: "M.6.1.5.2" },
    { week: 15, topic: "Kesirlerle Çarpma İşlemi ve Modelleme", outcome: "M.6.1.5.3" },
    { week: 16, topic: "Kesirlerle Bölme İşlemi (Ters Çevirip Çarpma)", outcome: "M.6.1.5.4" },
    { week: 17, topic: "Kesir Problemleri (Çok Adımlı Günlük Hayat Senaryoları)", outcome: "M.6.1.5.5" },
    { week: 18, topic: "Ondalık Gösterim: Çözümleme ve Basamak Değerleri", outcome: "M.6.1.6.1" },
    { week: 19, topic: "Ondalık Gösterimleri Yuvarlama (Birler, Onda Birler)", outcome: "M.6.1.6.2" },
    { week: 20, topic: "Ondalık Gösterimlerle Çarpma ve Kısa Yoldan 10, 100, 1000", outcome: "M.6.1.6.3" },
    { week: 21, topic: "Ondalık Gösterimlerle Bölme İşlemi", outcome: "M.6.1.6.4" },
    { week: 22, topic: "Oran Kavramı ve Çoklukları Karşılaştırma", outcome: "M.6.1.7.1" },
    { week: 23, topic: "Birimli ve Birimsiz Oran Ayrımı (Hız: km/sa, m/sn)", outcome: "M.6.1.7.2" },
    { week: 24, topic: "Cebirsel İfadeler: Terim, Değişken, Sabit Terim, Katsayı", outcome: "M.6.2.1.1" },
    { week: 25, topic: "Cebirsel İfadenin Değerini Hesaplama (x yerine değer yazma)", outcome: "M.6.2.1.2" },
    { week: 26, topic: "Veri Analizi: İki Gruba Ait Verileri Karşılaştırma", outcome: "M.6.3.1.1" },
    { week: 27, topic: "Aritmetik Ortalama ve Açıklık Hesaplama", outcome: "M.6.3.2.1" },
    { week: 28, topic: "Açılar: Komşu Açılar, Tümler ve Bütünler Açılar", outcome: "M.6.4.1.1" },
    { week: 29, topic: "Ters Açılar ve Açı Problemleri", outcome: "M.6.4.1.2" },
    { week: 30, topic: "Üçgende Alan Bağıntısı (Taban x Yükseklik / 2)", outcome: "M.6.4.2.1" },
    { week: 31, topic: "Paralelkenarda Alan Bağıntısı", outcome: "M.6.4.2.2" },
    { week: 32, topic: "Alan Ölçme Birimleri (m², dm², cm², mm², ar, dekar, hektar)", outcome: "M.6.4.2.3" },
    { week: 33, topic: "Çember: Merkez, Yarıçap, Çap ve Çevre Uzunluğu (2πr)", outcome: "M.6.4.3.1" },
    { week: 34, topic: "Dikdörtgenler Prizmasının Hacmi (Taban Alanı x Yükseklik)", outcome: "M.6.4.4.1" },
    { week: 35, topic: "Sıvı Ölçme Birimleri (Litre, Desilitre, Santilitre, Mililitre)", outcome: "M.6.4.4.2" },
    { week: 36, topic: "6. Sınıf Yıl Sonu Bütüncül Sayısal Prova", outcome: "M.6.LGS.01" }
  ],
  fen: [
    { week: 1, topic: "Güneş Sistemi: Gezegenlerin Özellikleri ve Sıralaması", outcome: "F.6.1.1.1" },
    { week: 2, topic: "Asteroit ve Meteorlar, Gök Taşları", outcome: "F.6.1.1.2" },
    { week: 3, topic: "Güneş Tutulması Modeli ve Özellikleri", outcome: "F.6.1.2.1" },
    { week: 4, topic: "Ay Tutulması Modeli ve Karşılaştırma", outcome: "F.6.1.2.2" },
    { week: 5, topic: "Destek ve Hareket Sistemi: Kemikler ve Kıkırdak", outcome: "F.6.2.1.1" },
    { week: 6, topic: "Eklemler ve Kas Çeşitleri (Çizgili, Düz, Kalp Kası)", outcome: "F.6.2.1.2" },
    { week: 7, topic: "Sindirim Sistemi: Ağızdan Mideye, İnce ve Kalın Bağırsağa", outcome: "F.6.2.2.1" },
    { week: 8, topic: "Mekanik ve Kimyasal Sindirim, Emilim Olayı", outcome: "F.6.2.2.2" },
    { week: 9, topic: "Sindirime Yardımcı Organlar: Karaciğer ve Pankreas", outcome: "F.6.2.2.3" },
    { week: 10, topic: "Dolaşım Sistemi: Kalbin Yapısı ve Çalışması", outcome: "F.6.2.3.1" },
    { week: 11, topic: "Damarlar (Atardamar, Toplardamar, Kılcal Damar)", outcome: "F.6.2.3.2" },
    { week: 12, topic: "Küçük ve Büyük Kan Dolaşımı", outcome: "F.6.2.3.3" },
    { week: 13, topic: "Kanın Yapısı ve Görevleri, Kan Grupları ve Bağışı", outcome: "F.6.2.3.4" },
    { week: 14, topic: "Solunum Sistemi Organları ve Gaz Değişimi", outcome: "F.6.2.4.1" },
    { week: 15, topic: "Boşaltım Sistemi Organları: Böbrekler, Üreter, İdrar Kesesi", outcome: "F.6.2.5.1" },
    { week: 16, topic: "Kuvvetin Yönü, Doğrultusu ve Büyüklüğü", outcome: "F.6.3.1.1" },
    { week: 17, topic: "Bileşke Kuvvet (Net Kuvvet) Hesaplamaları", outcome: "F.6.3.1.2" },
    { week: 18, topic: "Dengelenmiş ve Dengelenmemiş Kuvvetler", outcome: "F.6.3.1.3" },
    { week: 19, topic: "Sabit Süratli Hareket, Yol-Zaman Grafikleri", outcome: "F.6.3.2.1" },
    { week: 20, topic: "Maddenin Tanecikli, Boşluklu ve Hareketli Yapısı", outcome: "F.6.4.1.1" },
    { week: 21, topic: "Yoğunluk (Özkütle) Kavramı: d = m / V Hesabı", outcome: "F.6.4.2.1" },
    { week: 22, topic: "Birbiri İçinde Çözünmeyen Sıvıların Yoğunluk Dengesi", outcome: "F.6.4.2.2" },
    { week: 23, topic: "Suyun Özel Durumu ve Canlılar İçin Önemi", outcome: "F.6.4.2.3" },
    { week: 24, topic: "Isı İletimi: İletken ve Yalıtkan Maddeler", outcome: "F.6.4.3.1" },
    { week: 25, topic: "Binalarda Isı Yalıtımı ve Enerji Tasarrufu", outcome: "F.6.4.3.2" },
    { week: 26, topic: "Yakıtlar ve Çevresel Etkileri (Fosil, Biyokütle)", outcome: "F.6.4.4.1" },
    { week: 27, topic: "Sesin Yayılması (Katı, Sıvı ve Gaz Ortamlar)", outcome: "F.6.5.1.1" },
    { week: 28, topic: "Sesin Farklı Ortamlarda Farklı Duyulması", outcome: "F.6.5.2.1" },
    { week: 29, topic: "Sesin Sürati ve Işık Sürati ile Karşılaştırılması", outcome: "F.6.5.3.1" },
    { week: 30, topic: "Sesin Maddeyle Etkileşimi: Yansıma, Soğurulma, Yalıtım", outcome: "F.6.5.4.1" },
    { week: 31, topic: "Denetleyici ve Düzenleyici Sistemler: Beyin, Beyincik, Omurilik", outcome: "F.6.6.1.1" },
    { week: 32, topic: "Refleks Olayı ve İç Salgı Bezleri (Hormonlar)", outcome: "F.6.6.1.2" },
    { week: 33, topic: "Duyu Organları: Göz, Kulak, Burun, Dil, Deri", outcome: "F.6.6.2.1" },
    { week: 34, topic: "Elektriksel İletkenlik ve Yalıtkanlık", outcome: "F.6.7.1.1" },
    { week: 35, topic: "Elektriksel Direnç ve Bağlı Olduğu Faktörler (Boy, Kesit)", outcome: "F.6.7.2.1" },
    { week: 36, topic: "6. Sınıf Fen Bilimleri Bütüncül Deneme", outcome: "F.6.LGS.01" }
  ],
  sosyal: [
    { week: 1, topic: "Değişen Rollerim: Hak ve Sorumluluk Bilinci", outcome: "SB.6.1.1" },
    { week: 2, topic: "Kültürümüzle Yaşıyor ve Gelişiyoruz (Maddi/Manevi Değerler)", outcome: "SB.6.1.2" },
    { week: 3, topic: "Önyargıları Kırıyorum: Hoşgörü ve Empati", outcome: "SB.6.1.3" },
    { week: 4, topic: "Farklılıklara Saygı ve Toplumsal Birliktelik", outcome: "SB.6.1.4" },
    { week: 5, topic: "Tarihe Yolculuk: Destan ve Yazıtlarda İlk Türk Devletleri", outcome: "SB.6.2.1" },
    { week: 6, topic: "Orta Asya Türk Kültürü: Yaşam Tarzı ve Yönetim", outcome: "SB.6.2.2" },
    { week: 7, topic: "İslamiyet'in Doğuşu ve Yayılışı (Dört Halife Dönemi)", outcome: "SB.6.2.3" },
    { week: 8, topic: "Türklerin İslamiyet'i Kabulü ve İlk Türk-İslam Devletleri", outcome: "SB.6.2.4" },
    { week: 9, topic: "Karahanlılar, Gazneliler ve Büyük Selçuklu Devleti", outcome: "SB.6.2.5" },
    { week: 10, topic: "Yeni Yurt Anadolu: Malazgirt Zaferi ve Beylikler", outcome: "SB.6.2.6" },
    { week: 11, topic: "Tarihî Ticaret Yolları: İpek ve Baharat Yolu", outcome: "SB.6.2.7" },
    { week: 12, topic: "Dünya'nın Neresindeyiz: Paralel, Meridyen ve Koordinat", outcome: "SB.6.3.1" },
    { week: 13, topic: "Türkiye'nin Coğrafi Konumu (Matematik ve Özel Konum)", outcome: "SB.6.3.2" },
    { week: 14, topic: "Türkiye'nin Fiziki Coğrafyası: Dağlar, Ovalar, Platolar, Akarsular", outcome: "SB.6.3.3" },
    { week: 15, topic: "Türkiye'nin İklimi ve Bitki Örtüsü Özellikleri", outcome: "SB.6.3.4" },
    { week: 16, topic: "Farklı İklimlerde Yaşam: Ekvatoral, Kutup, Çöl, Muson", outcome: "SB.6.3.5" },
    { week: 17, topic: "Tıp ve Matematik Öncüleri: İbn-i Sina, Harizmi, Farabi", outcome: "SB.6.4.1" },
    { week: 18, topic: "Matbaanın Gelişimi ve Bilginin Yayılması", outcome: "SB.6.4.2" },
    { week: 19, topic: "Bilimsel Araştırma Basamakları ve Kaynakça Gösterme", outcome: "SB.6.4.3" },
    { week: 20, topic: "Telif ve Patent Haklarının Önemi", outcome: "SB.6.4.4" },
    { week: 21, topic: "Ülkemizin Doğal Kaynakları: Topraklarımız ve Tarım", outcome: "SB.6.5.1" },
    { week: 22, topic: "Sularımız ve Denizlerimiz: Balıkçılık, Ulaşım, Turizm", outcome: "SB.6.5.2" },
    { week: 23, topic: "Ormanlarımız ve Maden Kaynaklarımız", outcome: "SB.6.5.3" },
    { week: 24, topic: "Türkiye'de Enerji Kaynakları (Yenilenebilir ve Tükenebilir)", outcome: "SB.6.5.4" },
    { week: 25, topic: "Yatırım ve Pazarlama: Coğrafi Şartlara Göre Yatırım Projeleri", outcome: "SB.6.5.5" },
    { week: 26, topic: "Vergilerimizle Büyüyoruz: Vatandaşlık Görevimiz", outcome: "SB.6.5.6" },
    { week: 27, topic: "Mesleğimi Seçiyorum: İlgi, Yetenek ve Meslek Analizi", outcome: "SB.6.5.7" },
    { week: 28, topic: "Demokrasinin Temel İlkeleri: Millî Egemenlik, Eşitlik, Özgürlük", outcome: "SB.6.6.1" },
    { week: 29, topic: "Yönetim Biçimleri: Monarşi, Oligarşi, Teokrasi, Cumhuriyet", outcome: "SB.6.6.2" },
    { week: 30, topic: "Türkiye Cumhuriyeti Devleti'nin Temel Organları (Yasama, Yürütme, Yargı)", outcome: "SB.6.6.3" },
    { week: 31, topic: "Karar Alma Sürecinde Ben de Varım: Kamuoyu ve Sivil Toplum", outcome: "SB.6.6.4" },
    { week: 32, topic: "Kanun Önünde Eşitlik ve Kadın Haklarının Gelişimi", outcome: "SB.6.6.5" },
    { week: 33, topic: "Komşularımız ve Türk Cumhuriyetleri ile İlişkilerimiz", outcome: "SB.6.7.1" },
    { week: 34, topic: "Uluslararası Kuruluşlar (BM, NATO, TİKA, UNESCO)", outcome: "SB.6.7.2" },
    { week: 35, topic: "Uluslararası Ticaret ve Dış Alım / Dış Satım", outcome: "SB.6.7.3" },
    { week: 36, topic: "6. Sınıf Sosyal Bilgiler Yıl Sonu Denemesi", outcome: "SB.6.LGS.01" }
  ]
};

export const ACADEMIC_CALENDAR_GRADE_7 = {
  turkce: [
    { week: 1, topic: "Fiillerde Anlam (İş, Oluş, Durum Fiilleri)", outcome: "T.7.4.1" },
    { week: 2, topic: "Fiil Çekimi: Haber (Bildirme) Kipleri", outcome: "T.7.4.2" },
    { week: 3, topic: "Fiil Çekimi: Dilek (Tasarlama) Kipleri", outcome: "T.7.4.3" },
    { week: 4, topic: "Fiillerde Kişi (Şahıs) Ekleri ve Olumsuzluk", outcome: "T.7.4.4" },
    { week: 5, topic: "Fiillerde Anlam (Zaman) Kayması", outcome: "T.7.4.5" },
    { week: 6, topic: "Ek Fiil (İsimlere Gelen Ek Fiil ve İşlevleri)", outcome: "T.7.4.6" },
    { week: 7, topic: "Ek Fiil (Basit Zamanlı Fiilleri Birleşik Zamanlı Yapma)", outcome: "T.7.4.7" },
    { week: 8, topic: "Zarflar (Belirteçler): Durum, Zaman, Miktar, Yer-Yön, Soru", outcome: "T.7.4.8" },
    { week: 9, topic: "Zarfların Cümleye Kattığı Anlamlar", outcome: "T.7.4.9" },
    { week: 10, topic: "Fiillerde Yapı: Basit, Türemiş ve Birleşik Fiiller", outcome: "T.7.4.10" },
    { week: 11, topic: "Kurallı Birleşik Fiiller (Yeterlilik, Tezlik, Süreklilik, Yaklaşma)", outcome: "T.7.4.11" },
    { week: 12, topic: "Deyimleşmiş ve Yardımcı Eylemle Kurulan Birleşik Fiiller", outcome: "T.7.4.12" },
    { week: 13, topic: "Paragrafta Ana Düşünce ve Vurgu", outcome: "T.7.3.1" },
    { week: 14, topic: "Paragrafta Yardımcı Fikirler ve Yargı Tespiti", outcome: "T.7.3.2" },
    { week: 15, topic: "Düşüncenin Akışını Bozan Cümle ve İkiye Bölme", outcome: "T.7.3.3" },
    { week: 16, topic: "Anlatım Biçimleri: Öyküleme, Betimleme, Açıklama, Tartışma", outcome: "T.7.3.4" },
    { week: 17, topic: "Düşünceyi Geliştirme Yolları (Tanık Gösterme, Karşılaştırma)", outcome: "T.7.3.5" },
    { week: 18, topic: "Metin Türleri: Söyleşi (Sohbet) ve Fıkra (Köşe Yazısı)", outcome: "T.7.3.6" },
    { week: 19, topic: "Metin Türleri: Deneme, Makale ve Biyografi", outcome: "T.7.3.7" },
    { week: 20, topic: "Söz Sanatları: Teşbih, Teşhis, İntak, Tezat, Mübalağa", outcome: "T.7.3.8" },
    { week: 21, topic: "Cümlede Anlam İlişkileri (Neden, Amaç, Koşul)", outcome: "T.7.1.1" },
    { week: 22, topic: "Örtülü Anlam ve Cümle Yorumu", outcome: "T.7.1.2" },
    { week: 23, topic: "Deyimler ve Atasözleri Tahlili", outcome: "T.7.1.3" },
    { week: 24, topic: "Yazım Kuralları: Büyük Harfler ve Kısaltmalar", outcome: "T.7.4.13" },
    { week: 25, topic: "Yazım Kuralları: Birleşik Sözcükler ve Eklerin Yazımı", outcome: "T.7.4.14" },
    { week: 26, topic: "Noktalama: Noktalı Virgül ve İki Nokta", outcome: "T.7.4.15" },
    { week: 27, topic: "Noktalama: Tırnak İşareti ve Kesme İşareti İstisnaları", outcome: "T.7.4.16" },
    { week: 28, topic: "Sözel Mantık: Çoklu Değişkenli Tablo Analizi", outcome: "T.7.3.9" },
    { week: 29, topic: "Sözel Mantık: Şifreleme ve Sıralama Problemleri", outcome: "T.7.3.10" },
    { week: 30, topic: "Görsel, Grafik ve İnfografik Yorumlama", outcome: "T.7.3.11" },
    { week: 31, topic: "Diyalog Tamamlama ve Metin Karşılaştırma", outcome: "T.7.3.12" },
    { week: 32, topic: "Eleştirel Okuma ve Metin Çözümleme", outcome: "T.7.3.13" },
    { week: 33, topic: "7. Sınıf Türkçe LGS Hazırlık Denemesi - I", outcome: "T.7.LGS.01" },
    { week: 34, topic: "7. Sınıf Türkçe LGS Hazırlık Denemesi - II", outcome: "T.7.LGS.02" },
    { week: 35, topic: "7. Sınıf Yıl Sonu Bütüncül Sözel Prova - I", outcome: "T.7.LGS.03" },
    { week: 36, topic: "7. Sınıf Yıl Sonu Bütüncül Sözel Prova - II", outcome: "T.7.LGS.04" }
  ],
  matematik: [
    { week: 1, topic: "Tam Sayılarla Toplama ve Çıkarma İşlemleri", outcome: "M.7.1.1.1" },
    { week: 2, topic: "Tam Sayılarla Çarpma ve Bölme İşlemleri", outcome: "M.7.1.1.2" },
    { week: 3, topic: "Tam Sayıların Tam Sayı Kuvvetleri (Üslü Nicelikler)", outcome: "M.7.1.1.3" },
    { week: 4, topic: "Tam Sayı Problemleri ve Çok Adımlı İşlemler", outcome: "M.7.1.1.4" },
    { week: 5, topic: "Rasyonel Sayılar: Sayı Doğrusunda Gösterimi ve Sıralama", outcome: "M.7.1.2.1" },
    { week: 6, topic: "Devirli Ondalık Gösterimleri Rasyonel Sayıya Dönüştürme", outcome: "M.7.1.2.2" },
    { week: 7, topic: "Rasyonel Sayılarla Toplama ve Çıkarma İşlemleri", outcome: "M.7.1.3.1" },
    { week: 8, topic: "Rasyonel Sayılarla Çarpma ve Bölme İşlemleri", outcome: "M.7.1.3.2" },
    { week: 9, topic: "Rasyonel Sayıların Kare ve Küpleri", outcome: "M.7.1.3.3" },
    { week: 10, topic: "Rasyonel Sayılarla Çok Adımlı İşlemler ve Merdivenli Kesirler", outcome: "M.7.1.3.4" },
    { week: 11, topic: "Rasyonel Sayı Problemleri (Gerçek Yaşam Senaryoları)", outcome: "M.7.1.3.5" },
    { week: 12, topic: "Cebirsel İfadelerle Toplama ve Çıkarma İşlemleri", outcome: "M.7.2.1.1" },
    { week: 13, topic: "Bir Doğal Sayı ile Cebirsel İfadeyi Çarpma", outcome: "M.7.2.1.2" },
    { week: 14, topic: "Sayı Örüntülerinin Genel Kuralını (n) Bulma", outcome: "M.7.2.1.3" },
    { week: 15, topic: "Eşitliğin Korunumu İlkesi ve Terazi Denge Modelleri", outcome: "M.7.2.2.1" },
    { week: 16, topic: "Birinci Dereceden Bir Bilinmeyenli Denklemler", outcome: "M.7.2.2.2" },
    { week: 17, topic: "Parantezli ve Rasyonel Katsayılı Denklem Çözümü", outcome: "M.7.2.2.3" },
    { week: 18, topic: "Birinci Dereceden Bir Bilinmeyenli Denklem Problemleri", outcome: "M.7.2.2.4" },
    { week: 19, topic: "Oran Kavramı ve Orantı Sabiti (k)", outcome: "M.7.1.4.1" },
    { week: 20, topic: "Doğru Orantı ve Problem Çözümleri", outcome: "M.7.1.4.2" },
    { week: 21, topic: "Ters Orantı ve Problem Çözümleri", outcome: "M.7.1.4.3" },
    { week: 22, topic: "Doğru ve Ters Orantı Karışık Problemleri (İşçi, Havuz, Yol)", outcome: "M.7.1.4.4" },
    { week: 23, topic: "Yüzde Hesaplamaları: Bir Çokluğun Yüzdesini Bulma", outcome: "M.7.1.5.1" },
    { week: 24, topic: "Yüzde ile Artırma ve Azaltma (KDV, İndirim, Zam)", outcome: "M.7.1.5.2" },
    { week: 25, topic: "Kâr-Zarar Problemleri ve Faiz Hesaplamaları", outcome: "M.7.1.5.3" },
    { week: 26, topic: "Açılar: Bir Açının Açıortayı", outcome: "M.7.3.1.1" },
    { week: 27, topic: "İki Paralel Doğruyla Bir Kesenin Oluşturduğu Açılar (Z, U, M Kuralları)", outcome: "M.7.3.1.2" },
    { week: 28, topic: "Çokgenler: Düzgün Çokgenler ve İç/Dış Açı Özellikleri", outcome: "M.7.3.2.1" },
    { week: 29, topic: "Özel Dörtgenler: Paralelkenar, Eşkenar Dörtgen, Dikdörtgen, Kare, Yamuk", outcome: "M.7.3.2.2" },
    { week: 30, topic: "Eşkenar Dörtgen ve Yamuğun Alanı", outcome: "M.7.3.2.3" },
    { week: 31, topic: "Çemberde Merkez Açı ve Gördüğü Yay İlişkisi", outcome: "M.7.3.3.1" },
    { week: 32, topic: "Çember Yayının Uzunluğu ve Çevre Hesaplamaları", outcome: "M.7.3.3.2" },
    { week: 33, topic: "Dairenin ve Daire Diliminin Alanı (πr² x α/360)", outcome: "M.7.3.3.3" },
    { week: 34, topic: "Veri Analizi: Çizgi Grafiği Çizme ve Yorumlama", outcome: "M.7.4.1.1" },
    { week: 35, topic: "Daire Grafiği ve Grafikler Arası Dönüşüm (360 Derece Dağılımı)", outcome: "M.7.4.1.2" },
    { week: 36, topic: "7. Sınıf Yıl Sonu Bütüncül Sayısal Prova", outcome: "M.7.LGS.01" }
  ],
  fen: [
    { week: 1, topic: "Uzay Araştırmaları: Roketler, Uydular ve Uzay İstasyonları", outcome: "F.7.1.1.1" },
    { week: 2, topic: "Uzay Kirliliği ve Çözüm Önerileri", outcome: "F.7.1.1.2" },
    { week: 3, topic: "Teleskobun Yapısı ve Tarihsel Gelişimi (Aynalı/Mercekli)", outcome: "F.7.1.1.3" },
    { week: 4, topic: "Güneş Sistemi Ötesi Gök Cisimleri: Yıldızlar ve Yaşam Döngüsü", outcome: "F.7.1.2.1" },
    { week: 5, topic: "Bulutsu (Nebula), Karadelik ve Galaksiler (Samanyolu, Andromeda)", outcome: "F.7.1.2.2" },
    { week: 6, topic: "Hücrenin Temel Kısımları: Çekirdek, Sitoplazma, Hücre Zarı", outcome: "F.7.2.1.1" },
    { week: 7, topic: "Hücre Organelleri ve Görevleri (Bitki ve Hayvan Hücresi Farkları)", outcome: "F.7.2.1.2" },
    { week: 8, topic: "Hücre - Doku - Organ - Sistem - Organizma İlişkisi", outcome: "F.7.2.1.3" },
    { week: 9, topic: "Mitoz Bölünme: Evreleri ve Canlılar İçin Önemi (Kromozom Sayısı)", outcome: "F.7.2.2.1" },
    { week: 10, topic: "Mayoz Bölünme: Mayoz I ve Mayoz II Evreleri", outcome: "F.7.2.3.1" },
    { week: 11, topic: "Parça Değişimi (Krossing-over) ve Genetik Çeşitlilik", outcome: "F.7.2.3.2" },
    { week: 12, topic: "Mitoz ve Mayoz Bölünme Karşılaştırmalı Analizi", outcome: "F.7.2.3.3" },
    { week: 13, topic: "Kütle ve Ağırlık Kavramları Arasındaki Farklar", outcome: "F.7.3.1.1" },
    { week: 14, topic: "Yer Çekimi Kuvveti ve Gök Cisimlerinde Ağırlık", outcome: "F.7.3.1.2" },
    { week: 15, topic: "Fiziksel Anlamda İş: Kuvvet x Yol İlişkisi", outcome: "F.7.3.2.1" },
    { week: 16, topic: "Kinetik Enerji ve Değişkenleri (Kütle ve Sürat)", outcome: "F.7.3.3.1" },
    { week: 17, topic: "Potansiyel Enerji (Çekim ve Esneklik Potansiyel Enerjisi)", outcome: "F.7.3.3.2" },
    { week: 18, topic: "Enerjinin Korunumu ve Dönüşümü (Sürtünmesiz Ortam)", outcome: "F.7.3.4.1" },
    { week: 19, topic: "Sürtünme Kuvveti ve Enerji Kaybı (Isıya Dönüşüm)", outcome: "F.7.3.4.2" },
    { week: 20, topic: "Maddenin Tanecikli Yapısı ve Atom Modelleri (Democritus'tan Günümüze)", outcome: "F.7.4.1.1" },
    { week: 21, topic: "Atomun Temel Parçacıkları: Proton, Nötron, Elektron", outcome: "F.7.4.1.2" },
    { week: 22, topic: "Saf Maddeler: Elementler, Sembolleri ve Periyodik Sistem Giriş", outcome: "F.7.4.2.1" },
    { week: 23, topic: "Bileşikler ve Formülleri (Su, Tuz, Karbondioksit vb.)", outcome: "F.7.4.2.2" },
    { week: 24, topic: "Karışımlar: Homojen (Çözelti) ve Heterojen Karışımlar", outcome: "F.7.4.3.1" },
    { week: 25, topic: "Çözünme Hızını Etkileyen Faktörler (Sıcaklık, Temas Yüzeyi, Karıştırma)", outcome: "F.7.4.3.2" },
    { week: 26, topic: "Karışımların Ayrılması Yöntemleri (Buharlaştırma, Damıtma, Yoğunluk)", outcome: "F.7.4.4.1" },
    { week: 27, topic: "Evsel Atıklar ve Geri Dönüşümün Önemi", outcome: "F.7.4.5.1" },
    { week: 28, topic: "Işığın Soğurulması ve Koyu/Açık Renklerin Etkisi", outcome: "F.7.5.1.1" },
    { week: 29, topic: "Düzlem Aynalar ve Görüntü Özellikleri", outcome: "F.7.5.2.1" },
    { week: 30, topic: "Küresel Aynalar: Çukur ve Tümsek Aynalar", outcome: "F.7.5.2.2" },
    { week: 31, topic: "Işığın Kırılması ve Kırılma Kanunları", outcome: "F.7.5.3.1" },
    { week: 32, topic: "Mercekler (İnce ve Kalın Kenarlı Mercekler, Odak Noktası)", outcome: "F.7.5.4.1" },
    { week: 33, topic: "İnsanda Üreme, Büyüme ve Gelişme (Üreme Organları, Zigot, Fetüs)", outcome: "F.7.6.1.1" },
    { week: 34, topic: "Bitki ve Hayvanlarda Üreme (Eşeyli ve Eşeysiz Üreme Çeşitleri)", outcome: "F.7.6.2.1" },
    { week: 35, topic: "Ampullerin Bağlanma Şekilleri: Seri ve Paralel Bağlama", outcome: "F.7.7.1.1" },
    { week: 36, topic: "Elektrik Akımı, Gerilim (Voltaj) ve Ohm Kanunu (V = I x R)", outcome: "F.7.7.1.2" }
  ],
  sosyal: [
    { week: 1, topic: "İletişimin Gücü: İletişim Türleri ve Beden Dili", outcome: "SB.7.1.1" },
    { week: 2, topic: "Olumlu ve Olumsuz İletişim (Ben Dili - Sen Dili)", outcome: "SB.7.1.2" },
    { week: 3, topic: "Medya ve İletişim: Doğru Bilgiye Ulaşma ve Medya Okuryazarlığı", outcome: "SB.7.1.3" },
    { week: 4, topic: "Düşünce ve İfade Özgürlüğü, Doğru Haber Alma Hakkı", outcome: "SB.7.1.4" },
    { week: 5, topic: "Beylikten Cihan Devletine: Osmanlı Devleti'nin Kuruluşu", outcome: "SB.7.2.1" },
    { week: 6, topic: "Osmanlı'nın Kısa Sürede Büyümesini Sağlayan Faktörler", outcome: "SB.7.2.2" },
    { week: 7, topic: "Gaza ve Cihat Anlayışı, İskân ve İstimâlet (Hoşgörü) Politikası", outcome: "SB.7.2.3" },
    { week: 8, topic: "Fethin Müjdesi: İstanbul'un Fethi ve Dünya Tarihindeki Sonuçları", outcome: "SB.7.2.4" },
    { week: 9, topic: "Denizlerde Hâkimiyet: Karadeniz ve Akdeniz'in Türk Gölü Olması", outcome: "SB.7.2.5" },
    { week: 10, topic: "Osmanlı Kültür ve Medeniyeti: Divan-ı Hümayun ve Toplum Yapısı", outcome: "SB.7.2.6" },
    { week: 11, topic: "Avrupa'daki Gelişmeler: Coğrafi Keşifler, Rönesans ve Reform", outcome: "SB.7.2.7" },
    { week: 12, topic: "Aydınlanma Çağı ve Sanayi İnkılabı'nın Osmanlı'ya Etkileri", outcome: "SB.7.2.8" },
    { week: 13, topic: "Osmanlı'da Islahat Hareketleri (Lale Devri, Tanzimat, Meşrutiyet)", outcome: "SB.7.2.9" },
    { week: 14, topic: "Nereden Nereye: Türkiye'de Nüfusun Dağılışı ve Etkileyen Faktörler", outcome: "SB.7.3.1" },
    { week: 15, topic: "Türkiye'nin Nüfus Özellikleri ve Nüfus Piramitleri", outcome: "SB.7.3.2" },
    { week: 16, topic: "Göçün Neden ve Sonuçları (İç ve Dış Göç, Beyin Göçü)", outcome: "SB.7.3.3" },
    { week: 17, topic: "Yerleşme ve Seyahat Özgürlüğü Anayasal Hakkı", outcome: "SB.7.3.4" },
    { week: 18, topic: "Kil Tabletten Akıllı Tablete: Yazının ve Bilginin Serüveni", outcome: "SB.7.4.1" },
    { week: 19, topic: "Türk-İslam Dünyasında Bilim İnsanları (Harezmi, Ali Kuşçu, Katip Çelebi)", outcome: "SB.7.4.2" },
    { week: 20, topic: "Avrupa'da Bilimsel Aydınlanma (Kopernik, Galileo, Newton)", outcome: "SB.7.4.3" },
    { week: 21, topic: "Özgür Düşüncenin Bilime Katkısı", outcome: "SB.7.4.4" },
    { week: 22, topic: "Toprak Ana: Tarih Boyunca Toprağın Yönetimi (İkta ve Tımar)", outcome: "SB.7.5.1" },
    { week: 23, topic: "Üretim Teknolojisi Hayatımızı Değiştiriyor (Buhar Makinesinden Robotlara)", outcome: "SB.7.5.2" },
    { week: 24, topic: "Vakıf Demek Medeniyet Demektir: Sosyal Dayanışma Kurumları", outcome: "SB.7.5.3" },
    { week: 25, topic: "İşinin Ehli İnsan Yetiştirmek: Ahilik Teşkilatı ve Mesleki Eğitim", outcome: "SB.7.5.4" },
    { week: 26, topic: "Geleceğin Meslekleri ve Dijital Ekonomi", outcome: "SB.7.5.5" },
    { week: 27, topic: "Demokrasinin Serüveni: İlk Çağ'dan Günümüze Demokrasi", outcome: "SB.7.6.1" },
    { week: 28, topic: "Magna Carta'dan İnsan Hakları Evrensel Beyannamesi'ne", outcome: "SB.7.6.2" },
    { week: 29, topic: "Türkiye Cumhuriyeti'nde Demokrasinin Gelişimi", outcome: "SB.7.6.3" },
    { week: 30, topic: "Demokratik Vatandaşlık ve Seçme-Seçilme Hakkı", outcome: "SB.7.6.4" },
    { week: 31, topic: "Türkiye'nin Bölgesel ve Küresel Gücü", outcome: "SB.7.7.1" },
    { week: 32, topic: "Kültürlerarası Köprü Türkiye: Dış Politika ve İş Birlikleri", outcome: "SB.7.7.2" },
    { week: 33, topic: "Küresel Sorunlar ve Çözüm Arayışları (İklim Değişikliği, Açlık, Göç)", outcome: "SB.7.7.3" },
    { week: 34, topic: "Uluslararası Yardım Kuruluşları ve İnsani Diplomasi", outcome: "SB.7.7.4" },
    { week: 35, topic: "7. Sınıf Sosyal Bilgiler Kazanım Denemesi - I", outcome: "SB.7.LGS.01" },
    { week: 36, topic: "7. Sınıf Sosyal Bilgiler Kazanım Denemesi - II", outcome: "SB.7.LGS.02" }
  ]
};
