/**
 * MEB Maarif LGS Platformu - 36 Haftalık Yıllık Müfredat ve Kazanım Takvimi
 * T.C. Millî Eğitim Bakanlığı & Türkiye Yüzyılı Maarif Modeli
 * 
 * 4 Branş (Türkçe, Matematik, Fen Bilimleri, T.C. İnkılap Tarihi) için
 * 36 haftalık ünite haritası, kazanım kodları, LGS çıkmış soru referansları
 * ve pedagojik merak/keşif bağlamlarını tanımlar.
 */

export const ACADEMIC_CALENDAR_36W = {
  turkce: [
    { week: 1, topic: "Sözcükte Anlam (Gerçek, Mecaz, Terim)", outcome: "T.8.1.1", lgsRef: "2024 LGS Soru 1 • Bağlamsal Anlam" },
    { week: 2, topic: "Söz Grupları, Deyim ve Atasözleri", outcome: "T.8.1.2", lgsRef: "2023 LGS Soru 2 • Kalıplaşmış Sözler" },
    { week: 3, topic: "Cümlede Anlam (Öznel-Nesnel ve Örtülü Anlam)", outcome: "T.8.1.3", lgsRef: "2022 LGS Soru 3 • Kanıtlanabilirlik" },
    { week: 4, topic: "Cümlede Anlam İlişkileri (Neden, Amaç, Koşul)", outcome: "T.8.1.4", lgsRef: "2021 LGS Soru 4 • Nedensellik Analizi" },
    { week: 5, topic: "Cümle Yorumlama ve Yakın Anlam", outcome: "T.8.1.5", lgsRef: "2020 LGS Soru 3 • Çıkarım Yapma" },
    { week: 6, topic: "Fiilimsiler (İsim-Fiiller)", outcome: "T.8.3.9", lgsRef: "2024 LGS Soru 5 • Kuralı Verilen Dil Bilgisi" },
    { week: 7, topic: "Fiilimsiler (Sıfat-Fiiller)", outcome: "T.8.3.10", lgsRef: "2023 LGS Soru 6 • Adlaşmış Sıfat-Fiil" },
    { week: 8, topic: "Fiilimsiler (Zarf-Fiiller ve Gruplar)", outcome: "T.8.3.11", lgsRef: "2022 LGS Soru 5 • Zarf-Fiil İşlevleri" },
    { week: 9, topic: "Paragrafta Ana Düşünce ve Vurgu", outcome: "T.8.3.14", lgsRef: "2024 LGS Soru 7 • Metin Omurgası" },
    { week: 10, topic: "Paragrafta Yardımcı Fikirler (Değinilmemiştir)", outcome: "T.8.3.15", lgsRef: "2024 LGS Soru 8 • Çoklu Tarama" },
    { week: 11, topic: "Paragrafın Yapısı (Giriş-Gelişme-Sonuç)", outcome: "T.8.3.16", lgsRef: "2023 LGS Soru 9 • Boşluk Doldurma" },
    { week: 12, topic: "Düşüncenin Akışını Bozan Cümle & İkiye Bölme", outcome: "T.8.3.17", lgsRef: "2022 LGS Soru 10 • Bakış Açısı Değişimi" },
    { week: 13, topic: "Düşünceyi Geliştirme Yolları (Tanımlama, Tanık Gösterme)", outcome: "T.8.3.18", lgsRef: "2024 LGS Soru 11 • Fikir Destekleri" },
    { week: 14, topic: "Anlatım Biçimleri (Öyküleme, Betimleme, Açıklama, Tartışma)", outcome: "T.8.3.19", lgsRef: "2023 LGS Soru 12 • Biçem Tahlili" },
    { week: 15, topic: "Cümlenin Ögeleri (Yüklem ve Özne)", outcome: "T.8.3.20", lgsRef: "2024 LGS Soru 13 • Temel Ögeler" },
    { week: 16, topic: "Cümlenin Ögeleri (Nesne ve Tamlayıcılar)", outcome: "T.8.3.21", lgsRef: "2023 LGS Soru 14 • Öge Dizilişi" },
    { week: 17, topic: "Ara Sözler, Cümle Vurgusu ve Çözümleme", outcome: "T.8.3.22", lgsRef: "2021 LGS Soru 13 • Vurgulu Öge" },
    { week: 18, topic: "Metin Türleri (Makale, Deneme, Fıkra, Söyleşi)", outcome: "T.8.3.23", lgsRef: "2024 LGS Soru 14 • Kanıtlama Amacı" },
    { week: 19, topic: "Metin Türleri (Biyografi, Anı, Günlük, Gezi)", outcome: "T.8.3.24", lgsRef: "2022 LGS Soru 15 • Olay Yazıları" },
    { week: 20, topic: "Söz Sanatları (Teşbih, Teşhis, İntak, Tezat, Mübalağa)", outcome: "T.8.3.25", lgsRef: "2024 LGS Soru 15 • Edebî Derinlik" },
    { week: 21, topic: "Fiilde Çatı (Öznesine Göre: Etken-Edilgen)", outcome: "T.8.3.26", lgsRef: "2020 LGS Soru 16 • İşi Yapan ve Sözde Özne" },
    { week: 22, topic: "Fiilde Çatı (Nesnesine Göre: Geçişli-Geçişsiz)", outcome: "T.8.3.27", lgsRef: "2019 LGS Soru 16 • Nesne Alabilirlik" },
    { week: 23, topic: "Cümle Türleri (Yapısına Göre: Tek Yüklemli, Fiilimsili)", outcome: "T.8.3.28", lgsRef: "2024 LGS Soru 16 • Birleşik Cümle" },
    { week: 24, topic: "Cümle Türleri (Birden Çok Yüklemli ve Bağlaçlı Cümleler)", outcome: "T.8.3.29", lgsRef: "2023 LGS Soru 17 • Sıralı-Bağlı Cümle" },
    { week: 25, topic: "Yazım Kuralları (Büyük Harfler, Kısaltmalar)", outcome: "T.8.4.1", lgsRef: "2024 LGS Soru 17 • TDK İmla Standardı" },
    { week: 26, topic: "Yazım Kuralları (Sayılar, 'de', 'ki', 'mi'nin Yazımı)", outcome: "T.8.4.2", lgsRef: "2023 LGS Soru 18 • Ek ve Bağlaç Ayrımı" },
    { week: 27, topic: "Noktalama İşaretleri (Nokta, Virgül, Noktalı Virgül)", outcome: "T.8.4.3", lgsRef: "2024 LGS Soru 18 • Virgülün Görevleri" },
    { week: 28, topic: "Noktalama İşaretleri (İki Nokta, Kesme İşareti, Tırnak)", outcome: "T.8.4.4", lgsRef: "2022 LGS Soru 18 • Kesme İşareti İstisnaları" },
    { week: 29, topic: "Anlatım Bozuklukları (Anlamsal ve Mantıksal)", outcome: "T.8.4.5", lgsRef: "2018 LGS Soru 19 • Sözcüğün Yanlış Anlamda Kullanımı" },
    { week: 30, topic: "Sözel Mantık ve Muhakeme (Sıralama ve Derecelendirme)", outcome: "T.8.3.30", lgsRef: "2024 LGS Soru 19 • Kronolojik Matris" },
    { week: 31, topic: "Sözel Mantık ve Muhakeme (Tablo Okuma ve Şifreleme)", outcome: "T.8.3.31", lgsRef: "2023 LGS Soru 19 • Çok Değişkenli Tablo" },
    { week: 32, topic: "Görsel, Grafik ve İnfografik Okuma", outcome: "T.8.3.32", lgsRef: "2024 LGS Soru 20 • Pasta-Çubuk Grafik Tahlili" },
    { week: 33, topic: "Metin Karşılaştırma ve Çapraz Tahlil", outcome: "T.8.3.33", lgsRef: "2022 LGS Soru 20 • İki Bağımsız Metin Sentezi" },
    { week: 34, topic: "Diyalog Tamamlama ve Gazeteci-Yazar Soruları", outcome: "T.8.3.34", lgsRef: "2021 LGS Soru 19 • İki Aşamalı Soru Eşleme" },
    { week: 35, topic: "Karma LGS Sözel Bölüm Prova Denemesi - I", outcome: "T.8.LGS.01", lgsRef: "MEB Maarif Bütüncül Sözel Model" },
    { week: 36, topic: "Karma LGS Sözel Bölüm Prova Denemesi - II", outcome: "T.8.LGS.02", lgsRef: "MEB Maarif Bütüncül Sözel Model" }
  ],

  matematik: [
    { week: 1, topic: "Pozitif Tam Sayıların Çarpanları ve Asal Çarpanlar", outcome: "M.8.1.1.1", lgsRef: "2024 LGS Soru 1 • Çarpan Ağacı" },
    { week: 2, topic: "EBOB Problemleri (Bütünden Parçaya - Şişeleme, Parselleme)", outcome: "M.8.1.1.2", lgsRef: "2024 LGS Soru 2 • EBOB ile Maliyet Optimizasyonu" },
    { week: 3, topic: "EKOK Problemleri (Parçadan Bütüne - Seferler, Nöbetler)", outcome: "M.8.1.1.3", lgsRef: "2023 LGS Soru 1 • Ortak Kat Modellemesi" },
    { week: 4, topic: "Aralarında Asal Sayılar ve Modelleme", outcome: "M.8.1.1.4", lgsRef: "2022 LGS Soru 1 • Asallık ve Kart Oyunu" },
    { week: 5, topic: "Tam Sayıların Tam Sayı Kuvvetleri (Negatif Üs)", outcome: "M.8.1.2.1", lgsRef: "2024 LGS Soru 3 • Negatif Kuvvet" },
    { week: 6, topic: "Üslü İfadelerde Çarpma ve Bölme İşlemleri", outcome: "M.8.1.2.2", lgsRef: "2023 LGS Soru 3 • Taban ve Üs Eşitleme" },
    { week: 7, topic: "Ondalık Gösterimlerin Çözümlenmesi ve 10'un Kuvvetleri", outcome: "M.8.1.2.3", lgsRef: "2022 LGS Soru 3 • Dijital Tartı Senaryosu" },
    { week: 8, topic: "Çok Büyük ve Çok Küçük Sayılar & Bilimsel Gösterim", outcome: "M.8.1.2.4", lgsRef: "2024 LGS Soru 4 • Mikrobiyolojik Boyut ve Bilimsel Notasyon" },
    { week: 9, topic: "Tam Kare Pozitif Sayılar ve Karekök Kavramı", outcome: "M.8.1.3.1", lgsRef: "2023 LGS Soru 4 • Kare Alanından Kenara Geçiş" },
    { week: 10, topic: "Kareköklü Sayının Yaklaşık Değeri ve Aralık Bulma", outcome: "M.8.1.3.2", lgsRef: "2024 LGS Soru 5 • Sayı Doğrusunda Cetvel Modeli" },
    { week: 11, topic: "Kareköklü İfadelerde a√b Gösterimi ve Katsayıyı İçeri Alma", outcome: "M.8.1.3.3", lgsRef: "2022 LGS Soru 5 • Kök İçine Alma" },
    { week: 12, topic: "Kareköklü İfadelerde Çarpma ve Bölme İşlemleri", outcome: "M.8.1.3.4", lgsRef: "2023 LGS Soru 5 • Dikdörtgen Alanı" },
    { week: 13, topic: "Kareköklü İfadelerde Toplama ve Çıkarma İşlemleri", outcome: "M.8.1.3.5", lgsRef: "2024 LGS Soru 6 • Şerit Uzunluğu ve Çevre Hesabı" },
    { week: 14, topic: "Doğal Sayı Yapan Çarpanlar ve İrrasyonel Sayılar", outcome: "M.8.1.3.6", lgsRef: "2021 LGS Soru 5 • Gerçek Sayılar Kümesi" },
    { week: 15, topic: "Veri Analizi: Çizgi ve Sütun Grafikleri", outcome: "M.8.4.1.1", lgsRef: "2024 LGS Soru 7 • Sıcaklık ve Satış Trendi" },
    { week: 16, topic: "Veri Analizi: Daire Grafiği ve Grafikler Arası Dönüşüm", outcome: "M.8.4.1.2", lgsRef: "2023 LGS Soru 7 • 360 Derece Açı Dağılımı" },
    { week: 17, topic: "Basit Olayların Olma Olasılığı: Olası Durumlar ve Eşit Şans", outcome: "M.8.5.1.1", lgsRef: "2022 LGS Soru 7 • Torbadan Çekiliş" },
    { week: 18, topic: "Bir Olayın Olma Olasılığı Hesabı", outcome: "M.8.5.1.2", lgsRef: "2024 LGS Soru 8 • İstenen / Tüm Durumlar" },
    { week: 19, topic: "Cebirsel İfadelerin Anlamı, Terimler ve Katsayılar", outcome: "M.8.2.1.1", lgsRef: "2023 LGS Soru 8 • Cebirsel Modelleme" },
    { week: 20, topic: "Cebirsel İfadelerle Çarpma ve Geometrik Alan Modelleri", outcome: "M.8.2.1.2", lgsRef: "2024 LGS Soru 9 • Şekil Üzerinde Alan Dağılımı" },
    { week: 21, topic: "Önemli Özdeşlikler: Tam Kare ve İki Kare Farkı", outcome: "M.8.2.1.3", lgsRef: "2024 LGS Soru 10 • (a-b)² ve a²-b² Kart Modeli" },
    { week: 22, topic: "Cebirsel İfadeleri Çarpanlarına Ayırma", outcome: "M.8.2.1.4", lgsRef: "2023 LGS Soru 10 • Ortak Çarpan Parantezi" },
    { week: 23, topic: "Birinci Dereceden Bir Bilinmeyenli Denklemler", outcome: "M.8.2.2.1", lgsRef: "2022 LGS Soru 9 • Terazi ve Denge Senaryoları" },
    { week: 24, topic: "Koordinat Sistemi ve Sıralı İkililer", outcome: "M.8.2.2.2", lgsRef: "2024 LGS Soru 11 • Düzlemde Nokta Konumu" },
    { week: 25, topic: "Doğrusal İlişkiler ve Tablo-Grafik Eşlemesi", outcome: "M.8.2.2.3", lgsRef: "2023 LGS Soru 11 • Sabit Değişim Oranı (y=mx)" },
    { week: 26, topic: "Doğrunun Eğimi ve Gerçek Hayat Uygulamaları", outcome: "M.8.2.2.4", lgsRef: "2024 LGS Soru 12 • Rampa, Merdiven ve Dikey/Yatay Oran" },
    { week: 27, topic: "Birinci Dereceden Bir Bilinmeyenli Eşitsizlikler", outcome: "M.8.2.3.1", lgsRef: "2024 LGS Soru 13 • Bütçe ve Kısıt Aralıkları" },
    { week: 28, topic: "Eşitsizliklerin Sayı Doğrusunda Çözümü", outcome: "M.8.2.3.2", lgsRef: "2023 LGS Soru 13 • Aralık Gösterimi" },
    { week: 29, topic: "Üçgende Kenarortay, Açıortay ve Yükseklik", outcome: "M.8.3.1.1", lgsRef: "2024 LGS Soru 14 • Katlama Çizgileri" },
    { week: 30, topic: "Üçgen Eşitsizliği ve Kenar-Açı Bağıntıları", outcome: "M.8.3.1.2", lgsRef: "2024 LGS Soru 15 • Üç Çubuktan Üçgen Oluşturma" },
    { week: 31, topic: "Pisagor Bağıntısı ve Uygulamaları", outcome: "M.8.3.1.3", lgsRef: "2024 LGS Soru 16 • Dik Üçgende Hipotenüs (3-4-5, 5-12-13)" },
    { week: 32, topic: "Eşlik ve Benzerlik: Benzerlik Oranı", outcome: "M.8.3.2.1", lgsRef: "2023 LGS Soru 16 • Gölge Boyu ve Benzer Üçgenler" },
    { week: 33, topic: "Dönüşüm Geometrisi (Öteleme ve Yansıma)", outcome: "M.8.3.3.1", lgsRef: "2024 LGS Soru 17 • Koordinat Düzleminde Simetri" },
    { week: 34, topic: "Dik Prizmalar ve Açınımları", outcome: "M.8.3.4.1", lgsRef: "2023 LGS Soru 18 • Kutu Katlama ve Yüzey Alanı" },
    { week: 35, topic: "Dik Dairesel Silindirin Alan ve Hacmi", outcome: "M.8.3.4.2", lgsRef: "2024 LGS Soru 18 • Sıvı Dolum ve r-h İlişkisi" },
    { week: 36, topic: "LGS Şampiyon Düzeyi Matematik Sentez Provası", outcome: "M.8.LGS.01", lgsRef: "MEB Maarif Üst Düzey Analiz ve Modelleme" }
  ],

  fen: [
    { week: 1, topic: "Dünya'nın Dönme Ekseni ve Mevsimlerin Oluşumu", outcome: "F.8.1.1.1", lgsRef: "2024 LGS Soru 1 • 21 Haziran ve 21 Aralık Modelleri" },
    { week: 2, topic: "Güneş Işınlarının Geliş Açısı, Birim Yüzey ve Gölge Boyu", outcome: "F.8.1.1.2", lgsRef: "2023 LGS Soru 1 • Termometre ve Işık Açısı Deneyi" },
    { week: 3, topic: "İklim ve Hava Olayları Arasındaki Farklar", outcome: "F.8.1.2.1", lgsRef: "2024 LGS Soru 2 • Meteorolog ve Klimatolog Görüşleri" },
    { week: 4, topic: "Rüzgâr Oluşumu (Yüksek ve Alçak Basınç Alanları)", outcome: "F.8.1.2.2", lgsRef: "2022 LGS Soru 2 • Mum Düzeneği ve Rüzgâr Yönü" },
    { week: 5, topic: "DNA'nın Yapısı, Nükleotitler ve Genetik Kod", outcome: "F.8.2.1.1", lgsRef: "2024 LGS Soru 3 • Fosfat-Şeker-Organik Baz Bağı" },
    { week: 6, topic: "DNA'nın Kendini Eşlemesi ve Hata Onarımı", outcome: "F.8.2.1.2", lgsRef: "2023 LGS Soru 3 • Yeni Zincir Oluşumu ve Eksik Nükleotit" },
    { week: 7, topic: "Kalıtım: Tek Karakter Çaprazlamaları (Genotip ve Fenotip)", outcome: "F.8.2.2.1", lgsRef: "2024 LGS Soru 4 • Bezelyelerde Baskın-Çekinik Genler" },
    { week: 8, topic: "İnsanda Cinsiyet Kalıtımı ve Akraba Evliliği Riskleri", outcome: "F.8.2.2.2", lgsRef: "2022 LGS Soru 4 • XX - XY Çaprazlaması" },
    { week: 9, topic: "Mutasyon ve Modifikasyon Karşılaştırmalı Analizi", outcome: "F.8.2.3.1", lgsRef: "2024 LGS Soru 5 • Çuha Çiçeği ve Sirke Sineği Deneyleri" },
    { week: 10, topic: "Adaptasyon ve Doğal Seçilim Mekanizması", outcome: "F.8.2.4.1", lgsRef: "2023 LGS Soru 5 • Kamuflaj ve Güve Kelebekleri" },
    { week: 11, topic: "Biyoteknoloji ve Genetik Mühendisliği Uygulamaları", outcome: "F.8.2.5.1", lgsRef: "2024 LGS Soru 6 • Gen Aktarımı ve Klonlama" },
    { week: 12, topic: "Katı Basıncı: Ağırlık ve Yüzey Alanı Değişkenleri", outcome: "F.8.3.1.1", lgsRef: "2024 LGS Soru 7 • Özdeş Tuğlalar ve Sünger Çökme Miktarı" },
    { week: 13, topic: "Sıvı Basıncı: Sıvı Derinliği ve Yoğunluğu", outcome: "F.8.3.1.2", lgsRef: "2024 LGS Soru 8 • U Borusu ve Manometre Düzenekleri" },
    { week: 14, topic: "Pascal Prensibi ve Hidrolik Sistemler", outcome: "F.8.3.1.3", lgsRef: "2023 LGS Soru 8 • Sıvıların Basıncı İletme İlkesi" },
    { week: 15, topic: "Gaz Basıncı: Açık Hava Basıncı ve Torricelli Deneyi", outcome: "F.8.3.1.4", lgsRef: "2024 LGS Soru 9 • Magdeburg Küreleri ve Cıva Sütunu" },
    { week: 16, topic: "Periyodik Sistem: Tarihsel Gelişim ve Grup/Periyot Mantığı", outcome: "F.8.4.1.1", lgsRef: "2023 LGS Soru 9 • Moseley ve Proton Numarası" },
    { week: 17, topic: "Elementlerin Sınıflandırılması (Metaller, Ametaller, Soygazlar)", outcome: "F.8.4.1.2", lgsRef: "2024 LGS Soru 10 • Isı ve Elektrik İletkenliği" },
    { week: 18, topic: "Fiziksel ve Kimyasal Değişimlerin Ayırt Edilmesi", outcome: "F.8.4.2.1", lgsRef: "2024 LGS Soru 11 • Paslanma, Yanma, Kırılma, Buharlaşma" },
    { week: 19, topic: "Kimyasal Tepkimeler ve Kütlenin Korunumu Kanunu", outcome: "F.8.4.3.1", lgsRef: "2024 LGS Soru 12 • Kapalı Kapta Gaz Çıkışı ve Kütle Grafiği" },
    { week: 20, topic: "Asitler ve Bazlar: Genel Özellikler ve Ayıraçlar (Turnusol, Fenolftalein)", outcome: "F.8.4.4.1", lgsRef: "2023 LGS Soru 12 • Renk Değişimi Deneyleri" },
    { week: 21, topic: "pH Kavramı, Asit-Baz Tepkimeleri ve Nötrleşme", outcome: "F.8.4.4.2", lgsRef: "2024 LGS Soru 13 • pH Ölçeği ve Tuz Oluşumu" },
    { week: 22, topic: "Asit Yağmurları ve Çevresel Etkileri", outcome: "F.8.4.4.3", lgsRef: "2022 LGS Soru 13 • Mermer ve Metal Yüzeylerin Aşınması" },
    { week: 23, topic: "Maddenin Isı ile Etkileşimi: Öz Isı ve Sıcaklık Değişimi", outcome: "F.8.4.5.1", lgsRef: "2024 LGS Soru 14 • Eşit Isıtılan Farklı Sıvılar" },
    { week: 24, topic: "Saf Maddelerde Hâl Değişimi ve Isınma/Soğuma Grafikleri", outcome: "F.8.4.5.2", lgsRef: "2023 LGS Soru 14 • Hâl Değişim Sıcaklığı Platosu" },
    { week: 25, topic: "Türkiye'de Kimya Endüstrisi ve Meslekler", outcome: "F.8.4.6.1", lgsRef: "2021 LGS Soru 14 • İthalat ve İhracat Verileri" },
    { week: 26, topic: "Basit Makineler: Kaldıraçlar ve Mekanik Avantaj", outcome: "F.8.5.1.1", lgsRef: "2024 LGS Soru 15 • Destek, Yük ve Kuvvet Kolu Oranları" },
    { week: 27, topic: "Basit Makineler: Sabit ve Hareketli Makaralar, Palangalar", outcome: "F.8.5.1.2", lgsRef: "2024 LGS Soru 16 • İp Çekilme Miktarı ve Kuvvetten Kazanç" },
    { week: 28, topic: "Basit Makineler: Eğik Düzlem, Çıkrık, Dişli Çarklar", outcome: "F.8.5.1.3", lgsRef: "2023 LGS Soru 16 • İşten Kazanç Yoktur İlkesi" },
    { week: 29, topic: "Besin Zinciri ve Enerji Akışı (Üretici, Tüketici, Ayrıştırıcı)", outcome: "F.8.6.1.1", lgsRef: "2024 LGS Soru 17 • Biyolojik Birikim ve Ekolojik Piramit" },
    { week: 30, topic: "Fotosentez Deneyleri ve Hızını Etkileyen Faktörler", outcome: "F.8.6.2.1", lgsRef: "2024 LGS Soru 18 • Işık Şiddeti, Renk ve CO2 Deney Düzeneği" },
    { week: 31, topic: "Hücresel Solunum: Oksijenli ve Oksijensiz (Fermantasyon)", outcome: "F.8.6.2.2", lgsRef: "2023 LGS Soru 18 • Maya Hücresi ve Gaz Balonu Deneyi" },
    { week: 32, topic: "Madde Döngüleri (Su, Karbon, Oksijen, Azot) ve Küresel Isınma", outcome: "F.8.6.3.1", lgsRef: "2022 LGS Soru 18 • Karbon Ayak İzi" },
    { week: 33, topic: "Elektriklenme Çeşitleri (Sürtünme, Dokunma ve Etki)", outcome: "F.8.7.1.1", lgsRef: "2024 LGS Soru 19 • Yün Kumaş-Ebonit ve İpek-Cam Çubuk" },
    { week: 34, topic: "Elektroskop ve Topraklama Uygulamaları", outcome: "F.8.7.1.2", lgsRef: "2024 LGS Soru 20 • Yaprakların Açılması ve Nötrleşme" },
    { week: 35, topic: "Elektrik Enerjisinin Isı, Işık ve Harekete Dönüşümü", outcome: "F.8.7.2.1", lgsRef: "2023 LGS Soru 20 • Sigorta ve Güvenlik Önlemleri" },
    { week: 36, topic: "LGS Şampiyon Düzeyi Fen Bilimleri Deney Sentez Provası", outcome: "F.8.LGS.01", lgsRef: "MEB Maarif Bilimsel Süreç Becerileri" }
  ],

  sosyal: [
    { week: 1, topic: "19. Yüzyıl Başlarında Osmanlı Devleti ve Fikir Akımları", outcome: "İTA.8.1.1", lgsRef: "2024 LGS Soru 1 • Fransız İhtilali ve Sanayi İnkılabı" },
    { week: 2, topic: "Mustafa Kemal'in Çocukluğu, Öğrenim Hayatı ve Şehirler", outcome: "İTA.8.1.2", lgsRef: "2023 LGS Soru 1 • Selanik, Manastır, İstanbul, Sofya" },
    { week: 3, topic: "Mustafa Kemal'in Askerlik Hayatı (Trablusgarp, Çanakkale)", outcome: "İTA.8.1.3", lgsRef: "2024 LGS Soru 2 • Teşkilatçılık ve Liderlik Vasıfları" },
    { week: 4, topic: "Mustafa Kemal'in Düşünce Dünyasını Etkileyen Yazarlar", outcome: "İTA.8.1.4", lgsRef: "2022 LGS Soru 1 • Ziya Gökalp, Namık Kemal, Montesquieu" },
    { week: 5, topic: "I. Dünya Savaşı'nın Sebepleri ve Osmanlı'nın Savaşa Girişi", outcome: "İTA.8.2.1", lgsRef: "2024 LGS Soru 3 • İttifak ve İtilaf Devletleri Stratejisi" },
    { week: 6, topic: "Osmanlı Devleti'nin Savaştığı Cepheler (Kafkas, Çanakkale, Kanal)", outcome: "İTA.8.2.2", lgsRef: "2023 LGS Soru 2 • Taarruz ve Savunma Cepheleri" },
    { week: 7, topic: "Mondros Ateşkes Antlaşması ve Anadolu'nun İşgali", outcome: "İTA.8.2.3", lgsRef: "2024 LGS Soru 4 • 7. ve 24. Maddelerin Hukuki Analizi" },
    { week: 8, topic: "Kuvâ-yı Millîye Ruhu ve Millî/Zararlı Cemiyetler", outcome: "İTA.8.2.4", lgsRef: "2023 LGS Soru 3 • Bölgesel Direnişten Topyekûn Savunmaya" },
    { week: 9, topic: "Mustafa Kemal'in Samsun'a Çıkışı ve Havza Genelgesi", outcome: "İTA.8.2.5", lgsRef: "2024 LGS Soru 5 • Millî Bilincin Uyandırılması" },
    { week: 10, topic: "Amasya Genelgesi: Millî Mücadele'nin Amacı, Gerekçesi ve Yöntemi", outcome: "İTA.8.2.6", lgsRef: "2024 LGS Soru 6 • 'Milletin Bağımsızlığını Yine Milletin Azmi...'" },
    { week: 11, topic: "Erzurum ve Sivas Kongreleri (Toplanış ve Kararlar Bakımından)", outcome: "İTA.8.2.7", lgsRef: "2023 LGS Soru 4 • Manda ve Himayenin Kesin Reddi" },
    { week: 12, topic: "Amasya Görüşmeleri, Misakımillî ve İstanbul'un Resmen İşgali", outcome: "İTA.8.2.8", lgsRef: "2022 LGS Soru 4 • Millî Sınırlar ve Kapitülasyonlar" },
    { week: 13, topic: "Büyük Millet Meclisinin Açılışı ve Nitelikleri", outcome: "İTA.8.2.9", lgsRef: "2024 LGS Soru 7 • Kurucu Meclis, Güçler Birliği İlkesi" },
    { week: 14, topic: "BMM'ye Karşı Ayaklanmalar ve Hıyanet-i Vataniye Kanunu", outcome: "İTA.8.2.10", lgsRef: "2023 LGS Soru 5 • İstiklal Mahkemeleri ve Otorite" },
    { week: 15, topic: "Sevr Antlaşması ve Türk Milletinin Kararlı Duruşu", outcome: "İTA.8.2.11", lgsRef: "2021 LGS Soru 5 • Ölü Doğan Antlaşma" },
    { week: 16, topic: "Doğu Cephesi ve Gümrü Antlaşması", outcome: "İTA.8.3.1", lgsRef: "2024 LGS Soru 8 • Kazım Karabekir ve İlk Siyasi Başarı" },
    { week: 17, topic: "Güney Cephesi ve Destansı Direnişler (Maraş, Antep, Urfa)", outcome: "İTA.8.3.2", lgsRef: "2023 LGS Soru 6 • Fransız ve Ermeni Çetelerine Karşı Mücadele" },
    { week: 18, topic: "Batı Cephesi: I. İnönü Zaferi, Londra Konferansı, İstiklal Marşı", outcome: "İTA.8.3.3", lgsRef: "2024 LGS Soru 9 • Düzenli Ordunun İlk Zaferi ve Moskova Antlaşması" },
    { week: 19, topic: "II. İnönü Zaferi ve Sonuçları", outcome: "İTA.8.3.4", lgsRef: "2022 LGS Soru 6 • 'Siz Orada Sadece Düşmanı Değil...'" },
    { week: 20, topic: "Kütahya-Eskişehir Muharebeleri ve Maarif Kongresi", outcome: "İTA.8.3.5", lgsRef: "2024 LGS Soru 10 • Savaş Ortasında Eğitime Verilen Önem" },
    { week: 21, topic: "Tekâlif-i Millîye Emirleri ve Topyekûn Dayanışma", outcome: "İTA.8.3.6", lgsRef: "2023 LGS Soru 7 • Ordunun Donatılması ve Millî Fedakarlık" },
    { week: 22, topic: "Sakarya Meydan Muharebesi: 'Hattı Müdafaa Yoktur...'", outcome: "İTA.8.3.7", lgsRef: "2024 LGS Soru 11 • Taktik Savunmadan Stratejik Zafere" },
    { week: 23, topic: "Büyük Taarruz ve Başkomutanlık Meydan Muharebesi", outcome: "İTA.8.3.8", lgsRef: "2023 LGS Soru 8 • Kesin Sonuç ve Yunan Ordusunun Çıkarılması" },
    { week: 24, topic: "Mudanya Ateşkes Antlaşması ve Diplomatik Kazanımlar", outcome: "İTA.8.3.9", lgsRef: "2022 LGS Soru 8 • Savaşsız Kurtarılan Bölgeler" },
    { week: 25, topic: "Lozan Barış Antlaşması: Bağımsızlığın Tescili ve Kapitülasyonlar", outcome: "İTA.8.3.10", lgsRef: "2024 LGS Soru 12 • Misakımillî'nin Kabul Ettirilmesi" },
    { week: 26, topic: "Atatürk İlkeleri: Cumhuriyetçilik ve Milliyetçilik", outcome: "İTA.8.4.1", lgsRef: "2024 LGS Soru 13 • Millî İrade ve Ortak Tarih Bilinci" },
    { week: 27, topic: "Atatürk İlkeleri: Halkçılık, Devletçilik, Laiklik, İnkılapçılık", outcome: "İTA.8.4.2", lgsRef: "2023 LGS Soru 9 • Sosyal Adalet ve Çağdaşlaşma" },
    { week: 28, topic: "Siyasi Alanda İnkılaplar (Saltanatın ve Halifeliğin Kaldırılması)", outcome: "İTA.8.4.3", lgsRef: "2024 LGS Soru 14 • Ulusal Egemenlik Yolunda Adımlar" },
    { week: 29, topic: "Hukuk Alanında İnkılaplar ve Türk Medeni Kanunu", outcome: "İTA.8.4.4", lgsRef: "2023 LGS Soru 10 • Kadın Hakları ve Hukukta Birlik" },
    { week: 30, topic: "Eğitim ve Kültür Alanında İnkılaplar (Tevhid-i Tedrisat, Harf İnkılabı)", outcome: "İTA.8.4.5", lgsRef: "2024 LGS Soru 15 • Maarif Seferberliği ve Millet Mektepleri" },
    { week: 31, topic: "Toplumsal ve Ekonomik Alanda İnkılaplar (İzmir İktisat Kongresi, Kabotaj)", outcome: "İTA.8.4.6", lgsRef: "2022 LGS Soru 10 • Millî İktisat ve Deniz Egemenliği" },
    { week: 32, topic: "Çok Partili Hayata Geçiş Denemeleri ve Rejime Yönelik Tehditler", outcome: "İTA.8.5.1", lgsRef: "2024 LGS Soru 16 • Demokrasi Kültürü ve Şeyh Sait/Menemen" },
    { week: 33, topic: "Atatürk Dönemi Türk Dış Politikası (Barışçılık, Gerçekçilik)", outcome: "İTA.8.6.1", lgsRef: "2023 LGS Soru 11 • 'Yurtta Sulh, Cihanda Sulh'" },
    { week: 34, topic: "Boğazlar Meselesi (Montrö) ve Balkan Antantı / Sadabat Paktı", outcome: "İTA.8.6.2", lgsRef: "2024 LGS Soru 17 • Bölgesel Güvenlik ve Tam Egemenlik" },
    { week: 35, topic: "Hatay'ın Ana Vatana Katılması ve Diplomatik Zafer", outcome: "İTA.8.6.3", lgsRef: "2024 LGS Soru 18 • Atatürk'ün Şahsi Meselesi" },
    { week: 36, topic: "Atatürk'ün Vefatı, Eserleri ve İkinci Dünya Savaşı Öncesi Türkiye", outcome: "İTA.8.7.1", lgsRef: "MEB Maarif Tarihsel Bilinç ve Değerlendirme" }
  ]
};
