// Original diagnostic drafts. Official curriculum/style reference does not imply MEB approval.
const reference='https://odsgm.meb.gov.tr/';
const programIds={mathematics:'legacy-2018-matematik',turkish:'legacy-2019-turkce',science:'legacy-2018-fen-bilimleri'};
function q(subject,n,topic,family,stimulus,stem,options,answer,strategy,steps,check,tip,figure){
 const prefix={mathematics:'M',turkish:'T',science:'F'}[subject];
 const reviewedOutcome=subject==='mathematics'?({16:'M.8.3.3.1',17:'M.8.3.4.1'}[n]):null;
 return {id:`P8-${prefix}${String(n).padStart(2,'0')}`,grade:8,subject,topic,familyId:family,stimulus,stem,options,answer,
 explanation:{given:stimulus,wanted:stem,strategy,steps,check,tip},
 source:{programId:programIds[subject],alignmentStatus:'draft',styleReference:reference,...(reviewedOutcome?{physicalPage:77}:{})},...(reviewedOutcome?{outcomeCode:reviewedOutcome}:{}),layout:stimulus.length>380?'extended':'regular',...(figure?{figure}:{})};
}
const fig=(body,alt)=>({svg:`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 360 150" role="img"><g font-family="Arial,sans-serif" font-size="12" fill="#222" stroke-width="1.4">${body}</g></svg>`,alt});
const rect=(x,y,w,h)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="none" stroke="#333"/>`;
const t=(x,y,s)=>`<text x="${x}" y="${y}" text-anchor="middle">${s}</text>`;
const line=(x,y,a,b)=>`<line x1="${x}" y1="${y}" x2="${a}" y2="${b}" stroke="#333"/>`;
const math=(...x)=>q('mathematics',...x),tr=(...x)=>q('turkish',...x),science=(...x)=>q('science',...x);
export const GRADE8_CORE_QUESTIONS=[
 math(1,'Çarpanlar ve katlar','gcd_packaging','Bir yardım paketi için 24 kalem ve 36 silgi, her pakette eşit sayıda kalem ve eşit sayıda silgi bulunacak biçimde ayrılacaktır. Malzemelerin tümü kullanılacak ve olabilecek en çok sayıda paket hazırlanacaktır.','Her paketteki kalem ve silgi sayılarının çarpımı kaçtır?',['5','6','12','24'],1,'Önce en çok paket sayısını EBOB ile bul, sonra bir paketteki iki miktarı hesapla.',['24 ve 36’nın EBOB’u 12’dir.','Bir pakette 24÷12=2 kalem ve 36÷12=3 silgi olur.','2×3=6 bulunur.'],'12 paket, tüm malzemeyi artıksız kullanır.','“En çok eş paket” ifadesi ortak böleni düşündürür.'),
 math(2,'Çarpanlar ve katlar','lcm_schedule','Bir duraktan geçen iki servis, sırasıyla 18 ve 24 dakikada bir hareket ediyor. İkisi de saat 08.00’de birlikte hareket ediyor.','08.00’den sonra üçüncü kez birlikte hareket ettiklerinde saat kaçtır?',['09.12','10.24','11.00','11.36'],3,'Birlikte hareket aralığını bul; 08.00 anını tekrar sayma.',['18 ve 24’ün EKOK’u 72’dir.','Sonraki ortak hareketler 09.12, 10.24 ve 11.36’dır.'],'3×72=216 dakika, yani 3 saat 36 dakika geçer.','Başlangıç anının sayılıp sayılmadığına dikkat et.'),
 math(3,'Üslü ifadeler','power_division','Bir depodaki 2¹² eş kart, her kutuda 2³ kart olacak biçimde kutulanıyor.','Kaç kutu kullanılır?',['128','256','512','1024'],2,'Toplam kart sayısını bir kutudaki kart sayısına böl.',['2¹²÷2³=2⁹.','2⁹=512.'],'512×8=4096 kart eder.','Aynı tabanlı üslü ifadeleri bölerken üsleri çıkar.'),
 math(4,'Üslü ifadeler','scientific_notation','Bir lifin kalınlığı 0,0002 metredir. Aynı kalınlıkta üç lif boşluk kalmadan üst üste yerleştiriliyor.','Toplam kalınlığın metre cinsinden bilimsel gösterimi hangisidir?',['6 × 10⁻⁴','6 × 10⁻³','0,6 × 10⁻⁴','6 × 10⁴'],0,'Üç lifin toplam kalınlığını bul, katsayıyı 1 ile 10 arasında yaz.',['3×0,0002=0,0006.','0,0006=6×10⁻⁴.'],'6×0,0001=0,0006.','Bilimsel gösterimde katsayı en az 1, 10’dan küçüktür.'),
 math(5,'Kareköklü ifadeler','root_integer_bounds','Alanı 170 cm² olan kare biçimindeki bir levhanın bir kenar uzunluğu a cm’dir.','a’dan küçük en büyük tam sayı kaçtır?',['12','13','14','15'],1,'Alanı iki ardışık tam kare arasında bul.',['13²=169, 14²=196.','169<170<196 olduğundan 13<√170<14.'],'13 cm kenarlı karenin alanı 170’ten az, 14 cm kenarlı olanınki fazladır.','Yakın tam kareler, kökün hangi iki tam sayı arasında olduğunu gösterir.'),
 math(6,'Kareköklü ifadeler','root_perimeter_square','Bir dikdörtgenin kenarları √18 cm ve √8 cm’dir. Bu dikdörtgenin çevresiyle aynı çevreye sahip bir eşkenar üçgen çiziliyor.','Üçgenin bir kenar uzunluğunun karesi kaç cm² olur?',['40/9','100/9','200/9','90'],2,'Önce kökleri sadeleştirip çevreyi bul; üçgenin çevresini üçe böl.',['√18=3√2 ve √8=2√2.','Dikdörtgenin çevresi 10√2 cm’dir.','Üçgenin bir kenarı 10√2/3 cm; karesi 200/9 cm² olur.'],'Üç eş kenarın toplamı tekrar 10√2 verir.','Çevreyi tek kenar uzunluğuyla karıştırma.'),
 math(7,'Olasılık','probability_without_selection_bias','Bir torbada 5 kırmızı, 4 mavi ve 3 sarı özdeş top vardır. Torbaya bakılmadan bir top çekiliyor.','Çekilen topun kırmızı olma olasılığı kaçtır?',['5/7','4/12','5/12','7/12'],2,'İstenen durumları bütün eş olasılıklı durumlara böl.',['Toplam 5+4+3=12 top vardır.','Kırmızı olan 5 top bulunduğundan olasılık 5/12’dir.'],'Pay 5, bütün top sayısı olan payda 12’den küçüktür.','Payda, yalnız diğer renkler değil tüm toplardır.'),
 math(8,'Veri analizi','pie_chart_angle','Bir sınıftaki 30 öğrencinin tercih ettiği kulüpler tabloda gösteriliyor.','Veriler daire grafiğine dönüştürülürse satranç kulübünü gösteren merkez açı kaç derece olur?',['60°','72°','108°','144°'],1,'Satranç seçenlerin bütüne oranını 360 dereceyle çarp.',['Satranç seçen 6 öğrenci, 30 öğrencinin 1/5’idir.','360÷5=72°.'],'Diğer açılarla birlikte toplam 360 derece olmalıdır.','Daire grafiğinde bütün 360 derecedir.',fig(rect(30,25,300,90)+line(30,55,330,55)+line(30,85,330,85)+line(210,25,210,115)+t(120,45,'Müzik')+t(270,45,'12 öğrenci')+t(120,75,'Spor')+t(270,75,'12 öğrenci')+t(120,105,'Satranç')+t(270,105,'6 öğrenci'),'Müzik 12, spor 12, satranç 6 öğrenci.')),
 math(9,'Cebirsel ifadeler','rectangle_identity','Kenarları (x+3) cm ve (x−3) cm olan bir dikdörtgende x=9’dur.','Dikdörtgenin alanı kaç cm²’dir?',['36','54','72','81'],2,'Kenarları yerine yazarak çarp veya iki kare farkından yararlan.',['9+3=12, 9−3=6.','12×6=72.'],'x²−9=81−9=72 aynı sonucu verir.','(a+b)(a−b)=a²−b².'),
 math(10,'Özdeşlikler','area_square_identity','Bir karenin bir kenarı (x−4) cm’dir; x>4.','Karenin alanını gösteren cebirsel ifade hangisidir?',['x² − 16','x² − 4x + 16','x² + 8x + 16','x² − 8x + 16'],3,'İki terimin farkının karesini aç.',['(x−4)²=x²−2·x·4+4².','Sonuç x²−8x+16’dır.'],'x=5 için alan 1 olur; doğru ifade 25−40+16=1 verir.','(a−b)²=a²−2ab+b²; orta terimi unutma.'),
 math(11,'Doğrusal denklemler','context_equation','Bir gezi için her öğrenci 40 TL ödüyor. Toplanan paradan 120 TL araç gideri karşılanınca geriye 120 TL kalıyor.','Geziye kaç öğrenci katılmıştır?',['3','6','8','12'],1,'Toplanan toplamı gider ve kalan tutarın toplamı olarak yaz.',['40x−120=120.','40x=240 olduğundan x=6.'],'6×40−120=120.','Kalan para toplam para değildir; harcananı da ekle.'),
 math(12,'Eşitsizlikler','integer_inequality','Bir atölyeye giriş 30 TL, hazırlanan her ürün için ek ücret 18 TL’dir. Ece’nin bu etkinlik için 110 TL’si vardır.','Ece en çok kaç ürün hazırlayabilir?',['3','4','5','6'],1,'Toplam ücretin bütçeyi aşmaması koşulunu kur.',['30+18x≤110; 18x≤80.','80÷18=4 kalan 8; en çok 4 ürün yapılır.'],'4 ürün 102 TL, 5 ürün 120 TL tutar.','Kesirli ürün yapılmıyorsa bulunan üst sınırın altındaki tam sayıyı al.'),
 math(13,'Doğrusal ilişki','table_linear_model','Bir bisiklet kiralama şirketinin ücretleri tabloda verilmiştir. Sabit açılış ücreti ve saat başına değişmeyen ücret alınmaktadır.','Bisikleti 5 saat kiralayan biri kaç TL öder?',['30','35','40','45'],2,'Saat artışındaki sabit farkı bul, sonra başlangıç ücretini ayır.',['Her ek saat 6 TL’dir.','1 saatte 16 TL ise açılış 10 TL’dir.','5 saat için 10+5×6=40 TL.'],'2 saatte 10+12=22 TL tabloyla uyumludur.','Tabloda sabit artış, doğrusal ilişkiyi fark ettirir.',fig(rect(30,25,300,90)+line(30,55,330,55)+line(30,85,330,85)+line(180,25,180,115)+t(105,45,'Süre (saat)')+t(255,45,'Ücret (TL)')+t(105,75,'1')+t(255,75,'16')+t(105,105,'2')+t(255,105,'22'),'1 saat 16 TL, 2 saat 22 TL.')),
 math(14,'Üçgenler','pythagoras','Bir duvara dayanan 13 m uzunluğundaki merdivenin alt ucu, duvarın tabanından yatay olarak 5 m uzaktadır. Duvar zemine diktir.','Merdivenin üst ucu yerden kaç metre yüksektedir?',['8','10','12','18'],2,'Merdiven dik üçgenin en uzun kenarıdır; Pisagor bağıntısını kur.',['h²+5²=13².','h²=169−25=144; h=12.'],'5²+12²=13².','Hipotenüsün karesi, iki dik kenarın kareleri toplamıdır.',fig(line(150,5,150,130)+line(140,130,220,130)+line(150,10,200,130)+line(150,120,160,120)+line(160,120,160,130)+t(204,70,'13 m')+t(175,146,'5 m')+t(133,75,'h'),'Duvara dayanan 13 m merdivenin alt ucu duvar tabanından 5 m uzaktadır. Duvar zemine diktir.')),
 math(15,'Üçgenler','triangle_inequality','Bir üçgenin iki kenarının uzunlukları 5 cm ve 7 cm’dir. Üçüncü kenarın uzunluğu tam sayıdır.','Üçüncü kenarın alabileceği en büyük değer kaç santimetredir?',['10','11','12','13'],1,'Üçüncü kenar, diğer ikisinin toplamından küçük olmalıdır.',['|7−5|<x<7+5; yani 2<x<12.','12’den küçük en büyük tam sayı 11’dir.'],'11+5>7, 11+7>5 ve 5+7>11 koşulları sağlanır.','Üçgen eşitsizliğinde sınır değerler dâhil değildir.'),
 math(16,'Eşlik ve benzerlik','similar_not_congruent','K dikdörtgeninin kenar uzunlukları 6 cm ve 9 cm’dir. Şekilde diğer dikdörtgenlerin kenar uzunlukları santimetre cinsinden verilmiştir.','Numaralanmış dikdörtgenlerden hangisi K dikdörtgenine benzer fakat eş değildir?',['I','II','III','IV'],1,'Eş şekillerin kenarları aynı, benzer şekillerin karşılıklı kenarları orantılıdır.',['I numaralı dikdörtgenin kenarları K ile aynı olduğundan K’ye eştir.','II için karşılıklı kenar oranları 4/6 ve 6/9 olup ikisi de 2/3’tür; uzunluklar K ile aynı değildir.','III ve IV’ün karşılıklı kenar oranları birbirine eşit değildir.'],'II’de iki kenar da K’nin karşılık gelen kenarının 2/3’üdür.','Eş olan şekiller benzerdir; benzer olan her şekil eş olmak zorunda değildir.',fig(rect(150,10,54,36)+t(177,62,'K: 6 × 9')+rect(45,93,54,36)+t(72,85,'6 × 9')+t(72,145,'I')+rect(127,105,36,24)+t(145,96,'4 × 6')+t(145,145,'II')+rect(194,105,48,24)+t(218,96,'4 × 8')+t(218,145,'III')+rect(270,111,54,18)+t(297,102,'3 × 9')+t(297,145,'IV'),'K: 6 ve 9 cm. I: 6 ve 9 cm. II: 4 ve 6 cm. III: 4 ve 8 cm. IV: 3 ve 9 cm.')),
 math(17,'Geometrik cisimler','prism_net_faces','Şekilde bir dikdörtgenler prizmasının açınımı verilmiştir. Yüzlerin üzerinde yazan sayılar, o yüzün kenar uzunluklarını santimetre cinsinden göstermektedir.','Soru işaretiyle gösterilen yüzün kenar uzunlukları hangisidir?',['6 cm × 4 cm','6 cm × 5 cm','4 cm × 5 cm','5 cm × 5 cm'],0,'Prizmada birbirine karşılık gelen yüzlerin eş dikdörtgenler olduğunu kullan.',['Açınımdaki dört yan yüz şerit oluşturur.','Şeridin üstündeki 6 cm × 4 cm yüz ile soru işaretli yüz prizmanın iki tabanıdır.','Tabanlar eş olduğundan eksik yüzün kenarları 6 cm ve 4 cm’dir.'],'Dört yan yüzün kenarları 6–4–6–4 sırasını izler; iki taban da 6 × 4 olmalıdır.','Bir açınımı düşünürken hangi yüzlerin karşılıklı kapanacağını belirle.',fig(rect(70,20,48,32)+rect(70,52,48,40)+rect(118,52,32,40)+rect(150,52,48,40)+rect(198,52,32,40)+`<rect x="150" y="92" width="48" height="32" fill="none" stroke="#333" stroke-dasharray="4 3"/>`+t(94,41,'6 × 4')+t(94,77,'6 × 5')+t(134,77,'4 × 5')+t(174,77,'6 × 5')+t(214,77,'4 × 5')+t(174,113,'?'),'Dört yan yüz sırayla 6 × 5, 4 × 5, 6 × 5 ve 4 × 5 cm. İlk yan yüzün üstünde 6 × 4 cm taban var. Üçüncü yan yüzün altında diğer taban soru işaretiyle gösteriliyor.')),
 math(18,'Geometrik cisimler','cylinder_volume','Dik dairesel silindirin taban yarıçapı 4 cm, yüksekliği 5 cm’dir. Bu soruda π=3 alınacaktır.','Silindirin hacmi kaç cm³’tür?',['60','120','240','480'],2,'Önce dairesel tabanın alanını, sonra hacmi bul.',['Taban alanı πr²=3×4²=48 cm².','Hacim 48×5=240 cm³.'],'Yarıçap 4’tür; çap 8’i yarıçap yerine kullanma.','Silindirde V=πr²h.',fig(`<ellipse cx="175" cy="30" rx="65" ry="18" fill="none" stroke="#333"/><path d="M110 30 V112 Q175 148 240 112 V30" fill="none" stroke="#333"/>`+line(175,30,240,30)+t(205,23,'4 cm')+t(269,80,'5 cm'),'Yarıçap 4 cm, yükseklik 5 cm silindir.')),
 math(19,'Olasılık','probability_complement','1’den 12’ye kadar numaralanmış 12 eş karttan biri rastgele seçiliyor.','Seçilen kartın numarasının 3’ün katı olma olasılığı kaçtır?',['1/4','1/3','1/2','2/3'],1,'Aralıkta 3’ün katlarını eksiksiz say.',['3, 6, 9, 12 olmak üzere 4 uygun kart vardır.','4/12=1/3.'],'12 de aralığa dâhildir; son katı atlama.','Aralığın uç değerlerinin dâhil olup olmadığını kontrol et.'),
 math(20,'Kareköklü ifadeler','square_border_area','Kare biçimindeki bir bahçenin alanı 324 m²’dir. Bahçenin dışına, dört yanda genişliği 1 m olan bir yürüyüş yolu yapılıyor. Yolun dış sınırı da karedir.','Yol ve bahçenin birlikte kapladığı toplam alan kaç m² olur?',['361','380','400','484'],2,'Bahçenin kenarını bul; yol iki karşı tarafta da olduğundan 2 m ekle.',['Bahçenin kenarı √324=18 m.','Dış karenin kenarı 18+1+1=20 m.','Toplam alan 20²=400 m².'],'Sorulan yalnız yolun alanı olsaydı 400−324=76 m² olurdu.','Çevredeki şerit, toplam kenarı iki genişlik kadar artırır.',fig(rect(120,15,120,120)+rect(126,21,108,108)+t(180,81,'324 m²')+line(240,15,260,15)+line(234,21,260,21)+line(255,15,255,21)+t(293,24,'1 m yol'),'Alanı 324 m² olan kare bahçenin dört yanında 1 m genişliğinde yol vardır. Dış sınır da karedir.')),
 tr(1,'Paragrafta anlam','main_idea','Bir kitabı bitirince yalnız olayları hatırlamak yetmez. Kahramanın verdiği bir kararı kendi yaşamımızdaki seçimlerle karşılaştırdığımızda kitap bizimle konuşmaya başlar. Okuma, bu bağlantılar sayesinde kişisel bir deneyime dönüşür.','Bu parçanın ana düşüncesi hangisidir?',['İyi kitaplar her zaman gerçek olayları anlatır.','Okumak, kişinin metinle kendi yaşamı arasında bağ kurmasıyla derinleşir.','Bir kitabın değeri bitirilme hızına bağlıdır.','Kahramanın her kararını doğru bulmak gerekir.'],1,'Örneklerin hangi ortak düşünceyi desteklediğini bul.',['Olay hatırlamanın ötesinde kişisel bağlantı vurgulanıyor.','Yaşamla bağ kurma düşüncesi parçanın bütününü kapsıyor.'],'Parçada kitapların yalnız gerçek olayları anlatması, hızlı bitirilmesi veya kahramanın her kararının doğru bulunması savunulmuyor.','Ana düşünce tek bir ayrıntıyı değil parçanın bütününü kapsar.'),
 tr(2,'Paragrafta anlam','supported_inference','Kentteki kütüphane geçen yıl akşamları da açık kalmaya başladı. O tarihten sonra okul çıkışında birlikte gelen öğrenci grupları çoğaldı. Bazı öğrenciler çalışma saatlerini artık kütüphanenin kapanışına göre düzenliyor.','Bu parçadan hangisine ulaşılabilir?',['Kentteki her öğrenci kütüphaneye gitmektedir.','Öğrenciler evde hiç ders çalışmamaktadır.','Akşam erişimi bazı öğrencilerin çalışma düzenini etkilemiştir.','Kütüphanedeki bütün kitaplar yenilenmiştir.'],2,'Metindeki sınırlı gözlemden bütün öğrencileri kapsayan sonuç çıkarma.',['Bazı öğrenciler çalışma saatlerini kapanışa göre ayarlamaktadır.','Bu bilgi, akşam erişiminin çalışma düzenine etkisini destekler.'],'“Her”, “hiç” ve “bütün kitaplar” metinde karşılık bulmuyor.','Çıkarımın kapsamı verilen bilgiyi aşmamalıdır.'),
 tr(3,'Cümlede anlam','cause_result','“Yol buzlandığı için servis yavaş ilerledi.”','Bu cümlede neden-sonuç ilişkisini doğru gösteren seçenek hangisidir?',['Neden: Servisin yavaş ilerlemesi; sonuç: Yolun buzlanması.','Neden: Yolun buzlanması; sonuç: Servisin yavaş ilerlemesi.','Amaç: Yolun buzlanması; sonuç: Öğrencilerin yürümesi.','Koşul: Servisin durması; sonuç: Yolun açılması.'],1,'“Niçin yavaş ilerledi?” sorusuna cevap veren bölümü bul.',['Yavaş ilerlemenin nedeni yolun buzlanmasıdır.','Yavaş ilerleme bu durumun sonucudur.'],'Neden ve sonuç yer değiştirildiğinde cümlenin mantığı bozulur.','Nedeni bulmak için eyleme “Niçin?” diye sor.'),
 tr(4,'Cümlede anlam','purpose_result','“Bitkilerin gelişimini karşılaştırmak için iki saksıdaki bitkilerin boylarını her gün ölçtü.”','Cümlede ölçme işinin amacı hangisidir?',['Saksıları boyamak','Her gün su tüketmek','Bitkilerin gelişimini karşılaştırmak','Bitkileri başka yere taşımak'],2,'Eylemin hangi hedefle yapıldığını bul.',['Bitkilerin boylarını ölçme eylemdir; gelişimlerini karşılaştırma hedefidir.'],'Cümlede boyama veya taşıma bilgisi yoktur.','“Ne amaçla?” sorusunun yanıtı hedefi gösterir.'),
 tr(5,'Sözcükte anlam','figurative_meaning','“Bu öneri, tartışmaya yeni bir kapı açtı.”','Bu cümlede “kapı açmak” sözü hangi anlamda kullanılmıştır?',['Yeni bir düşünme olanağı sağlamak','Binanın girişini genişletmek','Konuşmayı kesin olarak bitirmek','Bir öneriyi bütünüyle reddetmek'],0,'Sözün gerçek bir nesneye mi düşünceye mi karşılık geldiğine bak.',['Tartışmada fiziksel bir kapı yoktur.','Öneri, yeni olasılıkların düşünülmesini sağlamıştır.'],'Konuşmayı bitirmek veya reddetmek anlamı bağlama uymaz.','Mecaz anlamı belirlerken sözü bütün cümle içinde değerlendir.'),
 tr(6,'Paragrafın yapısı','sentence_order','I. Sonunda her grubun bulgusunu tek bir raporda topladık.\nII. Önce araştıracağımız soruyu birlikte belirledik.\nIII. Ardından görevleri paylaşarak kaynakları inceledik.','Numaralanmış cümlelerin anlamlı sıralanışı hangisidir?',['I–II–III','II–I–III','III–II–I','II–III–I'],3,'Zaman ve bağlama ifadelerini izle.',['Önce soru belirlenir.','Ardından görev ve inceleme gelir.','Sonunda bulgular birleştirilir.'],'“Önce–ardından–sonunda” dizisi akışı doğrular.','Geçiş sözleri, parçanın iskeletini gösterir.'),
 tr(7,'Paragrafın yapısı','irrelevant_sentence','I. Kentte bisiklet yollarının birbirine bağlanması ulaşımı kolaylaştırır. II. Kesintisiz bir hat, sürücünün trafikte sık sık yön değiştirmesini önler. III. Bisiklet yarışlarının tarihi on dokuzuncu yüzyıla uzanır. IV. Bu nedenle yeni yollar planlanırken mevcut güzergâhlarla bağlantı kurulmalıdır.','Hangi cümle düşüncenin akışını bozmaktadır?',['I','II','III','IV'],2,'Ortak konunun yalnız bisiklet değil, bisiklet yollarının bağlantısı olduğunu fark et.',['I, II ve IV güzergâhların bağlantısını tartışır.','III ise yarışların tarihine geçer.'],'III çıkarıldığında II’den IV’e neden-sonuç bağı korunur.','Aynı sözcüğün geçmesi, aynı düşüncenin sürdüğü anlamına gelmez.'),
 tr(8,'Anlatım biçimleri','description','Dar sokaktaki evlerin mavi kepenkleri yarıya kadar açıktı. Taş duvarları sarmaşıklar kaplamış, pencere önlerine küçük toprak saksılar dizilmişti.','Bu parçada ağır basan anlatım biçimi hangisidir?',['Tartışma','Betimleme','Açıklama','Öyküleme'],1,'Parçanın okura bir görünüm mü yoksa bir olay akışı mı sunduğuna bak.',['Renk, konum ve nesne ayrıntıları bir görünüm oluşturur.'],'Bir olayın gelişimi anlatılmıyor; mekânın görünümü betimleniyor.','Betimleme, sözcüklerle görünüm canlandırır.'),
 tr(9,'Düşünceyi geliştirme','comparison','Basılı sözlükte bir sözcüğü ararken yakındaki başka sözcüklerle de karşılaşırız. Dijital sözlük ise aradığımız maddeye daha hızlı ulaştırır. İki araç, farklı kullanım alışkanlıkları kazandırır.','Bu parçada hangi düşünceyi geliştirme yoluna başvurulmuştur?',['Tanık gösterme','Sayısal veri kullanma','Karşılaştırma','Tanımlama'],2,'İki varlığın hangi bakımdan ele alındığını belirle.',['Basılı ve dijital sözlüğün erişim özellikleri karşılaştırılıyor.'],'Bir kişinin görüşü aktarılmıyor, istatistik verilmiyor.','İki unsurun benzer veya farklı yönlerinin gösterilmesi karşılaştırmadır.'),
 tr(10,'Metin türleri','genre_diary','12 Nisan\nBugün ilk kez okulun tiyatro provasına katıldım. Sahneye çıkmadan önce heyecanlıydım; birkaç tekrarın ardından arkadaşlarımla rahatça çalışabildim. Eve dönerken bir sonraki provayı düşündüm.','Bu metin hangi türün özelliklerini taşır?',['Haber','Günlük','Makale','Fabl'],1,'Yazarın kendi gününü, tarih ve kişisel duygularla anlatmasına dikkat et.',['Tarih belirtilmiş.','Günlük yaşantı ve kişinin duyguları aynı gün aktarılmış.'],'Nesnel haber veya bilimsel kanıtlama amacı yoktur.','Tarih ve kişisel yaşantının birleşmesi günlük için önemli ipucudur.'),
 tr(11,'Yazım kuralları','conjunction_de','Aşağıdaki cümlelerden birinde “de”nin yazımı yanlıştır.','Yanlış yazılan cümle hangisidir?',['Kitap çantamda kaldı.','Ben de geziye katılacağım.','Bahçede iki kedi var.','Seninde fikrini dinleyelim.'],3,'Bağlaç olan “de” ile bulunma eki olan “-de”yi ayır.',['“Senin de fikrini” cümlesinde “de” bağlaçtır ve ayrı yazılır.'],'Çantamda ve bahçede bulunma bildirir; “ben de” ayrı yazılmıştır.','Bağlaç olan “de” ek değildir; ayrı yazılır.'),
 tr(12,'Noktalama','colon_example','“Çantaya üç şey koydum ... defter, kalem ve sözlük.”','Boş bırakılan yere hangi noktalama işareti getirilmelidir?',['Nokta','İki nokta','Soru işareti','Kesme işareti'],1,'Önceki ifadeyi açıklayan listenin başladığını gör.',['“Üç şey” ifadesinin ardından bu şeyler sıralanır.','Açıklama öncesinde iki nokta kullanılır.'],'Burada bir soru veya özel ada gelen ek yoktur.','Bir açıklama ya da örnek listesi öncesinde iki nokta kullanılabilir.'),
 tr(13,'Fiilimsiler','verbal_noun','“Yüzmek, yazın en sevdiğim etkinliktir.”','Bu cümlede “yüzmek” sözcüğünün türü hangisidir?',['Çekimli fiil','Sıfat-fiil','İsim-fiil','Zarf-fiil'],2,'Sözcüğün iş adını mı zamanla çekilmiş eylemi mi bildirdiğine bak.',['“Yüzmek”, yüzme işinin adıdır ve “-mek” ekini almıştır.'],'Yüklem “etkinliktir” sözcüğüdür; “yüzmek” zaman ve kişiyle çekimlenmemiştir.','-ma, -ış, -mak ekleriyle kurulan iş adlarını bağlamda kontrol et.'),
 tr(14,'Cümlenin ögeleri','subject_finding','“Öğrenciler deney sonuçlarını defterlerine yazdı.”','Bu cümlenin öznesi hangisidir?',['Öğrenciler','Deney sonuçlarını','Defterlerine','Yazdı'],0,'Yükleme işi yapanı sor.',['Yüklem “yazdı”dır.','“Kim yazdı?” sorusunun yanıtı “Öğrenciler”dir.'],'“Neyi yazdı?”nesneyi, “nereye yazdı?”yer tamlayıcısını buldurur.','Özneyi bulurken yüklemden hareket et.'),
 tr(15,'Cümle türleri','negative_sentence','Aşağıdaki cümlelerden biri anlamca olumsuzdur.','Bu cümle hangisidir?',['Bugün hava oldukça sıcak.','Toplantı biraz erken başladı.','Sınıfta hiç kimse kalmamış.','Soruyu birlikte çözdük.'],2,'Eylemin gerçekleşmediği veya varlığın bulunmadığı anlamını ara.',['“Kalmamış”eylemin gerçekleşmediğini bildirir.','“Hiç kimse” ifadesi bu olumsuzluğu pekiştirir.'],'Diğer cümleler gerçekleşen bir durum veya eylemi bildirir.','Olumsuzluğu yalnız tek bir sözcüğe değil tüm cümlenin anlamına bakarak belirle.'),
 tr(16,'Sözel mantık','ordering_constraint','Ece, Deniz ve Ali birer sunum yapacaktır. Deniz, Ece’den sonra; Ali ise Deniz’den sonra sunum yapacaktır.','Sunum sırası hangisidir?',['Ali–Ece–Deniz','Deniz–Ali–Ece','Ece–Deniz–Ali','Ece–Ali–Deniz'],2,'Her koşulu önce-sonra zincirine dönüştür.',['Ece, Deniz’den öncedir.','Deniz, Ali’den öncedir.','Zincir Ece–Deniz–Ali olur.'],'İki koşul da aynı anda sağlanır.','Sözel koşulları kısa oklarla göstermek karşılaştırmayı kolaylaştırır.'),
 tr(17,'Tablo yorumlama','schedule_constraints','Kütüphane atölyeleri tabloda verilmiştir. Mert yalnız salı ve perşembe günleri katılabiliyor. Saat 16.00’dan önce başlayan bir etkinlik istiyor.','Mert hangi atölyeyi seçebilir?',['Masal','Satranç','Robotik','Resim'],2,'Gün ve saat koşullarını birlikte uygula.',['Salı ve perşembe seçeneklerini ayır.','Bunlardan yalnız perşembe 15.00’teki robotik 16.00’dan önce başlar.'],'Salı 16.30saat koşulunu, diğer günlergün koşulunu sağlamaz.','Bir tablo sorusunda bütün koşulları tek tek işaretle.',fig(rect(20,15,320,120)+[45,75,105].map(y=>line(20,y,340,y)).join('')+[['Pazartesi','15.00','Masal'],['Salı','16.30','Satranç'],['Perşembe','15.00','Robotik'],['Cuma','14.00','Resim']].map((r,i)=>t(75,35+i*30,r[0])+t(180,35+i*30,r[1])+t(282,35+i*30,r[2])).join(''),'Atölyeler: Pazartesi 15.00 Masal; salı 16.30 Satranç; perşembe 15.00 Robotik; cuma 14.00 Resim.')),
 tr(18,'Metin karşılaştırma','common_message','I. Bir ağacı tanımak için yalnız yaprağına değil, yaşadığı toprağa ve iklime de bakmak gerekir.\nII. Bir yerleşim yerini anlamaya çalışırken yalnız binaları saymak yeterli olmaz; insanların yaşam biçimlerini de incelemeliyiz.','Bu iki parçanın ortak düşüncesi hangisidir?',['Gözlem yaparken tek bir özelliğe bağlı kalmamak gerekir.','Doğadaki her şey sayılarla açıklanabilir.','Binalar, bitkilerden daha kolay incelenir.','İklim bütün insan davranışlarını belirler.'],0,'Farklı örneklerin dayandığı ortak yaklaşımı bul.',['Her iki metin de tek özellik yerine bağlamın incelenmesini önerir.'],'Diğer seçenekler iki parçada birlikte savunulmuyor.','Ortak düşünce, sözcük ortaklığı değil yaklaşım ortaklığıdır.'),
 tr(19,'Paragraf tamamlama','concluding_sentence','Yeni bir beceriyi öğrenirken ilk denemelerimiz kusursuz olmayabilir. Hataları saklamak yerine nerede zorlandığımızı belirlersek bir sonraki denememizi daha bilinçli yaparız. Bu nedenle ...','Bu parça hangisiyle tamamlanmalıdır?',['ilk başarısızlıkta çalışmayı bırakmalıyız.','yalnız çok kolay işleri seçmeliyiz.','hataları öğrenmeyi yönlendiren işaretler olarak görmeliyiz.','başkalarının yaptığı her şeyi aynen tekrarlamalıyız.'],2,'Sonucun, önceki cümlelerin olumlu öğrenme yaklaşımıyla uyumunu ara.',['Hata, zorlanılan yeri gösterir.','Bu bilgi sonraki denemeyi geliştirmeye yarar.'],'Bırakma veya yalnız kolay işi seçme, parçanın yönüyle çelişir.','“Bu nedenle” sonrasına önceki düşüncenin sonucu gelir.'),
 tr(20,'Söz sanatları','personification','“Rüzgâr, kapının önünde sabırsızca bekliyordu.”','Bu cümlede hangi söz sanatına başvurulmuştur?',['Abartma','Kişileştirme','Benzetme','Konuşturma'],1,'İnsan dışı varlığa verilen insan davranışını belirle.',['Rüzgâra “sabırsızca bekleme”davranışı yüklenmiş.','Bu, kişileştirmedir.'],'Rüzgârın söylediği bir söz aktarılmadığı için konuşturma değildir.','Kişileştirmede insan özelliği verilir; konuşturmada ayrıca söz söyletilir.'),
 science(19,'Madde döngüleri','carbon_cycle','Yeşil bir bitkinin ışıkta, yeterli su ve uygun sıcaklıkta fotosentez yaptığı belirleniyor.','Bitki fotosentezde kullanmak üzere havadan hangi gazı alır?',['Oksijen','Karbondioksit','Azot','Hidrojen'],1,'Fotosentezin girdisi ile çıktısını ayır.',['Bitki, fotosentez için havadan karbondioksit alır; suyu kökleriyle alabilir.','Işık enerjisiyle besin üretimi gerçekleşir.'],'Oksijen, fotosentezin girdisi değil ürünüdür. Bitkinin solunum yapması ayrı bir süreçtir.','Fotosentez sorularında “alınan” ile “üretilen” maddeyi karıştırma.'),
 science(20,'İklim ve hava olayları','weather_climate_evidence','Bir kent için iki bilgi veriliyor: I. Yarın öğleden sonra yağmur bekleniyor. II. Otuz yıllık gözlemlerde yazların genellikle sıcak ve kurak geçtiği görülüyor.','Bu bilgiler nasıl sınıflandırılır?',['I iklim, II hava olayı','İkisi de günlük hava olayı','I hava olayı, II iklim','İkisi de yarınki hava tahmini'],2,'Bilginin kısa süreli mi uzun yıllara dayalı mı olduğuna bak.',['I belirli bir günün hava durumudur.','II uzun yılların genel özelliğidir ve iklimi anlatır.'],'Bir günlük yağmur, tek başına kentin iklimini değiştirmez.','Zaman ölçeği, hava durumu ile iklimi ayırmada temel ipucudur.')
];
