// Original editor drafts, not official questions or accepted learner assessments.
// Historical source lineage does not settle the active school-year program or publication acceptance.
const sourceProfiles={
  english:{prefix:'EN',programId:'legacy-2018-ingilizce',styleReference:'https://mufredat.meb.gov.tr/Dosyalar/201812411191321-%C4%B0NG%C4%B0L%C4%B0ZCE%20%C3%96%C4%9ERET%C4%B0M%20PROGRAMI%20Klas%C3%B6r%C3%BC.pdf'},
  religion:{prefix:'DK',programId:'legacy-2018-din-kulturu',styleReference:'https://mufredat.meb.gov.tr/Dosyalar/20221229134650712-DKAB_(4-8.%20S%C4%B1n%C4%B1f)_DOP_%202018.pdf'},
  history:{prefix:'HI',programId:'legacy-2018-inkilap-tarihi',styleReference:'https://mufredat.meb.gov.tr/Dosyalar/201812104016155-%C4%B0NKILAP%20TAR%C4%B0H%C4%B0%20VE%20ATAT%C3%9CRK%C3%87%C3%9CL%C3%9CK%20%C3%96%C4%9ERET%C4%B0M%20PROGRAMI.pdf'}
};
function question(subject,n,topic,familyId,stimulus,stem,options,answer,strategy,steps,check,tip){
  const profile=sourceProfiles[subject];
  return {
    id:`P8-${profile.prefix}${String(n).padStart(2,'0')}`,grade:8,subject,topic,familyId,stimulus,stem,options,answer,
    explanation:{given:stimulus,wanted:stem,strategy,steps,check,tip},
    source:{programId:profile.programId,alignmentStatus:'draft',styleReference:profile.styleReference},
    layout:stimulus.length>380?'extended':'regular'
  };
}
const en=(...args)=>question('english',...args);
const dk=(...args)=>question('religion',...args);
const hi=(...args)=>question('history',...args);

export const GRADE8_VERBAL_QUESTIONS=[
  en(1,'Friendship','invitation_reason_inference',
    'Ece invites Deniz to a picnic on Sunday. Deniz replies: “Thanks for asking. I cannot join you because I will visit my grandparents. Can we meet next weekend?”',
    'What is Deniz doing in his reply?',
    ['Accepting the invitation without a condition.','Refusing an invitation and giving a reason.','Asking Ece to cancel every plan.','Saying that he dislikes picnics.'],1,
    'Yanıtın kabul mü ret mi olduğunu belirle; ardından gerekçeyi ve yeni öneriyi ayır.',
    ['Yanıttaki “I cannot join” ifadesi bu davete katılamayacağını gösterir.','Gerekçe, “Because” sonrasında aile ziyareti olarak verilir.','Yeni hafta önerisi, pikniği sevmediği anlamına gelmez.'],
    'Yanıt pazar davetini kabul etmiyor; nezaket, gerekçe ve başka bir zaman önerisi içeriyor.',
    'Davet yanıtında önce “Can / Cannot” ifadesine, sonra gerekçeye bak.'),
  en(2,'Teen Life','preference_schedule_intersection',
    'Mina enjoys stories and quiet places. She does not like noisy concerts. She is free only on Saturday afternoon. Four friends suggest different activities.',
    'Which activity fits both her interests and her free time?',
    ['A rock concert on Saturday afternoon.','A reading club on Sunday morning.','A quiet reading club on Saturday afternoon.','A shopping trip on Friday evening.'],2,
    'İlgi ve zaman koşullarını birlikte uygula; yalnız bir koşulu karşılayan seçeneği alma.',
    ['Mina sessiz ortamları ve hikâyeleri seviyor.','Etkinliğin cumartesi öğleden sonra olması gerekiyor.','Sessiz okuma kulübü iki koşulu da sağlıyor.'],
    'Konser ilgi koşulunu; pazar ve cuma etkinlikleri zaman koşulunu sağlamıyor.',
    'Tercih sorularında “Likes / Dislikes” ile zaman bilgisini ayrı işaretle.'),
  en(3,'In The Kitchen','recipe_next_step',
    'To prepare a fruit bowl, first wash the fruit. Next, peel the banana. Then slice it into small pieces. Finally, mix the fruit with yoghurt. Ada has just peeled the banana.',
    'What should Ada do next?',
    ['Mix the fruit with yoghurt.','Wash the finished bowl.','Peel the banana again.','Slice the banana.'],3,
    'Tarifin tamamını sırala ve tamamlanan adımın hemen sonrasını seç.',
    ['Sıra yıkama, soyma, dilimleme ve karıştırmadır.','Ada soyma adımını bitirmiştir.','Bir sonraki işlem muzun dilimlenmesidir.'],
    'Karıştırma en son adımdır; dilimleme bitmeden ona geçilmez.',
    'Soru “Next” diyorsa ilk adımı değil, belirtilen son işlemin ardından geleni bul.'),
  en(4,'On The Phone','phone_message_update',
    'Caller: “May I speak to Arda?”\nReceiver: “He is out. Would you like to leave a message?”\nCaller: “Yes. Please tell him the club will meet at four today. We changed the old time, three o’clock.”',
    'Which message should the receiver give Arda?',
    ['The club will meet at four, not three.','The club meeting is cancelled.','The club will meet at three tomorrow.','The caller wants Arda to leave the club.'],0,
    'Telefon mesajında değiştirilen eski bilgi ile geçerli yeni bilgiyi ayır.',
    ['Eski saat üç olarak belirtilmiştir.','Yeni toplantı saati bugün dörttür.','Arda’ya değişen saat iletilmelidir.'],
    'İptal veya yarın bilgisi konuşmada verilmemiştir.',
    'Mesajda “Changed” geçiyorsa eski saati cevap diye seçme.'),
  en(5,'The Internet','digital_action_purpose',
    'Lara finishes her project on her computer. She opens an e-mail, adds the project as an attachment and writes her teacher’s address. Then she clicks “Send”.',
    'Why does Lara add the attachment?',
    ['To delete her teacher’s e-mail address.','To create a new game account.','To send her project file to her teacher.','To turn off the Internet connection.'],2,
    'Ekrandaki tek düğmeyi değil, dosya ve alıcı bilgisiyle birlikte işlemin amacını oku.',
    ['Eklenen dosya Lara’nın projesidir.','Alıcı öğretmenidir ve son işlem göndermedir.','Ek, proje dosyasını iletmek için kullanılır.'],
    'Hesap açma, bağlantıyı kapatma veya adres silme işlemi anlatılmamıştır.',
    'E-postadaki “Attachment” gönderilen ek dosyayı gösterir.'),
  en(6,'Adventures','adventure_constraint_table',
    'Selin wants a water activity for no more than 70 TL. Canoeing costs 60 TL, climbing costs 50 TL, rafting costs 90 TL and cycling costs 40 TL.',
    'Which activity meets both of Selin’s conditions?',
    ['Climbing','Rafting','Cycling','Canoeing'],3,
    'Önce su etkinliklerini ayır, sonra bütçe sınırını uygula.',
    ['Kano ve rafting su etkinliğidir.','Rafting 90 TL ile 70 TL sınırını aşar.','Kano 60 TL olduğundan iki koşulu da karşılar.'],
    'Tırmanma ve bisiklet ucuz olsa da istenen etkinlik türü değildir.',
    'Koşuldaki “No more than” belirtilen değerin aşılmaması gerektiğini anlatır.'),
  en(7,'Tourism','tourism_feature_matching',
    'Omar wants to see an old bridge and travel by boat. River Tour includes a boat trip under a historic bridge. Castle Walk is a walking tour of a castle. City Bus visits new buildings. Mountain Walk follows a forest path.',
    'Which tour should Omar choose?',
    ['River Tour','Castle Walk','City Bus','Mountain Walk'],0,
    'Tur adlarını değil, aranan ulaşım türü ve tarihî yapı özelliklerini eşleştir.',
    ['Omar hem eski köprüyü hem tekne yolculuğunu istiyor.','River Tour iki özelliği birlikte içeriyor.','Diğer turların açıklamalarında bu iki özellik bir arada yoktur.'],
    'Kale tarihî olsa da Castle Walk tekne gezisi değildir.',
    'Turizm metninde “Historic” ve ulaşım biçimini ayrı koşullar olarak izle.'),
  en(8,'Chores','chore_order_constraint',
    'Aras has two tasks on Saturday. He must empty the dishwasher before breakfast at 9.30. He must walk the dog after 10.00. It is now 9.00.',
    'Which plan follows both instructions?',
    ['Walk the dog at 9.00 and empty the dishwasher at 11.00.','Empty the dishwasher at 9.15 and walk the dog at 10.30.','Do both tasks after lunch.','Leave both tasks for Sunday.'],1,
    'Yönergedeki “Before” ve “After” koşullarını zaman çizgisinde göster.',
    ['Bulaşık makinesi 9.30’dan önce boşaltılmalıdır; 9.15 bu koşulu sağlar.','Köpek gezdirme 10.00’dan sonra yapılmalıdır; 10.30 bu koşulu sağlar.','Bu plan hem görev sırasına hem de iki ayrı saat koşuluna uyar.'],
    '9.00’da köpeği gezdirmek ikinci yönergeyi; öğleden sonra iki işi yapmak erken görev koşulunu ihlal eder.',
    'Ev işi yönergelerinde sıra ve son zamanı birlikte kontrol et.'),
  en(9,'Science','experiment_repeat_purpose',
    'Nora tests a paper plane and records how far it flies. She uses the same plane, room and starting point three times. The distances are almost the same each time.',
    'Why does Nora repeat the test under the same conditions?',
    ['She wants to change every condition.','She wants to avoid recording any result.','She repeated the test to check the result.','She wants to compare three different rooms.'],2,
    'Değişen ve aynı tutulan bilgileri ayır; tekrarın hangi amaca hizmet ettiğini bul.',
    ['Uçak, oda ve başlangıç noktası aynı tutulmuştur.','Deney birden fazla kez yapılmıştır.','Bu tekrar, sonucun benzer biçimde elde edilip edilmediğini kontrol eder.'],
    'Metin üç farklı oda veya her koşulun değiştirilmesini anlatmıyor.',
    'Metindeki “Same Conditions” ifadesi tekrarlanan denemenin karşılaştırılabilir olduğunu gösterir.'),
  en(10,'Natural Forces','future_reason_evidence',
    'A town gets its water from a lake. During the last three summers, there was little rain and the lake became smaller. Residents are asked to save water.',
    'Which prediction is supported by this information?',
    ['There may be a water shortage because the lake is getting smaller.','Every lake in the world will disappear tomorrow.','The town will certainly have a flood tonight.','The lake is getting bigger because rain is increasing.'],0,
    'Tahminin gerekçesini metindeki gözlemle eşleştir; kesin ve aşırı genellemeleri ele.',
    ['Az yağış ve gölün küçülmesi, su kaynağının azalmasına işaret eder.','Bu bilgi su sıkıntısı ihtimalini destekler.','Tahmindeki “May” kesin olay değil olasılık bildirir.'],
    'Dünya çapında yarına ilişkin kesin sonuç veya sel bilgisi verilmemiştir.',
    'Tahminde “Because” ile kurulan gerekçe, verilen gözlemle aynı yönde olmalıdır.'),

  dk(1,'Kader İnancı','choice_responsibility_boundary',
    'Zeynep hangi ailede doğacağını seçemediğini, fakat ders çalışma saatini planlayabildiğini söylüyor. Sınava hazırlanırken kendi kararlarını uyguluyor ve eksiklerini tamamlıyor.',
    'Bu örnekte insanın irade ve sorumluluğuna doğrudan örnek olan durum hangisidir?',
    ['Doğduğu aileyi kendisinin belirlemesi.','Çalışma biçimini seçmesi ve kendi çabasından sorumlu olması.','Her sonucun yalnızca başkalarının kararına bağlı olması.','Çalışmadan da aynı başarıyı kesin olarak beklemesi.'],1,
    'Seçilemeyen koşulu, kişinin tercih edip uygulayabildiği davranıştan ayır.',
    ['Ailede doğma koşulu Zeynep’in tercihi olarak verilmemiştir.','Çalışma zamanı ve eksikleri tamamlama davranışı kendi kararlarıdır.','Bu tercihler, çabasına ilişkin sorumluluk örneğidir.'],
    'Verilen örnek bütün sonuçların kesin olarak kontrol edilebildiğini söylemez.',
    'İrade sorusunda “Kişi hangi davranışı seçebiliyor?” diye sor.'),
  dk(2,'Kader İnancı','trust_after_precaution',
    'Bir çiftçi tohumunu uygun zamanda ekiyor, tarlasını suluyor ve gerekli bakımı yapıyor. Ardından emeğinin karşılığını almayı umarak Allah’a güveniyor.',
    'Bu davranış tevekkül anlayışını nasıl örneklendirir?',
    ['Hiç çalışmadan ürünün oluşmasını beklemek.','Sonucun kesinlikle istenen biçimde olacağını söylemek.','Önlem almayı gereksiz görmek.','Gerekli önlemleri alıp emek verdikten sonra Allah’a güvenmek.'],3,
    'Güveni, önlem ve çalışma adımlarını dışlayan bekleyişle karıştırma.',
    ['Çiftçi ekim, sulama ve bakımı yerine getiriyor.','Sonra Allah’a güveniyor.','Bu örnekte güven, emeğin yerine değil ardından geliyor.'],
    'Metinde ne çalışma terk edilmiş ne de sonuç için kesinlik iddia edilmiştir.',
    'Tevekkül örneğinde çaba ve tedbir bulunup bulunmadığını önce kontrol et.'),
  dk(3,'Zekât Ve Sadaka','solidarity_social_effect',
    'Bir mahallede zekât verebilecek kişiler, ihtiyaç sahiplerinin temel gereksinimlerine destek oluyor. Bu destekle bazı ailelerin gıda ve okul malzemesi eksikleri azalıyor.',
    'Örnekte zekâtın hangi toplumsal etkisi vurgulanmaktadır?',
    ['Ekonomik güçlük yaşayan kişilerle dayanışmayı güçlendirmek.','Yardım alanların bütün tercihlerini belirlemek.','Yalnız yardım verenleri tanıtmak.','İnsanlar arasındaki iletişimi tamamen kesmek.'],0,
    'Yardımın nasıl tanıtıldığını değil, ihtiyaç sahiplerinin yaşamındaki etkisini bul.',
    ['Gıda ve okul malzemesi eksikleri destekle azalıyor.','Maddi imkânlar paylaşılmış oluyor.','Vurgulanan sonuç toplumsal dayanışmadır.'],
    'Metinde kişilerin bütün tercihlerini yönetme veya reklam yapma amacı yoktur.',
    'Toplumsal fayda sorusunda “Bu uygulama insanlar arasındaki ilişkiyi nasıl etkiledi?” diye düşün.'),
  dk(4,'Zekât Ve Sadaka','continuing_charity_duration',
    'Sadaka-i cariye, insanların uzun süre yararlanmaya devam edebildiği iyiliklerle ilişkilendirilir. Bir öğrenci dört farklı yardım önerisini bu özellik bakımından karşılaştırıyor.',
    'Hangi öneri bu süreklilik özelliğine en doğrudan örnektir?',
    ['Bir arkadaşına yalnız bugün içeceği suyu vermek.','Bugünkü öğle yemeğini bir kişiyle paylaşmak.','İnsanların uzun süre yararlanacağı bir kütüphane kurulmasına destek vermek.','Bir kişiye yalnız bugün kullanacağı otobüs bileti vermek.'],2,
    'Yardımların değerini sıralama; sorulan uzun süreli yararlanma özelliğini karşılaştır.',
    ['Su, yemek ve günlük bilet örnekleri tek kullanımlı olarak verilmiştir.','Kütüphane tekrar tekrar yararlanılabilen bir hizmettir.','Bu nedenle süreklilik özelliği en doğrudan bu seçenektedir.'],
    'Diğer yardımlar da iyilik olabilir; soru onların değersiz olduğunu değil süre farkını soruyor.',
    'Sorudaki “Uzun süre” koşulunu taşıyan hizmeti bul; yardımları iyi-kötü diye ayırma.'),
  dk(5,'Din Ve Hayat','protection_domain_matching',
    'Bir esnaf, müşterinin fark etmeyeceğini bilse de tartının doğru çalışmasını kontrol ediyor. Eksik tartarak haksız kazanç elde etmemeyi ilke ediniyor.',
    'Bu örnek dinin temel gayeleri arasında doğrudan hangisiyle ilişkilidir?',
    ['Neslin korunması.','Malın korunması.','Ulaşım hızının artırılması.','Bütün insanların aynı mesleği seçmesi.'],1,
    'Davranışın koruduğu hakkı belirle ve bu hakkı ilgili temel gayeyle eşleştir.',
    ['Eksik tartı müşterinin parasal hakkına zarar verebilir.','Doğru tartı haksız kazancı önler.','Bu nedenle örnek malın korunmasıyla doğrudan ilişkilidir.'],
    'Aile kurumu, ulaşım veya meslek seçimi olayın konusu değildir.',
    'Temel gaye sorularında doğrudan hangi hakkın zarar görebileceğini işaretle.'),
  dk(6,'Din Ve Hayat','individual_social_link',
    'Bir öğrenci, paylaşmanın önemini öğrenince komşusunun taşınmasına yardım ediyor. Sonraki günlerde komşular da birbirlerinin ihtiyaçlarını sormaya ve birlikte destek olmaya başlıyor.',
    'Bu olay birey ve toplum ilişkisi açısından hangi sonucu örneklendirir?',
    ['Bireysel davranışların toplumsal ilişkilere hiç etkisinin olmaması.','Her yardımın yalnız maddi kazanç için yapılması.','Toplumsal dayanışmanın herkesin aynı düşünmesine bağlı olması.','Bireysel bir iyiliğin toplumsal dayanışmayı güçlendirmesi.'],3,
    'İlk kişinin davranışı ile daha sonra oluşan ortak davranış arasındaki bağı izle.',
    ['İlk davranış, öğrencinin komşusuna yardım etmesidir.','Sonra komşular arasında karşılıklı destek gelişmiştir.','Bireysel iyilik daha geniş bir dayanışmayı desteklemiştir.'],
    'Metinde maddi kazanç veya herkesin aynı düşünmesi koşulu bulunmuyor.',
    'Birey-toplum sorularında başlangıçtaki davranış ile yayılan sonucu ayrı yaz.'),
  dk(7,'Hz. Muhammed’in Örnekliği','trustworthiness_behaviour_transfer',
    'Derste Hz. Muhammed’in güvenilirliği ele alındıktan sonra öğrenciler günlük davranış örnekleri hazırlıyor. Örneklerin doğru sözlü olma ve emanet bilincini birlikte göstermesi isteniyor.',
    'Hangi davranış iki özelliği de taşır?',
    ['Emaneti korumak ve verdiği sözü yerine getirmek.','Ödünç aldığı kitabı izinsiz başka birine vermek.','Yapamayacağını bildiği işi kesin yapacağını söylemek.','Arkadaşının eşyasını kullandıktan sonra saklamak.'],0,
    'Güvenilirliğin söz ve emanet davranışında aynı anda görünmesini ara.',
    ['Emaneti korumak, verilen şeye özen göstermektir.','Sözünü yerine getirmek, davranışın sözle tutarlı olmasıdır.','İlk seçenek iki özelliği birlikte taşır.'],
    'İzinsiz verme, gerçek dışı vaat ve eşyayı saklama güveni zedeler.',
    'Güvenilirlik sorularında “Söz ile davranış uyumlu mu, emanet korunuyor mu?” diye kontrol et.'),
  dk(8,'Hz. Muhammed’in Örnekliği','consultation_before_decision',
    'Bir sınıf temsilcisi gezi planı hazırlıyor. Karar vermeden önce sınıftaki öğrencileri ve öğretmenini dinliyor, önerileri değerlendirip uygulanabilir bir plan oluşturuyor.',
    'Bu süreç Hz. Muhammed’in örnekliğinde yer alan hangi yaklaşımı yansıtır?',
    ['Hiçbir görüşü dinlemeden yalnız karar vermek.','Kararın sorumluluğunu tamamen başkasına bırakmak.','Karar vermeden önce ilgili kişilerin görüşünü almak.','Herkesin söylediğini aynı anda ve değişmeden uygulamak.'],2,
    'Görüş toplama ile sorumluluğu bırakma veya her öneriyi uygulama arasında ayrım yap.',
    ['Temsilci ilgililerin görüşünü dinliyor.','Önerileri değerlendirdikten sonra plan oluşturuyor.','Bu, istişare yani danışma örneğidir.'],
    'Metin ne sorumluluğun terk edildiğini ne de bütün önerilerin aynen uygulandığını söylüyor.',
    'İstişare, karar öncesinde görüşleri dinleyip değerlendirmektir.'),
  dk(9,'Kur’an-I Kerim Ve Özellikleri','main_theme_classification',
    'Bir çalışma kartında üç başlık bulunuyor: I. Allah’ın birliğine inanmak. II. Namaz kılmak. III. Verilen sözü tutmak. Kartlar, Kur’an’ın ana konularıyla ilişkilendiriliyor.',
    'I, II ve III için sırasıyla uygun sınıflandırma hangisidir?',
    ['İbadet – Ahlak – İnanç','İnanç – İbadet – Ahlak','Ahlak – İnanç – İbadet','İnanç – Ahlak – İbadet'],1,
    'Her ifadeyi önce ayrı sınıflandır; ardından seçeneklerde aynı sırayı ara.',
    ['Allah’ın birliğine inanmak inanç alanındadır.','Namaz bir ibadettir.','Sözünü tutmak ahlaki davranıştır.'],
    'Üç kavramın doğru olması yetmez; I–II–III sırası korunmalıdır.',
    'Sıralı sınıflandırmada her başlığın altına tek kavram yazıp seçenekle karşılaştır.'),
  dk(10,'Kur’an-I Kerim Ve Özellikleri','fundamental_sources_distinction',
    'Bir öğrenci İslam’ın temel kaynakları için bir liste hazırlıyor: Kur’an, tarihî roman, sünnet ve bir gezi günlüğü. Listede temel dinî kaynaklarla diğer metin türlerini ayırması isteniyor.',
    'Listeden hangi ikili temel dinî kaynak olarak seçilmelidir?',
    ['Tarihî roman ve gezi günlüğü.','Kur’an ve tarihî roman.','Sünnet ve gezi günlüğü.','Kur’an ve sünnet.'],3,
    'Dinî temel kaynak ile bir konuyu anlatabilecek diğer metin türünü ayır.',
    ['Kur’an, İslam’ın temel kaynağıdır.','Sünnet, Hz. Muhammed’in söz, davranış ve onaylarıyla ilgili örneklik içerir.','Roman ve gezi günlüğü bu temel kaynak ikilisinin yerine geçmez.'],
    'Bir metnin dinle ilgili olay anlatması, onu temel dinî kaynak yapmaz.',
    'Kaynak sorusunda metnin konusu ile dinî kaynak niteliğini karıştırma.'),

  hi(1,'Bir Kahraman Doğuyor','intellectual_comparison_inference',
    'Mustafa Kemal gençlik yıllarında farklı yazarların eserlerini okumuş, fikirler üzerine arkadaşlarıyla konuşmuş ve karşılaştığı görüşleri değerlendirmiştir.',
    'Bu bilgiler onun fikir hayatı hakkında hangi çıkarımı destekler?',
    ['Yalnız tek bir görüşle ilgilenmesi.','Okuduklarını hiç sorgulamadan kabul etmesi.','Farklı görüşleri karşılaştırarak düşüncesini geliştirmesi.','Arkadaşlarıyla düşünce paylaşmaktan kaçınması.'],2,
    'Okuma, tartışma ve değerlendirme davranışlarının ortak düşünsel sonucunu bul.',
    ['Birden çok yazarın görüşüyle karşılaşmıştır.','Arkadaşlarıyla tartışıp görüşleri değerlendirmiştir.','Bu durum karşılaştırarak düşünce geliştirmeyi destekler.'],
    'Tek görüşe bağlılık veya sorgusuz kabul, verilen değerlendirme davranışıyla uyumsuzdur.',
    'Kişilik çıkarımında olayda doğrudan görülen davranışı esas al.'),
  hi(2,'Millî Uyanış','organisation_purpose',
    'Millî Mücadele’nin başında farklı bölgelerde direniş çalışmaları vardı. Sivas Kongresi’nde millî cemiyetlerin ortak bir yapı altında toplanması yönünde adım atıldı.',
    'Bu adımın temel amacı hangisidir?',
    ['Birlikte hareket etmek ve mücadeleyi ortak bir örgüte bağlamak.','Bölgeler arasındaki iletişimi tamamen durdurmak.','Bütün kararları yabancı devletlere bırakmak.','Yerel çalışmaların birbirinden habersiz sürmesini sağlamak.'],0,
    'Dağınık çalışmaların ortak yapıya dönüşmesini neden-sonuç ilişkisiyle oku.',
    ['Başlangıçta çalışmalar farklı bölgelerde yürütülüyordu.','Ortak yapı koordinasyonu ve birlikteliği artırır.','Temel amaç mücadelenin birlikte yürütülmesidir.'],
    'İletişimi kesmek veya çalışmaların habersiz sürmesi birleşme amacıyla çelişir.',
    'Metindeki “Ortak yapı altında toplama” ifadesi birlik ve örgütlenmeyi düşündürür.'),
  hi(3,'Millî Uyanış','sovereignty_institution_link',
    '23 Nisan 1920’de açılan Büyük Millet Meclisinde milletin temsilcileri ülkenin geleceğine ilişkin kararlar almaya başladı. Yönetim yetkisinin milletin iradesine dayanması vurgulandı.',
    'Bu gelişme doğrudan hangi kavramla ilişkilidir?',
    ['Sömürgecilik.','Hanedan yönetimi.','Manda yönetimi.','Ulusal egemenlik.'],3,
    'Karar yetkisinin kimde olduğuna bak; bağımsızlık ile egemenliğin odaklarını ayır.',
    ['Kararlar milletin temsilcileri tarafından alınıyor.','Vurgulanan kaynak milletin iradesidir.','Bu, ulusal egemenlik kavramını gösterir.'],
    'Manda veya hanedan seçenekleri yetkiyi milletin iradesine dayandırmaz.',
    'Egemenlik sorusunda “Yönetme yetkisi kime dayanıyor?” sorusu yolu kısaltır.'),
  hi(4,'Millî Bir Destan','parallel_priorities_evidence',
    'Millî Mücadele sürerken 1921’de Maarif Kongresi toplandı. Cephedeki güçlükler devam ederken eğitimle ilgili sorunlar ve gelecekte yapılacak çalışmalar da ele alındı.',
    'Bu olay hangi yargıyı destekler?',
    ['Eğitim çalışmalarının yalnız savaş sonrasında önemsendiğini.','Askerî mücadele ile eğitim çalışmalarının birlikte önemsenmesi.','Eğitimin yalnız asker yetiştirmek için ele alındığını.','Cephedeki mücadeleden tamamen vazgeçildiğini.'],1,
    'Aynı dönemde süren iki çalışmayı birlikte değerlendir; birinin diğerini sona erdirdiğini varsayma.',
    ['Millî Mücadele devam etmektedir.','Bu sırada eğitim için kongre düzenlenmiştir.','İki alanın birlikte önemsendiği görülür.'],
    'Metin savaşın bırakıldığını veya eğitimin yalnız askerlikle sınırlandığını söylemez.',
    'Bir olayın gerçekleştiği zamanı, çıkarımın sınırı olarak kullan.'),
  hi(5,'Millî Bir Destan','mobilisation_social_evidence',
    'Tekâlif-i Millîye kapsamında halkın bazı malzemeleri ve ulaşım imkânları ordunun ihtiyaçları için kullanıldı. Farklı mesleklerden insanlar bu ihtiyaçların karşılanmasına katkı verdi.',
    'Bu uygulamalar hangi duruma kanıt oluşturur?',
    ['Mücadelenin yalnız dış yardımla yürütüldüğüne.','Sivil halkın hiçbir katkısının olmadığına.','Toplumun imkânlarını Millî Mücadele için seferber etmesi.','Her mesleğin tamamen kaldırıldığına.'],2,
    'Katkıyı kimin yaptığına ve hangi ortak amaca yöneldiğine bak.',
    ['Halk malzeme ve ulaşım imkânı sağlıyor.','Farklı mesleklerden kişiler ortak ihtiyaca katkı veriyor.','Bu, toplumsal seferberlik ve dayanışma örneğidir.'],
    'Sivil katkının olmadığı seçeneği verilen örneklerle doğrudan çelişir.',
    'Farklı kesimlerin aynı amaca katkısı, birlik ve dayanışma göstergesidir.'),
  hi(6,'Millî Bir Destan','treaty_independence_result',
    'Lozan Barış Antlaşması’yla kapitülasyonlar kaldırıldı. Yabancı devletlere tanınan bu ayrıcalıkların sona ermesi, Türkiye’nin kendi ekonomik ve hukukî düzenini belirleme gücünü destekledi.',
    'Bu sonucun tam bağımsızlıkla ilişkisi hangisidir?',
    ['Bağımsızlığa aykırı ayrıcalıkların kaldırılması.','Bütün ekonomik kararların başka devletlere verilmesi.','Ülkenin hukukî yetkilerinden tamamen vazgeçmesi.','Yabancı ayrıcalıklarının sınırsız biçimde artırılması.'],0,
    'Ayrıcalığın kaldırılmasının karar verme yetkisine etkisini belirle.',
    ['Kapitülasyonlar yabancı ayrıcalıklarıdır.','Kaldırılmaları Türkiye’nin karar yetkisini destekler.','Bu sonuç tam bağımsızlık yönündedir.'],
    'Yetkiyi dışarıya bırakma seçenekleri belirtilen sonuçla ters düşer.',
    'Bağımsızlık sorularında başka bir güce bağımlılığı artıran ve azaltan sonucu ayır.'),
  hi(7,'Atatürkçülük Ve Çağdaşlaşan Türkiye','education_unification_goal',
    'Tevhid-i Tedrisat Kanunu ile eğitim kurumları Millî Eğitim Bakanlığına bağlandı. Eğitim işlerinin ortak bir yönetim ve düzen içinde yürütülmesi hedeflendi.',
    'Bu düzenlemenin doğrudan amacı hangisidir?',
    ['Her okulun birbirinden tamamen bağımsız kurallarla çalışması.','Eğitim kurumlarının tümünün kapatılması.','Eğitim yönetiminde birliğin sağlanması.','Öğrenmenin yalnız bir meslek grubuna ayrılması.'],2,
    'Kurumların ortak yönetime bağlanmasıyla oluşan idarî sonucu bul.',
    ['Eğitim kurumları tek bakanlık çatısına bağlanıyor.','Ortak yönetim ve düzen hedefleniyor.','Doğrudan sonuç eğitim yönetiminde birliktir.'],
    'Kanunla bütün okulların kapatıldığı sonucu verilmemiştir.',
    'Kurumları bir merkezde toplama, öncelikle yönetim birliğiyle ilişkilidir.'),
  hi(8,'Demokratikleşme Çabaları','political_representation_purpose',
    'Cumhuriyetin ilk yıllarında farklı siyasi görüşlerin partiler aracılığıyla temsil edilmesi için girişimler yapıldı. Amaç, yönetimle ilgili farklı önerilerin siyasal hayatta ifade edilebilmesiydi.',
    'Bu girişimlerin demokratikleşme bakımından hedefi hangisidir?',
    ['Bütün görüşlerin yalnız tek kişiye bağlı olması.','Farklı görüşlerin siyasal temsilini geliştirmek.','Halkın siyasi konularla ilgilenmesini tamamen önlemek.','Seçim ve temsil düşüncesinden vazgeçmek.'],1,
    'Girişimin hedefini, girişimlerin sonradan bütün amaçlarına ulaşıp ulaşmadığıyla karıştırma.',
    ['Metinde farklı siyasi görüşlerin ifade edilmesi hedefleniyor.','Partiler bu görüşlerin temsil aracı olarak görülüyor.','Bu hedef siyasal temsili geliştirmektir.'],
    'Soru girişimlerin başarı sonucunu değil belirtilen demokratik amacı soruyor.',
    'Tarih sorularında “Amaç” ile “Gerçekleşen sonuç” farklı olabilir.'),
  hi(9,'Atatürk Dönemi Türk Dış Politikası','diplomacy_method_inference',
    'Türkiye, dış politikada bazı sorunlar için görüşmeler yürüttü ve antlaşmalarla çözüm aradı. Ülkenin çıkarlarını korurken komşularıyla barışçı ilişkiler geliştirmeye önem verildi.',
    'Bu yaklaşımın yöntemini en iyi anlatan seçenek hangisidir?',
    ['Her sorunda savaşı tek çözüm kabul etmek.','Ulusal çıkarları bütünüyle göz ardı etmek.','Başka devletlerle bütün iletişimi kesmek.','Sorunları diplomasi yoluyla ve barışçı yöntemlerle çözmek.'],3,
    'Hedef olan çıkarları koruma ile kullanılan çözüm yöntemini ayrı belirle.',
    ['Görüşme ve antlaşma çözüm araçlarıdır.','Barışçı ilişkiler vurgulanmaktadır.','Bu araçlar diplomasi yöntemini gösterir.'],
    'Ulusal çıkarları korumak, her sorunda savaş seçmek anlamına gelmez.',
    'Dış politika sorusunda görüşme ve antlaşma, diplomasi için doğrudan ipuçlarıdır.'),
  hi(10,'Atatürk’ün Ölümü Ve Sonrası','institution_continuity',
    'Atatürk’ün vefatından sonra devletin kurumları görevlerini sürdürdü. Cumhuriyet yönetimi devam etti ve yeni cumhurbaşkanı seçildi.',
    'Bu bilgiler hangi çıkarımı destekler?',
    ['Cumhuriyetin, tek bir kişinin yaşamıyla sınırlı olmayan kalıcı bir kurum olması.','Devletin bütün kurumlarının vefatla birlikte sona ermesi.','Cumhuriyetin yalnız geçici bir toplantı olması.','Yönetimin artık hiçbir kurala dayanmaması.'],0,
    'Kişinin yaşamı ile kurumsal yönetimin devamlılığını ayır.',
    ['Kurumların çalışmayı sürdürdüğü belirtilmiştir.','Cumhuriyet yönetimi ve yeni seçim devam etmektedir.','Bu, yönetimin kişisel yaşamı aşan kurumsal sürekliliğini gösterir.'],
    'Bütün kurumların sona ermesi, verilen devam bilgisiyle çelişir.',
    'Kurumsal süreklilik sorusunda bir değişimden sonra neyin devam ettiğine bak.')
];
