import {grade6Questions} from '../science-booklet/grade6.mjs';
import {grade7Questions} from '../science-booklet/grade7.mjs';

/** Original small formative pilot. No pupil norm, expert approval or full curriculum claim.
 * Program links are candidates; exact outcome/page acceptance is pending except preserved
 * science-source observations. English school profile and 4th-grade social program need review.
 * Adults read grades 1–2 prompts aloud without supplying the answer. No timer/penalty.
 */
const sourceFor=(grade,subject)=>{
  const programId=subject==='mathematics'?(grade===4?'legacy-2018-matematik':`tymm-current-${grade<=4?'ilkokul':'ortaokul'}-matematik`)
    :subject==='turkish'?(grade===4?'legacy-2019-turkce':`tymm-current-${grade<=4?'ilkokul':'ortaokul'}-turkce`)
    :subject==='science'?(grade===4?'legacy-2018-fen-bilimleri':'tymm-current-fen-bilimleri')
    :subject==='life_studies'?'tymm-current-hayat-bilgisi'
    :subject==='social'?'tymm-current-sosyal-bilgiler'
    :subject==='english'?(grade===4||grade===7?'legacy-2018-ingilizce':'tymm-current-ingilizce')
    :grade===4?'legacy-2018-din-kulturu':'tymm-current-din-kulturu';
  return {programId,alignmentStatus:'draft',styleReference:'original-short-formative-pilot',
    note:grade===4&&subject==='social'?'Katalog referansı; 2026–27 için 2023 Sosyal Bilgiler etkin dosyası eşlemesi bekliyor.':subject==='english'?'Olağan/çoklu dil okul profili ve etkin sürüm kabulü bekliyor.':'Sınıf ve konu eşleşmesi taslak; kesin çıktı/sayfa ve öğretmen kabulü bekliyor.'};
};
const svg=(body,alt)=>({svg:`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 360 130"><rect width="360" height="130" fill="white"/><g fill="none" stroke="#333" stroke-width="1.5">${body}</g></svg>`,alt});
const text=(x,y,value)=>`<text x="${x}" y="${y}" font-family="Arial" font-size="12" fill="#222" stroke="none">${value}</text>`;
const rectangle=(w,h)=>{const width=parseFloat(w)*22,height=parseFloat(h)*22,x=180-width/2;return svg(`<rect x="${x}" y="25" width="${width}" height="${height}"/>${text(167,18,w)}${text(x+width+8,25+height/2,h)}`,'Dikdörtgenin yatay ve düşey kenar uzunlukları verilmiştir.');};
const rows=[];
const seq=new Map();
function add(grade,subject,topic,familyId,stimulus,stem,options,answer,strategy,steps,check,tip,figure){
  const n=(seq.get(grade)??0)+1;seq.set(grade,n);
  rows.push({id:`P${grade}-${String(n).padStart(2,'0')}`,grade,subject,topic,familyId,stimulus,stem,options,answer,
    explanation:{given:stimulus,wanted:stem,strategy,steps,check,tip},source:sourceFor(grade,subject),
    ...(figure?{figure}:{}),layout:'regular',adultAssisted:grade<=2,timeLimitSeconds:null,publicationStatus:'draft'});
}
function science(grade,id){
  const original=(grade===6?grade6Questions:grade7Questions).find(q=>q.id===id);
  if(!original)throw new Error(`Missing source question ${id}`);
  const n=(seq.get(grade)??0)+1;seq.set(grade,n);
  rows.push({...structuredClone(original),id:`P${grade}-${String(n).padStart(2,'0')}`,subject:'science',
    familyId:`science:${id}`,originalQuestionId:id,source:{...original.source,alignmentStatus:'draft'},
    adultAssisted:false,timeLimitSeconds:null,publicationStatus:'draft'});
}

// 1. Sınıf — yetişkinle kısa yönerge, sayma, dinleme ve günlük yaşam.
add(1,'mathematics','Toplama','combine-small-sets','Ece’nin 7 boncuğu vardır. Ece’ye 5 boncuk daha veriliyor.','Ece’nin kaç boncuğu olur?',['10','12','13'],1,'Yeni gelenleri önceki gruba ekle.',['7’nin üzerine 5 say: 8, 9, 10, 11, 12.'],'12’den 5 çıkarınca başlangıçtaki 7 kalır.','Önce onluğa tamamlayabilirsin: 7 + 3 + 2.',svg(`${Array.from({length:7},(_,i)=>`<circle cx="${35+i*17}" cy="42" r="5"/>`).join('')}${Array.from({length:5},(_,i)=>`<circle cx="${210+i*17}" cy="42" r="5"/>`).join('')}${text(160,47,'+')}`,'Solda yedi, sağda beş boncuk; gruplar birleştiriliyor.'));
add(1,'mathematics','Eksik toplanan','complete-to-target','Bir kutuda 13 boya kalemi vardır. Kutuda 18 kalem olması isteniyor.','Kutuya kaç kalem daha konulmalıdır?',['4','6','5'],2,'13’ten 18’e kadar artışı bul.',['14, 15, 16, 17, 18: Beş kalem gerekir.'],'13 + 5 = 18.','Eksik kısmı, istenen toplamdan elindekini çıkararak da bulabilirsin.');
add(1,'mathematics','Sayıları karşılaştırma','largest-number','Üç kartta 16, 19 ve 12 yazıyor.','En büyük sayı hangisidir?',['19','16','12'],0,'Onluklar eşitse birlikleri karşılaştır.',['Üç sayının da bir onluğu var. Birlikler 6, 9 ve 2; en büyük birlik 9.'],'19, hem 16’dan hem 12’den büyüktür.','Önce onluklara, sonra birliklere bak.');
add(1,'mathematics','Geometrik şekiller','equal-sided-quadrilateral','Şeklin dört kenarı eşit uzunluktadır. Dört köşesi de defterin köşesi gibi diktir.','Bu şeklin adı nedir?',['Üçgen','Kare','Çember'],1,'Kenarları ve köşeleri say.',['Dört eşit kenarı ve dik köşeleri olan şekil karedir.'],'Üçgenin üç köşesi vardır; çemberin köşesi yoktur.','Şekli döndürmek adını değiştirmez.',svg('<rect x="137" y="20" width="80" height="80"/>','Dört eşit kenarı olan, dört köşesi de defterin köşesi gibi dik gösterilmiş bir şekil.'));
add(1,'turkish','Dinlediğini anlama','listen-purpose','Duru, saksıdaki çiçeklerin toprağını kuru gördü. Küçük sulama kabını suyla doldurdu.','Duru suyu niçin doldurmuş olabilir?',['Çiçekleri sulamak için.','Oyuncaklarını toplamak için.','Kitap okumak için.'],0,'Kuru toprakla su arasındaki ilişkiyi düşün.',['Duru kuru toprağı görüyor. Suyu çiçeklerin toprağına vermek için hazırlıyor.'],'Diğer seçeneklerde suya gerek yok.','Bir davranışın amacını önceki olaydan anlayabilirsin.');
add(1,'turkish','Olay sırası','listen-sequence','Ali önce ellerini yıkadı, sonra yemek yedi, en son dişlerini fırçaladı.','Ali ellerini yıkadıktan hemen sonra ne yapmıştır?',['Dişlerini fırçalamıştır.','Uyumuştur.','Yemek yemiştir.'],2,'Önce, sonra ve en son sözlerini izle.',['Ellerini yıkamasından sonra yemek yemesi anlatılıyor.'],'Diş fırçalama üçüncü olaydır.','Hemen sonra, sıradaki bir sonraki olay demektir.');
add(1,'turkish','Zıt anlam','opposite-size','Büyük kutunun yanında onunla aynı türden daha ufak bir kutu var.','Büyük sözcüğünün zıttı hangisidir?',['Uzun','Küçük','Yuvarlak'],1,'Boyut bildiren karşıt sözcüğü bul.',['Büyük ve küçük, boyut bakımından zıt anlamlıdır.'],'Yuvarlak biçim bildirir; büyüğün zıttı değildir.','Sözcükleri aynı özellik üzerinden karşılaştır.');
add(1,'life_studies','Okulda güvenlik','report-slip-risk','Sınıfın kapısına su dökülmüş. Bir arkadaşın oraya doğru koşuyor.','En güvenli davranış hangisidir?',['Suyun üzerinden atlamak.','Hiçbir şey söylememek.','Öğretmene haber vermek.'],2,'Kayma tehlikesini güvenli biçimde giderecek yardımı seç.',['Öğretmene haber verilir; arkadaş da kaygan yer için uyarılır.'],'Koşmak ve atlamak düşme tehlikesini artırır.','Tehlikeli durumlarda güvendiğin yetişkinden yardım iste.');
add(1,'life_studies','Öz bakım','hand-hygiene','Deniz bahçede toprakla oynadıktan sonra sofraya geliyor.','Deniz önce ne yapmalıdır?',['Yemekten önce ellerini yıkamak.','Ellerini yalnızca pantolonuna silmek.','Yıkanmadan yemeğe başlamak.'],0,'Yemekten önce el temizliğini düşün.',['Eller su ve sabunla yıkanır. Sonra yemeğe başlanır.'],'Pantolona silmek el yıkamanın yerini tutmaz.','Oyun sonrası ve yemek öncesi el temizliğini hatırla.');
add(1,'life_studies','Trafikte güvenlik','pedestrian-light','Bir çocuk, yanında yetişkin varken ışıklı yaya geçidinde karşıya geçecek. Yaya ışığı kırmızı.','Ne yapmalıdır?',['Araçların arasından koşmak.','Yaya geçidinde yeşil ışığı beklemek.','Kırmızı ışıkta hemen geçmek.'],1,'Yayalara ait ışığın işaretini izle.',['Kırmızıda beklenir. Yeşilde de yol kontrol edilerek yetişkinle geçilir.'],'Koşmak veya kırmızıda geçmek güvenli değildir.','Işık yeşil olsa da yolu kontrol et.');

// 2. Sınıf.
add(2,'mathematics','Onluk bozma ve toplama','two-digit-regroup','Kütüphanenin bir rafında 24, diğer rafında 18 kitap var.','İki rafta toplam kaç kitap vardır?',['32','42','44'],1,'Birlikleri ve onlukları birlikte topla.',['4 + 8 = 12; 2 birlik yazıp bir onluğu onluklara ekle. 20 + 10 + 10 + 2 = 42.'],'42 − 18 = 24.','On birlik, bir onluk eder.');
add(2,'mathematics','Çıkanı bulma','missing-subtrahend','Bir kutuda 40 düğme vardı. Bir kısmı kullanıldı; kutuda 17 düğme kaldı.','Kaç düğme kullanılmıştır?',['17','27','23'],2,'Başlangıçtan kalanı çıkar.',['40 − 17 = 23 düğme kullanılmıştır.'],'23 kullanılan + 17 kalan = 40.','Kullanılan ile kalanın toplamı başlangıcı verir.');
add(2,'mathematics','Eş gruplar','equal-groups','Üç tabakta dörder kurabiye bulunuyor.','Tabaklarda toplam kaç kurabiye vardır?',['12','7','16'],0,'Üç eş grubu birleştir.',['4 + 4 + 4 = 12.'],'Her tabaktan dört sayıldığında üç tabak tamamlanır.','Tekrarlı toplama, eş grupları saymayı kolaylaştırır.');
add(2,'turkish','Ana düşünce','cooperation-main-idea','Mina sınıf kitaplığını tek başına düzenleyemedi. İki arkadaşı yardım edince kitaplar kısa sürede yerleşti.','Bu metinde vurgulanan düşünce hangisidir?',['Kitaplar yalnızca büyük raflara konur.','Birlikte çalışmak işleri kolaylaştırır.','Kitapları hiç düzenlememek gerekir.'],1,'Olayın başı ile sonu arasındaki değişimi bul.',['Yardım gelince iş kolaylaşıp kısa sürede bitiyor.'],'Kitapların raf boyutundan söz edilmiyor.','Ana düşünce, metnin vermek istediği temel mesajdır.');
add(2,'turkish','Eş anlam','guest-synonym','Bugün evimize bir konuk gelecek.','Bu cümlede konuk yerine hangi sözcük kullanılabilir?',['Misafir','Komşuluk','Yolculuk'],0,'Cümlenin anlamını bozmayan sözcüğü seç.',['Konuk ve misafir aynı anlamda kullanılabilir.'],'“Evimize bir misafir gelecek.” anlamı korur.','Eş anlamlı sözcüğü cümlenin içine yerleştirip dene.');
add(2,'turkish','Neden-sonuç','wind-cause','Uçurtma yerde duruyordu. Rüzgâr çıkınca uçurtma yükselmeye başladı.','Uçurtma neden yükselmeye başlamıştır?',['Hava karardığı için.','İpi kısaldığı için.','Rüzgâr çıktığı için.'],2,'Değişimden hemen önce olan olayı bul.',['Metinde rüzgâr çıktıktan sonra yükselme başlıyor.'],'Havanın kararması ve ipin kısalması anlatılmıyor.','Neden sorusunun cevabı metinde bulunmalıdır.');
add(2,'life_studies','Acil yardım','emergency-number','Bir yetişkin, ciddi bir trafik kazası için acil yardım isteyecek.','Türkiye’de hangi numara aranır?',['1100','112','1000'],1,'Acil yardım için kullanılan ortak numarayı hatırla.',['Türkiye’de ortak acil çağrı numarası 112’dir.'],'Acil çağrı hattı oyun veya deneme için aranmaz.','Acil durumda konum ve olay kısa, doğru biçimde anlatılır.');
add(2,'life_studies','Hava koşulları','choose-clothes','Hava çok soğuk ve yağmurlu. Ekin dışarı çıkacak.','Hangisi bu havaya daha uygun bir seçimdir?',['İnce tişört ve terlik.','Mayo ve güneş şapkası.','Mont ve kapalı ayakkabı.'],2,'Giyimi hava koşullarıyla eşleştir.',['Soğukta sıcak tutan, yağmurda koruyan giysiler seçilir.'],'Diğer seçenekler soğuğa ve yağmura karşı yeterli koruma sağlamaz.','Dışarı çıkmadan hava durumuna bak.');
add(2,'english','Colours','colour-word','Lale says: “My pencil is blue.”','What colour is Lale’s pencil?',['Blue','Red','Yellow'],0,'Kalemin rengini belirten sözcüğü bul.',['Cümlede kalemin blue, yani mavi olduğu söyleniyor.'],'Red kırmızı, yellow sarı demektir.','Renk sorularında colour sözcüğüne dikkat et.');
add(2,'english','Numbers','number-word','There are seven stars on a card.','Which word tells the number of stars?',['Six','Seven','Nine'],1,'Yıldız sayısını bildiren sözcüğü seç.',['Seven, yedi demektir.'],'Six altı, nine dokuz demektir.','Sayıyı nesne adından ayır.');

// 3. Sınıf.
add(3,'mathematics','Doğal sayılarla toplama','three-digit-addition','Bir okulun kitaplığında 246 kitap vardı. Kitaplığa 178 kitap bağışlandı.','Kitaplıkta toplam kaç kitap oldu?',['414','434','424'],2,'Basamakları hizalayarak topla.',['6 + 8 = 14; elde 1. Onluklar 4 + 7 + 1 = 12; elde 1. Yüzlükler 2 + 1 + 1 = 4.'],'424 − 178 = 246.','Eldeleri bir sonraki basamağa ekle.');
add(3,'mathematics','Bölme','equal-sharing','72 fide, 8 sıraya eşit sayıda dikilecek.','Her sırada kaç fide olur?',['9','8','12'],0,'Toplam fide sayısını sıra sayısına böl.',['72 ÷ 8 = 9.'],'8 × 9 = 72.','Eşit paylaşmada bölme kullanılır.');
add(3,'mathematics','Yarım','half-a-set','18 mandalinanın yarısı bir sepete, kalanı başka bir sepete konuluyor.','İlk sepette kaç mandalina vardır?',['6','9','12'],1,'Yarımı bulmak için iki eş gruba ayır.',['18 ÷ 2 = 9.'],'9 + 9 = 18.','Yarım, iki eş parçadan biridir.');
add(3,'mathematics','Çevre','rectangle-perimeter','Dikdörtgen bir kartın uzun kenarı 5 cm, kısa kenarı 3 cm’dir.','Kartın çevresi kaç santimetredir?',['8 cm','15 cm','16 cm'],2,'Dört kenarın uzunluklarını topla.',['5 + 3 + 5 + 3 = 16 cm.'],'Karşılıklı kenarlar eşittir; iki kısa, iki uzun kenar sayıldı.','Çevre, şeklin etrafındaki toplam uzunluktur.',rectangle('5 cm','3 cm'));
add(3,'turkish','Sözcükte anlam','literal-thin','“İnce kalem, kalın defterin üstündeydi.”','Bu cümlede ince olan nedir?',['Kalem','Defter','Masa'],0,'Sözcüğün nitelediği varlığı bul.',['İnce sözcüğü kalemin, kalın sözcüğü defterin özelliğidir.'],'Masa sözcüğü cümlede yoktur.','Özellik bildiren sözcüğün yanındaki adı kontrol et.');
add(3,'turkish','Başlık','book-journey-title','Bir kitap önce yazılır, sonra basılır. Kitapçıya veya kütüphaneye ulaşır. Sonunda bir okurun ellerinde yeni bir yolculuğa çıkar.','Bu metne en uygun başlık hangisidir?',['Oyuncakların Dünyası','Kitapların yolculuğu','Spor Yapmanın Önemi'],1,'Metnin bütününde anlatılan varlığı ve süreci düşün.',['Metin, kitabın yazılmasından okura ulaşmasına kadar olan yolu anlatıyor.'],'Diğer başlıklar metnin konusunu yansıtmaz.','Başlık yalnız bir sözcüğe değil, bütün metne uymalıdır.');
add(3,'turkish','Noktalama','question-ending','“Bugün kütüphane açık mı” cümlesinin sonuna bir işaret konulacak.','Hangi işaret kullanılmalıdır?',['Nokta (.)','Virgül (,)','Soru işareti (?)'],2,'Cümlenin bilgi isteyip istemediğine bak.',['Açık mı ifadesi bir soru soruyor. Sonuna soru işareti gelir.'],'Virgül cümlenin sonunu bu şekilde kapatmaz.','Soru cümlelerinin sonuna soru işareti koy.');
add(3,'turkish','Olay sırası','planting-sequence','Selin tohumları toprağa ekti. Sonra toprağı suladı. Birkaç gün sonra filizleri gördü.','Selin ilk olarak ne yapmıştır?',['Tohumları toprağa ekmiştir.','Filizleri görmüştür.','Toprağı sulamıştır.'],0,'Metindeki ilk olayı bul.',['Ekimden sonra sulama, daha sonra filizlenme anlatılıyor.'],'Filizleri görmek birkaç gün sonradır.','Önce ve sonra ilişkisini bir sıra gibi düşün.');
add(3,'science','Kuvvetin etkileri','push-away','Duru, duran oyuncak arabayı eliyle kendisinden uzağa doğru hareket ettiriyor.','Duru arabaya hangi tür kuvvet uygulamıştır?',['Çekme','İtme','Kuvvet uygulamamıştır.'],1,'Elin arabayı hangi yöne hareket ettirdiğini düşün.',['Duru arabayı kendisinden uzağa itiyor; arabanın hareket etmesini sağlıyor.'],'Kendisine doğru alsaydı çekme yapmış olurdu.','Kuvvetin itme mi çekme mi olduğunu yapılan hareketten anla.');
add(3,'science','Elektrikli araçlar','battery-powered-tool','Bir masada el feneri, tahta cetvel ve cam bardak bulunuyor.','Hangisinin çalışması için elektrik enerjisi gerekir?',['Tahta cetvel','Cam bardak','El feneri'],2,'Araçların nasıl kullanıldığını düşün.',['El fenerinin lambası, pilin sağladığı elektrik enerjisiyle ışık verir.'],'Tahta cetvel ve cam bardak kullanılırken elektrik gerekmez.','Pille çalışan araçlar da elektrikli araçtır.');
add(3,'science','Duyu organları','hearing-organ','Arda, kapı zilini duyunca kapıya yöneldi.','Arda zilin sesini hangi duyu organıyla algıladı?',['Kulak','Burun','Deri'],0,'Uyaranın ses olduğunu belirle.',['Ses işitme duyusuyla, kulak yardımıyla algılanır.'],'Burun koku, deri dokunma ile ilişkilidir.','Önce duyunun türünü belirle.');
add(3,'life_studies','Dijital güvenlik','private-information','Bir oyun sırasında tanımadığı biri, Ada’dan ev adresini istiyor.','Ada ne yapmalıdır?',['Adresini hemen yazmak.','Güvendiği bir yetişkine haber vermek.','Arkadaşının adresini göndermek.'],1,'Kişisel bilgiyi koruyan seçeneği seç.',['Ada adresini paylaşmaz; güvendiği yetişkinden yardım ister.'],'Başkasının adresini vermek de güvenli değildir.','Adres, parola ve telefon numarası özel bilgilerdir.');
add(3,'life_studies','Yönler','opposite-direction','Bir öğrenci kuzeye bakıyor. Arkasını döndüğünde tam ters yöne bakmış oluyor.','Şimdi hangi yöne bakar?',['Doğu','Batı','Güney'],2,'Kuzeyin karşısındaki yönü bul.',['Kuzey ile güney birbirinin ters yönüdür.'],'Doğu ve batı, kuzeyin karşısında değil yanlarındadır.','Yön çiftlerini hatırla: Kuzey–Güney, Doğu–Batı.');
add(3,'english','Abilities','fish-ability','A fish lives in water. It moves through the water.','Which sentence is correct?',['It can swim.','It can ride a bike.','It can read a book.'],0,'Balığın yapabildiği hareketi seç.',['Swim, yüzmek demektir; balık yüzebilir.'],'Bisiklet sürmek ve kitap okumak balığın yeteneği değildir.','Can, yapabilme anlamı verir.');
add(3,'english','Greetings','morning-greeting','It is eight o’clock in the morning. You meet your teacher.','What do you say?',['Good night!','Good morning!','Goodbye!'],1,'Günün zamanına uygun selamı seç.',['Sabah karşılaşınca Good morning denir.'],'Good night gece, goodbye ayrılırken kullanılır.','Morning sabah demektir.');

// 4. Sınıf — eski program adayları ile güncel katalog referansı karıştırılmaz.
add(4,'mathematics','Kesirler','remaining-fraction','Bir kâğıt sekiz eş parçaya ayrılıyor. Üç parçası boyanıyor.','Boyanmayan kısım bütünün kaçta kaçıdır?',['3/8','5/8','5/3'],1,'Toplam parçalardan boyalıları çıkar.',['8 − 3 = 5 parça boyanmamış; her parça bütünün sekizde biridir.'],'3/8 + 5/8 = 8/8, yani bütün.','Payda bütünün kaç eş parçaya ayrıldığını söyler.');
add(4,'mathematics','Bölme','packing-without-remainder','168 kalem, her birinde 7 kalem olacak şekilde paketlenecek.','Kaç paket hazırlanır?',['21','28','24'],2,'Toplam kalemi paket başına kaleme böl.',['168 ÷ 7 = 24.'],'24 × 7 = 168; hiç kalem artmaz.','Paket sayısı ile paketteki miktarın çarpımı toplamdır.');
add(4,'mathematics','Zaman ölçme','elapsed-time','Bir etkinlik saat 09.35’te başlayıp 50 dakika sürüyor.','Etkinlik saat kaçta biter?',['10.25','10.15','09.85'],0,'Önce sonraki tam saate ulaş.',['09.35’ten 10.00’a 25 dakika vardır. Kalan 25 dakika eklenince 10.25 olur.'],'25 + 25 = 50 dakika.','Bir saat 60 dakikadır, 100 dakika değildir.');
add(4,'mathematics','Alan','rectangle-area','Dikdörtgen bir kartın kenar uzunlukları 6 cm ve 4 cm’dir.','Kartın alanı kaç santimetrekaredir?',['20 cm²','24 cm²','10 cm²'],1,'Birim karelerin sıra ve sütun sayısını çarp.',['6 × 4 = 24 cm².'],'Çevre toplam uzunluğu verir; burada iç bölgenin alanı soruluyor.','Alan için birim kare sayısını düşün.',rectangle('6 cm','4 cm'));
add(4,'turkish','Ana düşünce','reading-quality','Bora her gün çok sayfa okuduğunu söylüyordu ama okuduklarını anlatamıyordu. Daha yavaş okuyup not almaya başlayınca metinleri daha iyi anladı.','Metnin vermek istediği mesaj hangisidir?',['Çok kitap okuyan herkes aynı şeyi anlar.','Not tutmak okumayı tamamen gereksiz kılar.','Okunanı anlamak, yalnızca sayfa sayısından önemlidir.'],2,'Bora’nın değişiklikten sonra ne kazandığını düşün.',['Yavaş okuyup not almak, anlamasını artırmıştır. Vurgu sayfa sayısında değil anlamadadır.'],'Metin okumayı bırakmayı önermiyor.','Ana düşünce, örnekteki kişiyi aşan genel mesajdır.');
add(4,'turkish','Yazım','locative-suffix','Bulunma anlamındaki -da eki sözcüğe bitişik yazılır.','Hangi cümlede bu ek doğru yazılmıştır?',['Kitabım çantamda kaldı.','Kitabım çantam da kaldı.','Kitabım çanta mda kaldı.'],0,'Nerede sorusunun cevabını bul.',['Kitabım nerede kaldı? Çantamda. Bu, bulunma ekidir; bitişik yazılır.'],'Ayrı yazılan da burada istenen yer anlamını vermez.','Nerede sorusuna cevap veren -de/-da bir ektir.');
add(4,'turkish','Metin oluşturma','instruction-order','I. Kabuğunu soydu. II. Elmayı yıkadı. III. Elmayı dilimleyip tabağa koydu.','Bu işlemler hangi sırayla yapılmış olmalıdır?',['I – III – II','II – I – III','III – II – I'],1,'Hazırlıktan sunuma ilerle.',['Önce elma yıkanır, sonra soyulur, ardından dilimlenir.'],'Soymadan önce yıkamak, metindeki işlemleri düzenli hâle getirir.','İşlem metinlerinde önce yapılması gereken adımı bul.');
add(4,'science','Kuvvetin etkileri','direction-change','Düz ilerleyen bir topa yandan vuruluyor. Top farklı bir yöne doğru ilerlemeye başlıyor.','Kuvvetin hangi etkisi açıkça gözlenmiştir?',['Topun kütlesi artmıştır.','Top yok olmuştur.','Hareket yönü değişmiştir.'],2,'Vurmadan önce ve sonraki hareketi karşılaştır.',['Top önce düz gidiyor, sonra başka yöne dönüyor.'],'Kütle artışı veya yok olma bilgisi yoktur.','Kuvvet hız, yön veya şekil değişikliğine neden olabilir.');
add(4,'science','Karışımları ayırma','filter-leaves','Demlenmiş çayın içindeki yapraklar, çay sıvısından ayrılmak isteniyor.','Hangi yöntem uygundur?',['Süzme','Mıknatısla ayırma','Dondurma'],0,'Sıvıyı geçirip yaprakları tutan yöntemi düşün.',['Süzgeç çayı geçirir, yaprakları tutar.'],'Çay yaprakları mıknatısla toplanmaz.','Parça boyutları farklıysa uygun süzgeç işe yarar.');
add(4,'science','Basit elektrik devresi','close-circuit','Sağlam pil ve ampul doğru bağlanmış, bağlantılar tamamlanmıştır. Devrenin anahtarı açıktır.','Ampulün yanması için ne yapılmalıdır?',['Pili çıkarmak.','Anahtarı kapatmak.','Kablolardan birini ayırmak.'],1,'Elektrik yolunun kesintisiz olması gerekir.',['Açık anahtar yolu keser. Anahtar kapanınca devre tamamlanır.'],'Pili veya kabloyu çıkarmak devreyi tamamlamaz.','Devrede kapalı anahtar, elektrik yolunun açık olması demek değildir.');
add(4,'social','Geçmişi tanıma','historical-object-evidence','Bir müzede geçmişte kullanılan yağ lambası sergileniyor.','Bu eşya bize öncelikle hangi bilgiyi sağlar?',['Gelecekte hangi lambaların üretileceğini kesin gösterir.','O dönemde yaşayan herkesin adını verir.','Geçmişte kullanılan eşyalar hakkında bilgi verir.'],2,'Eşyanın doğrudan gösterebildiği bilgiyi seç.',['Yağ lambası, geçmişteki aydınlatma araçlarına örnektir.'],'Tek bir eşya geleceği veya herkesin adını göstermez.','Tarihî bir kaynaktan kanıtlayamayacağı sonuçlar çıkarma.');
add(4,'social','Bilinçli tüketim','need-before-want','Eylül’ün defteri bitmiştir. Parası ya gerekli deftere ya da istediği süs çıkartmalarına yetiyor.','Öncelikli seçim hangisidir?',['Gerekli defteri almak.','Yalnız çıkartmaları almak.','Parasının tamamını gereksiz bir ürüne vermek.'],0,'İhtiyaçla isteği ayır.',['Ders için defter gereklidir; çıkartma bir istektir.'],'Öncelik, acil ihtiyacın karşılanmasıdır.','Bütçe sınırlıysa önce ihtiyaçlarını sırala.');
add(4,'english','Jobs','medical-profession','“I work in a hospital. I examine sick people.”','What is this person’s job?',['Farmer','Doctor','Pilot'],1,'İş yeri ve yapılan işi birlikte düşün.',['Hastanede hastaları muayene eden kişi doctor, yani doktordur.'],'Farmer çiftçi, pilot uçak kullanandır.','İki ipucunu birleştirerek mesleği bul.');
add(4,'english','Activities','pool-activity','Mert says: “I like being in the pool and moving through water.”','Which activity does Mert like?',['Drawing','Cycling','Swimming'],2,'Pool ve water ipuçlarını kullan.',['Havuzda su içinde yapılan etkinlik swimming, yani yüzmedir.'],'Çizim ve bisiklet, bu anlatıma uymaz.','Etkinliği yer ve hareket bilgisiyle eşleştir.');
add(4,'religion','Güzel ahlak','help-with-dignity','Bir öğrenci, ihtiyaç duyan arkadaşına destek olmak istiyor. Arkadaşı bu durumun herkesin önünde konuşulmasını istemiyor.','Hangi davranış daha uygundur?',['Yardımı kişinin onurunu koruyarak yapmak.','Yardımı herkesin önünde övünerek anlatmak.','Arkadaşını yardım aldığı için küçümsemek.'],0,'Yardım ederken karşıdakinin duygularını da gözet.',['Destek sunulur; arkadaşın incinmemesine ve mahremiyetine dikkat edilir.'],'Övünme ve küçümseme yardımın amacına aykırıdır.','İyilik, karşılık beklemeden ve incitmeden yapılır.');

// 5. Sınıf.
add(5,'mathematics','Ondalık gösterimler','decimal-comparison','Dört yürüyüş yolunun uzunlukları 2,35 km; 2,4 km; 2,04 km ve 2,09 km’dir.','En uzun yol kaç kilometredir?',['2,35','2,4','2,04','2,09'],1,'Tam kısımlar eşitse onda birlikleri karşılaştır.',['2,4 = 2,40. Onda birlikler sırasıyla 3, 4, 0 ve 0; en büyük sayı 2,40.'],'2,40 hem 2,35’ten hem diğer iki sayıdan büyüktür.','Daha çok basamak yazılması daha büyük sayı olduğu anlamına gelmez.');
add(5,'mathematics','Kesirlerin gösterimleri','decimal-fraction-equivalence','Bir şeridin 0,5’i boyalıdır.','Boyalı kısmı hangi kesir aynı değerde gösterir?',['1/5','1/10','1/2','2/5'],2,'Ondalık gösterimi eş parça sayısıyla ilişkilendir.',['0,5 = 5/10. On parçanın beşi, bütünün yarısıdır: 1/2.'],'Bir bütünün yarısı 0,5’tir.','Ondalık gösterim ile kesir farklı yazılışlar olabilir, miktar aynı kalabilir.');
add(5,'mathematics','Yüzdeler','quarter-representation','Bir yüzlük tabloda 100 eş kareden 25’i boyalıdır.','Boyalı kısmı gösteren yüzde 25, aşağıdaki kesirlerden hangisine eşittir?',['1/5','1/2','3/4','1/4'],3,'Yüz eş parçanın 25’ini bütünle karşılaştır.',['25/100 kesrinin payı ve paydası 25’e bölünür: 1/4.'],'Dört tane 25, 100 eder; boyalı bölüm dört eş gruptan biridir.','%25 = 25/100 = 1/4.');
add(5,'mathematics','Açılar','complementary-angle','Bir dik açı, bir ışınla 35° ve x açısı olarak iki parçaya ayrılıyor.','x kaç derecedir?',['55°','65°','125°','35°'],0,'Dik açının toplamını 90° al.',['90 − 35 = 55°.'],'35 + 55 = 90°.','Dik açıyı tamamlayan açıları 90°’ye tamamla.');
add(5,'mathematics','Sayı örüntüleri','constant-step-pattern','Bir örüntü 3, 7, 11, 15 şeklinde her adımda aynı miktar artarak ilerliyor.','Bu kurala göre sonraki sayı kaçtır?',['18','19','20','23'],1,'Ardışık sayılar arasındaki farkı bul.',['7 − 3 = 4; 11 − 7 = 4; 15 − 11 = 4. Sonraki sayı 15 + 4 = 19.'],'19 − 15 de 4’tür.','Kuralın bütün verilen geçişlerde geçerli olduğunu kontrol et.');
add(5,'turkish','Ana düşünce','planning-main-idea','Defne ödevlerine rastgele başladığında bazılarını unutuyordu. İşlerini sıraya koyan bir liste hazırlayınca hem ödevlerini bitirdi hem dinlenmeye zaman ayırdı.','Parçada asıl anlatılmak istenen hangisidir?',['Dinlenmek zaman kaybıdır.','Bütün işler aynı anda yapılmalıdır.','Bir plan, zamanı daha verimli kullanmayı sağlar.','Listeler yalnız alışverişte kullanılır.'],2,'Sorun ile bulunan çözüm arasındaki ilişkiyi kur.',['Unutma ve zaman sorunu, işlerin planlanmasıyla çözülüyor.'],'Parça dinlenmeye de zaman ayırmayı olumlu anlatıyor.','Ana düşüncede gereksiz kesinliklerden kaçın.');
add(5,'turkish','Amaç-sonuç','birdwatching-purpose','Öğrenciler, kuşları ürkütmemek için gözlem alanında sessiz yürüdü.','Öğrenciler neden sessiz yürümüştür?',['Yol daha kısa olduğu için.','Hava sıcak olduğu için.','Ayakkabıları yeni olduğu için.','Kuşları ürkütmemek için.'],3,'İçin sözcüğünün bağladığı amacı bul.',['Sessiz yürümenin amacı kuşların ürkmemesidir.'],'Diğer nedenler cümlede belirtilmiyor.','Amaç, yapılmak istenen veya önlenmek istenen sonuçtur.');
add(5,'turkish','Çıkarım','practice-improvement','Deniz ilk denemede dikişini yamuk yaptı. Sonraki günlerde çalıştı. Bir hafta sonra düzgün dikişlerle küçük bir kese dikti.','Bu parçadan hangisi çıkarılabilir?',['Düzenli denemeler sonunda ilerleme sağlamıştır.','İlk denemede kusursuz sonuç almıştır.','Hiç çalışmadan öğrenmiştir.','Bütün el işlerini herkesten iyi yapar.'],0,'İlk ve son sonuç arasındaki gelişimi izle.',['İlk dikiş yamuktur; çalışma sonunda düzgün dikiş oluşur.'],'Bütün el işlerinde üstün olduğu söylenemez.','Çıkarım, verilenlerden destek almalıdır.');
add(5,'turkish','Metnin akışı','scientific-text-order','Bir öğrenci önce iki bitkinin büyümesini kaydediyor, sonra kayıtları karşılaştırıyor, en son bulgusunu yazıyor.','Bu sürecin sırası hangisidir?',['Sonuç → Gözlem → Karşılaştırma','Gözlem → Karşılaştırma → Sonuç','Karşılaştırma → Sonuç → Gözlem','Sonuç → Karşılaştırma → Gözlem'],1,'Önce bilgi topla, sonra ilişki kur, ardından sonuca ulaş.',['Büyümeyi kaydetmek gözlem; kayıtları incelemek karşılaştırma; bulguyu yazmak sonuçtur.'],'Sonuç gözlemden önce gelmez.','Süreçteki eylemleri kavramlarıyla eşleştir.');
add(5,'science','Sürtünme','increase-friction','Bir sporcu, kaygan olmayan aynı zeminde ayakkabısının daha iyi tutunmasını istiyor.','Hangi seçim sürtünmeyi artırmaya uygundur?',['Tabana yağ sürmek.','Tabanı tamamen düzleştirmek.','Tırtıklı tabanlı ayakkabı.','Tabana kaygan bir örtü takmak.'],2,'Kaymayı azaltacak yüzey özelliğini seç.',['Tırtıklı taban tutunmayı artırmaya yardımcı olur.'],'Yağ ve kaygan örtü tutunmayı azaltır.','Sürtünme her zaman istenmeyen bir etki değildir.');
add(5,'science','Ay’ın evreleri','full-moon-observation','Ay’ın Dünya’dan görünen yüzünün tamamı aydınlık ve daire biçiminde görülüyor.','Hangi ana evre gözlenmektedir?',['Yeni ay','İlk dördün','Son dördün','Dolunay'],3,'Görünen aydınlık kısmın büyüklüğünü düşün.',['Görünen yüz bütünüyle aydınlıksa dolunaydır.'],'Dördünlerde görünen yüzün yarısı aydınlıktır.','Ay’ın evresi, görünen aydınlık bölümle adlandırılır.');
add(5,'science','Hücre','plant-cell-distinction','Bitki ve hayvan hücrelerinin modelleri karşılaştırılıyor.','Aşağıdakilerden hangisi bitki hücresinde bulunur, hayvan hücresinde bulunmaz?',['Hücre duvarı','Hücre zarı','Sitoplazma','Çekirdek'],0,'İki modelin ortak ve farklı yapılarını ayır.',['Hücre duvarı bitki hücresinde bulunur; hayvan hücresinde bulunmaz.'],'Zar, sitoplazma ve çekirdek temel okul modellerinde her ikisinde yer alır.','Hücre zarı ile hücre duvarını karıştırma.');
add(5,'science','Kuvveti ölçme','measurement-tool','Bir öğrenci çantasına etki eden ağırlık kuvvetini newton cinsinden ölçmek istiyor.','Hangi aracı kullanmalıdır?',['Termometre','Dinamometre','Dereceli kap','Kronometre'],1,'Ölçülecek büyüklüğü ve birimini belirle.',['Kuvvet dinamometreyle ölçülür; birimi newtondur.'],'Termometre sıcaklığı, kronometre süreyi ölçer.','Önce neyi ölçtüğünü, sonra aracı seç.');
add(5,'social','Güvenilir bilgi','weather-source','Sınıf ertesi gün açık hava gezisi yapacak. Öğretmen güncel hava tahminine ihtiyaç duyuyor.','Hangi kaynak bu amaç için daha uygundur?',['Geçen yılın gezi fotoğrafı.','Tarihsiz bir sosyal medya mesajı.','Meteoroloji Genel Müdürlüğünün güncel tahmini.','Bir arkadaşın tahmini.'],2,'Kaynağın uzmanlığına ve güncelliğine bak.',['Meteoroloji Genel Müdürlüğü hava tahmini yayımlar; güncel tahmin istenen tarihle ilgilidir.'],'Eski fotoğraf yarının havasını göstermez; tahmin de kesin gerçekleşme garantisi değildir.','Güvenilirlik ve güncellik birlikte önemlidir.');
add(5,'social','Göreli konum','map-west','Haritanın üstü kuzeyi gösteriyor. Okul, parkın solunda yer alıyor.','Okul parkın hangi yönündedir?',['Kuzey','Doğu','Güney','Batı'],3,'Kuzey yukarıysa solu batı olarak belirle.',['Haritada sol taraf batıdır; okul parkın batısındadır.'],'Sağ taraf doğudur.','Yönü, referans alınan yere göre söyle.');
add(5,'social','Katılım ve iş birliği','shared-project-roles','Bir sınıf geri dönüşüm projesi hazırlıyor. Toplama, afiş ve bilgilendirme işleri yapılacak.','Hangisi etkili iş birliğine örnektir?',['Görevleri paylaşarak birlikte çalışmak.','Bütün işi tek kişiye bırakmak.','Diğer grupların işini engellemek.','Görevleri kimseyle konuşmadan sürekli değiştirmek.'],0,'Ortak amaç için sorumlulukları düzenle.',['Görevler paylaşılır; herkes kendi işiyle ortak sonuca katkı sağlar.'],'İşi tek kişiye bırakmak katılımı sınırlar.','İş birliği, görev paylaşımı ve iletişim gerektirir.');
add(5,'english','School life','school-subject','“We solve number problems and learn about shapes in this lesson.”','Which lesson is described?',['Music','Maths','Art','P.E.'],1,'Sayı ve şekil ipuçlarını dersle eşleştir.',['Number problems ve shapes matematik dersini anlatır.'],'Music müzik, art resim/sanat, P.E. beden eğitimidir.','Anahtar sözcükleri birlikte değerlendir.');
add(5,'english','Weather','cold-weather-inference','“Wear your coat and gloves. The temperature is below zero.”','Which sentence describes the weather?',['It is hot.','It is warm.','It is cold.','It is sunny and hot.'],2,'Kıyafet ve sıcaklık bilgisini birleştir.',['Coat ve gloves, sıfırın altındaki soğuk hava için öneriliyor.'],'Güneşli olup olmadığı belirtilmiyor; sıcak olmadığı açıktır.','Cold soğuk demektir.');
add(5,'religion','Allah’a teşekkür','gratitude-concept','İslam dininde kişinin sahip olduğu nimetlerin farkına varıp Allah’a teşekkür etmesi önemsenir.','Bu davranış hangi kavramla ifade edilir?',['İsraf','Kibir','İftira','Şükür'],3,'Teşekkür ve minnettarlık anlamını taşıyan kavramı bul.',['Nimetleri fark etmek ve Allah’a teşekkür etmek şükürdür.'],'İsraf savurganlık, kibir kendini üstün görme, iftira asılsız suçlamadır.','Kavramı tanımdaki temel davranışla eşleştir.');
add(5,'religion','Adalet','fair-turn-taking','Bir grup karar almadan önce bütün üyelerin düşüncesini duymak istiyor.','Hangi uygulama adalete uygundur?',['Herkese söz hakkı tanımak.','Yalnız yakın arkadaşları dinlemek.','Sessiz kalanlarla alay etmek.','Diğerlerini dinlemeden karar vermek.'],0,'Herkesin hakkını gözeten davranışı seç.',['Eşit söz hakkı, insanların düşüncelerini ifade etmesini sağlar.'],'Yakınları kayırmak adil değildir.','Adalet, hakkı ve sorumluluğu birlikte gözetir.');

// 6. Sınıf.
add(6,'mathematics','Kesirlerle problem','fraction-of-quantity','45 öğrencinin 2/3’ü okul bahçesindeki çalışmaya katılıyor.','Çalışmaya kaç öğrenci katılır?',['15','30','35','40'],1,'Önce üçte biri, ardından iki payı bul.',['45 ÷ 3 = 15; 15 × 2 = 30.'],'Katılmayan 15 öğrenciyle toplam 45 olur.','Bir miktarın kesri için miktarı paydaya bölüp payla çarp.');
add(6,'mathematics','Bölünebilme','missing-digit-divisibility','Üç basamaklı 24□ doğal sayısı 9’a tam bölünüyor. □ bir rakamı göstermektedir.','□ yerine hangi rakam gelmelidir?',['1','2','3','6'],2,'9’a bölünebilmek için rakamların toplamını kullan.',['2 + 4 = 6. Rakamlar toplamının 9’un katı olması için 3 eklenir. 243’ün rakamları toplamı 9’dur.'],'243 ÷ 9 = 27; kalan yoktur.','Rakam 0–9 arasındadır; bu nedenle toplam burada 9 olmalıdır.');
add(6,'mathematics','Üçgende açılar','triangle-missing-angle','Bir üçgenin iki iç açısı 48° ve 67°’dir.','Üçüncü iç açı kaç derecedir?',['55°','75°','115°','65°'],3,'Üç iç açının toplamını 180° al.',['48 + 67 = 115. 180 − 115 = 65°.'],'48 + 67 + 65 = 180°.','Üçgende bilinmeyen iç açıyı toplamdan tamamla.');
add(6,'mathematics','Üçgenin alanı','triangle-base-height','Bir üçgenin tabanı 6 cm, bu tabana ait yüksekliği 5 cm’dir.','Üçgenin alanı kaç santimetrekaredir?',['15 cm²','30 cm²','11 cm²','22 cm²'],0,'Taban ile ona dik yüksekliğin çarpımını ikiye böl.',['6 × 5 = 30. 30 ÷ 2 = 15 cm².'],'Aynı taban ve yükseklikteki paralelkenarın alanının yarısıdır.','Yükseklik, tabana dik uzaklıktır; eğik kenarı yükseklik sanma.',svg('<path d="M95 100L190 20L275 100Z M190 20V100"/><path d="M190 90H200V100"/>'+text(160,119,'6 cm')+text(196,64,'5 cm'),'Üçgenin yatay tabanı6cm, tepe noktasından tabana dik çizilen yüksekliği5cm olarak verilmiştir.'));
add(6,'mathematics','Aritmetik ortalama','mean-of-four','Bir öğrencinin dört günde okuduğu sayfa sayıları 4, 6, 8 ve 10’dur.','Günlük ortalama kaç sayfa okumuştur?',['6','7','8','28'],1,'Toplam sayfayı gün sayısına böl.',['4 + 6 + 8 + 10 = 28. 28 ÷ 4 = 7.'],'Dört gün her gün 7 sayfa olsa yine 28 sayfa olur.','Ortalama için toplamı veri sayısına böl.');
add(6,'turkish','Ana düşünce','compare-observations','Bir araştırmacı yalnız güneşli günde gözlem yapınca bütün kelebeklerin sabah uçtuğunu düşündü. Yağmurlu ve bulutlu günleri de inceleyince ilk düşüncesini değiştirdi.','Metnin temel mesajı hangisidir?',['Tek gözlem her zaman yeterlidir.','Hava hiçbir canlıyı etkilemez.','Bir sonuca varmadan önce gözlemleri karşılaştırmak gerekir.','Araştırmalarda düşünce değiştirilemez.'],2,'İlk yargıyı değiştiren yeni bilgileri dikkate al.',['Farklı günlerin gözlemleri tek günün yetersizliğini gösteriyor.'],'Metin bütün kelebek türleri için kesin bir zaman kuralı vermiyor.','Kesin yargı kurmadan önce kanıtın kapsamını düşün.');
add(6,'turkish','Mecaz anlam','figurative-sweet','Tatlı sözcüğü bazı cümlelerde tat alma dışında bir anlam taşır.','Hangi cümlede tatlı sözcüğü mecaz anlamdadır?',['Tatlı elmayı dilimledim.','Tatlı şerbet bardağa kondu.','Tatlı üzümden birkaç tane aldım.','Tatlı sözleriyle hepimizi rahatlattı.'],3,'Sözcüğün gerçek tat bildirmediği kullanımı bul.',['Sözün tatlılığı, hoş ve gönül alıcı olmasıdır; ağızda hissedilen tat değildir.'],'Diğer seçeneklerde yiyecek/içeceğin tadı anlatılır.','Mecaz, sözcüğün temel anlamından uzaklaşmasıdır.');
add(6,'turkish','Koşul-sonuç','conditional-learning','Bir sonucun gerçekleşmesi başka bir davranışa bağlı olarak anlatılabilir.','Hangi cümlede koşul anlamı vardır?',['Düzenli tekrar yaparsa konuyu daha iyi hatırlar.','Konuyu dün akşam tekrar etti.','Defterini çantasına koydu.','Ders biraz önce sona erdi.'],0,'Sonucun hangi şartta gerçekleştiğine bak.',['Daha iyi hatırlama, düzenli tekrar yapma koşuluna bağlanmıştır.'],'Diğer cümleler gerçekleşmiş olayları bildirir.','-sa/-se eki çoğu zaman koşula işaret eder; bağlamı da kontrol et.');
add(6,'turkish','Çıkarım sınırı','unsupported-universal','Sınıf anketinde 12 öğrenci macera, 8 öğrenci bilim kitaplarını seçti. Öğretmen kitaplığa her iki türden kitap ekledi.','Bu bilgilere dayanarak hangisi söylenemez?',['Ankette iki kitap türü seçilmiştir.','Bütün öğrenciler aynı tür kitapları sever.','Kitaplığa iki türden de kitap eklenmiştir.','Macera seçenlerin sayısı daha fazladır.'],1,'Her seçeneği metindeki veriyle karşılaştır.',['İki ayrı tür seçildiği için bütün öğrencilerin aynı türü sevdiği sonucuna ulaşılamaz.'],'12, 8’den büyüktür; diğer üç seçenek metinle desteklenir.','Bütün ve her gibi sözcükler güçlü kanıt gerektirir.');
science(6,'YF6-03');science(6,'YF6-06');science(6,'YF6-10');science(6,'YF6-14');
add(6,'social','Vatandaşlık','tax-public-service','Bir belediye, toplanan vergilerin bir bölümünü yol ve parkların bakımına ayırıyor.','Bu durum en doğrudan neyi gösterir?',['Vergilerin yalnız kişisel alışveriş için kullanıldığını.','Bütün hizmetlerin kendiliğinden oluştuğunu.','Vergilerle ortak hizmetlerin giderlerinin karşılanması.','Kamu hizmetlerinin yalnız tek kişiye sunulduğunu.'],2,'Gelir ile toplumun yararlandığı hizmet arasındaki bağı kur.',['Yol ve park ortak kullanım içindir; vergiler bu hizmetlerin giderlerine kaynak sağlar.'],'Bu örnek bütün vergi kullanımının eksiksiz denetlendiğini ayrıca kanıtlamaz.','Bir örnekten yalnız desteklediği sonucu çıkar.');
add(6,'social','Demokratik katılım','fair-election','Sınıf temsilcisi seçilecek. Öğrencilerin özgürce ve baskı görmeden karar vermesi isteniyor.','Hangi uygulama daha uygundur?',['Oyları herkesin önünde zorla açıklatmak.','Sadece bir adayın konuşmasına izin vermek.','Oy vermeyenleri küçümsemek.','Adayları dinleyip gizli oy kullanmak.'],3,'Bilgilenme ve özgür tercih imkânını birlikte gözet.',['Adaylar dinlenir; gizli oy, tercihin baskı altında açıklanmasını önler.'],'Zorlama ve tek adayı dinletme eşit katılımı engeller.','Demokratik seçim, yalnız oy saymak değildir.');
add(6,'social','Bilgi ve görüş','verifiable-statement','Bir öğrenci kütüphane hakkında farklı cümleler yazıyor.','Hangisi nesnel olarak doğrulanabilecek bir bilgidir?',['Kütüphane hafta içi saat 17.00’de kapanıyor.','Burası dünyanın en güzel kütüphanesidir.','Bu masalar herkese mutluluk verir.','Burada bütün kitaplar çok heyecanlıdır.'],0,'Kayıttan veya gözlemden kontrol edilebilen ifadeyi bul.',['Kapanış saati resmî çalışma saatleriyle doğrulanabilir.'],'En güzel ve çok heyecanlı kişisel değerlendirmelerdir.','Nesnel bilgi, kişisel beğeniden bağımsız denetlenebilir.');
add(6,'english','Daily routines','frequency-every-day','“I brush my teeth every morning. I never skip it.”','Which word best describes this habit?',['Never','Always','Rarely','Sometimes'],1,'Every morning ve never skip ifadelerini birlikte oku.',['Hiç atlamadan her sabah yapmak always anlamındadır.'],'Never hiç yapmamak, rarely nadiren, sometimes bazen demektir.','Sıklık sözcüğünü zaman ifadesiyle eşleştir.');
add(6,'english','Comparisons','transport-comparison','A train travels at 120 km/h. A bus travels at 80 km/h.','Which sentence is correct?',['The bus is faster than the train.','The train and the bus have the same speed.','The train is faster than the bus.','The train is slower than the bus.'],2,'Hızları karşılaştırıp faster sözcüğünü kullan.',['120 is greater than 80; the train is faster.'],'Aynı hızda değiller; slower daha yavaş demektir.','Than, karşılaştırılan ikinci varlığı bağlar.');
add(6,'religion','Ramazan ve oruç','iftar-concept','Ramazan ayında oruç tutan bir kişi, güneş battığında orucunu açar.','Orucun bu şekilde açılmasına ne ad verilir?',['Sahur','Sadaka','Teravih','İftar'],3,'Orucu açma zamanına ait kavramı bul.',['Güneş battıktan sonra orucun açılması iftardır.'],'Sahur, oruca başlamadan önceki hazırlık öğünüdür.','İftar ile sahuru zaman ve işlev bakımından ayır.');
add(6,'religion','Sorumluluk','keeping-trust','Efe, arkadaşının kitabını cuma günü geri vermek üzere ödünç aldı.','Emanet bilincine uygun davranış hangisidir?',['Emaneti özenle koruyup zamanında geri vermek.','Kitabı izinsiz başkasına vermek.','Kitabın kendisine ait olduğunu söylemek.','Geri verme sözünü önemsememek.'],0,'Başkasının hakkını ve verilen sözü birlikte gözet.',['Kitap korunur ve kararlaştırılan zamanda sahibine iade edilir.'],'Ödünç almak mülkiyeti kendine geçirmek değildir.','Emanet, korunması gereken bir sorumluluktur.');

// 7. Sınıf.
add(7,'mathematics','Rasyonel sayılar','signed-fraction-sum','Bir işlemde −3/4 ile 1/2 toplanıyor.','Sonuç kaçtır?',['−5/4','−1/4','1/4','5/4'],1,'Paydaları eşitle ve işaretleri koru.',['1/2 = 2/4. −3/4 + 2/4 = −1/4.'],'Negatif büyüklük daha fazla olduğu için sonuç negatiftir.','Paydalar eşitlenince paylarda tam sayı toplaması yap.');
add(7,'mathematics','Denklemler','linear-equation','Bir sayının üç katının 4 fazlası 25’tir.','Bu sayı kaçtır?',['6','8','7','9'],2,'Yapılan işlemleri ters sırayla geri al.',['3x + 4 = 25. 3x = 21. x = 7.'],'3 × 7 + 4 = 25.','Önce eklenen miktarı çıkar, sonra katsayıya böl.');
add(7,'mathematics','Yüzde problemleri','discounted-price','Etiket fiyatı 200 TL olan bir ürüne yüzde 20 indirim uygulanıyor.','İndirimli fiyat kaç liradır?',['40 TL','180 TL','220 TL','160 TL'],3,'Önce indirim tutarını bul, sonra fiyattan çıkar.',['200 × 20/100 = 40 TL indirim. 200 − 40 = 160 TL.'],'160 TL, eski fiyatın yüzde 80’idir.','İndirim miktarı ile ödenecek fiyatı karıştırma.');
add(7,'mathematics','Doğru orantı','unit-price','5 kg elma 120 TL’dir. Kilogram fiyatı değişmiyor.','8 kg elma kaç liradır?',['192 TL','180 TL','150 TL','200 TL'],0,'Bir kilogramın fiyatından istenen miktara geç.',['120 ÷ 5 = 24 TL/kg. 24 × 8 = 192 TL.'],'192 ÷ 8 = 24, birim fiyat aynıdır.','Doğru orantıda birim miktar sabit kalır.');
add(7,'mathematics','Doğrularda açılar','corresponding-angles','Paralel iki doğruyu kesen bir doğru oluşmuştur. Şekilde 65° olan açının yöndeşi x ile gösteriliyor.','x kaç derecedir?',['115°','65°','25°','180°'],1,'Paralel doğrularda yöndeş açıları eşleştir.',['Yöndeş açılar eşittir; x = 65°.'],'Bütünler olan komşu açı 115° olur; x o komşu değildir.','Önce açıların konumunu belirle, sonra eşitlik kuralını kullan.',svg('<path d="M40 40H310 M40 95H310 M145 120L198.625 5"/>'+text(210,34,'65°')+text(180,89,'x')+text(275,28,'d₁')+text(275,83,'d₂')+text(45,120,'d₁ ∥ d₂'),'İki paralel yatay doğruyu sağa eğik bir kesen kesiyor. Her iki açının etiketi, kendi kesişiminin sağ üst bölgesinde.'));
add(7,'turkish','Neden-sonuç','explicit-cause','“Bisikletin zinciri paslanmıştı; çünkü düzenli bakım yapılmamıştı.”','Paslanmanın nedenini bildiren bölüm hangisidir?',['Bisikletin zinciri.','Zinciri paslanmıştı.','Çünkü düzenli bakım yapılmamıştı.','Bisikletin zinciri paslanmıştı.'],2,'Çünkü sözcüğünden sonra açıklanan nedeni bul.',['Bakım yapılmaması, paslanmanın nedeni olarak belirtilmiştir.'],'Paslanmıştı bölümü sonucu bildirir.','Neden ve sonucu ok yönüyle düşünebilirsin: Bakım yok → Paslanma.');
add(7,'turkish','Öznel ve nesnel yargı','subjective-evaluation','Bir gezi yazısındaki cümleler değerlendiriliyor.','Hangisi kişisel beğeni içeren öznel bir yargıdır?',['Sokakta on iki ev var.','Müze saat dokuzda açılıyor.','Köprü iki kıyıyı birleştiriyor.','Bu, kasabanın en güzel sokağıdır.'],3,'Doğrulanabilir bilgiyle beğeniyi ayır.',['En güzel ifadesi kişisel estetik değerlendirmedir.'],'Ev sayısı, açılış saati ve köprünün konumu kontrol edilebilir.','Öznel yargıya herkesin aynı biçimde katılması gerekmez.');
add(7,'turkish','Deyimler','anticipating-events','“Yağmur başlamadan çadırı sağlamlaştırdı; gerçekten ileriyi gören biriydi.”','İleriyi görmek sözü bu cümlede neyi anlatır?',['Olayları önceden fark edip hazırlıklı olmayı.','Çok uzaktaki küçük nesneleri seçmeyi.','Yalnız geçmişteki olayları düşünmeyi.','Gözlük kullanmayı.'],0,'Sözü cümledeki davranışla ilişkilendir.',['Yağmurdan önce önlem almak, ileride olabilecek duruma hazırlanmaktır.'],'Fiziksel görme keskinliği anlatılmıyor.','Deyimin anlamını bağlam belirler.');
add(7,'turkish','Düşünceyi destekleme','data-supported-argument','Bir yazıda “Okulda su tüketimi azaldı.” deniyor. Ardından aylık tüketimi 120 tondan 90 tona düşmüş gösteren grafik veriliyor.','Grafiğin metne katkısı nedir?',['Yazının konusunu tamamen değiştirmek.','Grafik, görüşü sayısal bir veriye dayandırır.','Tüketimin neden azaldığını tek başına kesin açıklamak.','Bütün okulların aynı miktarda su kullandığını kanıtlamak.'],1,'Grafiğin doğrudan gösterdiği bilgiyi ayır.',['120’den 90’a düşüş, azalma yargısına sayısal destek verir.'],'Nedeni ve diğer okulların tüketimi grafikte yoktur.','Veri bir yargıyı destekleyebilir; bütün nedenleri tek başına açıklamaz.');
science(7,'YF7-02');science(7,'YF7-10');science(7,'YF7-13');science(7,'YF7-18');
add(7,'social','Medya okuryazarlığı','verify-news','Sosyal medyada kaynağı belirtilmeden önemli bir haber paylaşılıyor.','Paylaşmadan önce yapılması gereken hangisidir?',['Başlığı görür görmez yaymak.','Paylaşım sayısını tek doğruluk ölçüsü saymak.','Haberi farklı güvenilir kaynaklardan doğrulamak.','Tanımadığı kişilerden gelen her habere inanmak.'],2,'Kaynak, tarih ve diğer kanıtları kontrol et.',['Haberin aslına ve güvenilir bağımsız kaynaklara bakılır.'],'Çok paylaşılmış olması doğruluğunu kanıtlamaz.','Hızlı paylaşmak yerine doğru bilgiyi paylaş.');
add(7,'social','Kültürel etkileşim','trade-cultural-exchange','Tarihî ticaret yollarını kullanan tüccarlar malların yanında diller, yemekler ve sanat ürünleriyle de karşılaşıyordu.','Bu durum hangi sonuca katkı sağlamıştır?',['Bütün toplumların birbirinden tamamen kopmasına.','Ticaretin yalnız tek bir mal üzerinden yapılmasına.','İnsanların hiçbir yeni bilgi öğrenmemesine.','Farklı toplumlar arasında kültürel etkileşim gerçekleşmesi.'],3,'Maddi alışverişin dışındaki paylaşımı düşün.',['Dil, yemek ve sanatla karşılaşmak kültürler arası etkileşimi artırır.'],'Bütün toplumların aynı kültüre dönüşmesi sonucu çıkarılmaz.','Ticaret yalnız mal değil, fikir ve deneyim karşılaşması da oluşturabilir.');
add(7,'social','Nüfus ve yerleşme','employment-migration','Bir ilçede yeni iş alanları açıldıktan sonra çevre yerlerden gelenlerin sayısı arttı.','Bu örnek hangi ilişkiyi gösterir?',['İş olanaklarının nüfusu kendine çekmesi.','İş olanaklarının göçle hiçbir ilişkisi olmaması.','Her göçün yalnız iklimden kaynaklanması.','Yeni işlerin her yerde nüfusu azaltması.'],0,'Verilen ekonomik değişimi nüfus hareketiyle ilişkilendir.',['İş alanlarının artması ilçeye gelişleri artırmış; ekonomik çekicilik vardır.'],'Bu, bütün göçlerin tek nedeninin iş olduğu anlamına gelmez.','Bir örnekte görülen ilişkiyi evrensel tek neden sayma.');
add(7,'english','Biographies','past-event-date','“Elif was born in İzmir in 2002. She moved to Ankara in 2015. She finished school in 2020.”','Which event happened in 2015?',['She was born in Ankara.','She moved to Ankara in 2015.','She finished school in 2015.','She moved to İzmir in 2020.'],1,'İstenen tarihi doğru olayla eşleştir.',['2015 tarihi moved to Ankara olayıyla birliktedir.'],'Doğum 2002, okulu bitirme 2020 yılındadır.','Biyografide zaman çizelgesi kurmak karışıklığı önler.');
add(7,'english','Invitations','polite-refusal','A friend asks: “Would you like to join our picnic on Saturday?” You have a dentist appointment at that time.','Which is a polite refusal with a reason?',['Great! I will come.','Yes, I would love to.','Sorry, I cannot. I have a dentist appointment.','Sure, see you there.'],2,'Kabul değil, gerekçeli ve nazik bir ret ara.',['Sorry, I cannot reddi; dentist appointment gerekçeyi belirtir.'],'Diğer üç seçenek daveti kabul eder.','Nazik ret, karşıdakini kırmadan durumunu açıklar.');
add(7,'religion','Hac ve umre','tawaf-concept','Hac ve umre ibadetlerinde Kâbe’nin etrafında usulüne uygun olarak dönülür.','Bu ibadetin adı nedir?',['Sa‘y','Vakfe','Sahur','Tavaf'],3,'Tanımı ilgili ibadet adıyla eşleştir.',['Kâbe’nin etrafında dönmeye tavaf denir.'],'Sa‘y Safa ile Merve arasındaki ibadettir; vakfe bekleyiş, sahur oruç öncesi öğündür.','İbadetleri yer ve yapılan eylemle birlikte öğren.');
add(7,'religion','Adalet ve ahlak','consistent-fair-rule','Bir yarışmada kurallar önceden açıklanmıştır. Jüri üyelerinden birinin yakını da yarışmaya katılır.','Adalet ilkesine uygun davranış hangisidir?',['Aynı durumda olanlara aynı kuralları uygulamak.','Yakınına gizlice ek puan vermek.','Kuralları yalnız sevmediği kişilere uygulamak.','Sonuç belli olduktan sonra yakınını kazandıracak kural koymak.'],0,'Yakınlığa değil hakka ve kurala göre değerlendirme yap.',['Açıklanan kurallar aynı durumdaki herkese eşit uygulanır.'],'Kayırma ve sonradan çıkarına göre kural değiştirme adalete aykırıdır.','Adalet, kişisel yakınlığın değerlendirmeyi bozmamasını gerektirir.');

export const PILOT_QUESTIONS=rows;
