import {packQuestions} from './pagination.mjs';
import {mountAnnotationWidget} from './annotation_widget.mjs';
import {createRequestScope} from './request_scope.mjs';
const $=id=>document.getElementById(id),app=$('app');
const subjects={turkish:'Türkçe',mathematics:'Matematik',science:'Fen Bilimleri',social:'Sosyal Bilgiler',history:'İnkılap Tarihi',english:'İngilizce',religion:'Din Kültürü',life_studies:'Hayat Bilgisi'};
const roles={platform_admin:'Süper yönetici',school_admin:'Okul yöneticisi',teacher:'Öğretmen',student:'Öğrenci',parent:'Veli'};
let user=null,attempt=null,page=0,noteWidget=null,poll=null,busy=false,importReceipt=null,authBusy=false;
const requestScope=createRequestScope();
const esc=value=>String(value??'').replace(/[&<>"']/gu,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const field=(label,name,value='',type='text')=>`<label>${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}" required></label>`;
function notify(message){$('notice').textContent=message;setTimeout(()=>{if($('notice').textContent===message)$('notice').textContent='';},6500);}
const errors={invalid_credentials:'Kullanıcı adı veya parola doğru değil.',forbidden:'Bu kayıt için erişim yetkin yok.',quota_exceeded:'Okulun öğrenci kotası aşılacak. Hiçbir satır eklenmedi.',duplicate_username:'Aynı kullanıcı adı var. Hiçbir satır eklenmedi.',synthetic_alias_required:'Yalnız demo. kullanıcı adlarını ve Demo ile başlayan temsili adları kullan.',weak_password:'Yeni parola en az 12 karakter olmalı.',password_change_required:'Önce geçici parolanı yenilemelisin.',invalid_classroom:'Sınıf ve şube eşleşmiyor. Örnek: 6 ve 6A.',invalid_teacher:'Öğretmen bu okula ait değil.',login_throttled:'Bir dakika sonra tekrar dene.'};
async function api(path,body){const ticket=requestScope.capture(user?.id??null);const r=await requestScope.resolve(ticket,fetch('/api/'+path,{...(body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),credentials:'same-origin'}));const data=await requestScope.resolve(ticket,r.json());if(!r.ok){if(r.status===401&&path!=='login'){user=null;loginView();}const e=new Error(data.error);e.userMessage=errors[data.error]??'İşlem tamamlanamadı. Değişiklik kaydedilmedi.';throw e;}if(path==='import')importReceipt={owner:ticket.actorId,created:data.created};return data;}
function clearPrivateView(){requestScope.invalidate();clearInterval(poll);noteWidget?.destroy();noteWidget=null;$('note-dialog').close();$('note-content').replaceChildren();$('note-title').textContent='Soru notum';$('notice').textContent='';attempt=null;importReceipt=null;page=0;busy=false;}
function setAuthBusy(value){authBusy=value;for(const control of app.querySelectorAll('#login-form input,#login-form button,[data-demo]'))control.disabled=value;}
const act=fn=>async e=>{try{await fn(e);}catch(error){if(!error.silent)notify(error.userMessage??error.message);}};
function identity(){const id=$('identity');id.replaceChildren();if(!user){clearPrivateView();return;}const s=document.createElement('span');s.textContent=`${user.displayName} · ${roles[user.role]}`;const b=document.createElement('button');b.textContent='Çıkış';b.onclick=act(async()=>{if(authBusy)return;if(noteWidget?.isDirty()&&!confirm('Kaydedilmemiş notun var. Çıkmak istiyor musun?'))return;setAuthBusy(true);user=null;loginView();try{await api('logout',{});}finally{setAuthBusy(false);}});id.append(s,b);}
function loginView(){clearInterval(poll);identity();app.innerHTML=`<div class="login-wrap"><section class="login-intro"><p class="eyebrow">KİTAPÇIĞIN. NOTLARIN. GELİŞİMİN.</p><h1>Öğrenme yolculuğun<br>buradan devam ediyor.</h1><p class="muted">Beyaz bir sayfa, anlaşılır sorular ve sana ait bir not alanı. Her hesap yalnız kendi çalışma alanına açılır.</p><p class="alert">Yerel inceleme demosu. Hesaplar ve adlar temsilidir; gerçek öğrenci kaydı ve dışarıdan okul girişi henüz açılmadı.</p></section><section class="login-card"><h2>Çalışma alanına giriş</h2><form id="login-form">${field('Kullanıcı adı','username','demo.ogrenci.6.01')}${field('Parola','password','Demo2026!','password')}<button class="primary">Giriş yap</button></form><div class="demo-links"><p class="muted">Demo incelemek için bir rol seç. Ortak demo parolası: <b>Demo2026!</b></p>${[['Öğrenci','demo.ogrenci.6.01'],['Veli','demo.veli.6.01'],['Öğretmen','demo.ogretmen.6a'],['Müdür','demo.mudur.a'],['Süper yönetici','demo.superadmin']].map(([name,id])=>`<button type="button" data-demo="${id}">${name}</button>`).join('')}<p class="muted">Sınıflar 1–8, numaralar 01–10.<br>Örnek: <b>demo.ogrenci.8.01</b> ve velisi <b>demo.veli.8.01</b>. Öğrenci ekranında sınıf değiştirme yoktur.</p></div></section></div>`;
 for(const b of app.querySelectorAll('[data-demo]'))b.onclick=()=>{app.querySelector('[name=username]').value=b.dataset.demo;};
 setAuthBusy(authBusy);
 $('login-form').onsubmit=act(async e=>{e.preventDefault();if(authBusy)return;const credentials=Object.fromEntries(new FormData(e.currentTarget));setAuthBusy(true);user=null;clearPrivateView();try{user=(await api('login',credentials)).user;user.mustChangePassword?passwordView():await dashboard();}finally{setAuthBusy(false);}});}
function passwordView(){identity();app.innerHTML=`<section class="login-card"><h1>Hesabını güvenceye al</h1><p>İlk girişte geçici parolanı değiştir. En az 12 karakter kullan.</p><form id="password-form">${field('Geçici parola','current','','password')}${field('Yeni parola','next','','password')}<button class="primary">Parolayı değiştir</button></form></section>`;$('password-form').onsubmit=act(async e=>{e.preventDefault();await api('password',Object.fromEntries(new FormData(e.currentTarget)));user=null;loginView();notify('Parola değişti. Yeni parolanla giriş yap.');});}
const table=(headers,rows)=>`<div class="table-wrap"><table><thead><tr>${headers.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const metric=(value,label)=>`<div class="metric"><strong>${esc(value)}</strong><span>${esc(label)}</span></div>`;
function analyticTable(rows,label){return rows.length?table([label,'Doğru','Yanlış','Boş','Karşılaşma','Doğru oranı'],rows.map(r=>[esc(subjects[r.key]??r.key),r.correct,r.wrong,r.blank,r.total,`${Math.round(r.correctRate*100)}%`])):'<p class="empty">Henüz tamamlanmış çalışma yok. Öğrenci bitirdiğinde veriler burada oluşur.</p>';}
async function dashboard(){clearInterval(poll);attempt=null;page=0;const d=await api('dashboard');user=d.user;identity();const child=user.role==='student',parent=user.role==='parent',manage=['platform_admin','school_admin'].includes(user.role),t=d.analytics.totals;
 app.innerHTML=`<div class="view-heading"><div><p class="eyebrow">${esc(roles[user.role].toLocaleUpperCase('tr'))}</p><h1>${child?`${user.grade}. sınıf çalışma alanım`:parent?'Çocuğumun öğrenme süreci':user.role==='teacher'?'Sınıfımın çalışma özeti':user.role==='school_admin'?'Okulumun yönetim alanı':'Okullar ve erişim yönetimi'}</h1><p class="muted">${child?'Soruları çöz, not al; bitirdikten sonra çözüm yolunu karşılaştır.':parent?'Yalnız hesabına bağlı çocuğun kayıtlarını görüyorsun.':'Tamamlanan çalışmalardan hesaplanır; 15 saniyede bir yenilenir.'}</p></div><button id="refresh">Yenile</button></div><div class="metric-grid">${metric(d.analytics.completedAttempts,'Tamamlanan çalışma')}${metric(t.correct,'Doğru')}${metric(t.wrong,'Yanlış')}${metric(t.blank,'Boş')}</div>
 ${child?`<div class="exam-grid">${d.exams.map(ex=>`<section class="exam-card"><p class="eyebrow">${ex.grade<=4?'YETİŞKİN EŞLİĞİNDE İÇERİK ÖNİZLEMESİ':ex.grade===8?'LGS DAĞILIMLI ÇALIŞMA':'ÇOK DERSLİ ÇALIŞMA'}</p><h2>${ex.grade}. sınıf · ${ex.questionCount} soru</h2><p>${ex.subjects.map(s=>esc(subjects[s]??s)).join(' · ')}</p><p class="muted">${ex.grade<=4?'Bu çoktan seçmeli taslak okul sınavı değildir. Yetişkin birlikte okuyabilir; süre ve sıralama yok.':ex.grade===8?'Bu sürümde oturum süresi zorlanmaz; resmî LGS puanı hesaplanmaz.':'Süre baskısı ve sıralama yok. Yanlışlar doğruları götürmez.'}</p><button data-start="${esc(ex.id)}" class="primary">Çalışmayı aç</button></section>`).join('')}</div>`:''}
 <div class="portal-grid"><section class="panel"><h2>Derslere göre sonuçlar</h2>${analyticTable(d.analytics.bySubject,'Ders')}<p class="muted">${child?'Bitirdiğin çalışmalardaki doğru, yanlış ve boş cevaplarını burada görebilirsin.':'Oran, bitirilen çalışmalardaki soru karşılaşmalarından hesaplanır; boşlar dahildir. Az veriyle kalıcı öğrenci etiketi üretilmez.'}</p>${d.analytics.lgs?.completedAttempts?`<p>Ortalama ham net: <b>${d.analytics.lgs.averageNet.toFixed(2)}</b> (doğru − yanlış/3). Resmî LGS puanı değildir.</p>`:''}</section><section class="panel"><h2>${parent?'Birlikte değerlendirelim':child?'Son çalışmam':'Tamamlanan çalışmalar'}</h2>${d.analytics.recentAttempts.length?table(['Öğrenci','D/Y/B','İncele'],d.analytics.recentAttempts.map(a=>[esc(d.students.find(s=>s.id===a.studentId)?.displayName??'Öğrenci'),`${a.result.correct}/${a.result.wrong}/${a.result.blank}`,`<button data-attempt="${esc(a.id)}">Aç</button>`])):'<p class="empty">Henüz bitirilmiş çalışma yok.</p>'}${parent?'<p class="muted">İlk dört sınıfta çocuğunuzla soruları konuşun; biten çalışmayı açıp geri bildirim bırakabilirsiniz.</p>':''}</section></div>
 ${!child?`<section class="panel"><h2>Konu ve soru biçimi</h2><details><summary>Konu sonuçları</summary>${analyticTable(d.analytics.byTopic,'Konu')}</details><details><summary>Soru biçimi sonuçları</summary>${analyticTable(d.analytics.byFamily,'Soru biçimi')}</details></section><section class="panel"><h2>Soruların incelenmesi</h2>${d.analytics.questions.length?table(['Soru','Ders','Doğru','Yanlış','Boş','Karşılaşma'],[...d.analytics.questions].sort((a,b)=>b.wrong-a.wrong).map(q=>[esc(q.questionId),esc(subjects[q.subject]??q.subject),q.correct,q.wrong,q.blank,q.exposures])):'<p class="empty">Henüz soru bazında sonuç oluşmadı.</p>'}<h3>Öğrenci görüşleri</h3>${d.analytics.questionFeedback.length?table(['Soru','Görüş','Ortalama1–5','Olumlu4–5','Eleştirel1–2'],d.analytics.questionFeedback.map(q=>[esc(q.questionId),q.responses,q.averageRating.toFixed(1),q.positive,q.negative])):'<p class="muted">Henüz soru görüşü yok. Az sayıda oyla “en iyi soru” sonucu çıkarmıyoruz.</p>'}<div class="feedback-items">${d.analytics.feedback.map(f=>`<p><b>${esc(d.students.find(s=>s.id===f.studentId)?.displayName)} · ${f.rating}/5</b><br>${esc(f.text)}</p>`).join('')}</div></section>`:''}
 ${manage?management(d):''}${!child?`<section class="panel"><h2>${parent?'Hesabıma bağlı çocuk':'Erişimimdeki öğrenciler'} (${d.students.length})</h2>${table(['Ad','Sınıf','Hesap',...(manage?['Düzenle']:[])],d.students.map(s=>[esc(s.displayName),esc(s.classroom),esc(s.username),...(manage?[`<button data-student="${esc(s.id)}">Düzenle</button>`]:[])]))}</section>`:''}${child?`<p class="muted">Geliştirmeye katkıların: ${d.contributionPoints}. Başarı veya lig puanı değildir; eleştirel görüşler de aynı değerdedir.</p>`:''}`;
 if(manage&&importReceipt?.owner===user.id){const receipt=document.createElement('section');receipt.className='panel';receipt.innerHTML='<h2>Yeni hesapların ilk giriş bilgileri</h2><p class="alert">Geçici parolalar yalnız bu aktarımın yanıtında gösterilir. Yetkili kişiye güvenli biçimde teslim etmeden kapatma. Sayfayı tamamen yeniden yüklediğinde veya çıkışta bu görünüm silinir; parolalar genel listelerde bulunmaz.</p>'+table(['Hesap','Geçici parola'],importReceipt.created.map(row=>[esc(row.username),`<span class="token-value">${esc(row.temporaryPassword)}</span>`]))+'<button id="dismiss-receipt">Bilgileri aldım, görünümü kapat</button>';app.prepend(receipt);$('dismiss-receipt').onclick=()=>{importReceipt=null;receipt.remove();};}
 $('refresh').onclick=act(dashboard);for(const b of app.querySelectorAll('[data-start]'))b.onclick=act(async()=>{attempt=await api('start',{examId:b.dataset.start});page=0;examView();});for(const b of app.querySelectorAll('[data-attempt]'))b.onclick=act(async()=>{attempt=await api('attempt',{attemptId:b.dataset.attempt});page=0;examView();});if(manage)bindManagement(d);
 if(!child)poll=setInterval(()=>{if(!attempt&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)&&!document.querySelector('dialog[open]'))dashboard().catch(()=>{});},15000);
}
function management(d){return `<section class="panel"><h2>${user.role==='platform_admin'?'Okul kotaları':'Okul kotam'}</h2>${table(['Okul','Öğrenci','Kota',''],d.schools.map(s=>[esc(s.name),s.enrollment,s.quota,user.role==='platform_admin'?`<button data-quota="${esc(s.id)}">Kotayı düzenle</button>`:'']))}<p class="muted">Öğrenci kotası uygulanır. CPU/depolama kotası ve faturalama henüz etkin değil.</p></section>${user.role==='platform_admin'?`<section class="panel"><h2>Demo okul ve müdür hesabı aç</h2><form id="school-form" class="inline-form">${field('Okul adı','name','Demo Yeni Okul')}${field('Öğrenci kotası','quota','300','number')}${field('Müdür hesabı','adminUsername','demo.mudur.yeni')}${field('Müdür adı','adminDisplayName','Demo Yeni Müdür')}${field('Geçici parola (12+ karakter)','temporaryPassword','','password')}<button class="primary">Demo okul aç</button></form><p class="muted">Müdür ilk girişte parolasını değiştirir. Hesap başka okulu göremez.</p></section>`:''}<section class="panel"><h2>Excel’den öğrenci listesi aktar</h2><p class="muted">Excel’den bu dört sütunu kopyalayıp yapıştır: <b>Kullanıcı adı, Görünen ad, Sınıf, Şube</b>. Başlık ekleme. Bu sürüm .xlsx yüklemez; sekmeyle ayrılmış hücreleri okur. Yalnız temsili kayıt kullan.</p><label>Hedef okul<select id="import-school">${d.schools.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('')}</select></label><label>Öğrenci satırları<textarea id="roster" class="roster-text" rows="4" placeholder="demo.yeni.001&#9;Demo Yeni Öğrenci&#9;6&#9;6B"></textarea></label><button id="preview-import">Aktarımı önizle</button><div id="import-preview"></div><p class="muted">En fazla 300 satır. Hata veya kota aşımında hiçbir satır eklenmez. TC kimlik, adres ve doğum tarihi istenmez.</p></section>`;}
function bindManagement(d){
 for(const b of app.querySelectorAll('[data-quota]'))b.onclick=act(async()=>{const s=d.schools.find(s=>s.id===b.dataset.quota),value=prompt('Yeni öğrenci kotası',s.quota);if(value===null)return;await api('quota',{schoolId:s.id,quota:Number(value)});await dashboard();notify('Kota güncellendi.');});
 if($('school-form'))$('school-form').onsubmit=act(async e=>{e.preventDefault();const b=Object.fromEntries(new FormData(e.currentTarget));b.quota=Number(b.quota);b.confirmedSynthetic=true;await api('school/create',b);await dashboard();notify('Demo okul ve müdür hesabı açıldı.');});
 $('preview-import').onclick=act(async()=>{const raw=$('roster').value.trim();if(!raw)throw new Error('Önce satırları yapıştır.');const rows=raw.split(/\r?\n/u).map(line=>{const c=line.split('\t');if(c.length!==4)throw new Error('Her satır tam dört Excel hücresi içermeli.');return {username:c[0].trim(),displayName:c[1].trim(),grade:Number(c[2]),classroom:c[3].trim().toLocaleUpperCase('tr')};});if(rows.length>300)throw new Error('En fazla 300 satır.');const target=$('import-school').value;$('import-preview').innerHTML=table(['Hesap','Ad','Sınıf','Şube'],rows.map(r=>[esc(r.username),esc(r.displayName),r.grade,esc(r.classroom)]))+'<button id="commit-import" class="primary">Temsili kayıtları ekle</button>';$('commit-import').onclick=act(async e=>{e.target.disabled=true;try{await api('import',{schoolId:target,rows,confirmedSynthetic:true});await dashboard();notify('Kayıtlar eklendi. İlk girişte parola yenileme zorunlu.');}catch(err){e.target.disabled=false;throw err;}});});
 for(const b of app.querySelectorAll('[data-student]'))b.onclick=act(async()=>{const s=d.students.find(s=>s.id===b.dataset.student),classroom=prompt('Yeni sınıf ve şube (örn. 6B)',s.classroom);if(classroom===null)return;const grade=Number(classroom.match(/^([1-8])/u)?.[1]);await api('student/update',{studentId:s.id,grade,classroom:classroom.toLocaleUpperCase('tr'),displayName:s.displayName,teacherId:null});await dashboard();});
}
function renderQuestion(q,index){const finished=attempt.status==='finished',choice=attempt.responses[q.id],own=user.role==='student';return `<article class="question"><div class="subject-mark">${esc(subjects[q.subject]??q.subject)}</div><div class="question-heading"><span class="question-number">${index+1}.</span><p class="stimulus">${esc(q.stimulus)}</p></div>${q.figure?`<figure class="figure"><img src="data:image/svg+xml;charset=utf-8,${encodeURIComponent(q.figure.svg)}" alt="${esc(q.figure.alt)}"></figure>`:''}<p class="stem">${esc(q.stem)}</p><fieldset class="options"><legend class="sr-only">${index+1}. sorunun seçenekleri</legend>${q.options.map((option,i)=>`<label class="option ${finished?(q.answer===i?'correct':choice===i?'incorrect':''):''}"><input type="radio" name="answer-${esc(q.id)}" value="${i}" data-answer="${esc(q.id)}" ${choice===i?'checked':''} ${finished||!own?'disabled':''}><span class="option-letter">${'ABCD'[i]})</span><span>${esc(option)}</span></label>`).join('')}</fieldset><div class="question-actions">${own?`<button class="note-button" data-note="${esc(q.id)}">Not / Karalama</button>`:''}${!finished&&own?`<button data-clear="${esc(q.id)}">İşareti kaldır</button>`:''}</div>${finished?solution(q):''}</article>`;}
function solution(q){const e=q.explanation;if(!e)return '';return `<details class="solution"><summary>Çözüm yolu · ${'ABCD'[q.answer]}</summary>${[['Verilenler',e.given],['Ne soruluyor?',e.wanted],['Neden bu yol?',e.strategy]].map(([h,v])=>`<h3>${h}</h3><p>${esc(v)}</p>`).join('')}<ol>${(e.steps??[]).map(s=>`<li>${esc(s)}</li>`).join('')}</ol><h3>Sonucu kontrol et</h3><p>${esc(e.check)}</p><p class="tip">${esc(e.tip)}</p></details>`;}
function examView(){clearInterval(poll);identity();const finished=attempt.status==='finished',own=user.role==='student',numbered=attempt.questions.map((q,i)=>({...q,index:i})),pages=packQuestions(numbered);page=Math.min(page,pages.length-1);
 app.innerHTML=`<div class="toolbar-demo"><button id="back-dashboard">Çalışma alanım</button><span>${attempt.grade}. sınıf · ${attempt.questions.length} soru</span><span class="push">${Object.keys(attempt.responses).length}/${attempt.questions.length} yanıt</span><button id="toggle-map">Cevaplarım</button>${!finished&&own?'<button id="finish" class="primary">Çalışmayı bitir</button>':''}</div>${finished?`<section class="panel" id="results"><h1>Çalışman tamamlandı</h1><div class="result-band">${[['Doğru',attempt.result.correct],['Yanlış',attempt.result.wrong],['Boş',attempt.result.blank],...(attempt.result.net!==undefined?[['Ham net',Number(attempt.result.net).toFixed(2)]]:[])].map(([label,n])=>`<div><strong>${n}</strong><span>${label}</span></div>`).join('')}</div><p class="muted">Çözüm yollarını ve notlarını karşılaştır. Takıldığın yeri öğretmenine sorabilirsin.</p></section>`:''}<div id="answer-map" class="answer-map" hidden>${numbered.map(q=>`<button data-jump="${q.index}" class="${attempt.responses[q.id]!==undefined?'selected':''}">${q.index+1}</button>`).join('')}</div><section class="paper"><header class="paper-header"><h1>${attempt.grade<=4?'BİRLİKTE ÖĞRENELİM':'DERS ÇALIŞMASI'}</h1><span>${attempt.grade}. sınıf · Sayfa ${page+1}/${pages.length}</span></header><div class="paper-columns">${pages[page].map(col=>`<div class="paper-column">${col.map(q=>renderQuestion(q,q.index)).join('')}</div>`).join('')}</div><footer class="paper-footer"><span>${attempt.grade<=4?'Yetişkin eşliğinde içerik önizlemesi':'Soruyu dikkatle oku. Verilenlerle isteneni ayır.'}</span><span>${page+1}</span></footer></section><nav class="exam-nav"><button id="prev" ${page===0?'disabled':''}>Önceki sayfa</button><span>${page+1} / ${pages.length}</span><button id="next" ${page===pages.length-1?'disabled':''}>Sonraki sayfa</button></nav>${finished&&((own&&attempt.grade>=5)||(user.role==='parent'&&attempt.grade<=4))?feedbackView():''}`;
 $('back-dashboard').onclick=act(dashboard);$('prev').onclick=()=>{page--;examView();window.scrollTo(0,0);};$('next').onclick=()=>{page++;examView();window.scrollTo(0,0);};$('toggle-map').onclick=()=>{$('answer-map').hidden=!$('answer-map').hidden;};for(const b of app.querySelectorAll('[data-jump]'))b.onclick=()=>{page=pages.findIndex(cols=>cols.flat().some(q=>q.index===Number(b.dataset.jump)));examView();};
 const answer=async(id,choice)=>{if(busy||!attempt)return;const ticket=requestScope.capture(user?.id),attemptId=attempt.id;busy=true;for(const input of app.querySelectorAll('[data-answer],[data-clear],#finish'))input.disabled=true;try{const saved=await api('answer',{attemptId,questionId:id,choice});if(requestScope.isCurrent(ticket)&&attempt?.id===attemptId){attempt=saved;examView();}}catch(e){if(requestScope.isCurrent(ticket)&&attempt?.id===attemptId)examView();throw e;}finally{if(requestScope.isCurrent(ticket))busy=false;}};
 for(const input of app.querySelectorAll('[data-answer]'))input.onchange=act(()=>answer(input.dataset.answer,Number(input.value)));for(const b of app.querySelectorAll('[data-clear]'))b.onclick=act(()=>answer(b.dataset.clear,null));for(const b of app.querySelectorAll('[data-note]'))b.onclick=act(()=>openNote(b.dataset.note));
 if($('finish'))$('finish').onclick=act(async()=>{if(busy||!attempt)return;const blank=attempt.questions.length-Object.keys(attempt.responses).length;if(!confirm(`${blank} soru boş. Bitirdikten sonra cevaplar değiştirilemez. Bitirilsin mi?`))return;const ticket=requestScope.capture(user?.id),attemptId=attempt.id;busy=true;for(const input of app.querySelectorAll('[data-answer],[data-clear],#finish'))input.disabled=true;try{const saved=await api('finish',{attemptId});if(requestScope.isCurrent(ticket)&&attempt?.id===attemptId){attempt=saved;page=0;examView();window.scrollTo(0,0);}}catch(e){if(requestScope.isCurrent(ticket)&&attempt?.id===attemptId)examView();throw e;}finally{if(requestScope.isCurrent(ticket))busy=false;}});
 if($('feedback-form'))$('feedback-form').onsubmit=act(async e=>{e.preventDefault();const f=new FormData(e.currentTarget),qid=f.get('question');await api('feedback',{attemptId:attempt.id,rating:Number(f.get('rating')),text:f.get('text'),questionIds:qid?[qid]:[]});notify('Teşekkür ederiz. Görüşün kaydedildi; bu çalışma için bir katkı puanı. Eleştirilerin de aynı değerde.');});
}
function feedbackView(){return `<section class="panel feedback-form"><h2>${user.role==='parent'?'Çocuğunuzla birlikte değerlendirin':'Birlikte geliştirelim'}</h2><p class="muted">Hangi ifade anlaşılmadı? Görsel yardımcı oldu mu? Olumlu ya da eleştirel görüş aynı katkı puanını alır; başarı puanın değişmez.</p><form id="feedback-form"><label>Hangi soru? (İsteğe bağlı)<select name="question"><option value="">Çalışmanın geneli</option>${attempt.questions.map((q,i)=>`<option value="${esc(q.id)}">${i+1}. soru · ${esc(subjects[q.subject])}</option>`).join('')}</select></label><label>Deneyimin<select name="rating"><option value="3">3 · Kısmen anlaşılır</option><option value="1">1 · Anlaşılması çok zor</option><option value="2">2 · Geliştirilmeli</option><option value="4">4 · Anlaşılır</option><option value="5">5 · Çok anlaşılır</option></select></label><label>Geliştirme notun<textarea name="text" rows="3" maxlength="2000" required placeholder="Kişisel bilgi yazmadan görüşünü paylaş."></textarea></label><button class="primary">Görüşümü gönder</button></form></section>`;}
async function openNote(questionId){
 const attemptId=attempt.id,saved=await api('note/read',{attemptId,questionId});
 if(attempt?.id!==attemptId)return;
 const index=attempt.questions.findIndex(q=>q.id===questionId),q=attempt.questions[index];
 $('note-title').textContent=`${index+1}. soru · Notum ve karalamam`;
 noteWidget?.destroy();
 $('note-content').innerHTML=`<div class="note-spread"><section class="note-question" aria-label="Not aldığım soru"><p>${esc(q.stimulus)}</p>${q.figure?`<figure class="figure"><img src="data:image/svg+xml;charset=utf-8,${encodeURIComponent(q.figure.svg)}" alt="${esc(q.figure.alt)}"></figure>`:''}<p><b>${esc(q.stem)}</b></p><ol type="A">${q.options.map(option=>`<li>${esc(option)}</li>`).join('')}</ol></section><div id="note-editor"></div></div>`;
 noteWidget=mountAnnotationWidget($('note-editor'),{initial:saved,onSave:body=>api('note/save',{attemptId,questionId,...body})});$('note-dialog').showModal();
}
function closeNote(){if(noteWidget?.isDirty()&&!confirm('Kaydedilmemiş değişiklik var. Kaydetmeden kapatılsın mı?'))return;noteWidget?.destroy();noteWidget=null;$('note-dialog').close();}
$('note-close').onclick=closeNote;$('note-dialog').addEventListener('cancel',e=>{e.preventDefault();closeNote();});window.addEventListener('beforeunload',e=>{if(noteWidget?.isDirty()){e.preventDefault();e.returnValue='';}});
try{user=(await api('session')).user;user.mustChangePassword?passwordView():await dashboard();}catch{loginView();}
