// Original replacement questions. Source pages are curriculum anchors, not MEB approval.
// The LGS reference is used only for booklet style; Grade 6 content follows TYMM.
const escapeXml = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const text = (x, y, value, extra = '') => `<text x="${x}" y="${y}" ${extra}>${escapeXml(value)}</text>`;
const line = (x1, y1, x2, y2, extra = '') => `<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="#252525" stroke-width="1.4" ${extra}/>`;
const arrow = (x1, y1, x2, y2) => {
  const angle = Math.atan2(y2 - y1, x2 - x1), size = 6;
  const ax = x2 - size * Math.cos(angle - Math.PI / 6), ay = y2 - size * Math.sin(angle - Math.PI / 6);
  const bx = x2 - size * Math.cos(angle + Math.PI / 6), by = y2 - size * Math.sin(angle + Math.PI / 6);
  return `${line(x1, y1, x2, y2)}<path d="M ${ax.toFixed(2)} ${ay.toFixed(2)} L ${x2} ${y2} L ${bx.toFixed(2)} ${by.toFixed(2)}" fill="none" stroke="#252525" stroke-width="1.4"/>`;
};
const frame = body => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 360 150" role="img"><rect width="360" height="150" fill="#fff"/><g font-family="Arial, sans-serif" font-size="12" fill="#202020">${body}</g></svg>`;
const source = physicalPage => ({ programId: 'tymm-current-fen-bilimleri', physicalPage, styleReference: 'lgs-2024-numerical:p19' });
const explain = (given, wanted, strategy, steps, check, tip) => ({ given, wanted, strategy, steps, check, tip });
const figure = (body, alt) => ({ svg: frame(body), alt });

export const grade6Questions = [
  {
    id: 'YF6-01', grade: 6, branch: 'physics', topic: 'Güneş sistemi modelini düzeltme', outcomeCode: 'FB.6.1.2', source: source(112), difficulty: 'easy', bloom: 'apply', layout: 'regular',
    stimulus: 'Bir öğrenci, Güneş’e en yakın dört gezegeni aşağıdaki sırayla yerleştiriyor. Modelde yalnız iki gezegenin yerini değiştirerek sıralamayı düzeltecektir.',
    stem: 'Öğrenci hangi iki gezegenin yerini değiştirmelidir?',
    options: ['Merkür ile Venüs', 'Dünya ile Mars', 'Venüs ile Dünya', 'Merkür ile Mars'], answer: 1,
    figure: figure(`${arrow(26, 30, 326, 30)}${text(90, 20, 'Güneş’ten uzaklaşma yönü')}<circle cx="32" cy="85" r="20" fill="#e7e7e7" stroke="#333"/><circle cx="98" cy="85" r="8" fill="#b9b9b9" stroke="#333"/><circle cx="163" cy="85" r="11" fill="#ddd" stroke="#333"/><circle cx="232" cy="85" r="9" fill="#c7b8ac" stroke="#333"/><circle cx="301" cy="85" r="12" fill="#d2dce2" stroke="#333"/>${text(13, 125, 'Güneş')}${text(76, 125, 'Merkür')}${text(146, 125, 'Venüs')}${text(218, 125, 'Mars')}${text(282, 125, 'Dünya')}`, 'Güneş’ten uzaklaşma yönünde Merkür, Venüs, Mars ve Dünya yerleştirilmiş. Çizim ölçekli değildir.'),
    explanation: explain('Modelde ilk dört gezegen Merkür, Venüs, Mars, Dünya sırasındadır.', 'Doğru sıralama için yer değiştirmesi gereken iki gezegen.', 'Önce Güneş’e yakınlık sırasını hatırla, sonra modeldeki yerlerle karşılaştır.', ['Doğru sıra Merkür, Venüs, Dünya, Mars’tır.', 'İlk iki yer doğrudur; üçüncü ve dördüncü yerdeki Dünya ile Mars yer değiştirmelidir.'], 'Değişiklikten sonra Güneş’e en yakın gezegen yine Merkür olur.', 'Yakınlık sırası ile gezegenin büyüklüğünü birbirine karıştırma.'),
  },
  {
    id: 'YF6-02', grade: 6, branch: 'physics', topic: 'Tutulma modelinden çıkarım', outcomeCode: 'FB.6.1.3', source: source(112), difficulty: 'medium', bloom: 'analyze', layout: 'regular',
    stimulus: 'Güneş, Dünya ve Ay’ın merkezleri şekildeki gibi aynı doğrultudadır. Ay, Dünya’nın arkasındaki gölge bölgesinde bulunmaktadır. Büyüklükler ve uzaklıklar ölçekli değildir.',
    stem: 'Bu durumda gerçekleşen olay ve nedeni hangi seçenekte doğru verilmiştir?',
    options: ['Güneş tutulması; Ay, Dünya’nın gölgesine girer.', 'Ay tutulması; Ay, Güneş ile Dünya arasına girer.', 'Ay tutulması; Dünya, Güneş ışığının Ay’a ulaşmasını engeller.', 'Güneş tutulması; Dünya, Ay ile Güneş arasına girer.'], answer: 2,
    figure: figure(`<path d="M 195 53 L 320 64 L 320 86 L 195 97 Z" fill="#e2e2e2"/><circle cx="47" cy="75" r="30" fill="#f0e2b9" stroke="#555"/><circle cx="183" cy="75" r="23" fill="#d2dce2" stroke="#333"/><circle cx="289" cy="75" r="10" fill="#888" stroke="#333"/>${arrow(86, 62, 151, 62)}${arrow(86, 87, 151, 87)}${text(27, 125, 'Güneş')}${text(165, 125, 'Dünya')}${text(281, 125, 'Ay')}`, 'Solda Güneş, ortada Dünya, sağda Dünya’nın arkasındaki gölgede Ay var. Güneş ışınları Dünya’ya yöneliyor.'),
    explanation: explain('Dünya ortadadır ve Ay, Dünya’nın gölgesindedir.', 'Tutulmanın adını, gölgeyi oluşturan cisme dayanarak belirlemek.', 'Gölgesi Ay’ın üstüne düşen gök cismini izle.', ['Dünya, Güneş ile Ay arasındadır; Güneş ışığının Ay’a ulaşmasını engeller.', 'Ay gölgede kaldığından olay Ay tutulmasıdır.'], 'Güneş tutulmasında ortada Ay bulunurdu; şekil bu durumu göstermiyor.', 'Tutulmanın adını ezberden değil, gölgede kalan cisimden bul.'),
  },
  {
    id: 'YF6-03', grade: 6, branch: 'physics', topic: 'Alınan yol ve yer değiştirme', outcomeCode: 'FB.6.2.3', source: source(116), difficulty: 'medium', bloom: 'understand', layout: 'regular',
    stimulus: 'Ece, okul bahçesindeki parkurda K noktasından başlayıp okları izliyor. Bir turu tamamlayınca yeniden K noktasına geliyor.',
    stem: 'Ece’nin bu turdaki aldığı yol ve yer değiştirmesi için hangisi doğrudur?',
    options: ['Alınan yol sıfırdan büyüktür, yer değiştirme sıfırdır.', 'Alınan yol sıfırdır, yer değiştirme sıfırdan büyüktür.', 'Alınan yol ve yer değiştirme sıfırdır.', 'Alınan yol ve yer değiştirme birbirine eşit ve sıfırdan büyüktür.'], answer: 0,
    figure: figure(`<rect x="74" y="27" width="205" height="92" rx="22" fill="none" stroke="#aaa" stroke-width="10"/><path d="M 97 27 H 256 Q 279 27 279 50 V 96 Q 279 119 256 119 H 97 Q 74 119 74 96 V 50 Q 74 27 97 27" fill="none" stroke="#333"/>${arrow(153, 27, 205, 27)}${arrow(279, 58, 279, 91)}${arrow(205, 119, 153, 119)}${arrow(74, 91, 74, 58)}<circle cx="96" cy="27" r="4" fill="#111"/>${text(87, 17, 'K')}${text(115, 78, 'Başlangıç ve bitiş: K')}`, 'Kapalı dikdörtgen biçimli parkurda oklar bir tam turu gösteriyor. Başlangıç ve bitiş noktası aynı K noktası.'),
    explanation: explain('Ece yürüdükten sonra başladığı K noktasına dönüyor.', 'Yürüdüğü toplam yol ile başlangıç-bitiş konum farkını ayırmak.', 'Yol için izlenen parkura, yer değiştirme için yalnız ilk ve son konuma bak.', ['Ece parkurda yürüdüğünden aldığı yol sıfır değildir.', 'İlk ve son konum aynı olduğu için yer değiştirmesi sıfırdır.'], 'Tur tamamlanmış olsa da yürüyüş yapılmıştır; alınan yol sıfır olamaz.', 'Aynı noktaya dönüşte yer değiştirme sıfır olur; alınan yol sıfır olmak zorunda değildir.'),
  },
  {
    id: 'YF6-04', grade: 6, branch: 'physics', topic: 'Aynaların kullanım amacı', outcomeCode: 'FB.6.4.3', source: source(127), difficulty: 'medium', bloom: 'apply', layout: 'regular',
    stimulus: 'Okul, prova odasında öğrencinin görüntüsünü kendi boyunda gösteren bir ayna; otopark çıkışında ise daha geniş alanı gösterebilen bir güvenlik aynası kullanacaktır.',
    stem: 'Prova odası ve otopark çıkışı için sırasıyla hangi aynalar seçilmelidir?',
    options: ['Çukur ayna – Düz ayna', 'Tümsek ayna – Çukur ayna', 'Düz ayna – Çukur ayna', 'Düz ayna – Tümsek ayna'], answer: 3,
    figure: figure(`<rect x="42" y="28" width="65" height="94" fill="#fafafa" stroke="#333"/><circle cx="74" cy="53" r="8" fill="none" stroke="#666"/>${line(74, 61, 74, 92)}${line(74, 70, 58, 84)}${line(74, 70, 90, 84)}${line(74, 92, 61, 112)}${line(74, 92, 87, 112)}${text(32, 142, 'Prova odası')}<path d="M 201 31 H 273 V 79 H 332 M 201 65 H 239 V 116 H 332" fill="none" stroke="#555" stroke-width="2"/><circle cx="266" cy="62" r="14" fill="#fafafa" stroke="#333"/>${text(262, 66, '?')}${text(226, 142, 'Otopark çıkışı')}`, 'Solda bir öğrencinin tam boy görüleceği prova aynası alanı; sağda köşesi doğrudan görülemeyen bir otopark çıkışı ve ayna konumu gösteriliyor.'),
    explanation: explain('İlk yerde aynı boyda görüntü, ikinci yerde geniş görüş alanı isteniyor.', 'Her kullanım amacına uygun ayna türü.', 'İstenen görüntü özelliğini aynanın özelliğiyle eşleştir.', ['Düz ayna, cisimle aynı boyda görüntü oluşturur.', 'Tümsek ayna daha geniş alanın görülmesini sağladığı için güvenlik amacıyla kullanılır.'], 'Tümsek aynada görüntü küçüktür; aynı boy koşulunu sağlamaz.', 'Ayna seçerken yalnız görüntünün büyüklüğünü değil, kullanım amacını da oku.'),
  },
  {
    id: 'YF6-05', grade: 6, branch: 'physics', topic: 'Işığın soğurulması', outcomeCode: 'FB.6.4.4', source: source(127), difficulty: 'medium', bloom: 'analyze', layout: 'regular',
    stimulus: 'Yalnız dış yüzey renkleri farklı, özdeş iki kutu aynı süre güneş altında tutuluyor. Başlangıçta ikisi de 22 °C olan kutuların son sıcaklıkları şekilde verilmiştir.',
    stem: 'Bu deneyin sonucu hangi açıklamayı destekler?',
    options: ['Beyaz kutu ışığın tamamını soğurmuştur.', 'Siyah yüzey, beyaz yüzeye göre daha fazla ışık soğurmuştur.', 'Kutuların sıcaklığı yalnız biçimlerine bağlıdır.', 'Güneş ışığı kutuların sıcaklığını değiştirmemiştir.'], answer: 1,
    figure: figure(`${arrow(78, 16, 106, 47)}${arrow(116, 16, 144, 47)}${arrow(237, 16, 265, 47)}${arrow(275, 16, 303, 47)}<rect x="68" y="59" width="86" height="52" fill="#282828" stroke="#222"/><rect x="226" y="59" width="86" height="52" fill="#fff" stroke="#222"/>${text(91, 88, '38 °C', 'fill="#fff"')}${text(249, 88, '27 °C')}${text(89, 132, 'Siyah')}${text(247, 132, 'Beyaz')}`, 'Aynı güneş ışığı altında siyah kutunun son sıcaklığı 38 °C, beyaz kutunun son sıcaklığı 27 °C. Başlangıç sıcaklıkları eşit.'),
    explanation: explain('Aynı koşullarda siyah kutu 38 °C, beyaz kutu 27 °C olmuştur.', 'Sıcaklık farkının, değiştirilen yüzey rengiyle ilişkisini kurmak.', 'Diğer koşullar eşit olduğundan yalnız renk farkının etkisini karşılaştır.', ['Siyah kutunun sıcaklığı 16 °C, beyaz kutununki 5 °C artmıştır.', 'Bu sonuç, siyah yüzeyin daha fazla ışık soğurmasıyla açıklanır.'], 'Beyaz kutu da ısındığı için “ışığın hiçbirini soğurmaz” denemez.', 'Deneyde birden fazla özellik değişirse sonucu yalnız renge bağlayamazsın.'),
  },
  {
    id: 'YF6-06', grade: 6, branch: 'physics', topic: 'İletkenlik deneyinden madde seçme', outcomeCode: 'FB.6.6.1', source: source(138), difficulty: 'easy', bloom: 'apply', layout: 'regular',
    stimulus: 'Çalıştığı kontrol edilen basit devrenin X–Y uçları arasına sırayla K ve L maddeleri bağlanıyor. K bağlandığında ampul yanıyor, L bağlandığında yanmıyor. Bağlantılarda gevşeklik yoktur.',
    stem: 'K ve L maddeleri aşağıdakilerden hangisi olabilir?',
    options: ['K: Bakır tel, L: Plastik çubuk', 'K: Cam çubuk, L: Demir tel', 'K: Plastik çubuk, L: Bakır tel', 'K: Cam çubuk, L: Plastik çubuk'], answer: 0,
    figure: figure(`${line(52, 53, 110, 53)}${line(150, 53, 235, 53)}${line(289, 53, 313, 53)}${line(313, 53, 313, 116)}${line(313, 116, 183, 116)}${line(169, 116, 52, 116)}${line(52, 116, 52, 53)}<circle cx="130" cy="53" r="20" fill="none" stroke="#333"/>${line(116, 39, 144, 67)}${line(116, 67, 144, 39)}${line(169, 101, 169, 131)}${line(183, 107, 183, 125)}<rect x="235" y="45" width="54" height="16" fill="#e5e5e5" stroke="#333"/><circle cx="235" cy="53" r="2.4"/><circle cx="289" cy="53" r="2.4"/>${text(244, 32, 'Madde')}${text(226, 78, 'X')}${text(287, 78, 'Y')}${text(166, 145, 'Pil')}`, 'Tek bir seri yol üzerinde pil, ampul ve X–Y uçları arasına yerleştirilmiş deney maddesi bulunuyor. Maddeyi atlayan ikinci bir bağlantı yok.'),
    explanation: explain('K devreyi çalıştırıyor, L çalıştırmıyor; düzenek sağlam.', 'K için iletken, L için yalıtkan bir örnek seçmek.', 'Ampulün yanmasıyla maddenin elektriği iletmesini ilişkilendir.', ['Bakır tel iletkendir ve K yerine bağlanınca ampulün yanmasını sağlayabilir.', 'Plastik yalıtkandır; L yerine bağlandığında devreden elektrik iletilmez.'], 'Cam veya plastiğin K olması, verilen yanma gözlemiyle uyuşmaz.', 'Ampul yanmıyorsa önce pil ve bağlantıların sağlam olduğundan emin olunmalıdır.'),
  },
  {
    id: 'YF6-07', grade: 6, branch: 'chemistry', topic: 'Genleşmenin günlük yaşama aktarımı', outcomeCode: 'FB.6.5.1', source: source(132), difficulty: 'easy', bloom: 'apply', layout: 'regular',
    stimulus: 'Bir köprüdeki metal parçalar, sabit desteklerine şekildeki gibi bağlanmıştır. Parçaların arasındaki boşluk, sıcaklık değişimlerinde köprünün zarar görmesini önlemek için bırakılmıştır.',
    stem: 'Güneşli bir günde metallerin sıcaklığı arttığında aradaki boşluk nasıl değişir?',
    options: ['Büyür; metal parçalar ısınınca kısalır.', 'Değişmez; yalnız sıvılar genleşir.', 'Küçülür; metal parçalar ısınınca uzar.', 'Büyür; metallerin kütlesi azalır.'], answer: 2,
    figure: figure(`<rect x="34" y="58" width="130" height="27" fill="#e5e5e5" stroke="#333"/><rect x="197" y="58" width="130" height="27" fill="#e5e5e5" stroke="#333"/><path d="M 35 85 L 22 112 L 48 112 Z M 326 85 L 313 112 L 339 112 Z" fill="#aaa" stroke="#333"/>${line(164, 38, 197, 38)}${line(164, 31, 164, 45)}${line(197, 31, 197, 45)}${text(158, 25, 'Boşluk')}${text(20, 135, 'Sabit destek')}${text(262, 135, 'Sabit destek')}`, 'Uzak uçları sabit desteklerde olan iki metal köprü parçasının orta uçları arasında boşluk bulunuyor.'),
    explanation: explain('İki metal parçanın dış uçları sabit, orta uçları arasında boşluk var.', 'Sıcaklık artışının boşluğa etkisi.', 'Metallerin ısınınca genleştiğini, uzamanın hangi yöne olacağını düşün.', ['Metal parçalar ısındığında uzunlukları artar.', 'Dış uçlar sabit olduğundan orta uçlar birbirine yaklaşır; boşluk küçülür.'], 'Bu nedenle boşluk bırakılması sıcak havalarda sıkışmayı önler.', 'Genleşme, madde eklenmesi değil sıcaklığa bağlı boyut değişimidir.'),
  },
  {
    id: 'YF6-08', grade: 6, branch: 'chemistry', topic: 'Hâl değişimi sıcaklığı ile karşılaştırma', outcomeCode: 'FB.6.5.2', source: source(132), difficulty: 'medium', bloom: 'analyze', layout: 'regular',
    stimulus: 'Aynı basınçta incelenen saf P, Q ve R maddelerinin erime veya donma sıcaklıkları tabloda verilmiştir.',
    stem: 'Yalnız bu verilere göre hangi sonuca ulaşılabilir?',
    options: ['P ve Q kesinlikle aynı maddedir.', 'P ve R kesinlikle aynı maddedir.', 'Üç madde de farklıdır.', 'P ve R aynı madde olabilir; Q bu maddelerden farklıdır.'], answer: 3,
    figure: figure(`<rect x="28" y="25" width="304" height="108" fill="#fff" stroke="#444"/>${line(28, 55, 332, 55)}${line(28, 81, 332, 81)}${line(28, 107, 332, 107)}${line(94, 25, 94, 133)}${line(213, 25, 213, 133)}${text(37, 45, 'Madde')}${text(116, 45, 'Ölçülen özellik')}${text(230, 45, 'Sıcaklık (°C)')}${text(54, 73, 'P')}${text(121, 73, 'Erime noktası')}${text(268, 73, '18')}${text(54, 99, 'Q')}${text(119, 99, 'Donma noktası')}${text(268, 99, '32')}${text(54, 125, 'R')}${text(119, 125, 'Donma noktası')}${text(268, 125, '18')}`, 'P’nin erime noktası 18 °C, Q’nun donma noktası 32 °C ve R’nin donma noktası 18 °C. Hepsi aynı basınçta saf maddedir.'),
    explanation: explain('P 18 °C’de eriyor; R 18 °C’de, Q 32 °C’de donuyor.', 'Hangi maddelerin aynı olabileceğini, hangisinin farklı olduğunu ayırmak.', 'Aynı saf maddenin aynı basınçta erime ve donma noktaları eşittir.', ['P’nin erime noktası ile R’nin donma noktası eşittir; aynı madde olmaları mümkündür.', 'Q’nun donma noktası farklı olduğundan P ve R’den farklıdır.'], 'Tek bir özelliğin eşit olması, iki örneğin kesinlikle aynı madde olduğunu kanıtlamaz.', '“Olabilir” ile “kesinlikle” sözcüklerini ayır; kanıtın gücünü aşma.'),
  },
  {
    id: 'YF6-09', grade: 6, branch: 'chemistry', topic: 'Yoğunluğun miktardan bağımsızlığı', outcomeCode: 'FB.6.5.3', source: source(132), difficulty: 'medium', bloom: 'understand', layout: 'regular',
    stimulus: 'Homojen, saf bir metal çubuk şekildeki yerden kesiliyor. İşlem boyunca sıcaklık değişmiyor. Kesilmeden önce bütün çubuğun kütlesi 120 g, hacmi 40 cm³ olarak ölçülmüştür.',
    stem: 'K parçasının bütün çubuğa göre kütlesi, hacmi ve yoğunluğu nasıl değişir?',
    options: ['Kütle azalır; hacim ve yoğunluk değişmez.', 'Kütle, hacim ve yoğunluk azalır.', 'Kütle ve hacim azalır, yoğunluk değişmez.', 'Kütle ve yoğunluk azalır, hacim artar.'], answer: 2,
    figure: figure(`<rect x="44" y="52" width="266" height="42" fill="#dedede" stroke="#333"/><path d="M 132 39 V 107" stroke="#333" stroke-dasharray="4 3"/>${text(86, 78, 'K')}${text(151, 78, 'Kalan parça')}${text(117, 25, 'Kesme yeri')}${text(79, 128, 'Bütün: 120 g, 40 cm³')}`, 'Tek cins homojen metal çubuğun yaklaşık üçte birlik bölümüne K denmiş ve bu bölümü ayıran kesme yeri işaretlenmiş.'),
    explanation: explain('Aynı saf metalin daha küçük bir parçası alınıyor; sıcaklık sabit.', 'Madde miktarı azaldığında yoğunluğun değişip değişmediği.', 'Yoğunluğu kütle ve hacmin oranı olarak düşün.', ['K parçasında daha az madde bulunduğundan hem kütle hem hacim azalır.', 'Aynı homojen maddede kütle ve hacim aynı oranda azaldığından yoğunluk değişmez.'], 'Bütün çubuğun yoğunluğu 120 ÷ 40 = 3 g/cm³’tür; K da aynı sıcaklıkta 3 g/cm³ olur.', 'Küçük parça daha az kütleli olabilir; bu, daha az yoğun olduğu anlamına gelmez.'),
  },
  {
    id: 'YF6-10', grade: 6, branch: 'chemistry', topic: 'Karışmayan sıvılarda tabakalaşma', outcomeCode: 'FB.6.5.4', source: source(132), difficulty: 'hard', bloom: 'apply', layout: 'regular',
    stimulus: 'Birbirine karışmayan K, L ve M sıvılarından eşit hacimler alınarak kütleleri ölçülüyor. Ölçüm sonuçları şekilde verilmiştir. Bu sıvılar bir kaba konup bekletiliyor.',
    stem: 'Sıvılar üstten alta doğru hangi sırayla yerleşir?',
    options: ['M, K ve L', 'L, K ve M', 'K, L ve M', 'L, M ve K'], answer: 1,
    figure: figure([['K', 75, '20 g'], ['L', 180, '16 g'], ['M', 285, '24 g']].map(([name, x, mass]) => `<path d="M ${x - 26} 32 V 112 H ${x + 26} V 32" fill="none" stroke="#333"/><rect x="${x - 25}" y="61" width="50" height="50" fill="#e5edf2"/>${line(x - 25, 61, x + 25, 61)}${text(x - 4, 22, name)}${text(x - 21, 53, '20 cm³')}${text(x - 15, 135, mass)}`).join(''), 'Üç kapta da 20 cm³ sıvı var. K sıvısı 20 g, L sıvısı 16 g, M sıvısı 24 g kütleli.'),
    explanation: explain('Hacimler eşit; kütleler L:16 g, K:20 g, M:24 g.', 'Karışmayan sıvıların üstten alta yerleşme sırası.', 'Eşit hacimde daha fazla kütle, daha büyük yoğunluk demektir.', ['Yoğunluklar L için 0,8; K için 1; M için 1,2 g/cm³’tür.', 'En az yoğun L üstte, K ortada, en yoğun M altta kalır.'], 'Üstten alta giderken yoğunluğun artması gerekir; L–K–M bunu sağlar.', 'Hacimler eşitse kütleleri karşılaştırmak yoğunluk sırasını doğrudan verir.'),
  },
  {
    id: 'YF6-11', grade: 6, branch: 'chemistry', topic: 'Buz ve suyun yoğunluk farkının canlılar için önemi', outcomeCode: 'FB.6.5.5', source: source(132), difficulty: 'medium', bloom: 'understand', layout: 'regular',
    stimulus: 'Soğuk bir kış gününde bir gölün yüzeyinde buz oluşurken altta sıvı su kaldığı gözleniyor. Şekil, gölün kesitini göstermektedir.',
    stem: 'Bu durumun göldeki canlılar için önemini hangi ifade açıklar?',
    options: ['Altta sıvı su kalabilmesi, su canlılarının yaşamını sürdürmesine yardımcı olur.', 'Buz sudan yoğun olduğu için dibe çöker.', 'Göl yüzeyi donduğunda alttaki su da mutlaka donar.', 'Su donunca kütlesi yok olur ve canlılara yer açılır.'], answer: 0,
    figure: figure(`<path d="M 38 43 L 69 120 H 294 L 325 43" fill="#eef3f6" stroke="#444"/><path d="M 40 44 H 324 L 317 62 H 47 Z" fill="#ddd" stroke="#555"/>${text(167, 39, 'Buz')}${text(142, 85, 'Sıvı su')}<ellipse cx="171" cy="103" rx="14" ry="6" fill="#aaa" stroke="#555"/><path d="M 185 103 L 195 96 V 110 Z" fill="#aaa" stroke="#555"/><circle cx="163" cy="102" r="1.3" fill="#222"/>${text(114, 142, 'Gölün şematik kesiti')}`, 'Göl yüzeyinde buz tabakası, altında sıvı su ve su içinde balık gösteriliyor. Buz dibe çökmemiştir.'),
    explanation: explain('Buz yüzeyde, sıvı su ve canlılar altta görülüyor.', 'Yoğunluk farkının su canlılarının yaşamıyla ilişkisi.', 'Buzun neden üstte kaldığını ve altta hangi ortamın korunduğunu düşün.', ['Buz, sıvı sudan daha az yoğun olduğundan üstte kalır.', 'Yüzeyde buz bulunurken altta sıvı suyun kalabilmesi, su canlılarının yaşamını sürdürmesine yardımcı olur.'], 'Şekil bütün gölün donduğunu göstermiyor; buzun dibe çöktüğü de söylenemez.', 'Şekildeki gözlemi açıklarken gösterilmeyen bir sıcaklık değeri varsayma.'),
  },
  {
    id: 'YF6-12', grade: 6, branch: 'chemistry', topic: 'Yoğunluk ölçümünde kabın kütlesini ayırma', outcomeCode: 'FB.6.5.3', source: source(132), difficulty: 'hard', bloom: 'apply', layout: 'regular',
    stimulus: 'Boş bir ölçü kabının kütlesi 26 g’dır. Kaba bir sıvı konulduğunda sıvının hacmi 24 cm³, kap ile sıvının toplam kütlesi 74 g ölçülüyor.',
    stem: 'Bu sıvının yoğunluğu kaç g/cm³’tür?',
    options: ['0,5 g/cm³', '1 g/cm³', '3 g/cm³', '2 g/cm³'], answer: 3,
    figure: figure(`<path d="M 56 27 V 91 H 106 V 27" fill="none" stroke="#333"/><rect x="43" y="99" width="77" height="30" rx="3" fill="#eee" stroke="#333"/>${text(67, 120, '26 g')}<path d="M 232 27 V 91 H 282 V 27" fill="none" stroke="#333"/><rect x="233" y="50" width="48" height="40" fill="#d9e5ee"/>${line(232, 50, 282, 50)}${line(274, 39, 282, 39)}${line(274, 50, 282, 50)}${line(274, 61, 282, 61)}${line(274, 72, 282, 72)}${line(274, 83, 282, 83)}${text(290, 54, '24 cm³')}<rect x="220" y="99" width="77" height="30" rx="3" fill="#eee" stroke="#333"/>${text(243, 120, '74 g')}${text(55, 18, 'Boş kap')}${text(225, 18, 'Kap ve sıvı')}`, 'Soldaki terazide boş kap 26 g. Sağdaki terazide 24 cm³ sıvıyla birlikte kap 74 g gösteriyor.'),
    explanation: explain('74 g toplam kütleye 26 g olan kap da dahildir; sıvı hacmi 24 cm³.', 'Yalnız sıvının birim hacmindeki kütle.', 'Önce kabın kütlesini çıkar; sonra sıvının kütlesini hacmine böl.', ['Sıvının kütlesi 74 − 26 = 48 g’dır.', 'Yoğunluk 48 ÷ 24 = 2 g/cm³ olur.'], '2 g/cm³ × 24 cm³ = 48 g; kap eklenince toplam 74 g bulunur.', 'Terazi kapla birlikte ölçüyorsa toplam kütleyi doğrudan yoğunluk hesabında kullanma.'),
  },
  {
    id: 'YF6-13', grade: 6, branch: 'biology', topic: 'Bitkide vejetatif üreme', outcomeCode: 'FB.6.3.1', source: source(120), difficulty: 'easy', bloom: 'understand', layout: 'regular',
    stimulus: 'Bir çilek bitkisinden çıkan sürünücü gövde toprağa değdiği yerde kökleniyor ve yeni bir bitki oluşturuyor. Bu süreçte tohum oluşmuyor.',
    stem: 'Yeni bitkinin oluşmasıyla ilgili hangi ifade doğrudur?',
    options: ['İki üreme hücresinin birleşmesi zorunludur.', 'Yeni bitki, üreme hücreleri birleşmeden oluşmuştur.', 'Bu olay yalnız bitkinin boyunun uzamasıdır.', 'Yeni bitki oluşabilmesi için önce meyve oluşmalıdır.'], answer: 1,
    figure: figure(`${line(34, 105, 332, 105)}<path d="M 97 101 V 47 M 97 68 Q 74 42 60 65 Q 79 78 97 68 M 97 80 Q 119 52 135 72 Q 117 92 97 80 M 246 103 V 69 M 246 82 Q 227 60 214 79 Q 231 92 246 82 M 246 91 Q 265 69 278 86 Q 262 101 246 91 M 97 95 Q 161 70 246 103" fill="none" stroke="#444" stroke-width="2"/><path d="M 96 105 l -13 24 m 13 -24 l 8 25 m 147 -25 l -12 24 m 12 -24 l 10 22" fill="none" stroke="#666"/>${text(59, 28, 'Ana bitki')}${text(218, 52, 'Yeni bitki')}${text(122, 130, 'Sürünücü gövde')}${arrow(172, 116, 181, 94)}`, 'Ana çilek bitkisini yeni bitkiye bağlayan sürünücü gövde ve yeni bitkinin toprağa uzanan kökleri gösteriliyor.'),
    explanation: explain('Ana bitkinin gövdesinden, tohum oluşmadan yeni birey gelişiyor.', 'Bu üreme biçiminin temel özelliği.', 'Yeni birey oluşup oluşmadığını ve üreme hücrelerinin birleşmesini ayrı değerlendir.', ['Köklenen bölüm ayrı bir bitki oluşturduğu için olay üremedir.', 'Üreme hücrelerinin birleşmesi olmadan gerçekleştiğinden eşeysiz, vejetatif üreme örneğidir.'], 'Yalnız boy uzaması olsaydı yeni bir birey oluştuğu belirtilmezdi.', '“Yeni birey” üremeyi, aynı bireyin boyut artışı büyümeyi gösterir.'),
  },
  {
    id: 'YF6-14', grade: 6, branch: 'biology', topic: 'Çiçekte tozlaşma', outcomeCode: 'FB.6.3.2', source: source(120), difficulty: 'easy', bloom: 'understand', layout: 'regular',
    stimulus: 'Çiçeğin şemasında K, erkek organın başçığını; L, dişi organın tepeciğini göstermektedir. Küçük noktalar, K’den L’ye taşınan polenlerdir.',
    stem: 'Okla gösterilen olayın adı nedir?',
    options: ['Döllenme', 'Çimlenme', 'Tozlaşma', 'Meyve oluşumu'], answer: 2,
    figure: figure(`<path d="M 180 121 Q 114 112 101 80 Q 129 53 159 76 Q 142 27 180 24 Q 220 28 201 77 Q 232 50 259 80 Q 245 116 180 121 Z" fill="#f3f3f3" stroke="#777"/><path d="M 180 121 V 68 M 134 104 V 68 M 223 106 V 68" fill="none" stroke="#444" stroke-width="2"/><ellipse cx="134" cy="64" rx="10" ry="5" fill="#bbb" stroke="#333"/><ellipse cx="223" cy="64" rx="10" ry="5" fill="#bbb" stroke="#333"/><ellipse cx="180" cy="64" rx="10" ry="4" fill="#ddd" stroke="#333"/><ellipse cx="180" cy="113" rx="12" ry="8" fill="#e5e5e5" stroke="#333"/>${arrow(140, 49, 175, 49)}<circle cx="146" cy="55" r="1.5"/><circle cx="155" cy="57" r="1.5"/><circle cx="166" cy="56" r="1.5"/>${text(113, 53, 'K')}${text(192, 57, 'L')}${text(152, 143, 'Çiçek şeması')}`, 'Erkek organın başçığı K ile dişi organın tepeciği L arasında, polenlerin taşınmasını gösteren bir ok var.'),
    explanation: explain('Polenler başçıktan dişi organın tepeciğine taşınıyor.', 'Gösterilen sürecin adını belirlemek.', 'Polenin taşınması ile üreme hücrelerinin birleşmesini ayır.', ['Ok K’den, yani başçıktan başlıyor; L’de, yani tepecikte bitiyor.', 'Polenin başçıktan tepeciğe taşınması tozlaşmadır. Döllenme ise üreme hücrelerinin birleşmesidir.'], 'Şekilde üreme hücrelerinin birleşmesi, tohumun çimlenmesi veya meyvenin gelişmesi gösterilmiyor; doğru ad tozlaşmadır.', 'Taşınma: Tozlaşma. Üreme hücrelerinin birleşmesi: Döllenme.'),
  },
  {
    id: 'YF6-15', grade: 6, branch: 'biology', topic: 'Çimlenme deneyinden sınırlı çıkarım', outcomeCode: 'FB.6.3.3', source: source(120), difficulty: 'medium', bloom: 'analyze', layout: 'regular',
    stimulus: 'Aynı türden onar sağlam tohum, nemli pamuk üzerinde 25 °C’de bekletiliyor. Kapların ikisi de hava alıyor. K ışık alırken L karanlıkta tutuluyor. Beşinci gün iki kapta da dokuz tohumun çimlendiği görülüyor.',
    stem: 'Bu deneyden hangi sonuca ulaşılabilir?',
    options: ['Bu tohumlar, uygun diğer koşullarda ışık olmadan da çimlenebilir.', 'Tohumların çimlenmesi için suya gerek yoktur.', 'Her bitki yaşamı boyunca karanlıkta büyüyebilir.', 'Sıcaklık, çimlenmeyi hiçbir zaman etkilemez.'], answer: 0,
    figure: figure(`<path d="M 33 76 L 43 114 H 141 L 151 76 M 208 76 L 218 114 H 316 L 326 76" fill="#f6f6f6" stroke="#444"/><path d="M 42 103 H 142 M 217 103 H 317" stroke="#bbb" stroke-width="4"/>${[45, 220].map(start => Array.from({ length: 10 }, (_, i) => `<ellipse cx="${start + i * 10}" cy="102" rx="3.3" ry="2.2" fill="#bbb" stroke="#555"/>${i < 9 ? `<path d="M ${start + i * 10} 100 V 86 q -6 -8 -4 -1 q 3 3 4 1 q 6 -8 4 -1 q -3 3 -4 1" fill="none" stroke="#444"/>` : ''}`).join('')).join('')}${text(69, 29, 'K · Işık')}${text(229, 29, 'L · Karanlık')}${text(43, 52, '9/10 tohum çimlendi')}${text(217, 52, '9/10 tohum çimlendi')}${text(82, 142, 'Nem, sıcaklık ve hava koşulları aynı')}`, 'K ışıkta ve L karanlıkta; her kapta on tohum çizili, dokuzundan filiz çıkmış. Nem, sıcaklık ve hava koşulları aynı.'),
    explanation: explain('Işık alan ve almayan kaplarda aynı tür tohumların çimlendiği görülüyor.', 'Işığın gerekli olup olmadığına dair bu deneyin desteklediği çıkarım.', 'Yalnız değiştirilen etken ve gözlenen sonuç hakkında karar ver.', ['Karanlıkta tutulan L’de de çimlenme gerçekleşmiştir.', 'Bu gözlem, kullanılan tohumların diğer koşullar uygunken ışık olmadan çimlenebildiğini gösterir.'], 'Su veya sıcaklık değiştirilmedi; bu etkenlerin gereksiz olduğu sonucuna varılamaz.', 'Çimlenme ile bitkinin sonraki büyüme döneminin ihtiyaçları aynı şey değildir.'),
  },
  {
    id: 'YF6-16', grade: 6, branch: 'biology', topic: 'Başkalaşımın evrelerini sıralama', outcomeCode: 'FB.6.3.4', source: source(120), difficulty: 'easy', bloom: 'understand', layout: 'regular',
    stimulus: 'Bir kelebeğin yumurtadan çıktıktan sonraki üç gelişim evresi şekilde numaralandırılmıştır.',
    stem: 'I, II ve III ile gösterilen evreler sırasıyla hangileridir?',
    options: ['Pupa – Tırtıl – Ergin kelebek', 'Tırtıl – Ergin kelebek – Pupa', 'Ergin kelebek – Pupa – Tırtıl', 'Tırtıl – Pupa – Ergin kelebek'], answer: 3,
    figure: figure(`<circle cx="37" cy="84" r="8" fill="#ddd" stroke="#555"/><circle cx="49" cy="82" r="9" fill="#ddd" stroke="#555"/><circle cx="62" cy="81" r="9" fill="#ddd" stroke="#555"/><circle cx="75" cy="81" r="9" fill="#ddd" stroke="#555"/><circle cx="88" cy="77" r="10" fill="#ddd" stroke="#555"/><circle cx="91" cy="75" r="1.5"/>${line(43, 89, 39, 96)}${line(59, 89, 56, 96)}${line(73, 89, 73, 96)}${arrow(109, 78, 142, 78)}<path d="M 179 39 Q 163 51 166 82 Q 167 103 179 112 Q 192 103 193 82 Q 197 53 179 39 Z" fill="#ddd" stroke="#555"/>${line(179, 26, 179, 39)}${line(155, 26, 201, 26)}<path d="M 166 66 Q 179 74 193 66 M 167 84 Q 179 92 193 84" fill="none" stroke="#777"/>${arrow(214, 78, 247, 78)}<ellipse cx="293" cy="81" rx="4" ry="25" fill="#555"/><ellipse cx="275" cy="68" rx="16" ry="23" transform="rotate(-25 275 68)" fill="#e0e0e0" stroke="#555"/><ellipse cx="311" cy="68" rx="16" ry="23" transform="rotate(25 311 68)" fill="#e0e0e0" stroke="#555"/><ellipse cx="278" cy="99" rx="13" ry="15" fill="#eee" stroke="#555"/><ellipse cx="308" cy="99" rx="13" ry="15" fill="#eee" stroke="#555"/>${line(292, 57, 287, 47)}${line(294, 57, 299, 47)}${text(64, 138, 'I')}${text(175, 138, 'II')}${text(289, 138, 'III')}`, 'I’de parçalı gövdeli tırtıl, II’de bir dala asılı pupa, III’te kanatlı ergin kelebek var. Oklar I’den II’ye ve II’den III’e gidiyor.'),
    explanation: explain('İlk evre tırtıl, ikinci evre hareketsiz dış kılıflı pupa, son evre kanatlı bireydir.', 'Kelebeğin gelişim evrelerinin adları.', 'Yumurtadan çıkan yavrunun ergin kelebeğe benzemediğini dikkate al.', ['Yumurtadan çıkan evre tırtıldır; büyüyen tırtıl pupa evresine geçer.', 'Pupadaki gelişimden sonra ergin kelebek oluşur; bu değişime başkalaşım denir.'], 'Pupa ergin kelebekten önceki evredir, kelebekten sonraki evre değildir.', 'Başkalaşımda yalnız boyut değil, vücut yapısı da belirgin biçimde değişir.'),
  },
  {
    id: 'YF6-17', grade: 6, branch: 'biology', topic: 'Sinir sisteminde denge görevi', outcomeCode: 'FB.6.3.6', source: source(120), difficulty: 'medium', bloom: 'apply', layout: 'regular',
    stimulus: 'Bir öğrenci dar bir çizgi üzerinde yürürken kollarını açarak dengesini koruyor. Hareketlerinin birbiriyle uyumlu olması, düşmeden ilerlemesini kolaylaştırıyor.',
    stem: 'Denge ve hareketlerin uyumunun sağlanmasında özellikle hangi yapı görevlidir?',
    options: ['Omurilik', 'Omurilik soğanı', 'Beyincik', 'Hipofiz bezi'], answer: 2,
    figure: figure(`<path d="M 47 126 H 317" stroke="#aaa" stroke-width="7"/><circle cx="181" cy="31" r="11" fill="none" stroke="#333" stroke-width="2"/>${line(181, 42, 181, 83)}${line(181, 52, 129, 65)}${line(181, 52, 232, 62)}${line(181, 83, 165, 119)}${line(181, 83, 201, 112)}${line(159, 119, 174, 119)}${line(197, 112, 213, 112)}${text(113, 145, 'Dar çizgi üzerinde yürüme')}`, 'Dar bir çizgi üzerinde yürüyen öğrenci dengesini korumak için iki kolunu yanlara açıyor.'),
    explanation: explain('Öğrenci yürürken denge kuruyor ve hareketlerini uyumlu yapıyor.', 'Bu görevle ilişkili sinir sistemi yapısı.', 'Davranışın özellikle hangi işlevi gerektirdiğini belirle.', ['Sorunun vurgusu refleks veya solunum değil, denge ve hareket uyumudur.', 'Bu işlevlerde beyincik görevlidir.'], 'Hipofiz bir iç salgı bezidir; burada sorulan denge görevinin karşılığı değildir.', 'Organı seçmeden önce davranıştaki anahtar görevi belirle: denge, refleks, düşünme gibi.'),
  },
  {
    id: 'YF6-18', grade: 6, branch: 'biology', topic: 'Yaşam alanlarının parçalanmasına çözüm', outcomeCode: 'FB.6.7.4', source: source(142), difficulty: 'medium', bloom: 'apply', layout: 'regular',
    stimulus: 'Bir yol, aynı ormanda yaşayan hayvanların geçiş yaptığı alanı ikiye ayırmıştır. İzleme çalışmaları, hayvanların yolun iki tarafı arasında geçiş yapmakta zorlandığını göstermektedir.',
    stem: 'Bu sorunu azaltmak için hangi uygulama en uygundur?',
    options: ['Ormanın çevresindeki bütün bitkileri temizlemek', 'İki alanı bitki örtüsü bulunan bir geçitle birleştirmek', 'Hayvanların tamamını tek bir küçük alanda toplamak', 'Ormanın içinden geçen yolu daha da genişletmek'], answer: 1,
    figure: figure(`<rect x="23" y="24" width="131" height="104" fill="#f1f1f1" stroke="#777"/><rect x="206" y="24" width="131" height="104" fill="#f1f1f1" stroke="#777"/><rect x="164" y="12" width="31" height="116" fill="#ddd"/>${line(180, 14, 180, 126, 'stroke-dasharray="7 5"')}${[45, 91, 126, 228, 269, 312].map((x, i) => `<path d="M ${x} ${42 + (i % 2) * 34} l -10 19 h 20 Z" fill="#ddd" stroke="#666"/>${line(x, 61 + (i % 2) * 34, x, 71 + (i % 2) * 34)}`).join('')}${arrow(118, 113, 153, 113)}${arrow(207, 113, 239, 113)}${text(180, 143, 'Yol', 'text-anchor="middle"')}${text(56, 17, 'Orman alanı')}${text(230, 17, 'Orman alanı')}`, 'Ortadaki yol, orman alanını birbirinden ayrı iki parçaya ayırıyor. Hayvanların iki taraf arasında geçişi kesintiye uğramış.'),
    explanation: explain('Sorun, yol nedeniyle ormanın iki bölümünün bağlantısının kesilmesi.', 'Hayvanların güvenli geçişini kolaylaştıracak çözüm.', 'Çözümü, sorunun doğrudan nedenine yönelt.', ['Bitki örtülü bir geçit, ormanın iki bölümünü yeniden birbirine bağlayabilir.', 'Alanı küçültmek veya yolu genişletmek geçiş sorununu çözmez; yaşam alanına baskıyı artırabilir.'], 'Önerilen geçit, hem yolun kullanımını hem hayvanların hareketini birlikte gözetir.', 'Çevre sorusunda iyi niyetli görünen her seçenek değil, belirtilen nedeni azaltan seçenek aranır.'),
  },
];
