import { createHash } from 'node:crypto';
import { createGrade6QuestionReviewBank } from './grade6_question_review_bank.mjs';

// The sink rebuilds fixed source-bound items; it never accepts caller HTML,
// questions, answers or authority. Closed details are editorial convenience.
const fail=code=>{throw new Error(code);};
const esc=v=>{if(!['string','number','boolean'].includes(typeof v))fail('invalid_question_bank_editor_input');
  return String(v).replace(/[&<>"']/gu,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);};
const list=values=>`<ul>${values.map(v=>`<li>${esc(v)}</li>`).join('')}</ul>`;
const pairs=values=>values.map(pair=>pair.join(' × ')).join('; ');
const table=(caption,heads,rows)=>`<table><caption>${esc(caption)}</caption><thead><tr>${heads.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map((v,i)=>i?`<td>${esc(v)}</td>`:`<th scope="row">${esc(v)}</th>`).join('')}</tr>`).join('')}</tbody></table>`;
const letters='ABCDE';
const units={minute:'Dakika',card_per_package:'Kart/paket',package:'Paket'};
const labelRule=rule=>rule==='largest'?'En büyük':'En küçük';
const STYLE=`
:root{color-scheme:light;color:#223c43;background:#f5f3ed;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
*{box-sizing:border-box}body{margin:0;font-size:18px;line-height:1.65}main{max-width:1120px;margin:auto;padding:28px 20px 60px}
h1,h2,h3,p{margin:0 0 16px}h1{font-size:clamp(30px,4vw,44px);line-height:1.2;letter-spacing:-.025em}h2{font-size:28px;line-height:1.3}h3{font-size:21px;line-height:1.4}
header{padding:34px;border-radius:24px;background:#153e45;color:white}.eyebrow{color:#b8e0d5;font-weight:650}.counts{font-weight:650}
nav{display:flex;gap:10px;flex-wrap:wrap;margin:22px 0}nav a{padding:10px 16px;border:1px solid #96aca7;border-radius:12px;background:white;color:#173f39;text-decoration:none;font-weight:650}
a:focus-visible,summary:focus-visible{outline:3px solid #a35129;outline-offset:4px}aside{padding:22px;background:#fff5df;border:1px solid #d4b989;border-radius:16px;margin:24px 0}
.task{padding:24px;border:1px solid #b8c8c3;border-radius:18px;background:white;margin:28px 0;min-width:0;scroll-margin-top:24px}
.section-number,.lineage{color:#49645f}.section-number{font-size:16px;font-weight:650}.lineage{font-size:14px;overflow-wrap:anywhere}.status{display:inline-block;padding:6px 12px;background:#fff0d1;border-radius:10px;font-size:16px}
.choices{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.choice{border:1px solid #ccd6ce;border-radius:12px;padding:16px;min-width:0}.choice p:last-child{margin-bottom:0}
.given{padding:18px;background:#edf5f0;border-left:4px solid #46796a;border-radius:0 12px 12px 0}.shortcut{padding:16px;background:#edf5f0;border-left:4px solid #46796a}.shortcut p:last-child{margin-bottom:0}
table{border-collapse:collapse;table-layout:fixed;width:100%;font-variant-numeric:tabular-nums;margin:16px 0}caption{text-align:left;font-weight:650;padding:8px 0}th,td{padding:10px 5px;border-bottom:1px solid #d4dfd8;text-align:left;overflow-wrap:anywhere}thead th{background:#edf3ee}
details{margin-top:24px;border:1px solid #9ab7aa;border-radius:12px;overflow:hidden}summary{padding:18px;background:#e7f1ea;cursor:pointer;font-weight:650}.solution{padding:22px}.solution h3{margin-top:24px}.solution li{margin-bottom:12px}.answer{padding:16px;background:#e7f1ea;border-radius:10px}.result{font-weight:650;color:#19533d}footer{padding-top:24px;border-top:1px solid #bacbc1;color:#49645f}
@media(max-width:600px){main{padding:20px 12px 40px}header{padding:24px}.task,.solution{padding:18px}.choices{grid-template-columns:1fr}h2{font-size:25px}th,td{padding:8px 3px}}
`;
function shortcut(s){return `<div class="shortcut"><h3>Pratik bilgi ve püf nokta</h3><p><strong>Ne zaman?</strong> ${esc(s.worksWhen)}</p><p>${esc(s.why)}</p><p><strong>Kontrol:</strong> ${esc(s.check)}</p><p><strong>Sınır:</strong> ${esc(s.notImplied)}</p></div>`;}
function reason(e){return `<h3>Ne isteniyor?</h3><p>${esc(e.goal)}</p><h3>Verilenler neyi anlatıyor?</h3><p>${esc(e.givenMeaning)}</p><h3>Neden bu yol?</h3><p>${esc(e.route)}</p><p>${esc(e.because)}</p>${list(e.conditions)}<ol>${e.steps.map(step=>`<li><p>${esc(step.why)}</p><p class="result">${esc(step.meaning)}</p></li>`).join('')}</ol>`;}
function choice(id,index,body){return `<section class="choice" data-choice-id="${esc(id)}"><h3>Seçenek ${letters[index]}</h3>${body}</section>`;}
function inverseGiven(d){const p=d.problem;return `<div class="given"><p>Başlangıç sayısı: ${p.candidateDomain.minimum}–${p.candidateDomain.maximum}, sınırlar dahil.</p><p>Eksik çiftler: ${p.partialPairs.map(r=>`${r.left??'□'} × ${r.right??'□'}`).join(' · ')}.</p><p>Küçük çarpan önce yazılır. Seçenekteki kalan çiftler, bu iki satır dışındaki bütün çiftleri eksiksiz göstermeli.</p></div><div class="choices">${p.options.map((o,i)=>choice(o.id,i,`<p>Başlangıç sayısı: ${esc(o.number)}</p><p>Kalan çiftler: ${esc(pairs(o.remainingPairs))}</p>`)).join('')}</div>`;}
function primeGiven(d){return `${table('Başlangıç sayısı ve satıra özel seçim',['Kaynak satır','Başlangıç','Asal çarpan kuralı'],d.problem.rows.map((r,i)=>[`${letters[i]} · ${r.id}`,r.number,labelRule(r.selectionRule)]))}<p>Küçükten büyüğe sırala. Eşit değerlerin tümünü koru; eşitlikte A–E başlangıç sırasını kullan.</p><div class="choices">${d.problem.options.map((o,i)=>choice(o.id,i,table('Önerilen sıralama',['Kaynak satır','Başlangıç','Seçilen asal'],o.entries.map(r=>[r.sourceRowId,r.sourceNumber,r.selectedPrime])))).join('')}</div>`;}
function classificationGiven(d){return `<div class="given"><p>Sayı kartları: ${esc(d.problem.cards.map(c=>c.value).join(', '))}.</p>${list(d.problem.rules.map(r=>r.label))}${list(d.problem.categories.map(r=>r.label))}</div>`;}
function factorGiven(d){return `<div class="choices">${d.problem.boards.map((b,i)=>choice(b.id,i,`${table('Verilmiş çarpan çiftleri',['Küçük çarpan','Büyük çarpan'],b.factorPairs)}<p>Asal rozetler: ${esc(b.primeBadges.join(', '))}.</p><p>Rozet toplamı: ${esc(b.primeBadgeSum)}.</p>`)).join('')}</div>`;}
function commonGiven(d){return `${d.problem.contexts.map(c=>`<h3>${esc(c.title)}</h3><p>${esc(c.statement)}</p>`).join('')}<div class="given"><h3>Verilmiş dört kanıt kartı</h3>${list(d.problem.evidenceCards.map(c=>`${c.label}: ${c.values.join(', ')} · ${units[c.unit]}`))}</div>`;}
function inverseSolution(d){const s=d.solution;return `${reason(d.explanation)}<p class="answer">Doğru seçenek: B. Başlangıç sayısı ${esc(s.number)}.</p>${table('Eksik satırların tamamlanması',['Satır','Küçük çarpan','Büyük çarpan'],s.completedPairs.map(r=>[r.partialPairId,r.left,r.right]))}${table('Başlangıç sayısının bütün çarpan çiftleri',['Küçük çarpan','Büyük çarpan'],s.allFactorPairs)}<p>Kalan çiftler: ${esc(pairs(s.remainingPairs))}.</p>${shortcut(d.explanation.conditionalShortcut)}<p>${esc(d.explanation.transfer.meaning)}</p>`;}
function primeSolution(d){return `${reason(d.explanation)}${table('Her seçim kendi kaynağında kontrol edilir',['Kaynak satır','Başlangıç','Farklı asallar','Kural','Seçim'],d.solution.rowSelections.map(r=>[r.sourceRowId,r.sourceNumber,r.distinctPrimeFactors.join(', '),labelRule(r.selectionRule),r.selectedPrime]))}<p class="answer">Doğru seçenek: B. İki ayrı satırın 3 seçimi de korunur.</p>${table('Doğru sıralama · kaynaklar birlikte taşınır',['Kaynak satır','Başlangıç','Seçilen asal'],d.solution.orderedSelections.map(r=>[r.sourceRowId,r.sourceNumber,r.selectedPrime]))}${shortcut(d.explanation.conditionalShortcut)}<p>${esc(d.explanation.transfer.meaning)}</p>`;}
function classificationSolution(d){return `${reason(d.explanation)}${table('Her sayı için iki ayrı karar',['Sayı','2 ile','3 ile'],d.solution.cardReasons.map(r=>[d.problem.cards.find(c=>c.id===r.cardId).value,r.divisibleBy2?'Evet':'Hayır',r.divisibleBy3?'Evet':'Hayır']))}${list(d.solution.correctGroups.map(g=>`${d.problem.categories.find(c=>c.id===g.categoryId).label}: ${g.cardIds.map(id=>d.problem.cards.find(c=>c.id===id).value).join(', ')}`))}${shortcut(d.explanation.conditionalShortcut)}`;}
function factorSolution(d){return `${reason(d.explanation)}${table('Doğru panonun eksiksiz çiftleri',['Küçük çarpan','Büyük çarpan'],d.explanation.steps[0].result)}<p class="answer">Doğru seçenek: C. Farklı asal rozetler: 2, 3. Rozet toplamı: 5.</p>${shortcut(d.explanation.conditionalShortcut)}<p>${esc(d.explanation.transfer.meaning)}</p>`;}
function commonSolution(d){return `${d.explanation.paths.map(p=>`<h3>Ne isteniyor?</h3><p>${esc(p.goal)}</p><h3>Verilenler neyi anlatıyor?</h3><p>${esc(p.givenMeaning)}</p><h3>Neden bu yol?</h3><p>${esc(p.why)}</p><p>${esc(p.operationMeaning)}</p><p class="answer">${esc(p.result.join(', '))} · ${esc(units[p.unit])}</p><p>${esc(p.resultMeaning)}</p><h3>Pratik bilgi ve püf nokta</h3>${list(Object.values(p.conditionalNote))}`).join('')}${list(d.explanation.transfers.map(t=>t.meaning))}`;}
const GIVEN=[inverseGiven,primeGiven,classificationGiven,factorGiven,commonGiven];
const SOLUTION=[inverseSolution,primeSolution,classificationSolution,factorSolution,commonSolution];
const TITLES=['Eksik Bilgiden Bütünü Kur','Asal Seçimini Kaynağıyla Sırala','İki Kuralı Birlikte Gör','Dört Kanıt Panosunu Denetle','Zaman mı, Paket Boyutu mu?'];
function question(row,index){const d=row.draft;return `<article class="task" id="question-${index+1}" data-question-family="${esc(row.family)}" data-task-revision="${esc(row.source.contentSha256)}"><p class="section-number">${index+1<10?'0':''}${index+1} · ${index<2?'Yeni özgün taslak':'Mevcut görev'}</p><h2>${TITLES[index]}</h2><p>${esc(d.prompt)}</p><p class="status">${row.difficulty.level===null?'Zorluk atanmadı':`${row.difficulty.level==='hard'?'Zor':'Orta'} · Yazar tahmini`}</p>${GIVEN[index](d)}<details data-answer-revision="${esc(row.source.contentSha256)}"><summary>Soru ${index+1}: Gerekçeli çözümü aç</summary><div class="solution">${SOLUTION[index](d)}</div></details><p class="lineage">Öğrenci verisiyle kalibre edilmedi.<br>Kaynak görev: ${esc(row.source.id)}<br>Revizyon: ${esc(row.source.contentSha256)}<br>Kaynak: ${esc(d.sourceLineage.sourceId)}<br>Önerilen çıktı: ${esc(d.scope.proposedOutcomeCodes.join(' · '))} · Etkin yıl ve program kabulü bekliyor.</p></article>`;}
export function renderGrade6QuestionBankEditorView(input){
  if(arguments.length!==1)fail('invalid_question_bank_editor_arguments');
  let bank;try{bank=createGrade6QuestionReviewBank(input);}catch{fail('invalid_question_bank_editor_input');}
  const html=`<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'none'; img-src 'none'; media-src 'none'; connect-src 'none'; base-uri 'none'; form-action 'none'"><title>Soru atölyesi · Beş farklı düşünme yolu</title><style>${STYLE}</style></head><body><main><header><p class="eyebrow">Soru atölyesi · 6. sınıf matematik adayı</p><h1>Aynı soruyu çoğaltma.<br>Farklı düşünme yollarını dene.</h1><p>Konudan çok soru biçimine odaklanan editör incelemesi</p><p class="counts">2 yeni soru · 3 mevcut görev · 5 farklı aile · 0 yeni konu anlatımı</p></header><nav aria-label="Soru ailesi dizini">${TITLES.map((title,i)=>`<a href="#question-${i+1}">${i+1} · ${title}</a>`).join('')}</nav><aside aria-label="İnceleme sınırları"><p>Bu belge yanıt içeren editör incelemesidir; öğrenci teslimi veya kimlik doğrulanmış sınav değildir. Kapalı çözümler cevap güvenliği sağlamaz.</p><p>Kabul edilmiş ve yayımlanmış soru: 0. Seçenekler, satırlar ve aktarım örnekleri ayrı soru sayılmaz. Zorluk dağılımı henüz ölçülmedi; tam bir sınav veya ünite kapsamı iddia edilmez.</p></aside>${bank.items.map(question).join('')}<footer><p>Beş görev ayrı matematik denetiminden geçti. Program, yaş, zorluk, erişilebilirlik ve uzman kabulü bekliyor. Bu dilimde canlı üretici, ses veya video çağrısı yapılmadı.</p><p class="lineage">Banka revizyonu: ${esc(bank.contentSha256)}</p></footer></main></body></html>`;
  const htmlBytes=Buffer.byteLength(html);if(htmlBytes>131072)fail('question_bank_editor_output_budget');
  const manifest={schemaVersion:'grade6-question-bank-editor-view-manifest/v1',state:'partial_editor_inventory',
    reviewContentSha256:bank.contentSha256,htmlSha256:createHash('sha256').update(html).digest('hex'),htmlBytes,
    newAuthoredQuestions:2,existingDraftsReused:3,newLessonDerivatives:0,publishedQuestions:0,closedAnswerSections:5,
    providerCallsMade:0,audioGenerated:false,videoRendered:false,hiddenDetailsAreLearnerSecurity:false,
    answerBearingEditorArtifact:true,nativeVisualReviewPassed:false,accessibilityPassed:false,learnerReady:false,
    publicationReady:false,productionReady:false,serializedHashIsAuthority:false};
  return Object.freeze({html,manifest:Object.freeze(manifest)});
}
