// Fixed original editorial seeds. This is not a model provider, JEV generator,
// publication authority, curriculum completeness claim, or learner measurement.
const CURRENT_SHA='a56aab9c648f8293341be3f70c0b49e644ecb1d56be9fcaa200d6419bf1eeb97';
const LEGACY_SHA='3a8aa21327083bf15c33b9c404f299ff784b11d26024522a8c24b61387c8c0c1';
const LETTERS=['A','B','C','D'];
const JEV_LEVEL={easy:'KAVRAMA',medium:'UYGULAMA',hard:'LGS_YENI_NESIL',very_hard:'SEKIL_VE_OLIMPIYAT'};
const INTENT_NAMES={remember:'hatırlama',understand:'anlama',apply:'uygulama',analyze:'çözümleme',evaluate:'değerlendirme'};
const DIFFICULTY_NAMES={easy:'kolay',medium:'orta',hard:'zor',very_hard:'çok zor'};
// These literal editorial notes explain the task demand and estimated load.
// They are not difficulty calibration, Bloom measurement or expert acceptance.
const AUTHORING_NOTES={
  force_opposed_arrows:[
    ['Karşıt 7 N ve 3 N etiketlerini karşılaştırıp bileşke yönü ile dengeyi birlikte yorumlama.','İki okun büyüklüğünü doğrudan kıyaslama ve yön-denge çiftini seçme; başlangıç hareketi hakkında çıkarım gerekmiyor.'],
    ['Karşıt 8 N ve 8 N kuvvetlerde eşitliği sıfır bileşke ve denge ilişkisiyle ayırma.','Eşit ok etiketlerini iki denge iddiasıyla karşılaştırma; kuvvet bilgisini verilmemiş durma-hareket bilgisinden ayrı tutma.']],
  reflection_normal:[
    ['Normalden verilen 35° gelme açısını yansıma kuralına uygulama.','Tek verilen açı ve tek eşitlik ilişkisi; 55° yüzey açısı ile 70° iki ışın açısı çeldiricilerini ayırma.'],
    ['Normalden verilen 55° ile aynaya dik 90° referansını ayrı kullanarak doğru açı etiketini tamamlama.','İki farklı açı referansı arasından ışına ait 55° etiketi seçme; yüzey ve iki ışın toplamı seçeneklerini eleme.']],
  circuit_fair_variable:[
    ['Tel uzunluğu hedefi için 10 ve 20 cm satırlarını kalınlık, madde ve pil koşullarından ayırma.','Dört devrenin uzunluk, kalınlık, madde ve pil sütunlarını kıyaslama; tek değişkenli çifti seçme.'],
    ['Tel kalınlığı hedefinde 15 cm sabit uzunluğu, bakır maddesini ve tek pil koşulunu koruyan satır çiftini ayırma.','Dört devrede kalınlığı, 25 cm uzunluk farkını ve demir-bakır farkını birlikte denetleme.']],
  density_displacement:[
    ['20→24 ve 20→28 mL hacim artışlarını eşit kütleli iki katının yoğunluk karşılaştırmasında kullanma.','İki ayrı hacim artışını hesaplama, ardından eşit kütlede hacim-yoğunluk yönünü karşılaştırma.'],
    ['30→39 ve 10→13 mL hacim artışlarını başlangıç su miktarlarından ayırıp eşit kütle koşuluyla karşılaştırma.','Başlangıç düzeyleri 30 ve 10 mL olan iki kaptan ayrı artış çıkarma; son seviyeyi doğrudan katı hacmi sanma hatasını eleme.']],
  phase_identification:[
    ['Isıtma sırasındaki 60 °C katı-sıvı birlikteliğini önceki katı ve sonraki sıvı gözlemleriyle ilişkilendirme.','Dört gözlemden tekrar eden sıcaklığı ve iki hâli ayırma; ısıtma yönünü olay adıyla birleştirme.'],
    ['Soğutma sırasındaki 85 °C sıvı-katı birlikteliğini gözlem sırası ve enerji aktarım yönüyle ayırma.','95, 85, 85 ve 75 °C kayıtlarında soğutma yönünü koruma; aynı iki hâlin erime-donma ayrımını yapma.']],
  ice_water_density:[
    ['Yüzen buz kanıtını eşit hacimli buz ve su örneklerinin kütle ilişkisiyle yorumlama.','Eşit hacim koşulunda kütle ve yoğunluk yargılarını aynı seçenekte tutarlı eşleştirme.'],
    ['Madde kaybı olmayan donmada eşit kalan kütleyi değişen hacim ve yoğunluktan ayırma.','Kapalı kapta aynı kütle ve genleşme boşluğu koşullarını koruyup iki niceliğin nitel değişimini karşılaştırma.']],
  germination_control:[
    ['Su hedefi için dört tohum düzeneğinde hava, sıcaklık ve tohum sayısı farklarını ayırma.','10 ve 20 tohumlu satırları su-hava koşullarıyla karşılaştırma; henüz ölçülmemiş sonucu varsaymadan deney çifti seçme.'],
    ['Hava hedefi için her birinde 12 tohum bulunan satırlarda su ve sıcaklığı sabit tutan çifti ayırma.','Dört satırın hava, su ve ılık-soğuk koşullarını denetleme; tohum sayısının her düzende 12 olduğunu kullanma.']],
  reproduction_comparison:[
    ['Hidradaki gövde çıkıntısı ve ayrılma mekanizmasını üreme tipi ve hücre birleşmesi bakımından sınıflandırma.','Tek tomurcuklanma mekanizmasını iki kavramla eşleştirme; yalnız canlı adına göre genelleme yapmama.'],
    ['Çiçekli bitkide açıkça verilen erkek-dişi üreme hücresi birleşmesini tohum oluşumunun üreme türüyle eşleştirme.','Döllenme ve tohum oluşumu sırasını koruyup üreme türü-hücre birleşmesi çiftini seçme.']],
  biodiversity_evidence:[
    ['Eşit alan ve aynı yöntemle kaydedilen çam-meşe ile yalnız çam listelerinde gözlenen farklı türleri ayırma.','İki gözlem listesinin farklı adlarını sayma; sınırlı kaydı bütün ekosistem hakkında hükme dönüştürmeme.'],
    ['Çam-çam-meşe kaydındaki tekrarı çam-meşe-ardıç listesiyle karşılaştırıp birey sayısı ile tür sayısını ayırma.','Üçer birey içeren iki listede tekrar eden tür adını eleme; eşit birey sayısının eşit tür zenginliği olmadığını değerlendirme.']],
  work_direction:[
    ['Sağa uygulanan tek kuvveti yukarı yer değiştirmeyle karşılaştırarak yalnız incelenen kuvvetin iş koşulunu kullanma.','İki dik yönü ayırma ve kutunun hareketini bütün kuvvetlerin iş yaptığı genellemesine dönüştürmeme.'],
    ['Sola çekme kuvveti ve sola yer değiştirmeyi mekanik işin nitel koşuluyla eşleştirme.','İki aynı yönü tek kuvvet için doğrudan ilişkilendirme; sayısal iş veya süre hesabı gerekmiyor.']],
  kinetic_potential_transform:[
    ['Yükseklik azalması ve sürat artışını, yalnız yer çekimli ideal inişin toplam mekanik enerjisinden ayrı yorumlama.','İnişte potansiyel, kinetik ve toplam enerjiye ait üç nitel yargıyı aynı ideal koşul altında denetleme.'],
    ['İlk hareket sonrası yükseliş ve yavaşlamayı sürtünmesiz yer çekimi modelinin korunum koşuluyla birlikte ayırma.','Yükseliş-yavaşlama ilişkisinde iki enerji türünün ters değişimini toplam korunumdan ayrı tutma; üç iddialı seçenekleri kıyaslama.']],
  refraction_path:[
    ['Havadan suya geçen eğik ışında ortam sırası ve normali nitel ışık yolu-sürat kuralına uygulama.','Gelen ışın, normal ve iki ortamdan iki nitel sonuç çıkarma; sayısal kırılma bağıntısı gerekmiyor.'],
    ['Sudan havaya geçtiği açıkça verilen eğik ışında ters ortam sırasını yol ve sürat yorumuna uygulama.','Ters geçişte normal ilişkisi ve sürat yönünü birlikte koruma; geçmeyen ışın veya sınır açısı hakkında hesap gerekmiyor.']],
  particle_element_compound:[
    ['Üç aynı X-Y bağlı grubunda tanecik adedi, tanecik tipi ve atom türü sayılarını ayrı inceleme.','Aynı bağlı grubun üç kez çizildiğini fark etme; farklı atom türünü farklı tanecik tipiyle karıştırmama.'],
    ['İki X-X bağlı grubundaki tek atom türünü tanecik adedinden ayırarak saf maddeyi sınıflandırma.','İki atomlu ve iki kez tekrarlanan aynı yapıda atom türü, atom adedi ve tanecik tipi ayrımını koruma.']],
  dissolution_fair_test:[
    ['Su sıcaklığı hedefinde soğuk-ılık farkını karıştırma, tanecik büyüklüğü ve 100 mL su koşullarından ayırma.','Dört şeker düzeneğinde sıcaklık, karıştırma ve ince-iri farklarını denetleme; ölçülmemiş çözünme süresini uydurmama.'],
    ['Karıştırma hedefinde ılık su ve ince şekeri koruyup 150-200 mL su farkını ayrı eleme.','Dört satırdan hem sıcaklığı hem su miktarını sabit tutan tek karıştırma çiftini seçme.']],
  separation_method:[
    ['Uçucu olmayan çözünmüş tuzu kapta geri kazanma hedefini ayırma yöntemiyle eşleştirme.','Geri kazanılan bileşen yalnız tuzken çözünmüş maddeyi kuru katı süzme-eleme yöntemlerinden ayırma.'],
    ['Tuz-su örneğinde suyu ayrı kapta toplama hedefini buharı yoğuşturabilen yöntemle eşleştirme.','Su hedefi için buharlaştırma ile buharı toplama-yoğuşturma arasındaki farkı koruma; gerçek ısıtma uygulaması gerekmiyor.']],
  digestion_route:[
    ['Beş seçilmiş sindirim organını ağızdan kalın bağırsağa göreli besin yolu sırasıyla eşleştirme.','Beş organ kartında iki yer değiştirme çeldiricisini ayırma; bütün anatomik yapıların listelendiğini varsaymama.'],
    ['Karışık beş karttan yalnız mide ile kalın bağırsak arasındaki istenen alt yolu seçme.','Başlangıç ve bitiş sınırlarını beş kart üzerinde uygulama; ağızdan başlayan tam listeyi istenen aralık sanmama.']],
  circulation_route:[
    ['Akciğerde oksijen zenginleşmesi amacını kalp-akciğer-kalp yolu ve küçük dolaşım adıyla eşleştirme.','Üç basit organ-bölge etiketiyle tek amacı ve dolaşım adını yorumlama; özel damar veya odacık ayrıntısı gerekmiyor.'],
    ['Kalpten vücuda dağıtım ve geri dönüş amacını büyük dolaşımın basit yoluyla eşleştirme.','Akciğer amacından farklı vücuda dağıtım amacını yol ve ad çiftinde koruma; dolaşım türlerini ters adlandırmayı eleme.']],
  food_web_roles:[
    ['Besinden tüketene giden okta çekirgenin doğrudan besinini ve üreticiden sonraki basamağını ayırma.','Ot-çekirge-kurbağa zincirinde hedefe gelen tek oku ve üretici bilgisini birlikte kullanma.'],
    ['Aynı zincirde işaretli kurbağanın doğrudan besinini, aradaki çekirgeyi atlamadan tüketici basamağıyla ilişkilendirme.','İki oklu zincirde kurbağaya gelen okla ikinci tüketici basamağını ayırma; üretici otu doğrudan besin sanmayı eleme.']],
  solid_pressure_control:[
    ['Eşit ağırlıklı K ve L kutularında farklı temas alanının katı basıncına etkisini ayırma.','Ağırlığı sabit tutup tek alan sırasının nitel basınç etkisini kıyaslama; formül veya basınç hesabı gerekmiyor.'],
    ['Eşit temas alanlı K ve L kutularında farklı ağırlığın katı basıncına etkisini ayırma.','Bu kez alanı sabit tutup tek ağırlık sırasını nitel basınçla ilişkilendirme; önceki alan değişkenini yanlış aktarmama.']],
  liquid_depth_control:[
    ['Aynı suda ve aynı kapta yüzeyden farklı derinlikleri sıvı basıncı bakımından ayırma.','Yalnız daha derin-daha sığ sırasını aynı sıvı koşuluyla kıyaslama; sayısal derinlik ve basınç hesabı gerekmiyor.'],
    ['Farklı genişlikli açık kaplarda aynı su ve eşit yüzey derinliği kanıtını kap biçiminden ayırma.','Verilen kap genişliği farkını ilgili derinlik ve sıvı koşullarından eleme; verilmemiş sayısal bağıntı kullanmama.']],
  machine_work_tradeoff:[
    ['İdeal hareketli makarada kuvvet kolaylığını çekilen yol ve aynı yükün aynı yüksekliğe taşınma işinden ayrı yorumlama.','İdeal koşulda kuvvet, yol ve toplam işe ait üç yargıyı beraber denetleme; kuvvet kazancını iş kazancı sanmayı eleme.'],
    ['İdeal sabit makaranın yön değiştirmesini kuvvet büyüklüğü, çekme yolu ve işten kazanç iddialarından ayırma.','Aşağı çekilen ip ile yukarı çıkan yük yönlerini nitel kuvvet-yol-iş sonuçlarından ayrı tutma; hareketli makara kuralını aktarmama.']],
  periodic_pattern:[
    ['K, L ve M etkinlik etiketlerinde aynı grup numarasını aynı sütun kuralıyla eşleştirme.','Üç kartın iki koordinatından yalnız grup sütununu seçme; gerçek element özellikleri hakkında çıkarım gerekmiyor.'],
    ['Aynı üç konum kartında bu kez periyot numarasını yatay satır kuralına uygulama.','Grup çiftinden farklı istenen periyot çiftini iki koordinat arasında seçme; doğru fakat sorulmamış sütun çiftini eleme.']],
  pH_classification:[
    ['Sulu çözeltinin ölçülen pH 3 değerini nötr 7 eşiğiyle sınıflandırma kuralına uygulama.','Tek ölçüm ve tek eşik karşılaştırması; tatma, koklama, denklem veya madde adı tahmini gerekmiyor.'],
    ['pH 10 ölçümünü 7 eşiğinin üstünde sınıflandırıp nötr veya asidik seçeneklerden ayırma.','İki basamaklı verilen sayıyı tek eşikle kıyaslama; bazın gücü veya güvenliği hakkında ek yargı gerekmiyor.']],
  chemical_new_substance:[
    ['Bilinen demir paslanmasını yeni madde oluşumu ölçütüyle fiziksel-kimyasal değişim sınıfına eşleştirme.','Tek bilinen olayda değişim türü ve yeni madde iddialarını birlikte yorumlama; her renk değişimine genelleme yapmama.'],
    ['Hâlâ kâğıt olduğu belirtilen yırtık parçaları madde türü ile parça sayısını ayırarak sınıflandırma.','Görünür parça artışını yeni madde sayısı sanmadan iki sınıflandırma iddiasını eşleştirme; yakma veya tepkime eklememe.']],
  one_trait_cross:[
    ['Aa ve Aa ebeveynlerin dört eş olasılıklı alel birleşimini tam baskınlıkta görünüm sayılarına ayırma.','Aa × Aa için dört hücre oluşturma ve baskın-çekinik görünümü ayrı sayma; gerçek dört yavruyu garanti eden yorumdan kaçınma.'],
    ['Aa ve aa ebeveynlerde dört birleşimin baskın görünüm ve heterozigot genotip paylarını ayrı inceleme.','Aa × aa çaprazında dört hücreyi sayarken görünüm ve heterozigot genotipi ayırma; iki ayrı Aa hücresini tek saymama.']],
  mutation_modification:[
    ['Çevreye bağlı görünüm değişimini değişmeyen DNA dizisinden ayırıp olay sınıfı ve kalıtsallık iddiasını ilişkilendirme.','Çevre, görünüm ve DNA için üç kanıtı aynı kurgusal olayda ayırma; görünümü doğrudan mutasyon sanmayı eleme.'],
    ['Görünüm değişmediği hâlde üreme hücresindeki DNA değişimini sınıf ve aktarılabilme olasılığı bakımından ayrı yorumlama.','Görünür belirtiyi DNA kanıtından ve olabilirliği gerçekleşmiş aktarımdan ayırma; iki ayrı kavramsal karışıklığı eleme.']],
  photosynthesis_control:[
    ['Işık hedefi için aynı tür bitki satırlarında karbondioksit, su ve bitki sayısını sabit tutan çifti ayırma.','Dört düzende ışık, karbondioksit ve 1-2 bitki farklarını denetleme; ölçülmemiş fotosentez ürün miktarını varsaymama.'],
    ['İkişer aynı tür bitkide karbondioksit hedefini ışık ve su koşulları değişiminden ayırma.','Dört satırda düşük-normal karbondioksiti tek değişken olarak seçme; ek ışık veya su farkı içeren çiftleri eleme.']],
};
const authored=[];
const choice=(text,claims,why)=>({text,assertions:Object.entries(claims).map(([key,equals])=>({key,equals})),why});
function family(def,variants){
  // Each literal pair is authored below. There is no count or parameter API.
  for(const [offset,v] of variants.entries()){
    const variant=offset+1,index=authored.length,correctAt=index%4;
    const ordered=[...v.choices];const first=ordered.shift();ordered.splice(correctAt,0,first);
    const options=Object.fromEntries(LETTERS.map((key,i)=>[key,ordered[i].text]));
    const choices=Object.fromEntries(LETTERS.map((key,i)=>[key,{assertions:ordered[i].assertions}]));
    const correctOption=LETTERS[correctAt];
    const sourceId=def.grade===8?'legacy-2018-fen-bilimleri':'tymm-current-fen-bilimleri';
    const difficulty=v.difficulty??'medium',intent=v.intent??def.intent??'apply';
    const [demand,load]=AUTHORING_NOTES[def.familyId][offset];
    const reasoning={given:v.given,wanted:v.wanted,whyStrategy:def.strategy,
      steps:[{because:def.rule,action:def.action,result:v.result,meaning:v.meaning},
        {because:v.reason??def.rule,action:'Bulduğun yargıyı seçeneklerin bütün ifadeleriyle karşılaştır.',result:`Verilen koşulların tamamını ${correctOption} seçeneği karşılar.`,meaning:'Tek bir doğru sözcük değil, seçeneğin bütün iddiaları doğrulanmalıdır.'}],
      check:v.check??def.check,shortTip:def.tip};
    authored.push({id:`SCI-G${def.grade}-${def.familyId}-V${variant}`,grade:def.grade,branch:def.branch,
      familyId:def.familyId,variant,topic:def.topic,outcomeCode:def.code,
      source:{sourceId,pdfSha256:def.grade===8?LEGACY_SHA:CURRENT_SHA,physicalPdfPage:def.page,pageEvidenceId:`${sourceId}:p${def.page}`},
      cognitiveIntent:{level:intent,knowledgeDimension:def.knowledge??'conceptual',evidence:demand,
        rationale:`Yazarın ${INTENT_NAMES[intent]} düzeyi önerisinin dayanağı: ${demand} İşlem: ${def.action} Bu bir görev talebi etiketidir; öğrenci gelişimi ölçümü veya uzman kabulü değildir.`},
      difficulty:{level:difficulty,rationale:`${load} ${def.grade}. sınıf için ${DIFFICULTY_NAMES[difficulty]} düzeyi yazar tahminidir; öğrenci verisiyle kalibre edilmedi.`,estimatedOnly:true},
      question:{grade:def.grade,topic:def.topic,branch:def.branch,outcomeCode:def.code,stimulus:v.given,stem:v.wanted,options,correctOption,
        solutionStrategy:def.strategy,detailedSolution:`${def.strategy} ${v.result} ${v.reason??def.rule} Doğru seçenek ${correctOption}.`,
        distractors:Object.fromEntries(LETTERS.filter(k=>k!==correctOption).map(k=>[k,ordered[LETTERS.indexOf(k)].why])),difficultyJEV:JEV_LEVEL[difficulty]},
      model:{kind:def.kind,task:def.task,inputs:v.inputs,choices},
      visualSpec:{kind:def.kind,modelRef:'model.inputs',alt:v.alt??`${def.topic} için verilen durumlar. ${v.given}`},reasoning});
  }
}

family({grade:6,branch:'physics',familyId:'force_opposed_arrows',topic:'Aynı doğrultuda kuvvet ve denge',code:'FB.6.2.1',page:116,kind:'force_work_board',task:'opposed_force',
  rule:'Zıt yönlü aynı doğrultudaki kuvvetler karşılaştırılır; eşit büyüklükteyseler bileşke sıfırdır.',
  strategy:'Önce okların yönünü ayır; sonra sağa ve sola etki eden büyüklükleri karşılaştır. Hareketin hızını yalnız bu verilerden çıkarma.',
  action:'Sağ ve sol yönlü kuvvetleri ayrı değerlendir.',tip:'Okun boyunu tahmin etme; üzerindeki büyüklük etiketini oku.',check:'Yönü daha büyük kuvvetle, dengeyi büyüklüklerin eşitliğiyle yeniden kontrol et.'},[
  {inputs:{arrows:[{direction:'right',magnitude:7},{direction:'left',magnitude:3}]},
    given:'Bir oyuncak arabaya aynı doğrultuda sağa 7 N, sola 3 N kuvvet uygulanıyor. Oklar yalnız bu iki kuvveti gösteriyor; arabanın başlangıç hareketi bilinmiyor.',
    wanted:'Bu kuvvetlerin bileşkesi ve denge durumu için hangi yargı doğrudur?',result:'Sağa etki eden kuvvet daha büyüktür; bileşke sağa yönelir ve kuvvetler dengelenmez.',meaning:'Bileşke yönü başlangıçtaki hareket yönü veya sabit hız bilgisi değildir.',difficulty:'easy',intent:'understand',
    choices:[choice('Bileşke sağadır; kuvvetler dengelenmemiştir.',{resultantDirection:'right',balanced:false},''),choice('Bileşke soladır; kuvvetler dengelenmemiştir.',{resultantDirection:'left',balanced:false},'Daha büyük olan sağ kuvvetin yönü gözden kaçırılmıştır.'),choice('Bileşke sıfırdır; kuvvetler dengelenmiştir.',{resultantDirection:'none',balanced:true},'Zıt yönlü olmak eşit büyüklükte olmak değildir.'),choice('Bileşke sağadır; kuvvetler dengelenmiştir.',{resultantDirection:'right',balanced:true},'Sıfır olmayan bileşke ile denge iddiası çelişir.')]},
  {inputs:{arrows:[{direction:'right',magnitude:8},{direction:'left',magnitude:8}]},
    given:'Bir kutuya aynı doğrultuda karşılıklı iki ip üzerinden 8 N sağa ve 8 N sola kuvvet uygulanıyor. Kutunun başlangıçta durduğu veya hareket ettiği belirtilmiyor.',
    wanted:'Yalnız kuvvet oklarına bakarak hangi denge yargısına ulaşılabilir?',result:'İki karşıt kuvvet eşittir; bileşke sıfır ve kuvvetler dengelenmiştir.',meaning:'Dengelenmiş kuvvetler, başlangıç hareketi verilmeden kutunun mutlaka durduğu anlamına gelmez.',intent:'analyze',
    choices:[choice('Bileşke sıfırdır; kuvvetler dengelenmiştir.',{resultantDirection:'none',balanced:true},''),choice('Bileşke sağadır; kuvvetler dengelenmemiştir.',{resultantDirection:'right',balanced:false},'Eşit karşıt kuvvetlerden bir yön seçilemez.'),choice('Bileşke soladır; kuvvetler dengelenmiştir.',{resultantDirection:'left',balanced:true},'Dengelenmiş durumda yönlü bir bileşke yoktur.'),choice('Bileşke sıfırdır; kuvvetler dengelenmemiştir.',{resultantDirection:'none',balanced:false},'Sıfır bileşke ile dengelenmemiş kuvvet iddiası çelişir.')]},
]);
family({grade:6,branch:'physics',familyId:'reflection_normal',topic:'Yansıma ve normal',code:'FB.6.4.2',page:127,kind:'ray_path',task:'reflection_normal',
  rule:'Düz aynada gelme ve yansıma açıları yüzeye dik normalden ölçülür ve birbirine eşittir.',strategy:'Önce hangi doğrunun normal olduğunu belirle; yüzeyle yapılan açıya geçmeden normal açılarını eşleştir.',
  action:'Verilen gelme açısını normalden ölçülen yansıma açısıyla eşleştir.',tip:'Açı normalden ölçülüyorsa gelme açısı ile yansıma açısı aynıdır.',check:'Açının aynadan değil normalden ölçüldüğünü ve iki ışının farklı taraflarda olduğunu kontrol et.'},[
  {inputs:{incidentAngleNormal:35},given:'Bir ışın düz aynaya, aynaya dik çizilen normalle 35° açı yaparak geliyor. Çizimde yalnız ayna, normal ve gelen ışın bulunuyor.',wanted:'Yansıyan ışının normalle yaptığı açı kaç derecedir?',result:'Normalden ölçülen yansıma açısı 35° olur.',meaning:'Yüzeyle oluşan tamamlayıcı açı, yansıma açısının yerine kullanılamaz.',difficulty:'easy',
    choices:[choice('35°',{reflectionAngleNormal:35},''),choice('55°',{reflectionAngleNormal:55},'Normal açısı yerine yüzey açısı seçilmiştir.'),choice('70°',{reflectionAngleNormal:70},'İki ışın arasındaki açı yansıma açısıyla karıştırılmıştır.'),choice('90°',{reflectionAngleNormal:90},'Normalin yüzeye dikliği, ışının normal açısı değildir.')]},
  {inputs:{incidentAngleNormal:55},given:'Bir öğrencinin düz ayna çiziminde gelen ışın ile normal arasındaki açı 55° olarak işaretleniyor. Aynayla normal arasındaki dik açı ayrıca gösteriliyor.',wanted:'Bu çizimi tamamlayan öğrenci yansıma açısı etiketine hangi değeri yazmalıdır?',result:'Yansıma açısı 55° yazılmalıdır; iki açı aynı normalden ölçülür.',meaning:'Dik açı işareti referans doğrularını gösterir; ışının açısını değiştirmez.',
    choices:[choice('55°',{reflectionAngleNormal:55},''),choice('35°',{reflectionAngleNormal:35},'Yüzey açısı doğru etiketin yerine geçirilmiştir.'),choice('110°',{reflectionAngleNormal:110},'Gelme ve yansıma açıları toplamı tek yansıma açısı değildir.'),choice('90°',{reflectionAngleNormal:90},'Normalin aynaya dik oluşu her ışının dik geldiğini göstermez.')]},
]);
const VARIABLE_LABELS={length:'tel uzunluğu',thickness:'tel kalınlığı',water:'su koşulu',air:'hava koşulu',waterTemperature:'su sıcaklığı',stirring:'karıştırma',light:'ışık',carbonDioxide:'karbondioksit koşulu'};
const pairChoices=(pair,variable)=>[
  choice(`${pair}: Yalnız ${VARIABLE_LABELS[variable]} değişir.`,{fairPair:pair,changedVariable:variable},''),
  choice(`R1-R3: Yalnız ${VARIABLE_LABELS[variable]} değişir.`,{fairPair:'R1-R3',changedVariable:variable},'Bu iki düzenekte hedef dışında başka özellikler de farklıdır.'),
  choice(`R1-R4: Yalnız ${VARIABLE_LABELS[variable]} değişir.`,{fairPair:'R1-R4',changedVariable:variable},'Bu karşılaştırma hedef değişkeni tek başına sınamaz.'),
  choice(`R3-R4: Yalnız ${VARIABLE_LABELS[variable]} değişir.`,{fairPair:'R3-R4',changedVariable:variable},'Birden fazla fark neden-sonuç yorumunu belirsizleştirir.')];
family({grade:6,branch:'physics',familyId:'circuit_fair_variable',topic:'İletken telde kontrollü deney',code:'FB.6.6.2',page:138,kind:'experiment_board',task:'fair_test',intent:'analyze',knowledge:'procedural',
  rule:'Bir tel özelliğinin etkisi araştırılırken pil, ampul ve diğer tel özellikleri aynı tutulur.',strategy:'Önce araştırılan tel özelliğini bul; sonra diğer sütunları eşit olan iki düzeneği seç.',action:'Her deney çiftinde hedef dışındaki özellikleri satır satır karşılaştır.',
  tip:'Sonucu yorumlamadan önce deneyin adil olup olmadığını denetle.',check:'Seçtiğin iki devrede yalnız hedef tel özelliğinin farklı kaldığını kontrol et.'},[
  {inputs:{targetVariable:'length',rows:[{id:'R1',length:10,thickness:'thin',material:'copper',batteryCount:1},{id:'R2',length:20,thickness:'thin',material:'copper',batteryCount:1},{id:'R3',length:20,thickness:'thick',material:'copper',batteryCount:1},{id:'R4',length:10,thickness:'thin',material:'copper',batteryCount:2}]},
    given:'Özdeş ampullerle kurulan devre tablosunda tel uzunlukları 10 veya 20 cm olarak, kalınlıklar ince veya kalın olarak verilmiştir. R1:10/ince/bakır/1 pil; R2:20/ince/bakır/1 pil; R3:20/kalın/bakır/1 pil; R4:10/ince/bakır/2 pil.',wanted:'Tel uzunluğunun ampul parlaklığına etkisini tek değişkenle araştırmak için hangi devre çifti seçilmelidir?',result:'R1 ve R2 yalnız tel uzunluğunda farklıdır; kalınlık, madde ve pil sayısı aynıdır.',meaning:'Bu seçim deney tasarımını doğrular; ölçülmemiş parlaklık değerini uydurmaz.',choices:pairChoices('R1-R2','length')},
  {inputs:{targetVariable:'thickness',rows:[{id:'R1',length:15,thickness:'thin',material:'copper',batteryCount:1},{id:'R2',length:15,thickness:'thick',material:'copper',batteryCount:1},{id:'R3',length:25,thickness:'thick',material:'copper',batteryCount:1},{id:'R4',length:15,thickness:'thin',material:'iron',batteryCount:1}]},
    given:'Özdeş ampul ve piller kullanılan dört devrede R1:15 cm/ince/bakır; R2:15 cm/kalın/bakır; R3:25 cm/kalın/bakır; R4:15 cm/ince/demir tel vardır. Her devrede bir pil bulunur.',wanted:'Tel kalınlığına odaklanan bir araştırmada diğer tel özellikleri aynı kalan hangi iki devre karşılaştırılmalıdır?',result:'R1 ve R2 karşılaştırılır; yalnız kalınlık değişmektedir.',meaning:'Uzunluk veya madde değişirse parlaklıktaki fark tek başına kalınlığa bağlanamaz.',choices:pairChoices('R1-R2','thickness')},
]);
family({grade:6,branch:'chemistry',familyId:'density_displacement',topic:'Yer değiştirme ile hacim ve yoğunluk',code:'FB.6.5.3',page:132,kind:'matter_cards',task:'density_displacement',intent:'analyze',knowledge:'procedural',
  rule:'Tamamen batan, çözünmeyen katının hacmi taşma olmayan ölçekte su düzeyinin artışıdır; eşit kütlede daha küçük hacim daha büyük yoğunluk verir.',strategy:'Başlangıç ve son su düzeyini ayır; iki eşit kütlenin kapladığı hacimleri karşılaştır.',action:'Her katı için son düzeyden başlangıç düzeyini çıkar, ardından eşit kütle koşulunu kullan.',
  tip:'Dereceli kapta okunan son değer katının tek başına hacmi değildir.',check:'Katıların tamamen battığını, çözünmediğini, taşma olmadığını ve kütlelerin eşit olduğunu yeniden kontrol et.'},[
  {inputs:{equalMass:true,fullySubmerged:true,insoluble:true,samples:[{id:'K',before:20,after:24},{id:'L',before:20,after:28}]},given:'Eşit kütleli K ve L katıları ayrı dereceli kaplarda tamamen suya batırılıyor; çözünme ve taşma olmuyor. K için su 20 mL’den 24 mL’ye, L için 20 mL’den 28 mL’ye yükseliyor.',wanted:'Ölçüm verilerine göre hangi katının yoğunluğu daha büyüktür?',result:'K hacmi 4 mL, L hacmi 8 mL’dir; kütleler eşit olduğu için K daha yoğundur.',meaning:'Yoğunluk karşılaştırmasında suyun başlangıç hacmi değil katının yer değiştirdiği hacim kullanılır.',
    choices:[choice('K katısı',{denserSample:'K'},''),choice('L katısı',{denserSample:'L'},'Eşit kütlede büyük hacim yoğunluğu büyütmez.'),choice('Yoğunlukları eşittir.',{denserSample:'equal'},'Eşit kütle, hacimler farklıyken eşit yoğunluk demek değildir.'),choice('Verilen ölçümlerle K ve L’nin yoğunlukları karşılaştırılamaz.',{denserSample:'neither'},'Eşit kütle ve iki hacim artışı karşılaştırma için yeterlidir.')]},
  {inputs:{equalMass:true,fullySubmerged:true,insoluble:true,samples:[{id:'K',before:30,after:39},{id:'L',before:10,after:13}]},given:'Bir araştırmada eşit kütleli K ve L çözünmeyen katıları tamamen suya batırılıyor. Taşma yoktur. K kabında 30→39 mL, L kabında 10→13 mL okunuyor; kapların başlangıç su miktarları farklıdır.',wanted:'Başlangıç su miktarlarını ayırarak yapılan yoğunluk karşılaştırmasında hangi katı daha yoğundur?',result:'K 9 mL, L 3 mL hacim kaplar; eşit kütlede L daha yoğundur.',meaning:'Farklı başlangıç düzeyleri, her kapta kendi artışı hesaplandığında karşılaştırmayı bozmaz.',difficulty:'hard',
    choices:[choice('L katısı',{denserSample:'L'},''),choice('K katısı',{denserSample:'K'},'Eşit kütlede büyük hacimli K’nin daha yoğun olduğu sanılmıştır; büyük hacim burada daha küçük yoğunluk verir.'),choice('Yoğunlukları eşittir.',{denserSample:'equal'},'Üç kat farklı hacimler eşit kütlede aynı yoğunluğu vermez.'),choice('K ve L’den hiçbiri seçilemez.',{denserSample:'neither'},'Tam batma, çözünmeme ve eşit kütle koşulları karşılaştırma için yeterlidir.')]},
]);
family({grade:6,branch:'chemistry',familyId:'phase_identification',topic:'Saf maddede hâl değişimi gözlemi',code:'FB.6.5.2',page:132,kind:'matter_cards',task:'phase_observation',intent:'analyze',
  rule:'Aynı basınçta saf maddenin hâl değişimi sırasında iki hâl birlikte gözlenirken sıcaklık sabit kalabilir.',strategy:'Isıtma veya soğutma yönünü ve aynı sıcaklıkta birlikte bulunan hâlleri beraber oku.',action:'Tekrar eden sıcaklık satırlarında katı-sıvı birlikteliğini belirle ve enerji aktarım yönüne göre olayı adlandır.',
  tip:'Sabit sıcaklık tek başına yetmez; hâlleri ve ısıtma-soğutma yönünü birlikte kullan.',check:'Geçiş öncesi ve sonrası hâllerin sırası ile sabit basınç ve saflık koşullarını kontrol et.'},[
  {inputs:{direction:'heating',pure:true,samePressure:true,rows:[{time:1,temperature:50,phases:['solid']},{time:2,temperature:60,phases:['solid','liquid']},{time:3,temperature:60,phases:['solid','liquid']},{time:4,temperature:70,phases:['liquid']}]},
    given:'Saf bir madde aynı basınçta ısıtılıyor. Ardışık gözlemler 1:50 °C/katı;2:60 °C/katı ve sıvı;3:60 °C/katı ve sıvı;4:70 °C/sıvı şeklindedir. Süre etiketleri gözlem sırasını gösterir.',wanted:'Tablodaki sabit sıcaklıklı bölüm hangi olay ve sıcaklıkla açıklanır?',result:'Madde 60 °C’de erir; katı ve sıvının birlikte bulunduğu geçişte sıcaklık sabittir.',meaning:'Veri saf maddenin erime gözlemini destekler; bütün ısıtma boyunca sıcaklık sabit değildir.',
    choices:[choice('60 °C’de erime',{event:'melting',eventTemperature:60},''),choice('50 °C’de erime',{event:'melting',eventTemperature:50},'50 °C satırında yalnız katı vardır; geçiş bölümü değildir.'),choice('60 °C’de donma',{event:'freezing',eventTemperature:60},'Madde ısıtılıp katıdan sıvıya geçmektedir.'),choice('70 °C’de kaynama',{event:'boiling',eventTemperature:70},'Tabloda sıvı-gaz birlikteliği yoktur.')]},
  {inputs:{direction:'cooling',pure:true,samePressure:true,rows:[{time:1,temperature:95,phases:['liquid']},{time:2,temperature:85,phases:['liquid','solid']},{time:3,temperature:85,phases:['liquid','solid']},{time:4,temperature:75,phases:['solid']}]},
    given:'Saf bir madde aynı basınçta soğutuluyor. Gözlemler 1:95 °C/sıvı;2:85 °C/sıvı ve katı;3:85 °C/sıvı ve katı;4:75 °C/katı olarak kaydediliyor.',wanted:'Soğutma yönü dikkate alındığında 85 °C’de gözlenen hâl değişimi nedir?',result:'Sıvı 85 °C’de donar; sıvı ve katının birlikte bulunduğu bölümde sıcaklık sabit kalır.',meaning:'Aynı iki hâl, enerji aktarımının yönüne göre erime veya donma olarak adlandırılır.',
    choices:[choice('85 °C’de donma',{event:'freezing',eventTemperature:85},''),choice('85 °C’de erime',{event:'melting',eventTemperature:85},'Katıdan sıvıya değil sıvıdan katıya geçilmektedir.'),choice('95 °C’de donma',{event:'freezing',eventTemperature:95},'95 °C satırında yalnız sıvı vardır.'),choice('75 °C’de yoğuşma',{event:'condensation',eventTemperature:75},'Gaz hâli gözlenmediği için yoğuşma açıklaması uygun değildir.')]},
]);
family({grade:6,branch:'chemistry',familyId:'ice_water_density',topic:'Buz ve suyun yoğunluk ilişkisi',code:'FB.6.5.5',page:132,kind:'matter_cards',task:'ice_density',intent:'understand',
  rule:'Buzun yoğunluğu sıvı sudan küçüktür; aynı kütlede buz daha büyük hacim, aynı hacimde daha küçük kütle taşır.',strategy:'Önce karşılaştırmada eşit tutulan niceliği bul; kütle eşitse hacmi, hacim eşitse kütleyi düşün.',action:'Eşitlik koşulunu koruyarak buz-su yoğunluk ilişkisini yorumla.',tip:'Eşit kütle ile eşit hacim aynı karşılaştırma değildir.',check:'Karşılaştırmanın aynı hacim mi aynı kütle mi istediğini yeniden oku.'},[
  {inputs:{scenario:'floating',comparison:'equal_volume'},given:'Bir kap suya bırakılan buzun bir bölümü suyun üstünde kalıyor. Ayrı bir karşılaştırmada aynı hacimde buz ve sıvı su örnekleri tartılıyor; sıcaklık etkisinin ayrıntısı incelenmiyor.',wanted:'Eşit hacimdeki örneklerde buzun kütlesi ve daha yoğun madde için hangi yargı uygundur?',result:'Eşit hacimde buz daha az kütlelidir; sıvı su daha yoğundur.',meaning:'Yüzme gözlemi yoğunluk ilişkisine, eşit hacim koşulu kütle karşılaştırmasına yardım eder.',difficulty:'easy',
    choices:[choice('Buz daha az kütleli; sıvı su daha yoğundur.',{iceMassAtEqualVolume:'less',denser:'water'},''),choice('Buz daha çok kütleli; buz daha yoğundur.',{iceMassAtEqualVolume:'greater',denser:'ice'},'Buz-su yoğunluk ilişkisi ters yorumlanmıştır.'),choice('Kütleler ve yoğunluklar eşittir.',{iceMassAtEqualVolume:'equal',denser:'equal'},'Eşit hacim farklı yoğunluklarda eşit kütle vermez.'),choice('Buz daha az kütleli; buz daha yoğundur.',{iceMassAtEqualVolume:'less',denser:'ice'},'İki iddia aynı hacim koşulunda birbiriyle çelişir.')]},
  {inputs:{scenario:'freezing',comparison:'equal_mass'},given:'Bir miktar saf su kapalı bir kapta donduruluyor; madde kaybı olmuyor. Donma öncesi su ve donma sonrası buz aynı kütleye sahiptir. Kapta genleşmeye yetecek boşluk vardır.',wanted:'Donma sonrası buzun hacmi ile sıvı suyun yoğunluğu birlikte nasıl karşılaştırılmalıdır?',result:'Aynı kütlede buz daha büyük hacim kaplar; sıvı su daha yoğundur.',meaning:'Kütlenin korunması hacmin de korunacağı anlamına gelmez.',
    choices:[choice('Buzun hacmi daha büyük; sıvı su daha yoğundur.',{iceVolumeAtEqualMass:'greater',denser:'water'},''),choice('Buzun hacmi daha küçük; buz daha yoğundur.',{iceVolumeAtEqualMass:'less',denser:'ice'},'Donma sırasında buzun daha küçük yoğunluklu oluşu göz ardı edilmiştir.'),choice('Hacimler eşit; yoğunluklar eşittir.',{iceVolumeAtEqualMass:'equal',denser:'equal'},'Kütlenin aynı kalması farklı hâllerde eşit hacim gerektirmez.'),choice('Buzun hacmi daha büyük; buz daha yoğundur.',{iceVolumeAtEqualMass:'greater',denser:'ice'},'Aynı kütlede büyük hacim ile büyük yoğunluk iddiaları çelişir.')]},
]);
family({grade:6,branch:'biology',familyId:'germination_control',topic:'Çimlenme için kontrollü deney',code:'FB.6.3.3',page:120,kind:'experiment_board',task:'fair_test',intent:'analyze',knowledge:'procedural',
  rule:'Bir çimlenme koşulu araştırılırken aynı tür ve sayıdaki tohumlarla diğer koşullar sabit tutulur.',strategy:'Araştırılan koşulu işaretle; tohum sayısı ve hedef dışındaki çevre koşulları aynı kalan çifti seç.',action:'Deney satırlarını hedef dışındaki sütunlarda eşleştir.',tip:'Çimlenme yüzdesini karşılaştırmadan önce tohum sayısı ve diğer koşulları kontrol et.',check:'İki düzenekte yalnız hedef koşulun değiştiğini ve aynı tür tohum kullanıldığını denetle.'},[
  {inputs:{targetVariable:'water',rows:[{id:'R1',water:'yes',air:'yes',temperature:'warm',seedCount:10},{id:'R2',water:'no',air:'yes',temperature:'warm',seedCount:10},{id:'R3',water:'no',air:'no',temperature:'warm',seedCount:10},{id:'R4',water:'yes',air:'yes',temperature:'warm',seedCount:20}]},given:'Aynı tür tohumlar dört düzeneğe konuyor. R1:su var/hava var/ılık/10 tohum; R2:su yok/hava var/ılık/10; R3:su yok/hava yok/ılık/10; R4:su var/hava var/ılık/20. Sonuçlar henüz ölçülmedi.',wanted:'Suyun çimlenmeye etkisini tek başına araştırmak için hangi düzenek çifti uygundur?',result:'R1-R2 çifti yalnız su koşulunda farklıdır; tohum sayısı, hava ve sıcaklık aynıdır.',meaning:'Uygun deney seçilir; henüz ölçülmemiş çimlenme sayısı uydurulmaz.',choices:pairChoices('R1-R2','water')},
  {inputs:{targetVariable:'air',rows:[{id:'R1',water:'yes',air:'yes',temperature:'warm',seedCount:12},{id:'R2',water:'yes',air:'no',temperature:'warm',seedCount:12},{id:'R3',water:'no',air:'no',temperature:'warm',seedCount:12},{id:'R4',water:'yes',air:'yes',temperature:'cold',seedCount:12}]},given:'Her birinde aynı türden 12 tohum bulunan dört düzenek hazırlanıyor. R1:su var/hava var/ılık; R2:su var/hava yok/ılık; R3:su yok/hava yok/ılık; R4:su var/hava var/soğuk. Tabloda yalnız hazırlık koşulları bulunuyor.',wanted:'Hava koşulunun etkisini diğer değişkenlere karıştırmadan hangi iki düzenekle sınayabiliriz?',result:'R1-R2 yalnız hava koşulunda ayrılır; su, sıcaklık ve tohum sayısı sabittir.',meaning:'R3 veya R4 seçilirse hedef dışındaki su ya da sıcaklık da değişir.',choices:pairChoices('R1-R2','air')},
]);
family({grade:6,branch:'biology',familyId:'reproduction_comparison',topic:'Üreme biçimlerini karşılaştırma',code:'FB.6.3.1',page:120,kind:'biology_graph',task:'reproduction_compare',intent:'understand',
  rule:'Tomurcuklanmada üreme hücrelerinin birleşmesi yoktur; döllenmeyle oluşan tohumda bu birleşme vardır.',strategy:'Canlı adından tahmin yürütmek yerine anlatılan üreme mekanizmasına bak.',action:'Üreme hücrelerinin birleşip birleşmediğini yöntem bilgisinden belirle.',tip:'Yeni bir canlı oluşması her durumda eşeyli üreme demek değildir.',check:'Yeni bireyin oluşmasıyla döllenmenin varlığını ayrı sorular olarak kontrol et.'},[
  {inputs:{method:'budding'},given:'Bir hidranın gövdesinde küçük bir çıkıntı büyüyor; gelişen yeni birey daha sonra ayrılıyor. Olayda iki üreme hücresinin birleşmesi anlatılmıyor.',wanted:'Bu mekanizma için üreme tipi ve döllenme bakımından hangi sınıflandırma uygundur?',result:'Tomurcuklanma eşeysiz üremedir; üreme hücrelerinin birleşmesi yoktur.',meaning:'Anahtar ipucu çıkıntının büyüyüp yeni birey oluşmasıdır; birey sayısının artması tek başına türü belirlemez.',difficulty:'easy',
    choices:[choice('Eşeysiz; üreme hücreleri birleşmez.',{reproductionType:'asexual',gameteFusion:false},''),choice('Eşeyli; üreme hücreleri birleşir.',{reproductionType:'sexual',gameteFusion:true},'Tomurcuklanma döllenmeyle karıştırılmıştır.'),choice('Eşeysiz; üreme hücreleri birleşir.',{reproductionType:'asexual',gameteFusion:true},'Mekanizma ile birleşme iddiası çelişir.'),choice('Eşeyli; üreme hücreleri birleşmez.',{reproductionType:'sexual',gameteFusion:false},'Bu olayda eşeyli üremenin hücre birleşmesi gösterilmemiştir.')]},
  {inputs:{method:'seed_from_fertilization'},given:'Çiçekli bir bitkide erkek ve dişi üreme hücreleri birleşiyor. Bu döllenmenin ardından oluşan tohum uygun koşullarda yeni bitkiyi meydana getiriyor.',wanted:'Anlatılan tohum oluşumu hangi üreme tipi ve hücre birleşmesiyle eşleştirilmelidir?',result:'Döllenmeyle tohum oluşumu eşeyli üremedir; üreme hücreleri birleşir.',meaning:'Tohum sözcüğünden çok, soruda açıkça verilen döllenme kanıtı kullanılmalıdır.',
    choices:[choice('Eşeyli; üreme hücreleri birleşir.',{reproductionType:'sexual',gameteFusion:true},''),choice('Eşeysiz; üreme hücreleri birleşmez.',{reproductionType:'asexual',gameteFusion:false},'Verilen döllenme kanıtı yok sayılmıştır.'),choice('Eşeyli; üreme hücreleri birleşmez.',{reproductionType:'sexual',gameteFusion:false},'Birleşme soruda açıkça belirtilmiştir.'),choice('Eşeysiz; üreme hücreleri birleşir.',{reproductionType:'asexual',gameteFusion:true},'Üreme türü ile mekanizma yanlış eşleştirilmiştir.')]},
]);
family({grade:6,branch:'biology',familyId:'biodiversity_evidence',topic:'Gözlenen tür çeşitliliği',code:'FB.6.7.1',page:142,kind:'biology_graph',task:'biodiversity_evidence',intent:'analyze',
  rule:'Aynı alan ve yöntemle yapılan bu gözlemde tür zenginliği farklı türlerin sayısıyla karşılaştırılır; toplam birey sayısıyla aynı değildir.',strategy:'Tekrarlanan canlı adlarını bir kez say; yalnız gözlemdeki tür sayısı hakkında çıkarım yap.',action:'Her alanın kaydedilen farklı türlerini ayır ve sayıları karşılaştır.',tip:'Aynı türden çok birey, çok sayıda farklı tür demek değildir.',check:'Sonucun bütün ekosistem çeşitliliğini değil bu örneklemede gözlenen tür sayısını anlattığını kontrol et.'},[
  {inputs:{sites:[{id:'K',species:['pine','oak']},{id:'L',species:['pine']}],sameSampleArea:true},given:'Eşit büyüklükte K ve L alanları aynı yöntemle gözleniyor. K’de çam ve meşe, L’de yalnız çam kaydediliyor. Bu sınırlı sayımın dışında kalan canlılar hakkında bilgi yoktur.',wanted:'Yalnız bu sayımda gözlenen tür zenginliği açısından hangi alan öndedir ve hangi ölçüt kullanılır?',result:'K alanında iki farklı tür, L’de bir tür gözlenmiştir; K bu sayımda daha zengindir.',meaning:'Bu kanıt bütün ekosistemin her çeşitlilik boyutunu ölçmez.',
    choices:[choice('K; farklı tür sayısı',{richerSite:'K',criterion:'distinct_species'},''),choice('L; farklı tür sayısı',{richerSite:'L',criterion:'distinct_species'},'İki farklı tür yerine tek tür daha zengin sayılmıştır.'),choice('Eşit; farklı tür sayısı',{richerSite:'equal',criterion:'distinct_species'},'Kaydedilen tür sayıları eşit değildir.'),choice('K; toplam birey sayısı',{richerSite:'K',criterion:'total_individuals'},'Birey sayıları verilmediği gibi istenen ölçüt de farklı tür sayısıdır.')]},
  {inputs:{sites:[{id:'K',species:['pine','pine','oak']},{id:'L',species:['pine','oak','juniper']}],sameSampleArea:true},given:'Aynı yöntem ve eşit alanla yapılan kayıtta K listesi çam, çam, meşe; L listesi çam, meşe, ardıç biçimindedir. Her liste üç birey içerir; kayıtların kapsamı bu gözlemle sınırlıdır.',wanted:'Tekrarlanan adları ayırınca hangi alanın gözlenen tür zenginliği daha fazladır?',result:'K’de iki farklı tür, L’de üç farklı tür vardır; L öndedir.',meaning:'Birey sayıları eşitken tür sayıları farklı olabilir.',difficulty:'hard',
    choices:[choice('L; farklı tür sayısı',{richerSite:'L',criterion:'distinct_species'},''),choice('K; farklı tür sayısı',{richerSite:'K',criterion:'distinct_species'},'Aynı çam türü iki ayrı tür sayılmıştır.'),choice('Eşit; farklı tür sayısı',{richerSite:'equal',criterion:'distinct_species'},'Üçer birey bulunması üçer tür bulunduğu anlamına gelmez.'),choice('L; toplam birey sayısı',{richerSite:'L',criterion:'total_individuals'},'Her alanda üç birey vardır; fark tür sayısındadır.')]},
]);

family({grade:7,branch:'physics',familyId:'work_direction',topic:'Kuvvet ve yer değiştirme yönü',code:'FB.7.2.1',page:152,kind:'force_work_board',task:'work_direction',intent:'apply',
  rule:'Bu düzeyde incelenen mekanik iş için, incelenen kuvvet doğrultusunda yer değiştirme bulunmalıdır; dik kuvvet bu yer değiştirme boyunca iş yapmaz.',strategy:'Hangi kuvvetin sorulduğunu belirle; o kuvveti cismin yer değiştirme yönüyle karşılaştır.',action:'Kuvvet ve yer değiştirme oklarının paralel mi dik mi olduğunu ayır.',
  tip:'Yorulmak ile fiziksel anlamda iş yapmak aynı koşula bağlı değildir.',check:'Yargının bütün kuvvetlere değil soruda adı verilen kuvvete ilişkin olduğunu kontrol et.'},[
  {inputs:{forceDirection:'right',displacementDirection:'up'},given:'Bir kutu yukarı hareket ederken ona sağa doğru yatay bir kuvvet uygulanıyor. Soruda yalnız bu yatay kuvvetin, yukarı yönlü yer değiştirme boyunca yaptığı mekanik iş inceleniyor.',wanted:'Verilen yatay kuvvet için mekanik iş bakımından hangi yargı uygundur?',result:'Sağa yönlü kuvvet yukarı yer değiştirmeye diktir; bu yatay kuvvet bu hareket boyunca mekanik iş yapmaz.',meaning:'Diğer kuvvetler hakkında yargı kurulmaz; sorulan kuvvetin doğrultusu esas alınır.',
    choices:[choice('Bu kuvvet mekanik iş yapmaz.',{mechanicalWork:'none'},''),choice('Bu kuvvet mekanik iş yapar.',{mechanicalWork:'done'},'Kuvvet ile yer değiştirme dik olduğu hâlde paralel sayılmıştır.'),choice('Bu kuvvet için iş sonucu yalnız süreyle bulunur.',{mechanicalWork:'time_only'},'Kuvvet-yer değiştirme yönü yerine süre tek belirleyici sanılmıştır.'),choice('Kutu hareket ettiği için her kuvvet iş yapar.',{mechanicalWork:'all_forces'},'Cismin hareketi bütün kuvvetlerin o doğrultuda iş yaptığını göstermez.')]},
  {inputs:{forceDirection:'left',displacementDirection:'left'},given:'Bir öğrenci küçük bir arabayı sola yönlü kuvvetle çekiyor; araba da sola yer değiştiriyor. Burada öğrencinin uyguladığı çekme kuvveti inceleniyor, sayısal iş hesabı istenmiyor.',wanted:'Çekme kuvvetinin yönü ile yer değiştirme birlikte değerlendirildiğinde hangi sonuç doğrudur?',result:'Çekme kuvveti ve yer değiştirme aynı yöndedir; incelenen kuvvet mekanik iş yapar.',meaning:'Yön ilişkisi verilen temel iş koşulunu karşılar; işin sayısal büyüklüğü hesaplanmaz.',difficulty:'easy',
    choices:[choice('Bu kuvvet mekanik iş yapar.',{mechanicalWork:'done'},''),choice('Bu kuvvet mekanik iş yapmaz.',{mechanicalWork:'none'},'Aynı doğrultu ve yer değiştirme koşulu göz ardı edilmiştir.'),choice('Yalnız süre bilgisiyle karar verilir.',{mechanicalWork:'time_only'},'Bu nitel yön karşılaştırması için süre gerekli değildir.'),choice('Cisim yer değiştirdiği için bütün kuvvetler mekanik iş yapar.',{mechanicalWork:'all_forces'},'Tek bir kuvvetin koşulu diğer bütün kuvvetlere genellenmiştir.')]},
]);
family({grade:7,branch:'physics',familyId:'kinetic_potential_transform',topic:'Kinetik ve potansiyel enerji dönüşümü',code:'FB.7.2.3',page:152,kind:'force_work_board',task:'energy_transition',intent:'analyze',
  rule:'Yalnız yer çekimi etkili olup sürtünme ihmal edildiğinde yükseklikle potansiyel, süratle kinetik enerji nitel olarak ilişkilendirilir; mekanik enerji korunur.',strategy:'Yükseklik ve sürat değişimlerini ayrı oku; sonra verilen ideal koşulda iki enerji türünün dönüşümünü birleştir.',action:'Yükseklik değişimini potansiyelle, sürat değişimini kinetikle eşleştir.',tip:'Yükseklik ve sürat iki farklı enerji ipucudur; formül kullanmadan yönlerini izle.',check:'Korunum yargısı kurmadan önce yalnız yer çekimi ve sürtünmesizlik koşullarının verildiğini denetle.'},[
  {inputs:{heightChange:'decreases',speedChange:'increases',frictionIgnored:true,gravityOnly:true},given:'Bir top, yalnız yer çekiminin etkili olduğu ideal bir inişte daha alçak konuma gelirken süratleniyor. Sürtünme ihmal ediliyor; dışarıdan itme veya enerji aktarımı yoktur.',wanted:'İniş sırasında potansiyel, kinetik ve toplam mekanik enerji nasıl değişir?',result:'Potansiyel enerji azalır, kinetik enerji artar; bu ideal koşulda toplam mekanik enerji aynı kalır.',meaning:'Bir enerji türünün azalması toplam mekanik enerjinin mutlaka azalması demek değildir.',
    choices:[choice('Potansiyel azalır, kinetik artar, toplam aynıdır.',{potentialChange:'decreases',kineticChange:'increases',mechanicalEnergyChange:'same'},''),choice('İkisi de azalır, toplam azalır.',{potentialChange:'decreases',kineticChange:'decreases',mechanicalEnergyChange:'decreases'},'Sürat artışı ve ideal korunum koşulu göz ardı edilmiştir.'),choice('Potansiyel artar, kinetik azalır, toplam aynıdır.',{potentialChange:'increases',kineticChange:'decreases',mechanicalEnergyChange:'same'},'Yükseklik ve sürat değişimleri ters okunmuştur.'),choice('Potansiyel azalır, kinetik artar, toplam artar.',{potentialChange:'decreases',kineticChange:'increases',mechanicalEnergyChange:'increases'},'Dış enerji aktarımı olmadan toplam artışı varsayılmıştır.')]},
  {inputs:{heightChange:'increases',speedChange:'decreases',frictionIgnored:true,gravityOnly:true},given:'Bir top ilk hareketi verildikten sonra ideal bir yükselişte daha yüksek konuma gelirken yavaşlıyor. Yalnız yer çekimi etkilidir; sürtünme ve dış enerji aktarımı yoktur.',wanted:'Yükseliş için hangi üçlü enerji değişimi verilen koşullarla tutarlıdır?',result:'Potansiyel artar, kinetik azalır; toplam mekanik enerji korunur.',meaning:'Kinetik enerji kaybolmak yerine bu koşulda potansiyel enerjiye dönüşür.',difficulty:'hard',
    choices:[choice('Potansiyel artar, kinetik azalır, toplam aynıdır.',{potentialChange:'increases',kineticChange:'decreases',mechanicalEnergyChange:'same'},''),choice('Potansiyel azalır, kinetik artar, toplam aynıdır.',{potentialChange:'decreases',kineticChange:'increases',mechanicalEnergyChange:'same'},'Yükseliş ve yavaşlama ters yorumlanmıştır.'),choice('Potansiyel artar, kinetik azalır, toplam azalır.',{potentialChange:'increases',kineticChange:'decreases',mechanicalEnergyChange:'decreases'},'Verilmeyen sürtünme kaybı eklenmiştir.'),choice('Potansiyel ve kinetik artar, toplam artar.',{potentialChange:'increases',kineticChange:'increases',mechanicalEnergyChange:'increases'},'Yavaşlama bilgisi ve dış aktarımın bulunmaması kullanılmamıştır.')]},
]);
family({grade:7,branch:'physics',familyId:'refraction_path',topic:'Ortam değişiminde ışık yolu',code:'FB.7.4.1',page:165,kind:'ray_path',task:'refraction_path',intent:'apply',
  rule:'Normale eğik gelen ve sınırı geçen ışık, havadan optikçe daha yoğun suya geçerken normale yaklaşır; ters geçişte normalden uzaklaşır.',strategy:'Önce ortamların sırasını, sonra normal doğrusunu bul; kırılmayı yüzeye değil normale göre yorumla.',action:'Geldiği ve geçtiği ortamı normalle karşılaştırarak nitel kırılma yönünü seç.',tip:'Ortam sırası ters çevrilirse yaklaşma-uzaklaşma yorumu da tersine döner.',check:'Eğik geliş ve ışığın sınırı geçtiği koşulları kullan; açı değeri veya özel yansıma hesabı uydurma.'},[
  {inputs:{from:'air',to:'water',crossesBoundary:true,obliqueIncidence:true},given:'Işık havadan optikçe daha yoğun suya, normale eğik biçimde geliyor ve suya geçiyor. Çizimde sınır yüzeyi, normal ve gelen ışın gösteriliyor; kırılan ışın henüz çizilmemiştir.',wanted:'Suya geçen ışının normalle ilişkisi ve sürati için hangi nitel yorum doğrudur?',result:'Işın normale yaklaşır; sudaki sürati havadakinden küçüktür.',meaning:'Normal referansı kullanılarak yön yorumu yapılır; Snell hesabı veya belirli açı sonucu çıkarılmaz.',
    choices:[choice('Normale yaklaşır; sürati azalır.',{bend:'toward_normal',speedChange:'decreases'},''),choice('Normalden uzaklaşır; sürati artar.',{bend:'away_from_normal',speedChange:'increases'},'Havadan suya geçişin yönü ters çevrilmiştir.'),choice('Normale yaklaşır; sürati artar.',{bend:'toward_normal',speedChange:'increases'},'Yön doğru olsa da sürat değişimi ters verilmiştir.'),choice('Kırılmadan düz gider; sürati değişmez.',{bend:'straight',speedChange:'same'},'Farklı ortamlar ve eğik geliş göz ardı edilmiştir.')]},
  {inputs:{from:'water',to:'air',crossesBoundary:true,obliqueIncidence:true},given:'Bir ışın optikçe daha yoğun sudan havaya, normale eğik biçimde geliyor ve hava tarafına geçiyor. Gelen ışın ve normal çizili; sınırı geçtiği açıkça belirtilmiştir.',wanted:'Havaya geçen ışının yolunu ve sürat değişimini hangi seçenek doğru anlatır?',result:'Işın normalden uzaklaşır; havadaki sürati sudakinden büyüktür.',meaning:'Sınırı geçen eğik ışın için nitel karşılaştırma yapılır; özel sınır açısı konusu kullanılmaz.',
    choices:[choice('Normalden uzaklaşır; sürati artar.',{bend:'away_from_normal',speedChange:'increases'},''),choice('Normale yaklaşır; sürati azalır.',{bend:'toward_normal',speedChange:'decreases'},'Ortam sırası ters okunmuştur.'),choice('Normalden uzaklaşır; sürati azalır.',{bend:'away_from_normal',speedChange:'decreases'},'Işın yönü ile sürat değişimi yanlış birlikte eşleştirilmiştir.'),choice('Düz gider; sürati aynı kalır.',{bend:'straight',speedChange:'same'},'Eğik geliş ve optik ortam farkı dikkate alınmamıştır.')]},
]);
family({grade:7,branch:'chemistry',familyId:'particle_element_compound',topic:'Tanecik modelinden saf maddeyi ayırma',code:'FB.7.5.4',page:169,kind:'matter_cards',task:'particle_composition',intent:'analyze',
  rule:'Farklı semboller farklı atom türlerini, aynı kümedeki semboller bağlı atomları gösterir. Tek atom türünden oluşan saf madde element, farklı atom türlerinin bağlı tek tip tanecikleri bileşiktir.',strategy:'Renkten değil sembol ve bağ bilgisinden yararlan; önce tanecik tipini, sonra atom türlerini incele.',action:'Gösterilen kümelerdeki atom türlerini ve tekrarlanan tanecik yapısını karşılaştır.',tip:'İki atom içermek, mutlaka iki farklı atom türü içermek değildir.',check:'Aynı sembollerin aynı atom türü, aynı kümenin bağlı grup anlamını taşıdığını tekrar kontrol et.'},[
  {inputs:{clusters:[['X','Y'],['X','Y'],['X','Y']]},given:'Bir tanecik kartında üç ayrı bağlı X-Y grubu gösteriliyor. X ve Y farklı atom türlerini, aynı köşeli grupta yer alan semboller aralarındaki bağı temsil ediyor. Başka tanecik yoktur.',wanted:'Bu tek tip bağlı taneciklerden oluşan saf madde nasıl sınıflandırılır?',result:'Her tanecikte farklı atom türleri bağlıdır; tek tanecik tipi bileşik modelidir.',meaning:'Aynı tanecikteki farklı atom türleri, ayrı ayrı karışmış elementler değildir.',
    choices:[choice('Bileşik; tek tanecik tipi',{materialClass:'compound',distinctParticleTypes:1},''),choice('Element; tek tanecik tipi',{materialClass:'element',distinctParticleTypes:1},'Tek tanecik tipi bulunması tek atom türü bulunduğunu göstermez.'),choice('Karışım; iki tanecik tipi',{materialClass:'mixture',distinctParticleTypes:2},'X ve Y ayrı serbest tanecikler değil bağlı aynı gruptadır.'),choice('Bileşik; üç tanecik tipi',{materialClass:'compound',distinctParticleTypes:3},'Üç adet aynı tanecik, üç farklı tanecik tipi değildir.')]},
  {inputs:{clusters:[['X','X'],['X','X']]},given:'İkinci kartta iki ayrı bağlı X-X grubu var. Bütün X sembolleri aynı atom türünü gösteriyor; aynı grubun içindeki iki atom bağlıdır. Kartta başka sembol veya grup türü bulunmuyor.',wanted:'İki atomlu gruplar içeren bu saf madde için hangi sınıflandırma ve tanecik tipi sayısı doğrudur?',result:'Bütün atomlar aynı türdendir; bu element modelinde tek tanecik tipi vardır.',meaning:'Molekül biçiminde bulunmak tek başına bileşik olmak demek değildir.',
    choices:[choice('Element; tek tanecik tipi',{materialClass:'element',distinctParticleTypes:1},''),choice('Bileşik; tek tanecik tipi',{materialClass:'compound',distinctParticleTypes:1},'İki atom ile iki atom türü karıştırılmıştır.'),choice('Karışım; iki tanecik tipi',{materialClass:'mixture',distinctParticleTypes:2},'İki adet aynı grubun bulunması iki farklı tanecik tipi vermez.'),choice('Element; iki tanecik tipi',{materialClass:'element',distinctParticleTypes:2},'Aynı X-X yapısı iki kez gösterilse de tek tiptir.')]},
]);
family({grade:7,branch:'chemistry',familyId:'dissolution_fair_test',topic:'Çözünme hızında adil karşılaştırma',code:'FB.7.5.9',page:169,kind:'experiment_board',task:'fair_test',intent:'analyze',knowledge:'procedural',
  rule:'Çözünme süresine bir koşulun etkisi araştırılırken diğer hazırlık koşulları aynı tutulur.',strategy:'Hedef değişkeni seç; sıcaklık, karıştırma, tanecik büyüklüğü ve su miktarındaki diğer farkları ele.',action:'Tabloda yalnız araştırılan koşulun farklı olduğu iki satırı belirle.',tip:'İki koşul birlikte değişirse hangisinin süreyi etkilediğini bu çiftle ayıramazsın.',check:'Özdeş çözünen madde miktarı ve hedef dışındaki bütün koşulların eşitliğini kontrol et.'},[
  {inputs:{targetVariable:'waterTemperature',rows:[{id:'R1',waterTemperature:'cold',stirring:'no',grainSize:'fine',waterAmount:100},{id:'R2',waterTemperature:'warm',stirring:'no',grainSize:'fine',waterAmount:100},{id:'R3',waterTemperature:'warm',stirring:'yes',grainSize:'fine',waterAmount:100},{id:'R4',waterTemperature:'cold',stirring:'no',grainSize:'coarse',waterAmount:100}]},given:'Eşit miktarda aynı şekerle düzenekler hazırlanıyor. R1:soğuk su/karıştırma yok/ince şeker/100 mL; R2:ılık su/yok/ince/100 mL; R3:ılık su/var/ince/100 mL; R4:soğuk su/yok/iri/100 mL. Yetişkin gözetimiyle yalnız gözlem yapılacaktır.',wanted:'Su sıcaklığının çözünme süresine etkisi hangi iki düzenekte tek başına araştırılır?',result:'R1-R2 yalnız su sıcaklığında farklıdır; diğer koşullar aynıdır.',meaning:'Bu tasarım, ölçüm yapılmadan kesin çözünme süreleri vermez.',choices:pairChoices('R1-R2','waterTemperature')},
  {inputs:{targetVariable:'stirring',rows:[{id:'R1',waterTemperature:'warm',stirring:'no',grainSize:'fine',waterAmount:150},{id:'R2',waterTemperature:'warm',stirring:'yes',grainSize:'fine',waterAmount:150},{id:'R3',waterTemperature:'cold',stirring:'yes',grainSize:'fine',waterAmount:150},{id:'R4',waterTemperature:'warm',stirring:'no',grainSize:'fine',waterAmount:200}]},given:'Eşit miktarda aynı şeker kullanılıyor. R1:ılık su/karıştırma yok/ince şeker/150 mL; R2:ılık su/karıştırma var/ince/150 mL; R3:soğuk su/var/ince/150 mL; R4:ılık su/yok/ince/200 mL. Veriler yalnız hazırlık koşullarıdır.',wanted:'Karıştırmanın etkisini sıcaklık veya su miktarı farkına karıştırmayan hangi çift seçilmelidir?',result:'R1-R2 çifti yalnız karıştırma koşulunda farklıdır.',meaning:'Değişen su miktarı veya sıcaklık aynı soruda ek açıklama nedeni olurdu.',choices:pairChoices('R1-R2','stirring')},
]);
family({grade:7,branch:'chemistry',familyId:'separation_method',topic:'Ayırma yöntemini hedefe göre seçme',code:'FB.7.5.10',page:169,kind:'matter_cards',task:'separation_method',intent:'apply',knowledge:'procedural',
  rule:'Uçucu olmayan çözünmüş tuzu geride bırakmak için su buharlaştırılabilir; suyu toplamak için buhar yoğuşturularak damıtma yapılır.',strategy:'Yöntem adını ezberden seçmeden önce hangi bileşenin geri kazanılacağını belirle.',action:'Elde tutulmak istenen bileşeni seç ve buharı toplamanın gerekli olup olmadığını düşün.',tip:'Aynı karışımda farklı hedefler farklı ayırma düzenekleri gerektirebilir.',check:'Yöntemin yalnız ayırmayı değil istenen bileşeni toplamayı da sağladığını kontrol et.'},[
  {inputs:{components:['salt','water'],target:'salt'},given:'Çözünmüş tuz ve sudan oluşan bir örnekte tuz uçucu değildir. Amaç yalnız tuzu kapta geri kazanmaktır; suyun toplanması istenmiyor. Soru yöntem seçimi içindir, çocukların ısıtma uygulaması yapması istenmez.',wanted:'Bu hedef için hangi ayırma yöntemi yeterlidir?',result:'Su buharlaştırılırken uçucu olmayan tuz kapta kalır; buharlaştırma hedefi karşılar.',meaning:'Su istenmediği için buharın ayrıca toplanması zorunlu değildir.',
    choices:[choice('Buharlaştırma',{method:'evaporation'},''),choice('Süzme',{method:'filtration'},'Çözünmüş tuz sıradan süzgeçle sudan tutulamaz.'),choice('Mıknatısla ayırma',{method:'magnet'},'Tuz-su örneğinde mıknatısla tutulacak bir bileşen verilmemiştir.'),choice('Eleme',{method:'sieving'},'Çözünmüş tuz tanecikleri katı boyut eleğiyle ayrılmaz.')]},
  {inputs:{components:['salt','water'],target:'water'},given:'Bir tuz-su örneğinde tuz uçucu değildir. Bu kez amaç sudaki tuzu geride bırakıp suyu ayrı kapta toplamaktır. Yöntem yalnız görsel bir tasarım üzerinden seçiliyor; gerçek ısıtma işlemi yapılmıyor.',wanted:'Su geri kazanılmak istendiğinde hangi yöntem seçilmelidir?',result:'Suyun buharını ayrı yerde yoğuşturan damıtma, suyu toplamayı sağlar.',meaning:'Yalnız buharlaştırıp buharı kaybetmek suyu geri kazanma hedefini karşılamaz.',difficulty:'hard',
    choices:[choice('Damıtma',{method:'distillation'},''),choice('Yalnız açık kapta buharlaştırma',{method:'evaporation'},'Buhar kaybolursa istenen su ayrı kapta toplanmaz.'),choice('Eleme',{method:'sieving'},'Çözünmüş karışım kuru katı boyutu eleğiyle ayrılmaz.'),choice('Mıknatısla ayırma',{method:'magnet'},'Verilen bileşenlerin biri manyetik olarak ayrılacak biçimde tanımlanmamıştır.')]},
]);
family({grade:7,branch:'biology',familyId:'digestion_route',topic:'Besinin izlediği yolu sıralama',code:'FB.7.3.1',page:156,kind:'biology_graph',task:'digestion_route',intent:'understand',
  rule:'Seçilmiş sindirim organlarının göreli sırası ağız, yemek borusu, mide, ince bağırsak ve kalın bağırsak yönündedir; liste bütün anatomik yapıları gösterme iddiası taşımaz.',strategy:'Besinin ilerlediği kanalı yardımcı organlardan ayır; yalnız soruda seçilmiş organların göreli sırasını izle.',action:'Başlangıç ve bitiş arasındaki seçilmiş organları besinin ilerleme yönünde yerleştir.',tip:'Besin yolu ile sindirime yardımcı organ listesi aynı şey değildir.',check:'Bütün anatomik yapılar verilmiş gibi davranmadan seçili organların göreli sırasını kontrol et.'},[
  {inputs:{organs:['stomach','large_intestine','mouth','small_intestine','esophagus'],start:'mouth',finish:'large_intestine'},given:'Bir etkinlikte ağız, yemek borusu, mide, ince bağırsak ve kalın bağırsak kartları karışık veriliyor. Kartlar yalnız seçilmiş organları içeriyor; bütün anatomik yapılar listeye alınmış değildir.',wanted:'Ağızdan kalın bağırsağa kadar bu seçilmiş organların göreli sırası hangi seçenekte doğrudur?',result:'Göreli sıra ağız→yemek borusu→mide→ince bağırsak→kalın bağırsaktır.',meaning:'Yardımcı organlar besinin içinden geçtiği kanalın yerine eklenmez; dışarıda bırakılmış anatomik ayrıntılar hakkında sonuç çıkarılmaz.',difficulty:'easy',
    choices:[choice('Ağız → Yemek borusu → Mide → İnce bağırsak → Kalın bağırsak',{route:'mouth>esophagus>stomach>small_intestine>large_intestine'},''),choice('Ağız → Mide → Yemek borusu → İnce bağırsak → Kalın bağırsak',{route:'mouth>stomach>esophagus>small_intestine>large_intestine'},'Yemek borusu ile mide yer değiştirmiştir.'),choice('Ağız → Yemek borusu → Mide → Kalın bağırsak → İnce bağırsak',{route:'mouth>esophagus>stomach>large_intestine>small_intestine'},'Bağırsakların göreli sırası ters verilmiştir.'),choice('Mide → Ağız → Yemek borusu → İnce bağırsak → Kalın bağırsak',{route:'stomach>mouth>esophagus>small_intestine>large_intestine'},'İstenen başlangıç ağız olmasına rağmen mideyle başlanmıştır.')]},
  {inputs:{organs:['small_intestine','mouth','large_intestine','esophagus','stomach'],start:'stomach',finish:'large_intestine'},given:'Aynı beş seçilmiş organ bu kez farklı yerlerdeki kartlara yazılıyor: ince bağırsak, ağız, kalın bağırsak, yemek borusu, mide. Soru yalnız mide ile kalın bağırsak arasındaki göreli yolu istiyor.',wanted:'İstenen başlangıç ve bitişe göre hangi seçilmiş organ sırası kullanılmalıdır?',result:'Mide→ince bağırsak→kalın bağırsak sırası istenir.',meaning:'Bütün kartları her yanıta katmak yerine istenen başlangıç-bitiş aralığı seçilir.',intent:'apply',
    choices:[choice('Mide → İnce bağırsak → Kalın bağırsak',{route:'stomach>small_intestine>large_intestine'},''),choice('Mide → Kalın bağırsak → İnce bağırsak',{route:'stomach>large_intestine>small_intestine'},'Bağırsakların göreli sırası ters çevrilmiştir.'),choice('Ağız → Yemek borusu → Mide',{route:'mouth>esophagus>stomach'},'Başlangıç ve bitiş sorunun istediği aralığı karşılamaz.'),choice('Mide → Yemek borusu → Kalın bağırsak',{route:'stomach>esophagus>large_intestine'},'Besinin ilerleme yönünün tersine bir organ eklenmiştir.')]},
]);
family({grade:7,branch:'biology',familyId:'circulation_route',topic:'Küçük ve büyük dolaşım yolu',code:'FB.7.3.3',page:156,kind:'biology_graph',task:'circulation_route',intent:'understand',
  rule:'Küçük dolaşım kalp-akciğer-kalp, büyük dolaşım kalp-vücut-kalp yönündeki basitleştirilmiş yoldur.',strategy:'Önce dolaşımın amacını oku; akciğerde oksijenlenme ile vücuda dağıtımı ayır.',action:'Verilen amacı akciğer veya vücut yoluyla eşleştir.',tip:'Başlangıç ve dönüş ikisinde de kalptir; aradaki hedef organ ayrımı belirler.',check:'Kalp odacıkları veya özel damar adları eklemeden bu düzeyin basit yolunu kontrol et.'},[
  {inputs:{purpose:'oxygenate'},given:'Basitleştirilmiş bir dolaşım modelinde kanın akciğerde oksijen bakımından zenginleşip yeniden kalbe dönmesi inceleniyor. Model yalnız kalp, akciğer ve vücut bölgelerini kullanıyor.',wanted:'Bu amaç için yol ve dolaşım adı hangi seçenekte doğru eşleştirilmiştir?',result:'Kalp→akciğer→kalp yolu küçük dolaşımdır.',meaning:'Akciğerde oksijenlenme amacı, vücuda dağıtım yolundan ayrılır.',difficulty:'easy',
    choices:[choice('Kalp → Akciğer → Kalp; küçük dolaşım',{route:'heart>lungs>heart',circulationType:'pulmonary'},''),choice('Kalp → Vücut → Kalp; büyük dolaşım',{route:'heart>body>heart',circulationType:'systemic'},'Bu yol istenen akciğerde oksijenlenme amacını karşılamaz.'),choice('Kalp → Akciğer → Kalp; büyük dolaşım',{route:'heart>lungs>heart',circulationType:'systemic'},'Yol doğru olsa da dolaşım adı yanlış eşleştirilmiştir.'),choice('Akciğer → Vücut → Kalp; küçük dolaşım',{route:'lungs>body>heart',circulationType:'pulmonary'},'Kalpten başlayıp kalbe dönme yolu korunmamıştır.')]},
  {inputs:{purpose:'distribute'},given:'İkinci modelde oksijen bakımından zenginleşmiş kanın kalpten vücut bölgelerine taşınması ve yeniden kalbe dönmesi izleniyor. Özel damar adları ve kalp odacıkları bu modelde bulunmuyor.',wanted:'Vücuda dağıtım amacı hangi basit yol ve dolaşım adıyla açıklanır?',result:'Kalp→vücut→kalp yolu büyük dolaşımdır.',meaning:'Modelin amacı dağıtımdır; aradaki organ akciğer değil vücut bölgeleridir.',
    choices:[choice('Kalp → Vücut → Kalp; büyük dolaşım',{route:'heart>body>heart',circulationType:'systemic'},''),choice('Kalp → Akciğer → Kalp; küçük dolaşım',{route:'heart>lungs>heart',circulationType:'pulmonary'},'Akciğer yolu vücuda dağıtım amacı yerine geçirilmiştir.'),choice('Kalp → Vücut → Kalp; küçük dolaşım',{route:'heart>body>heart',circulationType:'pulmonary'},'Büyük dolaşımın yolu küçük dolaşım diye adlandırılmıştır.'),choice('Vücut → Akciğer → Kalp; büyük dolaşım',{route:'body>lungs>heart',circulationType:'systemic'},'Modelin kalpten başlama koşulu ve dönüş yolu bozulmuştur.')]},
]);
family({grade:7,branch:'biology',familyId:'food_web_roles',topic:'Besin ilişkisinde rol ve ok yönü',code:'FB.7.7.1',page:181,kind:'biology_graph',task:'food_web_roles',intent:'analyze',
  rule:'Bu modelde ok besinden onu yiyen canlıya gider; ot üreticidir, otu yiyen çekirge birincil ve çekirgeyi yiyen kurbağa ikincil tüketicidir.',strategy:'Önce okun anlamını oku; hedef canlıya gelen okun hangi besinden başladığını bul.',action:'Ot→çekirge→kurbağa zincirinde hedefe gelen bağlantıyı izle.',tip:'Ok, canlıların bakış yönünü değil besin ve enerji aktarımı yönünü gösterir.',check:'Yalnız verilen zincire ilişkin rolü kullan; başka besin kaynakları veya bütün ekosistem dengesi hakkında varsayım kurma.'},[
  {inputs:{edges:[['grass','grasshopper'],['grasshopper','frog']],target:'grasshopper'},given:'Verilen basit besin zinciri ot→çekirge→kurbağa biçimindedir. Ok, besinden onu yiyen canlıya yönelir. Ot fotosentez yapan bitkidir; yalnız çizilen zincirdeki ilişkiler soruluyor.',wanted:'Çekirgenin bu zincirdeki tüketici basamağı ve doğrudan besini hangisidir?',result:'Çekirge otu yer; bu zincirde birincil tüketicidir.',meaning:'Üreticiden doğrudan beslenme ile birincil tüketici basamağı ilişkilendirilir.',
    choices:[choice('Birincil tüketici; ot',{role:'primary_consumer',food:'grass'},''),choice('Üretici; ot',{role:'producer',food:'grass'},'Otu yemek fotosentezle kendi besinini üretmek değildir.'),choice('İkincil tüketici; kurbağa',{role:'secondary_consumer',food:'frog'},'Ok yönü ters okunmuştur.'),choice('Birincil tüketici; kurbağa',{role:'primary_consumer',food:'frog'},'Tüketici basamağı doğru olsa da doğrudan besin yanlış seçilmiştir.')]},
  {inputs:{edges:[['grass','grasshopper'],['grasshopper','frog']],target:'frog'},given:'Bir kartta ot→çekirge→kurbağa zinciri gösteriliyor. Ok yine besinden onu tüketene gidiyor ve ot fotosentez yapan bitki olarak tanımlanıyor. Bu kez kurbağa işaretlenmiştir.',wanted:'İşaretli kurbağanın yalnız bu zincirdeki basamağı ve doğrudan besini nedir?',result:'Kurbağa çekirgeyi yer; bu zincirde ikincil tüketicidir.',meaning:'Üreticiden iki beslenme adımı uzaklık bu sınırlı zincirde ikinci tüketici basamağına karşılık gelir.',
    choices:[choice('İkincil tüketici; çekirge',{role:'secondary_consumer',food:'grasshopper'},''),choice('Birincil tüketici; ot',{role:'primary_consumer',food:'grass'},'Kurbağa ile üretici arasındaki çekirge basamağı atlanmıştır.'),choice('Üretici; çekirge',{role:'producer',food:'grasshopper'},'Tüketerek beslenme üretici rolü değildir.'),choice('İkincil tüketici; ot',{role:'secondary_consumer',food:'grass'},'Rol doğru olsa da doğrudan besin zincirdeki okla uyuşmaz.')]},
]);

family({grade:8,branch:'physics',familyId:'solid_pressure_control',topic:'Katı basıncında nitel karşılaştırma',code:'F.8.3.1.1',page:51,kind:'experiment_board',task:'solid_pressure',intent:'analyze',
  rule:'Ağırlıklar aynıysa daha küçük temas alanında, temas alanları aynıysa daha büyük ağırlıkta katı basıncı daha büyüktür.',strategy:'Önce hangi değişkenin eşit olduğunu bul; yalnız diğer değişkenin basınca etkisini nitel olarak karşılaştır.',action:'Ağırlık ve temas alanı sıralarını ayrı oku; eşit olanı sabit tut.',tip:'Basınç karşılaştırmasına başlamadan önce ağırlık mı temas alanı mı sabit diye sor.',check:'İki değişken aynı anda farklıysa bu tek değişkenli kuralı koşulsuz uygulama; sayısal basınç formülü kullanma.'},[
  {inputs:{weightOrder:'equal',contactAreaOrder:'K>L'},given:'K ve L kutularının ağırlıkları eşittir. Aynı yatay zeminde K’nin temas alanı L’den daha büyüktür. Düzenek yalnız bu iki kutunun zemine uyguladığı katı basıncını karşılaştırıyor.',wanted:'Eşit ağırlık koşulunda hangi kutu daha büyük basınç uygular?',result:'Ağırlık aynı olduğundan daha küçük temas alanlı L daha büyük basınç uygular.',meaning:'Büyük temas alanı, aynı ağırlığın daha geniş alana dağılması demektir.',
    choices:[choice('L daha büyük basınç uygular.',{greaterPressure:'L'},''),choice('K daha büyük basınç uygular.',{greaterPressure:'K'},'Aynı ağırlıkta büyük temas alanının etkisi ters yorumlanmıştır.'),choice('Basınçlar eşittir.',{greaterPressure:'equal'},'Ağırlık eşit olsa da temas alanı eşit değildir.'),choice('Temas alanı hiçbir fark oluşturmaz.',{greaterPressure:'area_irrelevant'},'Katı basıncında temas alanının etkisi yok sayılmıştır.')]},
  {inputs:{weightOrder:'K>L',contactAreaOrder:'equal'},given:'İkinci düzende K ve L kutularının zemine temas alanları eşittir. K’nin ağırlığı L’den fazladır. İki kutu aynı yatay yüzey üzerinde duruyor; basınç değeri hesabı istenmiyor.',wanted:'Bu kez aynı temas alanı koşulunda hangi kutunun basıncı daha büyüktür?',result:'Temas alanları eşitken daha ağır K daha büyük basınç uygular.',meaning:'Bu karşılaştırma ağırlık etkisini, önceki alan etkisinden ayrı inceler.',
    choices:[choice('K daha büyük basınç uygular.',{greaterPressure:'K'},''),choice('L daha büyük basınç uygular.',{greaterPressure:'L'},'Ağırlık etkisinin yönü ters yorumlanmıştır.'),choice('Basınçlar eşittir.',{greaterPressure:'equal'},'Alanların eşitliği, farklı ağırlıklarda basınçları eşitlemez.'),choice('Ağırlık hiçbir fark oluşturmaz.',{greaterPressure:'weight_irrelevant'},'Katı basıncının ağırlıkla nitel ilişkisi yok sayılmıştır.')]},
]);
family({grade:8,branch:'physics',familyId:'liquid_depth_control',topic:'Sıvı basıncında derinlik ve kap',code:'F.8.3.1.2',page:51,kind:'experiment_board',task:'liquid_pressure',intent:'analyze',
  rule:'Aynı sıvıda daha derin noktada sıvı basıncı daha büyüktür; aynı derinlikte kap biçimi tek başına basıncı değiştirmez.',strategy:'Önce sıvının aynı olduğunu doğrula; yüzeyden ölçülen derinlikleri karşılaştır, kap biçimini ayrı tut.',action:'K ve L noktalarının serbest yüzeye göre derinlik sırasını oku.',tip:'Derinlik kabın dibinden değil sıvının serbest yüzeyinden değerlendirilir.',check:'Yoğunluk farkı uydurmadan aynı sıvı ve aynı ortam koşulunu kullan; sayısal bağıntıya dönüştürme.'},[
  {inputs:{sameLiquid:true,depthOrder:'K>L',vesselShapeDifferent:false},given:'Aynı su içindeki K noktası serbest yüzeyden daha derinde, L daha sığdadır. Ölçüm aynı ortamda yapılır ve kap biçimi aynıdır. Sayısal derinlik veya basınç değeri verilmemiştir.',wanted:'Yalnız verilen derinlik sırasına göre hangi noktada sıvı basıncı daha büyüktür?',result:'K daha derinde olduğu için K’de sıvı basıncı daha büyüktür.',meaning:'Nitel sıra belirlenir; basınç katları veya sayısal değerler çıkarılmaz.',
    choices:[choice('K noktasında',{greaterPressure:'K'},''),choice('L noktasında',{greaterPressure:'L'},'Sıvı basıncının derinlikle artması ters yorumlanmıştır.'),choice('İki noktada eşittir.',{greaterPressure:'equal'},'Aynı sıvı olması, farklı derinliklerde eşit basınç vermez.'),choice('Derinlik etkisizdir.',{greaterPressure:'depth_irrelevant'},'Sıvı basıncının derinlikle ilişkisi yok sayılmıştır.')]},
  {inputs:{sameLiquid:true,depthOrder:'equal',vesselShapeDifferent:true},given:'Farklı biçimdeki iki açık kapta aynı su vardır. K ve L ölçüm noktaları kendi serbest yüzeylerinden eşit derinliktedir; ortam koşulları aynıdır. Kapların genişlikleri farklıdır.',wanted:'Kap biçimi farklı olsa da verilen koşullarda K ve L basınçları nasıl karşılaştırılır?',result:'Aynı sıvıda aynı derinlikte basınçlar eşittir; kap biçimi tek başına farklılık oluşturmaz.',meaning:'Daha geniş kapta daha çok su bulunması bu eşit derinlik karşılaştırmasını değiştirmez.',difficulty:'hard',
    choices:[choice('Basınçlar eşittir.',{greaterPressure:'equal'},''),choice('Yalnız K’de daha büyüktür.',{greaterPressure:'K'},'Eşit derinlik ve aynı sıvı koşullarına dayanmayan bir yön seçilmiştir.'),choice('Yalnız L’de daha büyüktür.',{greaterPressure:'L'},'Kap şekli tek başına daha büyük basınç göstermez.'),choice('Kap genişliği tek belirleyicidir.',{greaterPressure:'shape_only'},'Sıvı basıncı kap genişliğiyle koşulsuz eşleştirilmiştir.')]},
]);
family({grade:8,branch:'physics',familyId:'machine_work_tradeoff',topic:'Basit makinede kuvvet-yol-iş ayrımı',code:'F.8.5.1.1',page:53,kind:'force_work_board',task:'machine_tradeoff',intent:'analyze',
  rule:'Ağırlığı ve sürtünmesi ihmal edilen ideal makarada aynı yük aynı yüksekliğe çıkarılırken işten kazanç yoktur; hareketli makara kuvveti azaltırken çekme yolunu artırır, sabit makara yön değiştirir.',strategy:'Önce ideal makine ve aynı yük hedefini kontrol et; kuvvet kolaylığı ile toplam iş kazancını birbirinden ayır.',action:'Makara türünü kuvvet ve çekilen ip yolu özellikleriyle eşleştir.',tip:'Daha az kuvvet kullanmak, işten kazanç demek değildir.',check:'Yükün aynı yüksekliğe çıktığını ve ideal koşulu kontrol et; kuvvet oranı veya makara bağıntısı hesabı yapma.'},[
  {inputs:{machine:'movable_pulley',ideal:true,loadSame:true},given:'Tek hareketli makaralı ideal bir model aynı yükü aynı yüksekliğe çıkarıyor. Makara ağırlığı ve sürtünme ihmal ediliyor. Doğrudan kaldırmaya göre kuvvet, çekilen ip yolu ve iş nitel olarak karşılaştırılıyor.',wanted:'Bu ideal hareketli makara için hangi üçlü yargı doğrudur?',result:'Gereken kuvvet azalır, çekilen ip yolu artar; işten kazanç sağlanmaz.',meaning:'Kuvvet kolaylığının karşılığında yol artar; yükün aynı hedefe taşınması daha az iş demek değildir.',difficulty:'hard',
    choices:[choice('Kuvvet azalır; yol artar; işten kazanç yoktur.',{forceNeeded:'less',pulledDistance:'more',workSaved:false},''),choice('Kuvvet azalır; yol azalır; işten kazanç vardır.',{forceNeeded:'less',pulledDistance:'less',workSaved:true},'Kuvvet kazancı iş kazancı sanılmış ve yol etkisi ters çevrilmiştir.'),choice('Kuvvet artar; yol artar; işten kazanç yoktur.',{forceNeeded:'more',pulledDistance:'more',workSaved:false},'Hareketli makaranın kuvvet kolaylığı göz ardı edilmiştir.'),choice('Kuvvet ve yol aynı; işten kazanç vardır.',{forceNeeded:'same',pulledDistance:'same',workSaved:true},'İdeal makinenin türü ve işten kazanç bulunmaması yanlış yorumlanmıştır.')]},
  {inputs:{machine:'fixed_pulley',ideal:true,loadSame:true},given:'Bir ideal sabit makara aynı yükü aynı yüksekliğe taşımak için kullanılıyor. Makara ağırlığı ve sürtünme ihmal ediliyor. İp aşağı çekilirken yük yukarı çıkıyor; doğrudan kaldırmayla nitel karşılaştırma isteniyor.',wanted:'Kuvvet büyüklüğü, çekilen ip yolu ve iş için hangi sonuç sabit makaranın işleviyle tutarlıdır?',result:'Kuvvet büyüklüğü ve yol aynı kalır; işten kazanç yoktur. Makara kuvvetin yönünü değiştirme kolaylığı sağlar.',meaning:'Yön değiştirme kolaylığı kuvvet büyüklüğünden veya işten kazançla aynı değildir.',
    choices:[choice('Kuvvet ve yol aynı; işten kazanç yoktur.',{forceNeeded:'same',pulledDistance:'same',workSaved:false},''),choice('Kuvvet azalır; yol artar; işten kazanç yoktur.',{forceNeeded:'less',pulledDistance:'more',workSaved:false},'Hareketli makara özelliği sabit makaraya aktarılmıştır.'),choice('Kuvvet ve yol aynı; işten kazanç vardır.',{forceNeeded:'same',pulledDistance:'same',workSaved:true},'İdeal makinenin işten kazanç sağladığı varsayılmıştır.'),choice('Kuvvet artar; yol azalır; işten kazanç vardır.',{forceNeeded:'more',pulledDistance:'less',workSaved:true},'Yön kolaylığına dayanmayan kuvvet, yol ve iş iddiaları eklenmiştir.')]},
]);
const elementBoard=[{id:'K',group:1,period:2},{id:'L',group:1,period:3},{id:'M',group:2,period:2}];
family({grade:8,branch:'chemistry',familyId:'periodic_pattern',topic:'Periyodik tabloda satır ve sütun',code:'F.8.4.1.2',page:52,kind:'matter_cards',task:'periodic_pattern',intent:'apply',
  rule:'Periyodik tabloda aynı grup aynı sütun, aynı periyot aynı satır anlamına gelir; burada semboller yalnız konum etiketi olarak kullanılır.',strategy:'Sorunun grup mu periyot mu istediğini ayır; doğru koordinat sütununu karşılaştır.',action:'Hedeflenen grup veya periyot numaraları aynı olan iki etiketi seç.',tip:'Grup dikey sütun, periyot yatay satırdır.',check:'Etiketlerden gerçek element adı veya verilmemiş özellik tahmini yapmadan yalnız konumu kullan.'},[
  {inputs:{elements:elementBoard,target:'same_group_pair'},given:'Bir tablo kesitinde konum etiketleri K:1. grup/2. periyot; L:1. grup/3. periyot; M:2. grup/2. periyot olarak verilmiştir. K, L, M gerçek element sembolü değil etkinlik etiketidir.',wanted:'Aynı grupta bulunan çift ve bu konumun anlamı hangi seçenekte doğrudur?',result:'K ve L’nin grup numarası aynıdır; aynı sütundadırlar.',meaning:'Periyotlarının farklı olması aynı grupta bulunmalarını engellemez.',difficulty:'easy',
    choices:[choice('K-L; aynı sütun',{pair:'K-L',locationRule:'same_column'},''),choice('K-M; aynı sütun',{pair:'K-M',locationRule:'same_column'},'Aynı periyot bilgisi grup bilgisi sanılmıştır.'),choice('K-L; aynı satır',{pair:'K-L',locationRule:'same_row'},'Doğru çiftin satır-sütun anlamı ters verilmiştir.'),choice('L-M; aynı satır',{pair:'L-M',locationRule:'same_row'},'Hem hedef koordinat hem çift yanlış seçilmiştir.')]},
  {inputs:{elements:[{id:'K',group:1,period:2},{id:'L',group:1,period:3},{id:'M',group:2,period:2}],target:'same_period_pair'},given:'K, L, M konum kartlarında sırasıyla 1. grup/2. periyot, 1. grup/3. periyot ve 2. grup/2. periyot yazıyor. Etiketler yalnız tablo konumunu temsil ediyor; bu kez yatay sıra soruluyor.',wanted:'Aynı periyotta bulunan çift ve doğru satır-sütun yorumu hangisidir?',result:'K ve M’nin periyot numarası aynıdır; aynı satırdadırlar.',meaning:'Grup numaraları farklı olan iki etiket aynı periyotta olabilir.',
    choices:[choice('K-M; aynı satır',{pair:'K-M',locationRule:'same_row'},''),choice('K-L; aynı sütun',{pair:'K-L',locationRule:'same_column'},'Doğru bir grup çifti verilse de soru periyot çiftini istemektedir.'),choice('K-M; aynı sütun',{pair:'K-M',locationRule:'same_column'},'Periyot satırı grup sütunuyla karıştırılmıştır.'),choice('L-M; aynı satır',{pair:'L-M',locationRule:'same_row'},'Periyot numaraları aynı değildir.')]},
]);
family({grade:8,branch:'chemistry',familyId:'pH_classification',topic:'pH verisini yorumlama',code:'F.8.4.4.4',page:52,kind:'matter_cards',task:'pH_classification',intent:'apply',
  rule:'Bu su bazlı çözelti modelinde pH 7 nötr, 7’den küçük asidik ve 7’den büyük baziktir.',strategy:'Verilen ölçümü 7 ile karşılaştır; tadına bakma veya koklama gibi güvenli olmayan yollar önerme.',action:'pH değerinin 7’nin altında, üstünde veya eşit olduğunu belirle.',tip:'pH değeri maddeyi tatma çağrısı değildir; ölçüm verisini kullan.',check:'Sınıflandırmanın verilen sulu çözeltiye ilişkin olduğunu ve kimyasal uygulama talimatı olmadığını kontrol et.'},[
  {inputs:{samplePH:3},given:'Bir sulu çözelti için pH ölçer ekranında 3 değeri okunuyor. Ölçüm yetişkin tarafından yapılmıştır; öğrenci yalnız veriyi yorumlayacaktır. Çözeltiyi tatma veya koklama istenmez.',wanted:'Verilen pH ölçümüne göre çözeltinin sınıfı nedir?',result:'3, 7’den küçüktür; çözelti asidiktir.',meaning:'Sınıflandırma ölçümden yapılır; maddenin adı veya güvenliği hakkında ek sonuç çıkarılmaz.',difficulty:'easy',
    choices:[choice('Asidik',{category:'acidic'},''),choice('Bazik',{category:'basic'},'7’nin altındaki pH bazik diye yorumlanmıştır.'),choice('Nötr',{category:'neutral'},'Nötr değer 7’dir; 3 değildir.'),choice('pH sınıflandırması yapılamaz.',{category:'unknown'},'Sulu çözelti ve ölçüm değeri sınıflandırma için verilmiştir.')]},
  {inputs:{samplePH:10},given:'İkinci bir sulu çözeltinin yalnız ölçüm kartı paylaşılıyor: pH 10. Öğrencinin maddeyle temas etmesi istenmiyor; kartta bir kimyasal tepkime veya formül bulunmuyor.',wanted:'10 değerini nötr eşikle karşılaştırınca hangi sınıflandırma elde edilir?',result:'10, 7’den büyüktür; çözelti baziktir.',meaning:'pH eşik karşılaştırması sınıfı verir; her bazın aynı güçte veya zararsız olduğunu göstermez.',
    choices:[choice('Bazik',{category:'basic'},''),choice('Asidik',{category:'acidic'},'7’den büyük pH asidik diye yorumlanmıştır.'),choice('Nötr',{category:'neutral'},'Ölçüm 7 olmadığı için nötr değildir.'),choice('Ölçümden bir sınıf çıkarılamaz.',{category:'unknown'},'Verilen pH eşik karşılaştırmasını mümkün kılar.')]},
]);
family({grade:8,branch:'chemistry',familyId:'chemical_new_substance',topic:'Fiziksel ve kimyasal değişim kanıtı',code:'F.8.4.2.1',page:52,kind:'matter_cards',task:'new_substance',intent:'understand',
  rule:'Demirin paslanması yeni madde oluşumuyla kimyasal, kâğıdın yırtılması madde türünü değiştirmeyen fiziksel değişimdir.',strategy:'Boyut veya görünüş değişimine tek başına karar verme; anlatılan süreçte madde türünün değişip değişmediğini incele.',action:'Verilen süreci yeni madde oluşumu ölçütüyle sınıflandır.',tip:'Şeklin değişmesi tek başına yeni madde oluştuğunu göstermez.',check:'Örneklerdeki bilinen süreci kullan; herhangi bir renk değişimini koşulsuz kimyasal değişim sayma.'},[
  {inputs:{process:'iron_rusting'},given:'Nemli ortamda bırakılan demir yüzeyinde pas oluştuğu gözleniyor. Etkinlik yalnız bu bilinen paslanma sürecini yorumlatıyor; bir kimyasal denklem kurması veya deney yapması istenmiyor.',wanted:'Paslanma için değişim türü ve yeni madde bakımından hangi yargı doğrudur?',result:'Pas oluşumu kimyasal değişimdir; yeni madde oluşur.',meaning:'Sonuç yalnız bilinen paslanma olayına ilişkindir; bütün renk değişimleri için genelleme yapılmaz.',difficulty:'easy',
    choices:[choice('Kimyasal değişim; yeni madde oluşur.',{changeType:'chemical',newSubstanceFormed:true},''),choice('Fiziksel değişim; yeni madde oluşmaz.',{changeType:'physical',newSubstanceFormed:false},'Pas oluşumu yalnız şekil değişimi değildir.'),choice('Kimyasal değişim; yeni madde oluşmaz.',{changeType:'chemical',newSubstanceFormed:false},'Kimyasal sınıflandırmayla yeni madde iddiası yanlış eşleştirilmiştir.'),choice('Fiziksel değişim; yeni madde oluşur.',{changeType:'physical',newSubstanceFormed:true},'Yeni madde oluşumu fiziksel değişim ölçütüyle çelişir.')]},
  {inputs:{process:'paper_tearing'},given:'Bir kâğıt elle birkaç parçaya ayrılıyor. Parçalar hâlâ kâğıttır; yakma, renk giderme veya başka bir maddeyle işlem yapma söz konusu değildir.',wanted:'Yalnız yırtma olayında değişim türü ve yeni madde oluşumu nasıl eşleştirilir?',result:'Yırtma fiziksel değişimdir; yeni madde oluşmaz.',meaning:'Parça sayısının artması madde türü sayısının artması değildir.',
    choices:[choice('Fiziksel değişim; yeni madde oluşmaz.',{changeType:'physical',newSubstanceFormed:false},''),choice('Kimyasal değişim; yeni madde oluşur.',{changeType:'chemical',newSubstanceFormed:true},'Parçalama yeni madde oluşumu sanılmıştır.'),choice('Fiziksel değişim; yeni madde oluşur.',{changeType:'physical',newSubstanceFormed:true},'Fiziksel boyut değişimine yeni madde iddiası eklenmiştir.'),choice('Kimyasal değişim; yeni madde oluşmaz.',{changeType:'chemical',newSubstanceFormed:false},'Kimyasal değişim sınıfı verilen olayla desteklenmemektedir.')]},
]);
family({grade:8,branch:'biology',familyId:'one_trait_cross',topic:'Tek karakterli çaprazlama',code:'F.8.2.2.2',page:50,kind:'genetic_grid',task:'one_trait_cross',intent:'analyze',knowledge:'procedural',
  rule:'Bu tek karakter modelinde A tam baskın, a çekiniktir; ebeveynlerden gelen eş olasılıklı alel çiftleri dört hücrede tek tek birleştirilir.',strategy:'Önce ebeveynlerin verebileceği alelleri ayır; dört eş olasılıklı birleşimi oluştur, sonra baskın-çekinik görünümü say.',action:'Her bir ebeveyn alelini diğerinin iki aleliyle ayrı eşleştir.',tip:'Dört model olasılığı, her gerçek dört yavruda aynı sayı çıkacağı garantisi değildir.',check:'Tek karakter, tam baskınlık ve eş olasılıklı alel aktarımı varsayımlarını kullan; gerçek çocuk veya aile genetiği hakkında çıkarım yapma.'},[
  {inputs:{parent1:['A','a'],parent2:['A','a'],dominantAllele:'A'},given:'Kurgusal bir bitki modelinde tek karakter inceleniyor. A tam baskın, a çekiniktir. Her ebeveyn Aa’dır ve iki alelini eş olasılıkla aktarır. Boş çaprazlama tablosunda ebeveyn alelleri gösterilir; birleşimler henüz yazılmamıştır.',wanted:'Dört eş olasılıklı model hücresinde baskın ve çekinik görünüm kaç payla temsil edilir?',result:'AA, Aa, aA ve aa birleşimlerinden üçü baskın, biri çekinik görünüm verir.',meaning:'3/4 ve 1/4 model olasılıklarıdır; gerçek dört yavru için kesin sayım değildir.',difficulty:'hard',
    choices:[choice('Baskın 3, çekinik 1; toplam 4 pay',{dominantPhenotypeParts:3,recessivePhenotypeParts:1,totalParts:4},''),choice('Baskın 2, çekinik 2; toplam 4 pay',{dominantPhenotypeParts:2,recessivePhenotypeParts:2,totalParts:4},'Heterozigot birleşimlerde baskın alelin etkisi eksik sayılmıştır.'),choice('Baskın 1, çekinik 3; toplam 4 pay',{dominantPhenotypeParts:1,recessivePhenotypeParts:3,totalParts:4},'Baskın ve çekinik görünüm sayıları ters çevrilmiştir.'),choice('Baskın 4, çekinik 0; toplam 4 pay',{dominantPhenotypeParts:4,recessivePhenotypeParts:0,totalParts:4},'aa birleşimi yok sayılmıştır.')]},
  {inputs:{parent1:['A','a'],parent2:['a','a'],dominantAllele:'A'},given:'Aynı tek karakterli tam baskınlık modelinde bir ebeveyn Aa, diğeri aa’dır. Alel aktarımı eş olasılıklıdır. Çaprazlama kartı yalnız ebeveyn alellerini gösterir; yavru birleşimleri tamamlanmamıştır.',wanted:'Baskın görünüm ve heterozigot birleşim, dört eş olasılıklı hücrede kaçar paydır?',result:'Aa, Aa, aa ve aa birleşimleri vardır; baskın görünüm 2 ve heterozigot birleşim 2 paydır.',meaning:'Genotip ile görünüm ayrı sayılır; bu modelde iki heterozigot hücre baskın görünür.',difficulty:'hard',
    choices:[choice('Baskın 2, heterozigot 2; toplam 4 pay',{dominantPhenotypeParts:2,heterozygousParts:2,totalParts:4},''),choice('Baskın 3, heterozigot 2; toplam 4 pay',{dominantPhenotypeParts:3,heterozygousParts:2,totalParts:4},'İki heterozigot ebeveyn çaprazının oranı bu farklı ebeveynlere aktarılmıştır.'),choice('Baskın 2, heterozigot 4; toplam 4 pay',{dominantPhenotypeParts:2,heterozygousParts:4,totalParts:4},'Çekinik aa birleşimleri de heterozigot sayılmıştır.'),choice('Baskın 1, heterozigot 1; toplam 4 pay',{dominantPhenotypeParts:1,heterozygousParts:1,totalParts:4},'Eş olasılıklı iki ayrı Aa hücresi tek hücre sayılmıştır.')]},
]);
family({grade:8,branch:'biology',familyId:'mutation_modification',topic:'Mutasyon ve modifikasyon kanıtı',code:'F.8.2.3.3',page:50,kind:'biology_graph',task:'mutation_modification',intent:'analyze',
  rule:'Çevresel etkiyle DNA dizisi değişmeden oluşan değişim modifikasyon olarak ele alınır; DNA dizisi değişimi mutasyondur. Üreme hücresindeki mutasyon aktarılabilir ama aktarılması kesin değildir.',strategy:'Önce DNA dizisinin değişip değişmediğine bak; kalıtsallık yorumunda hücre türünü ayrıca kullan.',action:'DNA kanıtını olay sınıfıyla, hücre türünü aktarılabilme olasılığıyla ayrı eşleştir.',tip:'Aktarılabilir olmak ile her yavruya kesin aktarılmak farklı iddialardır.',check:'Kurgusal hücre modelini gerçek öğrenci veya aile sağlığına ilişkin tanı diye kullanma; olabilirliği kesinlik yapma.'},[
  {inputs:{dnaSequenceChanged:false,environmentChanged:true,cellType:'somatic',phenotypeChanged:true},given:'Kurgusal bir canlı modelinde çevre koşulu değişince görünüm değişiyor. İncelenen vücut hücrelerinde DNA dizisinin aynı kaldığı belirtiliyor. Model sağlık veya tanı amacı taşımıyor.',wanted:'Verilen kanıta göre olay sınıfı ve bu değişimin yavruya kalıtsal aktarımı için hangi yargı uygundur?',result:'DNA dizisi değişmeden çevreye bağlı oluşan bu değişim modifikasyondur; bu değişim kalıtsal olarak aktarılmaz.',meaning:'Görünüm değişikliği tek başına DNA dizisi değişikliğini kanıtlamaz.',
    choices:[choice('Modifikasyon; kalıtsal aktarılmaz.',{classification:'modification',canBeInherited:false},''),choice('Mutasyon; aktarılabilir.',{classification:'mutation',canBeInherited:true},'DNA dizisinin aynı kaldığı kanıtı göz ardı edilmiştir.'),choice('Modifikasyon; kalıtsal aktarılabilir.',{classification:'modification',canBeInherited:true},'DNA dizisi değişmeyen verilen çevresel olay için kalıtsallık eklenmiştir.'),choice('Mutasyon; kalıtsal aktarılmaz.',{classification:'mutation',canBeInherited:false},'Aktarım yargısı olayın yanlış mutasyon sınıfını düzeltmez.')]},
  {inputs:{dnaSequenceChanged:true,environmentChanged:false,cellType:'gamete',phenotypeChanged:false},given:'İkinci kurgusal modelde bir üreme hücresinin DNA dizisi değişiyor; görünüm değişmesi gözlenmiyor. Çevresel görünüm değişimi anlatılmıyor. Soru değişimin ileride aktarılma ihtimalini soruyor; gerçek yavru oluşumu verilmemiştir.',wanted:'DNA değişimi ve üreme hücresi kanıtı birlikte hangi sınıflandırmayı destekler?',result:'Olay mutasyondur; üreme hücresindeki değişim yavruya aktarılabilir, fakat bu aktarım kesin gerçekleşmiş sayılmaz.',meaning:'Hücre türü kalıtsal aktarım olasılığına dayanak olur; gerçekleşmiş aktarım kanıtı değildir.',difficulty:'hard',
    choices:[choice('Mutasyon; yavruya aktarılabilir.',{classification:'mutation',canBeInherited:true},''),choice('Modifikasyon; aktarılmaz.',{classification:'modification',canBeInherited:false},'DNA dizisinin değiştiği kanıtı modifikasyonla bağdaşmaz.'),choice('Mutasyon; aktarılması mümkün değildir.',{classification:'mutation',canBeInherited:false},'Üreme hücresi kanıtı yok sayılmıştır.'),choice('Modifikasyon; aktarılabilir.',{classification:'modification',canBeInherited:true},'DNA dizisi değişimini modifikasyon olarak adlandırmak yanlıştır.')]},
]);
family({grade:8,branch:'biology',familyId:'photosynthesis_control',topic:'Fotosentez için kontrollü karşılaştırma',code:'F.8.6.2.2',page:54,kind:'experiment_board',task:'fair_test',intent:'analyze',knowledge:'procedural',
  rule:'Fotosenteze tek bir koşulun etkisi araştırılırken aynı tür ve sayıdaki bitkilerle diğer koşullar sabit tutulur.',strategy:'Işık veya karbondioksit hedefini belirle; diğer verilen koşulların aynı kaldığı çifti seç.',action:'Bitki sayısı, su ve hedef dışındaki çevre sütunlarını karşılaştır.',tip:'Birden çok koşulu değiştirmek, hangi etkenin sonucu değiştirdiğini ayırmayı zorlaştırır.',check:'Tek değişkenli çift seçildiğini ve kimyasal denklem veya ölçülmemiş ürün miktarı eklenmediğini kontrol et.'},[
  {inputs:{targetVariable:'light',rows:[{id:'R1',light:'yes',carbonDioxide:'normal',water:'yes',plantCount:1},{id:'R2',light:'no',carbonDioxide:'normal',water:'yes',plantCount:1},{id:'R3',light:'no',carbonDioxide:'low',water:'yes',plantCount:1},{id:'R4',light:'yes',carbonDioxide:'normal',water:'yes',plantCount:2}]},given:'Aynı tür bitkiler için tablo şöyledir: R1:ışık var/karbondioksit normal/su var/1 bitki; R2:ışık yok/normal/su var/1; R3:ışık yok/düşük/su var/1; R4:ışık var/normal/su var/2. Sıcaklık bütün düzeneklerde aynıdır.',wanted:'Işığın etkisini karbondioksit veya bitki sayısına karıştırmadan hangi çiftle araştırabiliriz?',result:'R1-R2 yalnız ışık koşulunda farklıdır; verilen diğer koşullar aynıdır.',meaning:'Bu deney seçimi kimyasal denklem veya kesin oksijen üretim miktarı bildirmez.',choices:pairChoices('R1-R2','light')},
  {inputs:{targetVariable:'carbonDioxide',rows:[{id:'R1',light:'yes',carbonDioxide:'normal',water:'yes',plantCount:2},{id:'R2',light:'yes',carbonDioxide:'low',water:'yes',plantCount:2},{id:'R3',light:'no',carbonDioxide:'low',water:'yes',plantCount:2},{id:'R4',light:'yes',carbonDioxide:'normal',water:'no',plantCount:2}]},given:'Özdeş türde ikişer bitkiyle R1:ışık var/karbondioksit normal/su var; R2:ışık var/karbondioksit düşük/su var; R3:ışık yok/karbondioksit düşük/su var; R4:ışık var/karbondioksit normal/su yok düzenekleri hazırlanıyor. Sıcaklık aynıdır.',wanted:'Karbondioksit koşulunun etkisini tek başına karşılaştırmak için hangi iki düzenek kullanılmalıdır?',result:'R1-R2 yalnız karbondioksit koşulunda ayrılır; ışık, su ve bitki sayısı sabittir.',meaning:'Bir başka çiftte ek ışık veya su farkı sonuçların nedenini ayırmayı engeller.',choices:pairChoices('R1-R2','carbonDioxide')},
]);

function freeze(value){if(value&&typeof value==='object'){Object.values(value).forEach(freeze);Object.freeze(value);}return value;}
const FIXED_SEEDS=freeze(authored);
export function createScienceAuthoringSeeds(...args){if(args.length)throw new Error('fixed_science_seed_api');return FIXED_SEEDS;}
